### PR TITLE
[Fix #3802] Ignore case when checking Gemfile order

### LINKED ISSUE #3802: OK to do case-insensitive checks on the OrderedGems cop?
I love the new OrderedGems cop, it's a fantastic idea!

However, the OrderedGems cop uses the `<` sign to perform its comparison, and I have one pesky dependency that starts with a capital letter (the wonderful-yet-inconsistently-named [StreetAddress](https://github.com/derrek/street-address) gem). Since `'a' < 'Z' #=> false`, it wants to sort this dependency at the top of my Gemfile. Would it be acceptable to write a PR that performs a case-insensitive comparison?

--------

## Expected behavior

The OrderedGems cop doesn't consider case when checking the Gemfile.

## Actual behavior

The OrderedGems cop considers case when checking the Gemfile.

## Steps to reproduce the problem

```ruby
# in Gemfile
source 'https://rubygems.org'
gem 'sinatra'
gem 'StreetAddress'
```

```sh
rubocop
Inspecting 1 file
C

Offenses:

Gemfile:4:1: C: Gem StreetAddress should appear before sinatra in their gem group.
gem 'StreetAddress'
^^^^^^^^^^^^^^^^^^^

1 file inspected, 1 offense detected
```

## RuboCop version

```
$ rubocop -V
0.46.0 (using Parser 2.3.3.1, running on ruby 2.3.1 x86_64-darwin16)
```

### PR DESCRIPTION
**Pull request by breckenedge**
Updates the Bundler/OrderedGems cop to not consider case when checking if a Gemfile is alphabetized.

### CODE REVIEW

File: lib/rubocop/cop/bundler/ordered_gems.rb [hunk 1]
```diff
@@ -25,12 +25,18 @@ def investigate(processed_source)
...
-                        previous.children[2].children.first.to_s
+            next unless case_insensitive_out_of_order?(
+              current.children[2].children.first.to_s,
+              previous.children[2].children.first.to_s
+            )
             register_offense(previous, current)
           end
         end
 
+        def case_insensitive_out_of_order?(string_a, string_b)
```
Comment (breckenedge) [inline lib/rubocop/cop/bundler/ordered_gems.rb]: Added as a separate method due to cyclomatic complexity cop offenses.

File: CHANGELOG.md [hunk 2]
```diff
@@ -2,6 +2,8 @@
 
 ## master (unreleased)
 
+* [#3802](https://github.com/bbatsov/rubocop/pull/3802): Ignore case when checking Gemfile order. ([@breckenedge][])
```
Comment (bbatsov) [inline CHANGELOG.md]: This should be under "changes".
