### PR TITLE
[Fix #4656] Fix Style/ConditionalAssignment auto-correction

### LINKED ISSUE #4656: Can't fix Style/ConditionalAssignment
## Expected behavior
I have [this code](https://github.com/codetriage/codetriage/blob/master/config/environments/production.rb#L89-L100): 
```ruby
  if ENV["MEMCACHIER_SERVERS"]
    config.cache_store = :dalli_store,
                        (ENV["MEMCACHIER_SERVERS"] || "").split(","),
                        {:username => ENV["MEMCACHIER_USERNAME"],
                         :password => ENV["MEMCACHIER_PASSWORD"],
                         :failover => true,
                         :socket_timeout => 1.5,
                         :socket_failure_delay => 0.2
                        }
    else
      config.cache_store = :dalli_store
    end
```

## Actual behavior

Rubocop notifies me for a Style/ConditionalAssignment offense. I tried to fix it with: 
```ruby
  config.cache_store = if ENV["MEMCACHIER_SERVERS"]
                         :dalli_store,
                           (ENV["MEMCACHIER_SERVERS"] || "").split(","),
                           {:username => ENV["MEMCACHIER_USERNAME"],
                            :password => ENV["MEMCACHIER_PASSWORD"],
                            :failover => true,
                            :socket_timeout => 1.5,
                            :socket_failure_delay => 0.2
                         }
                       else
                         :dalli_store
                       end
```
but it can't work like this
```ruby
/Users/bti/.rvm/gems/ruby-2.4.1/gems/bootsnap-0.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require': /Users/bti/code/codetriage/config/environments/production.rb:90: syntax error, unexpected ',', expecting keyword_end (SyntaxError)
                 :dalli_store, (ENV["MEMCACHIER_SERVERS"] ||
```

So for the moment, it's disabled. Is there a way to fix this?

## RuboCop version

```
$ rubocop -V
0.49.1 (using Parser 2.4.0.0, running on ruby 2.4.1 x86_64-darwin16)
```

### PR DESCRIPTION
**Pull request by akhramov**
`Style/ConditionalAssignment` cop's autocorrection results in invalid
syntax when it encounters assignment to unbracketed array.

This pull request modifies ConditionalAssignment cop's autocorrection so, it
wraps array in brackets, if needed.
This issue is very simillar to #3170, where `Style/MutableConstant`
wasn't able to properly handle assignment to unbracketed array.
Since both `MutableConstant` and `ConditionalAssignment` cops need to
check whether array node is bracketed or not, new method
`Rubocop::AST::ArrayNode#bracketed?` was introduced, to avoid
duplication.

-----------------

Before submitting the PR make sure the following are checked:

* [ ] Wrote [good commit messages][1].
* [ ] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [ ] Used the same coding conventions as the rest of the project.
* [ ] Feature branch is up-to-date with `master` (if not - rebase it).
* [ ] Squashed related commits together.
* [ ] Added tests.
* [ ] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [ ] All tests(`rake spec`) are passing.
* [ ] The new code doesn't generate RuboCop offenses that are checked by `rake internal_investigation`.
* [ ] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Updated cop documentation with `rake generate_cops_documentation` (required only when you've added a new cop or changed the configuration/documentation of an existing cop).

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: spec/rubocop/cop/style/conditional_assignment_assign_to_condition_spec.rb [hunk 1]
```diff
@@ -1192,6 +1192,26 @@
...
+      RUBY
+
+      new_source = autocorrect_source(source)
+
+      expect(new_source).to eq(<<-RUBY.strip_indent)
+        bar = if foo
+          1
+        else
+          [2, 5, 6]
+              end
```
Comment (Drenmi) [inline spec/rubocop/cop/style/conditional_assignment_assign_to_condition_spec.rb]: I guess this happens because of interference from `Lint/EndAlignment`?

**Comment by Drenmi** [comment]
Nice! Hadn't crossed my mind that parallel assignment is parsed as an array node. 🙂

File: spec/rubocop/cop/style/conditional_assignment_assign_to_condition_spec.rb (hunk 1 above)
Comment (akhramov) [reply spec/rubocop/cop/style/conditional_assignment_assign_to_condition_spec.rb]: Actually, `Style/ConditionalAssignment` realigns `end` keyword by itself. Please see #2719 / #2800 for details.

Comment (bbatsov) [reply spec/rubocop/cop/style/conditional_assignment_assign_to_condition_spec.rb]: That looks extremely strange.

Comment (akhramov) [reply spec/rubocop/cop/style/conditional_assignment_assign_to_condition_spec.rb]: @bbatsov 

Agreed. Would it be better to have an "explanatory" variable? i.e.

```ruby
indent = ' ' * 'bar = '.length
expect(new_source).to eq(<<-RUBY.strip_indent)
  bar = if foo
    1
  else
    [2, 5, 6]
  #{indent}end
RUBY
```

If so, I'd correct [the other case](https://github.com/akhramov/rubocop/blob/8cc74135877bb619a839ae863ca82f15d0567520/spec/rubocop/cop/style/conditional_assignment_assign_to_condition_spec.rb#L1186-L1192), from which I've derived the style.

Comment (Drenmi) [reply spec/rubocop/cop/style/conditional_assignment_assign_to_condition_spec.rb]: Is it possible to configure the auto-correct to produce a more ... reasonable style in the tests? 

Either:

```ruby
bar = if foo
        1
      else
        [2, 3]
      end
```

or:

```ruby
bar = if foo
  1
else
  [2, 3]
end
```

Comment (akhramov) [reply spec/rubocop/cop/style/conditional_assignment_assign_to_condition_spec.rb]: @Drenmi, thanks for guidance! Fixed.

Comment (Drenmi) [reply spec/rubocop/cop/style/conditional_assignment_assign_to_condition_spec.rb]: Well done, @akhramov! Looks much better now. 🙂

**Comment by Drenmi** [comment]
With the fix to the test configuration, I'm good with this @bbatsov. 🙂
