### PR TITLE
[Fix #4676] Make Style/RedundantConditional cop work with elsif

### LINKED ISSUE #4676: Autocorrection bug in `Style/RedundantConditional` cop
If "bad" code has `elsif`, `Style/RedundantConditional` generates wrong code when autocorrect.

```ruby
if cond
  foo
elsif x == y
  true
else
  false
end
```

--------

## Expected behavior

Autocorrection generates the following code.

```ruby
if cond
  foo
else
  x == y
end
```

## Actual behavior

Autocorrection generates the following code actually.

```ruby
if cond
  foo
  x == y
end
```

## Steps to reproduce the problem

1. Put the above code as `test.rb`
2. Run `rubocop -a`

## RuboCop version

master(ce6483c8f83691837519ab0a4f996a74f9de11dc)

### PR DESCRIPTION
**Pull request by akhramov**
Current implementation of `Style/RedundantConditional` cop doesn't
handle the case when redundant conditional occurred in the `elsif` node. As
a result, autocorrection fails.

This PR tweaks the cop so it handles the `elsif` nodes as well.

-----------------

Before submitting the PR make sure the following are checked:

* [ ] Wrote [good commit messages][1].
* [ ] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [ ] Used the same coding conventions as the rest of the project.
* [ ] Feature branch is up-to-date with `master` (if not - rebase it).
* [ ] Squashed related commits together.
* [ ] Added tests.
* [ ] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [ ] All tests(`rake spec`) are passing.
* [ ] The new code doesn't generate RuboCop offenses that are checked by `rake internal_investigation`.
* [ ] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Updated cop documentation with `rake generate_cops_documentation` (required only when you've added a new cop or changed the configuration/documentation of an existing cop).

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/style/redundant_conditional.rb [hunk 1]
```diff
@@ -25,26 +25,33 @@ module Style
...
+        def message(node)
+          replacement = replacement_condition(node)
+          msg = node.elsif? ? "\n#{replacement}" : replacement
+
+          format(MSG, msg)
+        end
+
         def_node_matcher :redundant_condition?, <<-RUBY
-          (if (send _ {:#{COMPARISON_OPERATORS.join(' :')}} _) true false)
+          ({if elseif} (send _ {:#{COMPARISON_OPERATORS.join(' :')}} _) true false)
```
Comment (pocke) [inline lib/rubocop/cop/style/redundant_conditional.rb]: `elseif` is not needed, `if` is enough.

File: lib/rubocop/cop/style/redundant_conditional.rb [hunk 2]
```diff
@@ -25,26 +25,33 @@ module Style
...
         RUBY
 
         def_node_matcher :redundant_condition_inverted?, <<-RUBY
-          (if (send _ {:#{COMPARISON_OPERATORS.join(' :')}} _) false true)
+          ({if elseif} (send _ {:#{COMPARISON_OPERATORS.join(' :')}} _) false true)
```
Comment (pocke) [inline lib/rubocop/cop/style/redundant_conditional.rb]: https://github.com/bbatsov/rubocop/pull/4681/files#r136286082 Same here

File: lib/rubocop/cop/style/redundant_conditional.rb [hunk 3]
```diff
@@ -25,26 +25,33 @@ module Style
...
         end
 
         private
 
+        def message(node)
+          replacement = replacement_condition(node)
+          msg = node.elsif? ? "\n#{replacement}" : replacement
+
+          format(MSG, msg)
+        end
```
Comment (pocke) [inline lib/rubocop/cop/style/redundant_conditional.rb]: I think this message is a bit difficult to understand.




the `else\n x ==y` is confusing. It also looks like code.
I guess it is a little easy to understand by adding backtick around `%s`( https://github.com/bbatsov/rubocop/pull/4681/files#diff-c73e58428562c0f62526309365c75b87R32 ).

File: lib/rubocop/cop/style/redundant_conditional.rb (hunk 1 above)
Comment (akhramov) [reply lib/rubocop/cop/style/redundant_conditional.rb]: Good catch, fixed!

File: lib/rubocop/cop/style/redundant_conditional.rb [hunk 4]
```diff
@@ -25,26 +25,33 @@ module Style
...
 
         MSG = 'This conditional expression can just be replaced by %s'.freeze
 
         def on_if(node)
           return unless offense?(node)
 
-          add_offense(node,
-                      :expression,
-                      format(MSG, replacement_condition(node)))
+          add_offense(node, :expression)
```
[the remark this answers is not in the document]
Comment (akhramov) [reply lib/rubocop/cop/style/redundant_conditional.rb]: Thanks, fixed!

There's a cop: [InternalAffairs/RedundantMessageArgument](https://github.com/bbatsov/rubocop/blob/4abb67df0aa5b53cb42ceaae899636ef7cae2529/lib/rubocop/cop/internal_affairs/redundant_message_argument.rb). It just doesn't handle this case. :)

File: lib/rubocop/cop/style/redundant_conditional.rb (hunk 3 above)
Comment (akhramov) [reply lib/rubocop/cop/style/redundant_conditional.rb]: Thanks. Actually, I tried to use backticks, but found out that it does not work with multiline strings, since [RuboCop::Formatter::SimpleTextFormatter#annotate_message](annotate_message) uses single-line regex for replacement purposes:

```ruby
def annotate_message(msg)
  msg.gsub(/`(.*?)`/, yellow('\1'))
end
```

Even though the fix is trivial (we just need to add the `m` modifier to the regex), should we do it in the scope of this pull request?

Comment (pocke) [reply lib/rubocop/cop/style/redundant_conditional.rb]: > Even though the fix is trivial (we just need to add the m modifier to the regex), should we do it in the scope of this pull request?

Yes, I think it should be fixed in this pull-request. Because the change is very small, and the change is necessary to display the message correctly.

Comment (akhramov) [reply lib/rubocop/cop/style/redundant_conditional.rb]: Makes sense, done.
