### PR TITLE
[Fix #5806] Space inside reference brackets when assigning another reference bracket.

### LINKED ISSUE #5806: Reference Brackets Assigned by Reference Brackets Do Not Enforce Spaces.
To be clear, whether you have `EnforcedStyle: no_space` or `EnforcedStyle: space`, the first Reference Bracket is completely ignored when assigning from another Reference Bracket.

## Expected behavior

Rubocop to register an offence when there is no space in the reference bracket being assigned:

**`EnforcedStyle: no_space`**
```ruby
a[ "foo"] = b["something"]
  ^ Do not use space inside reference brackets.
```

**`EnforcedStyle: space`**
```ruby
a["foo"] = b[ "something" ]
 ^ Use space inside reference brackets.
```

## Actual behavior

No offence was registered in either test case.

## Steps to reproduce the problem

Test the above lines with Rubocop, either enforcing spaces or not enforcing spaces.

## RuboCop version

```bash
$ bundle exec rubocop -V
0.55.0 (using Parser 2.5.1.0, running on ruby 2.2.0 x86_64-darwin16)
```

### PR DESCRIPTION
**Pull request by joshuapinter**
When assigning a reference bracket to another reference bracket, the `Layout/SpaceInsideReferenceBracket` Cop fails to pickup on the _assignee_ reference bracket correctly.

Examples:

**`EnforcedStyle: no_space`**
```ruby
a[ "foo"] = b["something"]
```

The above example would not register an offence when `EnforcedStyle: no_space` is set.

**`EnforcedStyle: space`**
```ruby
a["foo" ] = b[ "something" ]
```

The above example would not register an offence when `EnforcedStyle: space` is set.

The issue is due to how the `left_ref_bracket` method searches from the end of the node to the beginning of the node to find the _first_ left reference bracket that it encounters.

This works fine for all other test cases, especially when there are multiple reference brackets, however, when a reference bracket is being assigned to another reference bracket, this mistakenly picks up the _assignor_ left reference bracket (i.e. `b[`) instead of the _assignee_ left reference bracket (i.e. `a[`).

To handle this, we simple modify the `left_ref_bracket` method to check to see if the node is using the `[]=` method. If it is, look for the first left reference bracket from the _start_ of the node.

If the node is not using the `[]=` method, do as it normally does and check for the first left reference bracket from the _end_ of the node.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together. **Please do when merging in on your side.**
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `rake default` or `rake parallel`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/layout/space_inside_reference_brackets.rb [hunk 1]
```diff
@@ -110,8 +110,14 @@ def bracket_method?(node)
           BRACKET_METHODS.include?(method)
         end
 
-        def left_ref_bracket(tokens)
-          tokens.reverse.find(&:left_ref_bracket?)
+        def left_ref_bracket(node, tokens)
+          _, method = *node
+
+          if method.to_s == '[]='
```
Comment (rrosenblum) [inline lib/rubocop/cop/layout/space_inside_reference_brackets.rb]: Does `method` need to be converted to a string? Would a comparison to a symbol work here instead? `method == :[]=`

Comment (joshuapinter) [reply lib/rubocop/cop/layout/space_inside_reference_brackets.rb]: I tried it initially just comparing the symbols but it was not happy. I had to use a String comparison.

Comment (rrosenblum) [reply lib/rubocop/cop/layout/space_inside_reference_brackets.rb]: The issue that you ran into with the debugger is `byebug` implements a `method` command.

Comment (joshuapinter) [reply lib/rubocop/cop/layout/space_inside_reference_brackets.rb]: @rrosenblum Thanks for the clarification! That'll help my future self when I run into something like this again. 😀

File: lib/rubocop/cop/layout/space_inside_reference_brackets.rb [hunk 2]
```diff
@@ -110,8 +110,14 @@ def bracket_method?(node)
           BRACKET_METHODS.include?(method)
         end
 
-        def left_ref_bracket(tokens)
-          tokens.reverse.find(&:left_ref_bracket?)
+        def left_ref_bracket(node, tokens)
+          _, method = *node
```
Comment (Drenmi) [inline lib/rubocop/cop/layout/space_inside_reference_brackets.rb]: Method send nodes are decorated with the `SendNode` extension, which allows you to do things like:

```ruby
send_node.method?(:[]=)
```

Comment (joshuapinter) [reply lib/rubocop/cop/layout/space_inside_reference_brackets.rb]: Are you saying I could use `node.method?(:[]=)` instead of `method == :[]=` on line 116?

**Comment by joshuapinter** [comment]
@rrosenblum How do I go about squashing them on my side once I've already pushed them to this branch?

**Comment by joshuapinter** [comment]
@Drenmi What would this test look like for the RHS? Maybe a space inside the reference bracket just to ensure it's picking up on the RHS brackets at all?

File: lib/rubocop/cop/layout/space_inside_reference_brackets.rb (hunk 2 above)
Comment (Drenmi) [reply lib/rubocop/cop/layout/space_inside_reference_brackets.rb]: Yes. And skip the destructuring on L:114. 🙂

File: spec/rubocop/cop/layout/space_inside_reference_brackets_spec.rb [hunk 3]
```diff
@@ -109,6 +109,20 @@
       RUBY
     end
 
+    it 'registers an offense when ref bct w/lead spc assigned by ref bct' do
```
Comment (Drenmi) [inline spec/rubocop/cop/layout/space_inside_reference_brackets_spec.rb]: Just let the description trail two lines instead of scrambling the sentence. 🙂

**Comment by Drenmi** [comment]
Think this would be enough:

```ruby
expect_offense(<<-RUBY.strip_indent)
  a["foo"] = b[ "bar"]
               ^ Do not use space inside reference brackets.
RUBY
```

File: lib/rubocop/cop/layout/space_inside_reference_brackets.rb (hunk 2 above)
Comment (joshuapinter) [reply lib/rubocop/cop/layout/space_inside_reference_brackets.rb]: Awesome, I'll give that a go.

**Comment by joshuapinter** [comment]
@Drenmi Yup, makes sense. I'll toss that in there, too.

File: spec/rubocop/cop/layout/space_inside_reference_brackets_spec.rb (hunk 3 above)
Comment (joshuapinter) [reply spec/rubocop/cop/layout/space_inside_reference_brackets_spec.rb]: Trust me, it pained me to abbreviate these words. 😀 Was just following the style in the rest of the file. I'll fix this.

**Comment by joshuapinter** [comment]
I have no idea how to squash these commits. I've tried 3 different ways and all the commits are showing up here. Any pointers?

**Comment by Drenmi** [comment]
> How do I go about squashing them on my side once I've already pushed them to this branch?

Use [interactive rebase](https://robots.thoughtbot.com/git-interactive-rebase-squash-amend-rewriting-history) to squash, then force push the branch. 🙂

**Comment by joshuapinter** [comment]
Ugh, that was painful. Not sure if I was doing that wrong but I had to manually fix the same conflict for every single commit. Regardless, it looks like it worked.

So once the tests pass hopefully you guys can merge it in. :)

**Comment by Drenmi** [comment]
Okay. Please just fix up the commit message. It's currently an amalgamation of all the previous commits'. (`git commit --amend`) 🙂

**Comment by joshuapinter** [comment]
Okay, I cleaned that up. Check it out now. Thanks.

**Comment by bbatsov** [comment]
We are! 👍 Thanks for working on this!

**Comment by joshuapinter** [comment]
👍 Thanks for making the library! 🙏

**Comment by garettarrowood** [comment]
I'm late to the party. But wanted to throw in a 'Thanks!' for fixing this bug!

**Comment by joshuapinter** [comment]
@garettarrowood 👍 You're welcome!
