### PR TITLE
[Fix #4481] Prevent `Style/WordArray` and `Style/SymbolArray` from registering offenses where percent arrays don't work

### LINKED ISSUE #4481: Style/SymbolArray auto-correct creating invalid syntax
This seems to be more of surprising behavior with the Ruby parser than Rubocop, but nonetheless it is still creating errors.

```
# original, valid syntax, pre-Rubocop
prepend_before_filter only: [ :create, :destroy ] { request.env["devise.skip_timeout"] = true }

# invalid (Ruby 2.2.4) syntax created by Rubocop
prepend_before_filter only: %i[create destroy] { request.env["devise.skip_timeout"] = true }
```

The Ruby error:

```
app/controllers/users/sessions_controller.rb:4: syntax error, unexpected '{', expecting keyword_end
...tion only: %i[create destroy] { request.env['devise.skip_tim...
...                               ^
app/controllers/users/sessions_controller.rb:4: syntax error, unexpected '}', expecting keyword_end
```

--------

## Expected behavior

When running `rubocop -a`, it produces valid Ruby syntax.

## Actual behavior

It creates invalid syntax.

## Steps to reproduce the problem

1. Given a file:
    ```ruby
    # thing.rb
    class Thing
      do_anything only: [:word, :two] { 5 }
    end
    ```

2. When you run Rubocop with auto-correct `rubocop -a thing.rb`

3. It produces an error:
  ```
  Inspecting 1 file
  E

  Offenses:

  thing.rb:2:21: C: [Corrected] Use %i or %I for an array of symbols.
    do_anything only: [:word, :two] { 5 }
                      ^^^^^^^^^^^^^
  thing.rb:2:34: E: unexpected token tLCURLY
  (Using Ruby 2.1 parser; configure using TargetRubyVersion parameter, under AllCops)
    do_anything only: %i[word two] { 5 }
                                   ^

  1 file inspected, 2 offenses detected, 1 offense corrected
  ```

## RuboCop version

`0.48.1 (using Parser 2.4.0.0, running on ruby 2.2.4 x86_64-darwin16)`

### PR DESCRIPTION
**Pull request by Drenmi**
When configured to enforce percent arrays, these cops would register offenses in cases like:

```ruby
foo [:bar, :baz] { qux }
```

However, using a percent array in this context results in a syntax error.

This change prevents the cops from registering offenses in this case.

-----------------

Before submitting the PR make sure the following are checked:

* [X] Wrote [good commit messages][1].
* [X] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [X] Used the same coding conventions as the rest of the project.
* [X] Feature branch is up-to-date with `master` (if not - rebase it).
* [X] Squashed related commits together.
* [X] Added tests.
* [X] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [X] All tests(`rake spec`) are passing.
* [X] The new code doesn't generate RuboCop offenses that are checked by `rake internal_investigation`.
* [X] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [ ] Updated cop documentation with `rake generate_cops_documentation` (required only when you've added a new cop or changed the configuration/documentation of an existing cop).

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: spec/rubocop/cop/style/symbol_array_spec.rb [hunk 1]
```diff
@@ -68,6 +68,11 @@
       expect_no_offenses('[:one, :two, :"space here"]')
     end
 
+    # Bug: https://github.com/bbatsov/rubocop/issues/4481
+    it 'does not register an offense in an ambiguous block context' do
+      expect_no_offenses('foo [:bar, :baz] { qux }')
```
Comment (pocke) [inline spec/rubocop/cop/style/symbol_array_spec.rb]: Ruby can't parse `foo %[] {block}`, but Ruby can parse `foo(%[]) {block}`.(with braces)
Does this cop add an offense for it?

Comment (Drenmi) [inline spec/rubocop/cop/style/symbol_array_spec.rb]: It did not. Good catch! Fixed it and added test cases for that. 🙂

**Comment by bbatsov** [comment]
👍
