### PR TITLE
[Fix #4646] Make `Lint/Debugger` aware of `Kernel` and cbase

### LINKED ISSUE #4646: Lint::Debugger does not find `Kernel.binding.pry`
## Expected behavior

When writing `Kernel.binding.pry` instead of `binding.pry` the Cop `Lint::Debugger` should raise an error.

## Actual behavior

There is no violation being raised.

## Steps to reproduce the problem

Write `Kernel.binding.pry` instead of `binding.pry` in any source file.

## RuboCop version

```
$ rubocop -V
0.49.1 (using Parser 2.4.0.0, running on ruby 2.3.4 x86_64-darwin16)
```

### PR DESCRIPTION
**Pull request by pocke**
`binding`, `debugger` and `byebug` is a `Kernel` method. Therefore those methods are callable with `Kernel` receiver expressly.

```bash
binding.pry        # => start a pry
Kernel.binding.pry # => start a pry
```

`save_and_open_page` and others are not defined in `Kernel`. Therefore those method is not callable with `Kernel` receiver.

```
     Failure/Error: Kernel.save_and_open_screenshot

     NoMethodError:
       undefined method `save_and_open_screenshot' for Kernel:Module
```

And this change makes the cop aware of `cbase`.

```ruby
Pry == ::Pry
```

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Used the same coding conventions as the rest of the project.
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] All tests(`rake spec`) are passing.
* [x] The new code doesn't generate RuboCop offenses that are checked by `rake internal_investigation`.
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Updated cop documentation with `rake generate_cops_documentation` (required only when you've added a new cop or changed the configuration/documentation of an existing cop).

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/lint/debugger.rb [hunk 1]
```diff
@@ -35,18 +35,25 @@ module Lint
...
+          {
+            (const nil :Kernel)
+            (const (cbase) :Kernel)
+          }
+        PATTERN
+
         def_node_matcher :debugger_call?, <<-PATTERN
-          {(send nil {:debugger :byebug} ...)
-           (send (send nil :binding)
+          {(send {nil #kernel?} {:debugger :byebug} ...)
```
Comment (Drenmi) [inline lib/rubocop/cop/lint/debugger.rb]: It might be worthwhile to break these up soon. WDYT? 🙂

**Comment by Drenmi** [comment]
<3

File: lib/rubocop/cop/lint/debugger.rb (hunk 1 above)
Comment (pocke) [inline lib/rubocop/cop/lint/debugger.rb]: Sorry, I don't understand. What did you mean "to break these up soon" ?

**Comment by bbatsov** [comment]
👍
