### PR TITLE
[Fix #3308] Make `Lint/NextWithoutAccumulator` aware of nested enumeration

### LINKED ISSUE #3308: Lint/NextWithoutAccumulator is reported incorrectly for a nested loop
## Expected behavior

Having a `reduce` loop and another loop inside of it, it's normal to `next` without an argument from the nested loop. It's only wrong to `next` without an argument from the `reduce` loop.

## Actual behavior

`Lint/NextWithoutAccumulator` is reported.

## Steps to reproduce the problem

Example code to reproduce:

```
result = [[1, 2, 3], [4, 5, 6]].inject([]) do |acc, elems|
  elems.each_with_index do |elem, i|
    next if i == 1
    acc << elem
  end
  acc
end

puts result
```

gets us

```
Inspecting 1 file
W

Offenses:

repro.rb:3:5: W: Lint/NextWithoutAccumulator: Use next with an accumulator argument in a reduce.
    next if i == 1
    ^^^^

1 file inspected, 1 offense detected
```

## RuboCop version

```
$ rubocop -V
0.37.2 (using Parser 2.3.0.6, running on ruby 2.1.2 x86_64-darwin14.0)```

### PR DESCRIPTION
**Pull request by Drenmi**
This cop would register an offense if a nested block contained a `next` without an accumulator.

```
[(1..3), (4..6)].reduce(0) do |acc, elems|
  elems.each_with_index do |elem, i|
    next if i == 1
    acc << elem
  end
  acc
end
```

This fix addresses that, by checking if the direct block parent of any offending `next` is indeed the block that we were inspecting.

### CODE REVIEW

**Comment by Drenmi** [comment]
@bbatsov: Rebased.

File: spec/rubocop/cop/lint/next_without_accumulator_spec.rb [hunk 1]
```diff
@@ -34,23 +46,28 @@ def code_with_accumulator(method_name)
...
-  include_examples 'reduce/inject', :reduce
-  include_examples 'reduce/inject', :inject
+  it_behaves_like 'reduce/inject', :reduce
+  it_behaves_like 'reduce/inject', :inject
 
   context 'given an unrelated block' do
     it 'accepts a bare next' do
       inspect_source(cop, code_without_accumulator(:foo))
-      expect(cop.offenses).to be_empty
+      expect(cop.offenses.size).to eq(0)
```
Comment (bbatsov) [inline spec/rubocop/cop/lint/next_without_accumulator_spec.rb]: Actually we favour the use of `be_empty`. :-)

Comment (Drenmi) [inline spec/rubocop/cop/lint/next_without_accumulator_spec.rb]: Whoops. I changed this because I'd seen so many instances of `eq(0)`. 😀 Will fix.
