### PR TITLE
[Fix #3032] Autocorrect predicates without space before args - e.g. is_a?Integer

### LINKED ISSUE #3032: Autocorrect "or" and "and" expressions with predicates that don't have spaces
When autocorrecting "and" and "or" expression that contain predicates methods with no space before the args, the first character of the arg is removed.

## Expected behavior
```ruby
false or 'a'.is_a?String
=> false || 'a'.is_a?(String)
```

## Actual behavior
```ruby
false or 'a'.is_a?String
=> false || 'a'.is_a?(tring)
```

## Steps to reproduce the problem

````ruby
# test.rb
'1'.is_a?Integer or 1.is_a?Integer
````

```rubocop -a test.rb`
=> 1 file inspected, 1 offense detected, 1 offense corrected ``` 

```ruby
# updated test.rb
'1'.is_a?(nteger) || 1.is_a?(nteger)
```
## RuboCop version

```
$ rubocop -V
0.39.0 (using Parser 2.3.0.7, running on ruby 2.1.5 x86_64-darwin14.0)
```

### PR DESCRIPTION
**Pull request by graemeboy**
I've never seen this codebase before, so I don't know how hacky this solution is.

Summary of problem:

Using rubocop autocorrect on the following lines of code:

```ruby
false or 'a'.is_a?String
=> false || 'a'.is_a?(tring)

'1'.is_a?Integer or 1.is_a?Integer
=> '1'.is_a?(nteger) || 1.is_a?(nteger)
```

PR adds six example cases to the test specs, and some code that makes all pass.

### CODE REVIEW

**Comment by graemeboy** [comment]
♻️

File: lib/rubocop/cop/style/and_or.rb [hunk 1]
```diff
@@ -119,7 +119,9 @@ def correctable_send?(node)
         def whitespace_before_arg(node)
           sb = node.source_range.source_buffer
           begin_paren = node.loc.selector.end_pos
-          Parser::Source::Range.new(sb, begin_paren, begin_paren + 1)
+          end_paren = begin_paren
+          end_paren += 1 unless node.source =~ /\?[!\S]/
```
Comment (bbatsov) [inline lib/rubocop/cop/style/and_or.rb]: I'd add some comment here as it's not obvious what you're checking for.

**Comment by bbatsov** [comment]
You should also add a changelog entry mentioning this fix.

File: CHANGELOG.md [hunk 2]
```diff
@@ -10,7 +10,7 @@
 * [#2993](https://github.com/bbatsov/rubocop/pull/2993): `Style/SpaceAfterColon` now checks optional keyword arguments. ([@owst][])
 
 ### Bug fixes
-
+* [#3033](https://github.com/bbatsov/rubocop/pull/3033): Fix autocorrecting parentheses for predicate methods without space before args. ([@graemeboy][])
```
Comment (bbatsov) [inline CHANGELOG.md]: The PR says this fixed #3032.

Comment (graemeboy) [inline CHANGELOG.md]: The PR itself is #3033, ha. Thanks :)

Comment (bbatsov) [inline CHANGELOG.md]: I know. But we typically refer here to the bug reports.

**Comment by graemeboy** [comment]
@bbatsov ♻️

**Comment by bbatsov** [comment]
👍
