### PR TITLE
[Fix #3558] Mixin autocorrection logic moved into Corrector classes

### LINKED ISSUE #3558: Don't define `#autocorrect` in mixins
I want to argue that we shouldn't define the `#autocorrect` method in mixins used by cops.
## What's wrong with it?
1. If I want to use a mixin in a cop that shouldn't implement auto-correct, I need to add a no-op `#autocorrect` definition to the cop. This is pretty icky.
2. If I want to use two mixins, both implementing `#autocorrect` in a cop, which method is finally defined depends on the order of the mixins. This is very fragile.
3. There might be more than one `#autocorrect` that makes sense for a mixin, depending on the context it is being used.
4. There is no easy way to see if, and if so which, auto-correct is defined from within a `Cop` body.
## What should we do instead?

We already have a suitable abstraction in the callable objects that `#autocorrect` return. A mixin could simply make any number of `corrector`s available for the `Cop` to return from it's own `#autocorrect` method.

Another option could be to have the mixin provide lower level methods that the cop can use to assemble it's own `#autocorrect`. The `Parentheses` mixin could provide `#remove_parentheses` and `#add_parentheses`, for example.
## Which mixins are currently implementing it?
- `AutocorrectAlignment`
- `EmptyLinesAroundBody`
- `FirstElementLineBreak`
- `MultilineLiteralBraceLayout`
- `Parentheses`
- `SpaceAfterPunctuation`
- `SpaceBeforePunctuation`
- `SpaceInside`
- `StringLiteralsHelp`
- `TrailingComma`
- `UnusedArgument`

### PR DESCRIPTION
**Pull request by garettarrowood**
This implements refactoring discussed in #3558 .

This procedure brought forth some drawbacks, but it also encapsulated logic successfully. The result is that every cop now defines it's own `#autocorrect`, and nothing is hidden inside a mixin. Breakdown of `#autocorrect`s defined in mixins from issue:

> ### What's wrong with it?
> 1. If I want to use a mixin in a cop that shouldn't implement auto-correct, I need to add a no-op `#autocorrect` definition to the cop. This is pretty icky.
> 1. If I want to use two mixins, both implementing #autocorrect in a cop, which method is finally defined depends on the order of the mixins. This is very fragile.
> 1. There might be more than one #autocorrect that makes sense for a mixin, depending on the context it is being used.
> 1. There is no easy way to see if, and if so which, auto-correct is defined from within a Cop body.

### Related "issue" this PR resolves 

Since this meant moving around a lot of functionality in our mixins, I took this as an opportunity to make all `mixin` methods private _where possible_.  This is related to #4439 .  The remaining public methods in mixins must remain public. ... Unfortunately, these additions and movement of the `private` modifier leak into most commits and are not encapsulated to just one. _Sorry!_

### Something this PR does _NOT_ do 

Catch every place where refactoring is warranted. -- I resolved a few extra places where `corrector` logic had seeped into mixins outside of `#autocorrect` methods directly. However, some alterations got complicated, particularly when dealing with how our test suite dynamically changes cop_config.  Once this PR reaches a deliverable status and is merged, I'll open up a couple issues for the places that deserve their own PR to extract Corrector logic.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [fail] Squashed related commits together.
* [x] Test coverage on all bits of this code.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `rake default` or `rake parallel`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/rails/application_record.rb [hunk 1]
```diff
@@ -28,6 +28,12 @@ class ApplicationRecord < Cop
         # rubocop:disable Layout/ClassStructure
         include RuboCop::Cop::EnforceSuperclass
         # rubocop:enable Layout/ClassStructure
+
+        def autocorrect(node)
+          lambda do |corrector|
+            corrector.replace(node.source_range, self.class::SUPERCLASS)
+          end
+        end
```
Comment (garettarrowood) [inline lib/rubocop/cop/rails/application_record.rb]: Moved the Rails `application_record` and `application_job` autocorrections directly into the cop because they were so slim.

File: lib/rubocop/cop/mixin/alignment.rb [hunk 2]
```diff
@@ -0,0 +1,62 @@
+# frozen_string_literal: true
+
+module RuboCop
+  module Cop
+    # This module does auto-correction of nodes that should just be moved to
```
Comment (bbatsov) [inline lib/rubocop/cop/mixin/alignment.rb]: I guess you should update the description of the mixins, as now they are not doing auto-correction anymore.

Comment (garettarrowood) [reply lib/rubocop/cop/mixin/alignment.rb]: I cleaned up this description and went through all the other mixins I adjusted and checked that none mentioned autocorrection.

**Comment by bbatsov** [comment]
Great job! 👍
