### PR TITLE
[Fix #4283] `Style/EmptyCaseCondition` autocorrect bugfix

### LINKED ISSUE #4283: Style/EmptyCaseCondition wrongly autocorrects multiple values
This is an issue about the `Style/EmptyCaseCondition` cop that wrongly autocorrects lines with multiples values.

--------

Given a file with :

```ruby
case
when my.foo?, my.bar?
  something
when my.baz?
  something_else
end
```

## Expected behavior

File should be modified to:

```ruby
if my.foo? || my.bar?
  something
elsif my.baz?
  something_else
end
```

## Actual behavior

File is modified to:

```ruby
if my.foo?, my.bar?
  something
elsif my.baz?
  something_else
end
```

Rubocop output is :

```
rubocop -D -a                
Inspecting 1 file
E

Offenses:

test.rb:1:1: C: [Corrected] Style/EmptyCaseCondition: Do not use empty case condition, instead use an if expression.
case
^^^^
test.rb:2:11: E: unexpected token tCOMMA
(Using Ruby 2.3 parser; configure using TargetRubyVersion parameter, under AllCops)
if my.foo?, my.bar?
          ^
test.rb:4:1: E: unexpected token kELSIF
(Using Ruby 2.3 parser; configure using TargetRubyVersion parameter, under AllCops)
elsif my.baz?
^^^^^
test.rb:6:1: E: unexpected token kEND
(Using Ruby 2.3 parser; configure using TargetRubyVersion parameter, under AllCops)
end
^^^
```

## RuboCop version

```
$ rubocop -V
0.48.1 (using Parser 2.4.0.0, running on ruby 2.3.3 x86_64-darwin16)
```

### PR DESCRIPTION
**Pull request by ilansh**
When first `when` condition of an empty case included comma-delimited
alternatives, autocorrect did not replace the comma with `||`.
This commit fixes the issue.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Used the same coding conventions as the rest of the project.
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] All tests are passing.
* [x] The new code doesn't generate RuboCop offenses.
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [ ] Updated cop documentation with `rake generate_cops_documentation` (required only when you've added a new cop or changed the configuration/documentation of an existing cop).

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: spec/rubocop/cop/style/empty_case_condition_spec.rb [hunk 1]
```diff
@@ -167,5 +167,29 @@
 
       it_behaves_like 'detect/correct empty case, accept non-empty case'
     end
+
+    context 'with first when branch including comma-delimited alternatives' do
```
Comment (bbatsov) [inline spec/rubocop/cop/style/empty_case_condition_spec.rb]: Won't this be an issue for every `when` branch? Why just the first one?

Comment (ilansh) [inline spec/rubocop/cop/style/empty_case_condition_spec.rb]: @bbatsov This particular issue happened because autocorrect of `when` branches was done for all branches except the first.
`when_nodes.shift` removed the first one from the array before the correction function had a chance to fix it, I replaced it with `when_nodes.first`.
One more thing which needed to be fixed was to replace `elsif` starting from second `when` branch instead of first - which was the case before due to the `shift`, thus the `when_nodes[1..-1]`).
If you look at the spec, there were already passing tests with comma-delimited alternatives, but not in the first `when` branch.
