### PR TITLE
[Fix #1935] Allow Symbol#to_proc blocks in Performance/Size

### LINKED ISSUE #1935: Performance/Size false positive: Array#count with Symbol#to_proc block
Passes: `[1, 2, 3].count { |x| x.even? }`
Fails: `[1, 2, 3].count(&:even?)`

### PR DESCRIPTION
**Pull request by m1foley**
This check should pass when passing a block to `count`, but `Symbol#to_proc` blocks were not being allowed like they should.

Fixes #1935

### CODE REVIEW

**Comment by jonas054** [comment]
The heading of the commit message should start `[Fix #1935]`.

**Comment by m1foley** [comment]
Oops, fixed the commit message.

**Comment by m1foley** [comment]
Added to CHANGELOG as well.

**Comment by bbatsov** [comment]
The build is failing because of a couple of long lines.

**Comment by m1foley** [comment]
I've fixed the spec descriptions that were > 80 chars. I can't figure out why coveralls is failing though; the file I changed is still at 100% coverage.

File: spec/rubocop/cop/performance/size_spec.rb [hunk 1]
```diff
@@ -56,6 +56,12 @@
       expect(cop.messages).to be_empty
     end
 
+    it 'does not register an offense when calling count with a to_proc block' do
+      inspect_source(cop, '[1, 2, 3].count(&:nil?)')
+
+      expect(cop.messages).to be_empty
```
Comment (bbatsov) [inline spec/rubocop/cop/performance/size_spec.rb]: I'd suggest checking `cop.offenses` instead as it's more natural.

**Comment by bbatsov** [comment]
You can ignore this. Just address my tiny remark and rebase on top of the current `master`.

File: spec/rubocop/cop/performance/size_spec.rb (hunk 1 above)
Comment (m1foley) [inline spec/rubocop/cop/performance/size_spec.rb]: Fixed. The rest of the spec uses `cop.messages` though.

**Comment by m1foley** [comment]
Rebased on master. Should be good to merge.
