### PR TITLE
[Fix #4866] Prevent Layout/BlockEndNewline cop from introducing trailing whitespaces

### LINKED ISSUE #4866: Layout/BlockEndNewline cop introduces trailing whitespaces
## Expected behavior

The Layout/BlockEndNewline cop is introducing trailing whitespaces when doing the auto-correct.

Here is a diff of the [rspec test](https://github.com/bbatsov/rubocop/blob/master/spec/rubocop/cop/layout/block_end_newline_spec.rb#L44) for that cop. I would expect that it doesn't introduce trailing whitespaces:

```diff
     expect(new_source).to eq(['test do',
-                              '  foo ',
+                              '  foo',
                               'end',
                               ''].join("\n"))
```

## Actual behavior

Running the auto-correct introduces trailing whitespaces.

## Steps to reproduce the problem

Adjust the test like done above.

## RuboCop version

0.49.1 as well as master branch

### PR DESCRIPTION
**Pull request by bgeuken**
The auto-correct of the Layout/BlockEndNewline cop moves closing block
delimiters to a separate line.

When doing this, the auto-correct was not taking into account the
whitespaces that seperate the code of the block from it's delimiter.

Therefore it introduced trailing whitespaces when auto-correcting.

Fixes #4866

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Used the same coding conventions as the rest of the project.
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] All tests(`rake spec`) are passing.
* [x] The new code doesn't generate RuboCop offenses that are checked by `rake internal_investigation`.
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Updated cop documentation with `rake generate_cops_documentation` (required only when you've added a new cop or changed the configuration/documentation of an existing cop).

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/layout/block_end_newline.rb [hunk 1]
```diff
@@ -55,6 +56,18 @@ def indentation_of_block_start_line(node)
           match = /\S.*/.match(node.loc.begin.source_line)
           match.begin(0)
         end
+
+        def range_to_replace(node)
```
Comment (Drenmi) [inline lib/rubocop/cop/layout/block_end_newline.rb]: Could you rename this to something that isn't coupled to the context of its use in `#autocorrect`? 🙂

**Comment by Drenmi** [comment]
You'll need to rebase on `master` to remove the `CHANGELOG` conflict. 🙇

File: lib/rubocop/cop/layout/block_end_newline.rb (hunk 1 above)
Comment (bgeuken) [reply lib/rubocop/cop/layout/block_end_newline.rb]: Good point. How about `delimiter_range`?
