### PR TITLE
[Fix #4885] Fix false offense detected by `Style/MixinUsage` cop

### LINKED ISSUE #4885: false offense detected by Style/MixinUsage
## Expected behavior

```ruby
thing = Class.new do
  attr_accessor :value_text, :value_type
  include IsNameValueType
end

RSpec.describe IsNameValueType do
  subject { thing.new }
  # tests
end
```

expect Mixin usage to be correct

## Actual behavior

```
Inspecting 4 files
.C..

Offenses:

spec/models/concerns/is_name_value_type_spec.rb:3:3: C: Style/MixinUsage: include is used at the top level. Use inside class or module.
  include IsNameValueType
  ^^^^^^^^^^^^^^^^^^^^^^^

4 files inspected, 1 offense detected
```

## Steps to reproduce the problem

create the test as in the expected behaviour and run `rubocop <filename>`

## RuboCop version

Include the output of `rubocop -V`. Here's an example:

```
➔ rubocop -V
0.51.0 (using Parser 2.4.0.0, running on ruby 2.4.1 x86_64-darwin16)
```

### PR DESCRIPTION
**Pull request by koic**
Fixes https://github.com/bbatsov/rubocop/issues/4885.

This change makes the following modification based on Issue's report.

## Using `include` inside block

The follwing does not register an offense.

```ruby
Class.new do
  include IsNameValueType
end
```

and

```ruby
RSpec::Matchers.define :do_something do
  include Mixin
end
```

## Multiple definition classes in one

The follwing does not register an offense.

```ruby
class C1
  include M
end

class C2
  include M
end
```

## Nested module

The follwing register an offense.

```ruby
include M::M2::M3

class C
end
```

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Used the same coding conventions as the rest of the project.
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] All tests(`rake spec`) are passing.
* [x] The new code doesn't generate RuboCop offenses that are checked by `rake internal_investigation`.
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [ ] Updated cop documentation with `rake generate_cops_documentation` (required only when you've added a new cop or changed the configuration/documentation of an existing cop).

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/style/mixin_usage.rb [hunk 1]
```diff
@@ -48,7 +48,7 @@ class MixinUsage < Cop
 
         def_node_matcher :include_statement, <<-PATTERN
           (send nil? ${:include :extend :prepend}
-            (const nil? _))
+            (const _ _))
```
Comment (pocke) [inline lib/rubocop/cop/style/mixin_usage.rb]: We can replace `(const _ _)` with `const`

Comment (koic) [reply lib/rubocop/cop/style/mixin_usage.rb]: I fixed it. Thanks!

File: lib/rubocop/cop/style/mixin_usage.rb [hunk 2]
```diff
@@ -61,6 +61,8 @@ def on_send(node)
         private
 
         def top_level_node?(node)
+          return if node.class_type?
+
           if node.parent.parent.nil?
             node.sibling_index.zero?
```
Comment (pocke) [inline lib/rubocop/cop/style/mixin_usage.rb]: I guess using `sibling_index` is not correct to check top level.
For example, this cop does not add offenses to the code.


```ruby
def foo
end
include A # This include's `.parent.parent` is a nil, and the sibling index is not zero.
```

```bash
$ rubocop --only Style/MixinUsage
Inspecting 1 file
.

1 file inspected, no offenses detected
```


Maybe we can use `SendNode#macro?` instead. 

https://github.com/bbatsov/rubocop/blob/8459e201400f852df7c8ac01dd2ad5e760c092d5/lib/rubocop/ast/node/mixin/method_dispatch_node.rb#L32-L41

File: lib/rubocop/cop/style/mixin_usage.rb [hunk 3]
```diff
@@ -61,6 +61,8 @@ def on_send(node)
         private
 
         def top_level_node?(node)
+          return if node.class_type?
+
           if node.parent.parent.nil?
```
[the remark this answers is not in the document]
Comment (koic) [reply lib/rubocop/cop/style/mixin_usage.rb]: Surely the consideration of this case was missing 💦

File: lib/rubocop/cop/style/mixin_usage.rb (hunk 2 above)
Comment (koic) [reply lib/rubocop/cop/style/mixin_usage.rb]: It was this method that I really wanted🙏  This also can remove some unnecessary conditions.

File: lib/rubocop/cop/style/mixin_usage.rb [hunk 4]
```diff
@@ -48,24 +48,22 @@ class MixinUsage < Cop
 
         def_node_matcher :include_statement, <<-PATTERN
           (send nil? ${:include :extend :prepend}
-            (const nil? _))
+            const)
         PATTERN
 
         def on_send(node)
           return unless (statement = include_statement(node))
```
Comment (Drenmi) [inline lib/rubocop/cop/style/mixin_usage.rb]: We will normally use a block here, i.e.:

```ruby
include_statement(node) do |statement|
  return unless implicit_style?(node)

  add_offense(node, message: format(MSG, statement: statement))
end
```

Ideally the node matcher would integrate the call to `#implicit_style?` through a funcall as well. 🙂

File: spec/rubocop/cop/style/mixin_usage_spec.rb [hunk 5]
```diff
@@ -5,7 +5,7 @@
   subject(:cop) { described_class.new(config) }
 
   context 'include' do
-    it 'registers an offense when using outside class' do
+    it 'registers an offense when using outside class (used above)' do
```
Comment (Drenmi) [inline spec/rubocop/cop/style/mixin_usage_spec.rb]: Could you please add a test case for this:

```ruby
expect_no_offenses(<<-RUBY.strip_indent)
  Foo.include B
  class Bar; end
end
```

File: lib/rubocop/cop/style/mixin_usage.rb [hunk 6]
```diff
@@ -48,24 +48,22 @@ class MixinUsage < Cop
...
 
         private
 
-        def top_level_node?(node)
-          if node.parent.parent.nil?
-            node.sibling_index.zero?
-          else
-            top_level_node?(node.parent)
-          end
+        def implicit_style?(node)
```
Comment (Drenmi) [inline lib/rubocop/cop/style/mixin_usage.rb]: Not sure about the name `#implicit_style?`. I don't see how it being inside a context is "implicit" and in the top level "explicit"? 🙂

File: lib/rubocop/cop/style/mixin_usage.rb [hunk 7]
```diff
@@ -48,24 +48,22 @@ class MixinUsage < Cop
...
+          return true if node.parent.nil?
```
Comment (Drenmi) [inline lib/rubocop/cop/style/mixin_usage.rb]: I think:

```ruby
def implicit_style?
  node.parent || !node.macro?
end
```

is slightly easier to understand. WDYT?

File: lib/rubocop/cop/style/mixin_usage.rb (hunk 6 above)
Comment (pocke) [inline lib/rubocop/cop/style/mixin_usage.rb]: I think it should be recursive, and check class/module types.
For example: (but the example does not pass `Class.new` test case.)

```ruby
def implicit_style?(node)
  parent = node.parent
  return true unless parent
  return false if parent.respond_to?(:macro?) && parent.macro?
  return false if parent.class_type? || parent.module_type?
  implicit_style?(parent)
end
```



Currently the cop does not add offence for the following code.


```ruby
some_method do
  include A
end
```

Comment (Drenmi) [reply lib/rubocop/cop/style/mixin_usage.rb]: How about something like this?

```ruby
def accepted_include?(node)
  return true unless node.macro?
 
  node.each_ancestor(:class, :module, :send, :block).any? do |ancestor|
    accepted_include_context?(ancestor)
  end
end

def accepted_include_context?(ancestor)
  ancestor.class_type? || ancestor.module_type? || dynamic_class_definition?(ancestor)
end

def dynamic_class_definition?(ancestor)
  # Check for Class.new, class_eval, etc.
end
```

(I'm not sure

Comment (koic) [reply lib/rubocop/cop/style/mixin_usage.rb]: Indeed. It was named with an implicit assumption that [3 types of support](https://github.com/bbatsov/rubocop/pull/4840#issuecomment-335071288) will be done in the future 💦  I changed it to `accepted_include` proposed by [the following comment](https://github.com/bbatsov/rubocop/pull/4941/files#r147393506).

File: lib/rubocop/cop/style/mixin_usage.rb (hunk 7 above)
Comment (koic) [reply lib/rubocop/cop/style/mixin_usage.rb]: Right! I changed the method name to `accepted_include?`, so I reversed the condition, but I think it is easy to understand 😃

File: spec/rubocop/cop/style/mixin_usage_spec.rb (hunk 5 above)
Comment (koic) [reply spec/rubocop/cop/style/mixin_usage_spec.rb]: I added this test case.This is an important case 💦

File: lib/rubocop/cop/style/mixin_usage.rb (hunk 6 above)
Comment (koic) [reply lib/rubocop/cop/style/mixin_usage.rb]: I don't understand 2 things 😓 

1. Test cases that need recursive and class/module types
2. About the following use case

```ruby
some_method do
  include A
end
```

## 1. Test cases that need recursive and class/module types

Even without recursive and class/module types, there is no problem with existing bug cases (The test cases that currently exists passes). I could not make a test cases that fails without recursive and class/module types.

## 2. About the following use case

```ruby
some_method do
  include A
end
```

For this use case, I'd like to support with another PR at another opportunity. First of all, in this PR, I'd like to solve the known issue of informing what is not a offense as a offense.

**Comment by bbatsov** [comment]
Looks good to me. Rebase & squash.

**Comment by koic** [comment]
Thanks. I've done rebase and squash.

**Comment by bbatsov** [comment]
👍

**Comment by timoschilling** [comment]
@bbatsov can you release a version containing this fix?
