### PR TITLE
[Fix #4063] Fix Rails/ReversibleMigration misdetection

### LINKED ISSUE #4063: 0.47.1: Rails/ReversibleMigration misdetection
```
class AddNewColumn < ActiveRecord::Migration[5.0]
  def change
    change_table(:users) do |t|
      t.string :new_column
    end
  end
end
```

## Expected behavior

It should pass without problems. `change_table` is reversible. 

## Actual behavior

    C: Rails/ReversibleMigration: change_table is not reversible.

## RuboCop version

```
0.47.1 (using Parser 2.4.0.0, running on ruby 2.4.0 x86_64-darwin16)
```

### PR DESCRIPTION
**Pull request by gPrado**
Fixes #4063 by allowing Rails 4+ code to have `change_table` calls according to AR Migrations [docs](http://edgeguides.rubyonrails.org/active_record_migrations.html#using-the-change-method):

`change_table is also reversible, as long as the block does not call change, change_default or remove.`

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Used the same coding conventions as the rest of the project.
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] All tests are passing.
* [x] The new code doesn't generate RuboCop offenses.
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Updated cop documentation with `rake generate_cops_documentation` (required only when you've added a new cop or changed the configuration/documentation of an existing cop).

### CODE REVIEW

File: lib/rubocop/cop/rails/reversible_migration.rb [hunk 1]
```diff
@@ -7,16 +7,18 @@ module Rails
       # reversible.
       #
       # @example
+      #   # change_table
```
Comment (bbatsov) [inline lib/rubocop/cop/rails/reversible_migration.rb]: I don't see the point in adding this here.

File: lib/rubocop/cop/rails/reversible_migration.rb [hunk 2]
```diff
@@ -7,16 +7,18 @@ module Rails
...
       #   def change
       #     change_table :users do |t|
-      #       t.column :name, :string
+      #       t.remove :name
       #     end
       #   end
       #
       #   # good
       #   def change
-      #     create_table :users do |t|
```
Comment (bbatsov) [inline lib/rubocop/cop/rails/reversible_migration.rb]: Aren't both options a good solution?

File: lib/rubocop/cop/rails/reversible_migration.rb [hunk 3]
```diff
@@ -26,11 +28,11 @@ module Rails
       #     reversible do |dir|
       #       change_table :users do |t|
       #         dir.up do
-      #           t.column :name, :string
+      #           t.change :price, :string
```
Comment (bbatsov) [inline lib/rubocop/cop/rails/reversible_migration.rb]: Same here.

File: lib/rubocop/cop/rails/reversible_migration.rb [hunk 4]
```diff
@@ -93,9 +95,12 @@ module Rails
       # @see http://api.rubyonrails.org/classes/ActiveRecord/Migration/CommandRecorder.html
       class ReversibleMigration < Cop
         MSG = '%s is not reversible.'.freeze
+        IRREVERSIBLE_CHANGE_TABLE_CALLS = %i[
```
Comment (bbatsov) [inline lib/rubocop/cop/rails/reversible_migration.rb]: Calls? I think this terminology is a bit misleading.

Comment (bbatsov) [inline lib/rubocop/cop/rails/reversible_migration.rb]: Ah, I see the whole file uses this terminology.

File: lib/rubocop/cop/rails/reversible_migration.rb (hunk 1 above)
Comment (gPrado) [inline lib/rubocop/cop/rails/reversible_migration.rb]: There are examples for each special case (`drop_table`, `change_column_default`, `remove_column` and `remove_foreign_key`) so I added one entry for `change_table` as well. 

Maybe I could keep the general examples and only add the new ones at the bottom? In this case I'd still have to update the old examples since some uses of `change_table` are no longer "bad".
