### PR TITLE
[Fix #5155] Fix a false negative for `Naming/ConstantName` cop

### LINKED ISSUE #5155: Naming/ConstantName ignores constants that are frozen
If you give a constant a name that is not in `SCREAMING_SNAKE_CASE` the cop _Naming/ConstantName_ raises an offence. If you then `.freeze` that constant the offence is not detected.

--------

## Expected behavior

I expect Rubocop's _Naming/ConstantName_ cop to raise an offence for a mis-named constant whether the constant is frozen or not.

## Actual behavior

If the mis-named constant is frozen with `.freeze` the _Naming/ConstantName_ offence is not detected.

## Steps to reproduce the problem

1. Create a class in `my_class.rb` as follows:

```ruby
class MyClass
  MyConstant = "x"
end
```

2. Run Rubocop against that class

```bash
$ rubocop my_class.rb
Inspecting 1 file
C

Offenses:

tmp/my_class.rb:2:3: C: Naming/ConstantName: Use SCREAMING_SNAKE_CASE for constants. (https://github.com/bbatsov/ruby-style-guide#screaming-snake-case)
  MyConstant = "x"
  ^^^^^^^^^^
tmp/my_class.rb:2:16: C: Style/MutableConstant: Freeze mutable objects assigned to constants.
  MyConstant = "x"
               ^^^
```

3. Amend the class so that the constant is frozen

```ruby
class MyClass
  MyConstant = "x".freeze
end
```

4. Run Rubocop against that class again

```bash
$ rubocop my_class.rb
Inspecting 1 file
.

1 file inspected, no offenses detected
```

## RuboCop version

Include the output of `rubocop -V`. Here's an example:

```
$ rubocop -V
0.51.0 (using Parser 2.4.0.2, running on ruby 2.2.2 x86_64-darwin16)
```

### PR DESCRIPTION
**Pull request by koic**
Fixes #5155.

This PR fixes a false negative for `Naming/ConstantName` cop when
using frozen object assignment.

It also fixed the offenses that occurred in RuboCop itself.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Used the same coding conventions as the rest of the project.
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] All tests(`rake spec`) are passing.
* [x] The new code doesn't generate RuboCop offenses that are checked by `rake internal_investigation`.
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [ ] Updated cop documentation with `rake generate_cops_documentation` (required only when you've added a new cop or changed the configuration/documentation of an existing cop).

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/naming/constant_name.rb [hunk 1]
```diff
@@ -28,7 +28,8 @@ def on_casgn(node)
           # NewClass = something_that_returns_a_class
           # It's also ok to assign a class constant another class constant
           # SomeClass = SomeOtherClass
-          return if value && %i[send block const casgn].include?(value.type)
+          return if value && (%i[block const casgn].include?(value.type) ||
+                    value.send_type? && value.method_name != :freeze)
```
Comment (bbatsov) [inline lib/rubocop/cop/naming/constant_name.rb]: I think this can be extended to a whole list of safe methods - `to_s`, `to_a`, etc.

Comment (koic) [reply lib/rubocop/cop/naming/constant_name.rb]: Thanks for the review.
I see. For example, I think that we can prepare the following settings in default.yml.

```yaml
Naming/ConstantName
  Whitelist:
    - freeze
```

However, I don't know the following things.

- How much false negatives occur in cases other than `freeze`
- Criteria for preparing defaults other than `to_s`,` to_a`

How about opening another PR that sets `freeze` to `Whitelist` in default.yml?
Or is there any other good idea?

Comment (Drenmi) [reply lib/rubocop/cop/naming/constant_name.rb]: Off the top of my head, shouldn't it rather check that first receiver is a literal?

Comment (pocke) [reply lib/rubocop/cop/naming/constant_name.rb]: Maybe it should not be a whitelist, be a blacklist.

For example:

```ruby
def_node_matcher :class_return_method?, <<-P
  {
    (send (const _ :Class) :new ...)
    ...
  }
P
return if value && (%i[block const casgn].include?(value.type) || class_return_method?(value))
```

And I think RuboCop should give up on `some_user_defined_method`, or we can add `ReturnClassMethods`.

What do you think?

Comment (Drenmi) [reply lib/rubocop/cop/naming/constant_name.rb]: > Maybe it should not be a whitelist, be a blacklist.

I don't think this will work, because we don't know what methods return at runtime, so marking all other method sends as offenses is probably too aggressive. It is not on par with how we handle method sends in other cops.

> And I think RuboCop should give up on some_user_defined_method, or we can add ReturnClassMethods.
>
> What do you think?

I am also inclined to think that this cop doesn't quite need a configurable whitelist.

Comment (koic) [reply lib/rubocop/cop/naming/constant_name.rb]: Thank you for the ideas. I will try to improve by using only AST without using configurable whitelist or blacklist.

Comment (koic) [reply lib/rubocop/cop/naming/constant_name.rb]: I fixed that following your advices. 688acd1

File: lib/rubocop/cop/naming/constant_name.rb [hunk 2]
```diff
@@ -21,18 +21,32 @@ class ConstantName < Cop
...
         def on_casgn(node)
           _scope, const_name, value = *node
 
           # We cannot know the result of method calls like
           # NewClass = something_that_returns_a_class
           # It's also ok to assign a class constant another class constant
           # SomeClass = SomeOtherClass
-          return if value && (%i[block const casgn].include?(value.type) ||
-                    value.send_type? && value.method_name != :freeze)
+          return if value && %i[block const casgn].include?(value.type) ||
```
Comment (bbatsov) [inline lib/rubocop/cop/naming/constant_name.rb]: You should update the comment preceding the changed code.

Comment (koic) [reply lib/rubocop/cop/naming/constant_name.rb]: I updated it. 092750fc3
