### PR TITLE
[Fix #5016] Allow capitals with accents in Style/ConstantName

### LINKED ISSUE #5016: Style/ConstantName gives a false positive for SCREAMING_SNAKE_CASE with accents
`Rubocop::Cop::Style::ConstantName` enforces that constant names must be written using SCREAMING_SNAKE_CASE, by comparing them to its regex, `SNAKE_CASE`.

Capital letters can have accents, but the regular expression only permits unaccented letters A-Z. We should also allow capital letters with accents.

--------

## Expected behavior

```ruby
MATÍAS = "matías"
```

should be permitted by the cop, just as:

```ruby
MATIAS = "matías"
```

is permitted.

## Actual behavior

Rubocop detects an offence.

## Steps to reproduce the problem

Define a constant using what looks like SCREAMING_SNAKE_CASE, but including capital letterswith accents.

## RuboCop version

```
$ rubocop -V
0.51.0 (using Parser 2.4.0.0, running on ruby 2.4.2 x86_64-darwin16)
```

### PR DESCRIPTION
**Pull request by timrogers**
`Rubocop::Cop::Style::ConstantName` enforces that constant names must be written using SCREAMING_SNAKE_CASE, by comparing them to its regex, `SNAKE_CASE`.

Capital letters can have accents, but the regular expression only permits unaccented letters A-Z.

This modifies the regular expression to also permit capital letters with accents using [POSIX character classes][], and adds a spec confirming this behaviour.

Fixes https://github.com/bbatsov/rubocop/issues/5016.

[POSIX character classes]: https://en.wikibooks.org/wiki/Regular_Expressions/POSIX_Basic_Regular_Expressions#Character_classes

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Used the same coding conventions as the rest of the project.
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] All tests(`rake spec`) are passing.
* [x] The new code doesn't generate RuboCop offenses that are checked by `rake internal_investigation`.
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Updated cop documentation with `rake generate_cops_documentation` (required only when you've added a new cop or changed the configuration/documentation of an existing cop).

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by Drenmi** [comment]
Okay with me. You might need to disable `Naming/AsciiIdentifiers` though, or you'll get an offense from there. 🙂

File: lib/rubocop/cop/naming/constant_name.rb [hunk 1]
```diff
@@ -19,7 +19,7 @@ module Naming
       #   INCH_IN_CM = 2.54
       class ConstantName < Cop
         MSG = 'Use SCREAMING_SNAKE_CASE for constants.'.freeze
-        SNAKE_CASE = /^[\dA-Z_]+$/
+        SNAKE_CASE = /^[\dA-Z\u00C0-\u00DC_]+$/
```
Comment (rrosenblum) [inline lib/rubocop/cop/naming/constant_name.rb]: I think you may be missing a character in this range.

```ruby
[1] pry(main)> "\u00DD"
=> "Ý"
```

**Comment by timrogers** [comment]
@rrosenblum @Drenmi Should be ready to go now!

File: lib/rubocop/cop/naming/constant_name.rb [hunk 2]
```diff
@@ -19,7 +19,7 @@ module Naming
       #   INCH_IN_CM = 2.54
       class ConstantName < Cop
         MSG = 'Use SCREAMING_SNAKE_CASE for constants.'.freeze
-        SNAKE_CASE = /^[\dA-Z_]+$/
+        SNAKE_CASE = /^[\dA-Z\u00C0-\u00DD_]+$/
```
Comment (jonas054) [inline lib/rubocop/cop/naming/constant_name.rb]: Stopping at `\u00DD` seems arbitrary to me, see http://www.fileformat.info/info/unicode/category/Lu/list.htm
How about using a POSIX character class? `/^[\d[:upper:]_]+$/` or even `/^[[:digit:][:upper:]_]+$/`, but note that when we allow non-ASCII characters we open up for identifier names like `XӞ௮` in the screaming snake case category (Ruby constants must begin with an upper case ASCII letter). I'm not saying that's wrong, just providing an example.

**Comment by bbatsov** [comment]
This kind of contradicts the common rule of thumb to stick to ASCII in identifiers, so I'm wondering about the usefulness of this change. Frankly, I've never seen a good reason to start using non-ascii characters as identifiers of any kind.

**Comment by timrogers** [comment]
Happy to leave this if people don't think it's a good idea! But if we want to stipulate that you should only use ASCII characters (which would be a reasonable and viable choice), then that should explicitly be part of the description of this cop rather than an explicit thing.

@bbatsov What do you think?

**Comment by Drenmi** [comment]
> [...] if we want to stipulate that you should only use ASCII characters (which would be a reasonable and viable choice), then that should explicitly be part of the description of this cop rather than an explicit thing.

There's a separate cop explicitly stating to use only ASCII in identifiers. 🙂

File: lib/rubocop/cop/naming/constant_name.rb (hunk 2 above)
Comment (Drenmi) [reply lib/rubocop/cop/naming/constant_name.rb]: It also seems `U+00D7` is ... multiplication sign. 😅

**Comment by jonas054** [comment]
Yes, and since `Naming/AsciiIdentifiers` exists, I think it's better if this cop (`Style/ConstantName`) accepts non-ASCII characters, just to let `Naming/AsciiIdentifiers` do its job without interfering.

**Comment by timrogers** [comment]
Agree with @jonas054's approach on letting `Naming/AsciiIdentifiers` do its own discrete job. If I turn it off, I should potentially be allowed non-ASCII constant identifiers.

I think using the POSIX character classes would work - I've double-checked and they do work with accented letters. How about:

```ruby
/^[[:digit:][:upper:]_]+$/
```

as suggested by @jonas054?

**Comment by bbatsov** [comment]
@timrogers ping :-)

**Comment by timrogers** [comment]
@bbatsov Thanks for the ping - on it 🚀

**Comment by timrogers** [comment]
@bbatsov Should be ready to go now!

File: spec/rubocop/cop/naming/constant_name_spec.rb [hunk 3]
```diff
@@ -40,6 +40,10 @@
     expect_no_offenses('TOP_TEST, TEST_2 = 5, 6')
   end
 
+  it 'allows screaming snake case with accents' do
+    expect_no_offenses('TÖP_TEST = 5')
+  end
+
```
Comment (pocke) [inline spec/rubocop/cop/naming/constant_name_spec.rb]: [IMO] We should have a test case. The test case tests a constant with small case character with accents.

For example:

```ruby
it 'registers an offense for ...' do
  expect_offense(<<-RUBY)
    Aí_BCDEF = 5
    ^^^^^^^^^^ message
  RUBY
end
```

**Comment by timrogers** [comment]
I've made a few more updates:

* Improving the specs to test that small case letters with accents trigger an offense
* Adding a comment to the `SNAKE_CASE` regular expression explaining why we use the POSIX character classes
* Improving the commit message to be more up to date
* Improving the examples of good and bad constant names

**Comment by bbatsov** [comment]
@timrogers The manual is generated from the class documentation. You should actually update it and run the rake task that generates the manual afterwards to update it.

**Comment by timrogers** [comment]
@bbatsov Should be ready to go now! :rocket:

**Comment by bbatsov** [comment]
@timrogers There's a conflict that needs to be resolved. Please, rebase on top of the current master.

**Comment by timrogers** [comment]
@bbatsov Done! (Sorry for the high latency - I've been busy recently.)
