### PR TITLE
[Fix #3363] Style/EmptyElse autocorrection removes comments from braches

### LINKED ISSUE #3363: 0.50.0: Style/EmptyElse autocorrection removes comments from branches
`Style/EmptyElse` autocorrection removes comments from branches that contain no runnable code.
## Test case

```
a = true
if a
  puts 'OK'
else
  # TODO: implement else branch
end
```
## Expected behavior

No change in the code.
## Actual behavior

```
a = true
puts 'OK' if a
```
## Steps to reproduce the problem
1. Put test case in a `test.rb` file
2. Run `rubocop -a test.rb`
## RuboCop version

```
0.42.0 (using Parser 2.3.1.2, running on ruby 2.3.1 x86_64-darwin14)
```

### PR DESCRIPTION
**Pull request by dpostorivo**
This fixes the issue with Style/EmptyElse removing empty elses that also removed comments. The methodology for this fix is it checks for comments within the range of the else and end keywords.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Used the same coding conventions as the rest of the project.
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] All tests(`rake spec`) are passing.
* [x] The new code doesn't generate RuboCop offenses that are checked by `rake internal_investigation`.
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [ ] Updated cop documentation with `rake generate_cops_documentation` (required only when you've added a new cop or changed the configuration/documentation of an existing cop).

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/style/empty_else.rb [hunk 1]
```diff
@@ -112,14 +112,24 @@ def nil_check(node)
...
           lambda do |corrector|
             end_pos = base_if_node(node).loc.end.begin_pos
-
             corrector.remove(range_between(node.loc.else.begin_pos, end_pos))
           end
         end
 
+        def comment_in_else?(node)
+          range = else_line_range(node.loc)
+          processed_source.comments.find { |c| range.include?(c.loc.line) }
```
Comment (bbatsov) [inline lib/rubocop/cop/style/empty_else.rb]: @Drenmi This looks like something common enough that we should extract it (checking there are comments in some range, maybe even something more granular).

Comment (Drenmi) [reply lib/rubocop/cop/style/empty_else.rb]: Agree.

**Comment by dpostorivo** [comment]
@bbatsov @Drenmi anything I need to do to get the PR approved?

**Comment by bbatsov** [comment]
Looks good to me. Sorry about the slow turnaround - seems I forgot about it.
