### PR TITLE
[Fix #1676] Disable argument lambda auto-correction in Lambda

### LINKED ISSUE #1676: Incorrect handling of multiline blocks in the middle of the method
`0.29.1 (using Parser 2.2.0.3, running on ruby 2.1.5 x86_64-darwin14.0)`
`ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-darwin14.0]`

Happens in Rails 4-style association definition

```diff
-  has_many :kittens, -> {
+  has_many :kittens, lambda do
     where(cats: Cat.young.where_values_hash)
-  }, source: :cats, class_name: 'Cat'
+  end, source: :cats, class_name: 'Cat'
```

Causes `SyntaxError`:

```
.../2.1.0/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:247:in `require': ../Projects/catbook/app/models/master.rb:11: syntax error, unexpected ',', expecting keyword_end (SyntaxError)
  end, source: :cats, class_name: 'Cat'
      ^
```

### PR DESCRIPTION
**Pull request by lumeet**
Don't let `Style/Lambda` perform auto-corrections that would change
the abstract syntax tree.

This was the cleanest solution I could come up with. I'm not quite sure, though, if it violates some rules unknown to me. Please, review carefully. :)

### CODE REVIEW

File: lib/rubocop/cop/style/lambda.rb [hunk 1]
```diff
@@ -25,19 +27,19 @@ def on_block(node)
...
           elsif selector == '->' && length > 1
-            add_offense(block_method, :expression, MULTI_MSG)
+            add_offense(node, block_method.loc.expression, MULTI_MSG)
           end
         end
 
         private
 
-        def add_offense_for_single_line(block_method, args)
+        def add_offense_for_single_line(block_node, expression, args)
```
Comment (jonas054) [inline lib/rubocop/cop/style/lambda.rb]: Instead of `expression`, call the parameter `location`. It's used for selecting what will be highlighted in the report, and in the base class it's called `loc`.

**Comment by jonas054** [comment]
Looks good! I just had one small comment.

**Comment by lumeet** [comment]
Fixed `expression` -> `location` and rebased.

**Comment by bbatsov** [comment]
:+1:
