### PR TITLE
[Fix #5401] Fix Style/RedundantReturn to trigger when blocks present.

### LINKED ISSUE #5401: Style/RedundantReturn doesn't detect offenses if an ensure block is present
The Style/RedundantReturn cop doesn't detect offenses if an `ensure` block is present in a method. 

--------

## Expected behavior

Redundant returns should be flagged as an offense even if the method has an `ensure` block.

## Actual behavior

No offenses are detected.

## Steps to reproduce the problem

The following code should trigger an offense:

```ruby
class Foo
  def bar
    return nil
  ensure
    nil
  end
end
```

## RuboCop version

```
$ rubocop -V
0.52.1
```

### PR DESCRIPTION
**Pull request by asherkach**
Note that the new tests fail without these changes. Also note that these changes caused an existing redundant return within this codebase to be flagged.

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `rake default` or `rake parallel`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/style/redundant_return.rb [hunk 1]
```diff
@@ -73,14 +73,19 @@ def arguments?(args)
           !args.first.begin_type? || !args.first.children.empty?
         end
 
+        # rubocop:disable Metrics/CyclomaticComplexity
```
Comment (asherkach) [inline lib/rubocop/cop/style/redundant_return.rb]: That this causes a `Metrics/CylcomaticComplexity` violation suggests to me that its implementation is flawed.

File: lib/rubocop/cop/style/redundant_return.rb [hunk 2]
```diff
@@ -110,6 +115,15 @@ def check_if_node(node)
           check_branch(else_node) if else_node
         end
 
+        def check_rescue_node(node)
+          check_branch(node.child_nodes[0])
+        end
+
+        def check_ensure_node(node)
+          rescue_node = node.node_parts[0]
+          check_branch(rescue_node)
```
Comment (asherkach) [inline lib/rubocop/cop/style/redundant_return.rb]: Note that this could instead be `check_rescue_node`.

File: spec/rubocop/cop/style/redundant_return_spec.rb [hunk 3]
```diff
@@ -282,6 +282,92 @@ def func
...
+
+    it 'does register an offense when inside function block' do
+      expect_offense(<<-RUBY.strip_indent)
+        def func
+          1
+          2
+          return 3
+          ^^^^^^ Redundant `return` detected.
+        rescue SomeException
+          return 4
```
Comment (pocke) [inline spec/rubocop/cop/style/redundant_return_spec.rb]: I guess the `return` are also redundant.
Note: the `return` that is in `ensure` is not redundant.

Comment (asherkach) [reply spec/rubocop/cop/style/redundant_return_spec.rb]: Oops. Fixed.

File: CHANGELOG.md [hunk 4]
```diff
@@ -29,6 +29,10 @@
 * [#5348](https://github.com/bbatsov/rubocop/issues/5348): Fix false positive for `Style/SafeNavigation` when safe guarding more comparison methods. ([@rrosenblum][])
 * [#4889](https://github.com/bbatsov/rubocop/issues/4889): Auto-correcting `Style/SafeNavigation` will add safe navigation to all methods in a method chain. ([@rrosenblum][])
 * [#5287](https://github.com/bbatsov/rubocop/issues/5287): Do not register an offense in `Style/SafeNavigation` if there is an unsafe method used in a method chain. ([@rrosenblum][])
+* [#5348](https://github.com/bbatsov/rubocop/issues/5348): Fix false positive for `Style/SafeNavigation` when safe guarding more comparison methods. ([@rrosenblum][])
+* [#4889](https://github.com/bbatsov/rubocop/issues/4889): Auto-correcting `Style/SafeNavigation` will add safe navigation to all methods in a method chain. ([@rrosenblum][])
+* [#5287](https://github.com/bbatsov/rubocop/issues/5287): Do not register an offense in `Style/SafeNavigation` if there is an unsafe method used in a method chain. ([@rrosenblum][])
```
Comment (pocke) [inline CHANGELOG.md]: I guess the entries duplicate. L29-L31 and L32-34 looks same.

File: spec/rubocop/cop/style/redundant_return_spec.rb (hunk 3 above)
Comment (pocke) [reply spec/rubocop/cop/style/redundant_return_spec.rb]: Looks good 👍

File: CHANGELOG.md (hunk 4 above)
Comment (asherkach) [reply CHANGELOG.md]: Merge conflict mismerged. Fixed.

**Comment by bbatsov** [comment]
Great improvement! 👍
