### PR TITLE
[Fix #5648] Suggest valid memoized instance variable for predicate me…

### LINKED ISSUE #5648: MemoizedInstanceVariableName cop suggests syntactically invalid instance variable for predicate methods.
MemoizedInstanceVariableName cop suggests syntactically invalid instance variable for predicate methods.

https://github.com/bbatsov/rubocop/pull/5445#issuecomment-370947946

--------

## Expected behavior

It should suggest replacing `@has_something` with `@something`

## Actual behavior

Rubocop wants me to change the instance variable to `@something?`, which is not valid.

## Steps to reproduce the problem

```
def something?
  @has_something ||= figure_out_something
end
```

## RuboCop version

0.53.0

### PR DESCRIPTION
**Pull request by satyap**
https://github.com/bbatsov/rubocop/pull/5445#issuecomment-370947946
Fixes #5648 

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `rake default` or `rake parallel`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/naming/memoized_instance_variable_name.rb [hunk 1]
```diff
@@ -55,6 +55,7 @@ def on_def(node)
           msg = format(
             MSG,
             var: ivar_assign.children.first.to_s,
+            suggested_var: method_name.to_s.sub('?', ''),
```
Comment (mikegee) [inline lib/rubocop/cop/naming/memoized_instance_variable_name.rb]: `method_name.to_s.chomp('?')` would work too.

Comment (satyap) [reply lib/rubocop/cop/naming/memoized_instance_variable_name.rb]: I like the `chomp` way, thanks!

**Comment by bbatsov** [comment]
👍
