### PR TITLE
[Fix #3521] Disable autocorrect on `Security/JSONLoad` by default.

### LINKED ISSUE #3521: Security/JSONLoad autocorrect potential runtime error
The autocorrect on Security/JSONLoad will replace `JSON.load(request)` with `JSON.parse(request)`. One difference between these two methods is that `JSON.load` works with any object that responds to the `#read` method, such as an OpenURI HTTP request or a file handler. Here's an example:
```ruby
request = open("http://localhost:3000/output.json")
result = JSON.load(request)
```
This will crash if replaced with `JSON.parse`.

-----
The above is the exact issue I experienced, however I think there are other potential issues with this autocorrect. For example, consider the following difference between `JSON.load` and `JSON.parse`:
```ruby
irb(main):001:0> JSON.load('false')
=> false
irb(main):002:0> JSON.parse('false')
JSON::ParserError: 784: unexpected token at 'false'
irb(main):003:0> JSON.parse('false', quirks_mode: true)
=> false
```
`JSON.load` allows primitives to be parsed, without requiring them to be in an actual JSON object. `JSON.parse` requires the `:quirks_mode` option to be true for this to work. So this type of use could also cause runtime errors in applications.

-----
I think that the solution is to remove autocorrect for this cop.

-----
## RuboCop version
```
$ rubocop -V
0.43.0 (using Parser 2.3.1.3, running on ruby 2.3.1 x86_64-linux)
```

### PR DESCRIPTION
**Pull request by savef**
The autocorrect on this cop is dangerous for at least two reasons depending on the value being passed to the `JSON` class method, so this disabled it by default. One known reason is where we pass in a stream such as `JSON.load(open('file'))`, this cannot be swapped out for `JSON.parse` without calling `#read` on the stream. Another known reason is where the JSON string is a single value, rather than a full JSON object, such as `JSON.load('false')`, this cannot be swapped out for `JSON.parse` without adding the `quirks_mode: true` option.

I'm not sure if this is all you meant regarding improving the descriptions, let me know.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Used the same coding conventions as the rest of the project.
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [ ] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] All tests are passing.
* [x] The new code doesn't generate RuboCop offenses.
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.

### CODE REVIEW

File: lib/rubocop/cop/security/json_load.rb [hunk 1]
```diff
@@ -3,7 +3,8 @@
 module RuboCop
   module Cop
     module Security
-      # This cop checks for the use of unsecure JSON methods.
+      # This cop checks for the use of JSON class methods which have potential
+      # security issues.
```
Comment (bbatsov) [inline lib/rubocop/cop/security/json_load.rb]: I'd extend this class comment with explanation why autocorrect can't be implemented reliably for this.

**Comment by savef** [comment]
@bbatsov, sorted I think.

**Comment by savef** [comment]
@bbatsov, I'll try again.
