### PR TITLE
[Fix #2124] Find only comments between defs

### LINKED ISSUE #2124: EmptyLineBetweenDefs doesn't register offense for multiline methods with comment headers
```diff
diff --git a/spec/rubocop/cop/style/empty_line_between_defs_spec.rb b/spec/rubocop/cop/style/empty_line_between_defs_spec.rb
index 84d2da1..6c400fb 100644
--- a/spec/rubocop/cop/style/empty_line_between_defs_spec.rb
+++ b/spec/rubocop/cop/style/empty_line_between_defs_spec.rb
@@ -6,6 +6,30 @@ describe RuboCop::Cop::Style::EmptyLineBetweenDefs, :config do
   subject(:cop) { described_class.new(config) }
   let(:cop_config) { { 'AllowAdjacentOneLineDefs' => false } }
 
+  it 'finds offenses for adjacent multi-liners' do
+    source = ['  class J',
+              '    def n',
+              '    end',
+              '    def o',
+              '    end',
+              '  end']
+    inspect_source(cop, source)
+    expect(cop.offenses.size).to eq(1)
+  end
+
+  it 'finds offenses for adjacent multi-liners with comments' do
+    source = ['  class J',
+              '    # checks something n-related',
+              '    def n',
+              '    end',
+              '    # checks something o-related',
+              '    def o',
+              '    end',
+              '  end']
+    inspect_source(cop, source)
+    expect(cop.offenses.size).to eq(1)
+  end
+
   it 'finds offenses in inner classes' do
     source = ['class K',
               '  def m',
```

The first spec passes, but the second fails.

### PR DESCRIPTION
**Pull request by lumeet**
The `Style/EmptyLineBetweenDefs` cop registers an offense when there
are only comments between method definitions.

### CODE REVIEW

File: lib/rubocop/cop/style/empty_line_between_defs.rb [hunk 1]
```diff
@@ -9,20 +9,30 @@ class EmptyLineBetweenDefs < Cop
         MSG = 'Use empty lines between defs.'
 
         def on_def(node)
-          if @prev_def_end && (def_start(node) - @prev_def_end) == 1
-            unless @prev_was_single_line && singe_line_def?(node) &&
+          if @prev_def_end && @prev_def_end < def_end(node) &&
```
Comment (bbatsov) [inline lib/rubocop/cop/style/empty_line_between_defs.rb]: We should probably extract those complex conditions as helper methods.

**Comment by unmanbearpig** [comment]
Hey guys! I did some refactoring in this commit https://github.com/unmanbearpig/rubocop/commit/3c0b388da7afb8c7a402d8c758f0c039e77ecfa0 
What do you think? Is it ok? Should I make it a separate pull request?

**Comment by lumeet** [comment]
I'm afraid I'm not going to have time to look into this in detail this week. So, basically, I think, we could either have separate pull requests or we can close this one to get the fix merged as soon as possible.

**Comment by unmanbearpig** [comment]
Ok, so I can submit a separate pull request after this one is merged.

**Comment by lumeet** [comment]
@bbatsov Do you think we can handle this with separate issues? All in all, I think the refactoring by @unmanbearpig looks good and seems to make the code both cleaner and faster. However, there seems to be a couple of offenses to fix. In addition, I think the new tests are redundant.

**Comment by bbatsov** [comment]
@lumeet Sure. We just need to wrap your PR first. I had a tiny remark about some complex conditions and it has to rebased on top of the current `master`.

**Comment by unmanbearpig** [comment]
@lumeet Sorry, you're right about the redundant tests. I've fixed the issue before I noticed your pull request, so I've merged my fix with yours (since you've fixed the auto-correct and I didn't) and I didn't notice the redundant tests. 
I'll clean it up before I submit a pull request with my refactoring, I'm just waiting for this pull request to get merged.

**Comment by lumeet** [comment]
@bbatsov I was thinking it's unnecessary to fix it as @unmanbearpig has completely refactored that part of the code. I've now rebased in the hope that you agree. If not, I'll humbly do some more changes. :)

**Comment by bbatsov** [comment]
:+1: OK, let's roll with what we have.
