### PR TITLE
[Fix #4881] Fix a false positive for `HashEachMethods` when unused argument(s) exists in other blocks

### LINKED ISSUE #4881: Performance/HashEachMethods report another block
## Expected behavior

Do not detect `Performance/HashEachMethods` for block used key and value.
And detect `Lint/UnusedBlockArgument` only.

## Actual behavior

Detect `Performance/HashEachMethods` and `Lint/UnusedBlockArgument`.

## Steps to reproduce the problem

```
% cat r.rb
# frozen_string_literal: true

@h.each do |key, value|
  p(key * -value)
end
@h.sum { |key, value| -value }
% rubocop -D r.rb
Inspecting 1 file
W

Offenses:

r.rb:3:4: C: Performance/HashEachMethods: Use each_value instead of each.
@h.each do |key, value|
   ^^^^
r.rb:6:11: W: Lint/UnusedBlockArgument: Unused block argument - key. If it's necessary, use _ or _key as an argument name to indicate that it won't be used.
@h.sum { |key, value| -value }
          ^^^

1 file inspected, 2 offenses detected
```

## RuboCop version

```
% rubocop -V
0.51.0 (using Parser 2.4.0.0, running on ruby 2.3.5 x86_64-darwin16)
```

### PR DESCRIPTION
**Pull request by pocke**
Problem
===

`Performance/HashEachMethods` has a false positive for the following code.

```ruby
@h.each do |key, value|
  p(key * -value)
end
@h.sum { |key, value| -value }
```

The `each` does not have any unused arguments. `key` and `value` are used. So, this cop should not add an offense for the code.
But the cop adds an offence for the code currently.
This cause is the `sum` has an unused argument, and the argument is named `key`, the name is same as the `each`'s argument.
In this case, `Performance/HashEachMethods` adds a falsy offense.

Cause
=====

The cop handles only argument names to detect unused. So the cop does not work properly if an unused argument that has same name exists in other block.

Solution
=====

Check declared location of arguments instead of argument name.

Note
====

I found another bug while I was fixing this bug.
Auto-correction of this cop does not work properly.
For example:

```ruby
 # Auto-correct the following code.
foo.each { |key, _v| p key }
 # Expected
foo.each_key { |key| p key }
 # Actual
foo.each_value { |key| p key }
```

This change will fix the bug also.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Used the same coding conventions as the rest of the project.
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] All tests(`rake spec`) are passing.
* [x] The new code doesn't generate RuboCop offenses that are checked by `rake internal_investigation`.
* [ ] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Updated cop documentation with `rake generate_cops_documentation` (required only when you've added a new cop or changed the configuration/documentation of an existing cop).

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/performance/hash_each_methods.rb [hunk 1]
```diff
@@ -62,56 +62,57 @@ def register_kv_offense(node)
...
+          return correct_implicit(node, corrector, name) unless receiver
 
-          new_source = receiver.receiver.source +
-                       ".each_#{receiver.method_name[0..-2]}"
+          new_source = receiver.source + ".#{name}"
           corrector.replace(node.loc.expression, new_source)
         end
 
         def correct_plain_each(node, corrector)
-          method = @args.include?(:k) ? :key : :value
```
Comment (pocke) [inline lib/rubocop/cop/performance/hash_each_methods.rb]: This `:k` is a cause of the auto-correction bug.

**Comment by bbatsov** [comment]
👍
