### PR TITLE
Fix `Style/MethodCallParentheses` to work with multiple assignments

### LINKED ISSUE #3129: MethodCallParentheses error parsing parallel assignment
## Expected behavior

No error!

## Actual behavior

```
$ rubocop -d test.rb
For /Users/ben: configuration from /Users/ben/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.40.0/config/default.yml
Inheriting configuration from /Users/ben/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.40.0/config/enabled.yml
Inheriting configuration from /Users/ben/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.40.0/config/disabled.yml
Inspecting 1 file
Scanning /Users/ben/test.rb
An error occurred while Style/MethodCallParentheses cop was inspecting /Users/ben/test.rb.
undefined method `or_asgn_type?' for nil:NilClass
/Users/ben/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.40.0/lib/rubocop/cop/style/method_call_parentheses.rb:48:in `block in same_name_assignment?'
/Users/ben/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.40.0/lib/rubocop/ast_node.rb:581:in `visit_ancestors_with_types'
/Users/ben/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.40.0/lib/rubocop/ast_node.rb:147:in `each_ancestor'
/Users/ben/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.40.0/lib/rubocop/cop/style/method_call_parentheses.rb:39:in `each'
/Users/ben/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.40.0/lib/rubocop/cop/style/method_call_parentheses.rb:39:in `any?'
/Users/ben/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.40.0/lib/rubocop/cop/style/method_call_parentheses.rb:39:in `same_name_assignment?'
/Users/ben/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.40.0/lib/rubocop/cop/style/method_call_parentheses.rb:20:in `on_send'
/Users/ben/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.40.0/lib/rubocop/cop/commissioner.rb:42:in `block (2 levels) in on_send'
/Users/ben/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.40.0/lib/rubocop/cop/commissioner.rb:97:in `with_cop_error_handling'
/Users/ben/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.40.0/lib/rubocop/cop/commissioner.rb:41:in `block in on_send'
/Users/ben/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.40.0/lib/rubocop/cop/commissioner.rb:40:in `each'
/Users/ben/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.40.0/lib/rubocop/cop/commissioner.rb:40:in `on_send'
/Users/ben/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.40.0/lib/rubocop/ast_node/traversal.rb:102:in `block in on_send'
/Users/ben/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.40.0/lib/rubocop/ast_node/traversal.rb:100:in `each'
/Users/ben/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.40.0/lib/rubocop/ast_node/traversal.rb:100:in `each_with_index'
/Users/ben/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.40.0/lib/rubocop/ast_node/traversal.rb:100:in `on_send'
/Users/ben/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.40.0/lib/rubocop/cop/commissioner.rb:46:in `on_send'
(eval):2:in `block in on_masgn'
(eval):2:in `each'
(eval):2:in `on_masgn'
/Users/ben/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.40.0/lib/rubocop/cop/commissioner.rb:46:in `on_masgn'
/Users/ben/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.40.0/lib/rubocop/ast_node/traversal.rb:13:in `walk'
/Users/ben/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.40.0/lib/rubocop/cop/commissioner.rb:59:in `investigate'
/Users/ben/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.40.0/lib/rubocop/cop/team.rb:70:in `inspect_file'
/Users/ben/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.40.0/lib/rubocop/runner.rb:205:in `inspect_file'
/Users/ben/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.40.0/lib/rubocop/runner.rb:175:in `block in do_inspection_loop'
/Users/ben/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.40.0/lib/rubocop/runner.rb:165:in `loop'
/Users/ben/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.40.0/lib/rubocop/runner.rb:165:in `do_inspection_loop'
/Users/ben/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.40.0/lib/rubocop/runner.rb:87:in `process_file'
/Users/ben/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.40.0/lib/rubocop/runner.rb:59:in `block in inspect_files'
/Users/ben/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.40.0/lib/rubocop/runner.rb:57:in `each'
/Users/ben/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.40.0/lib/rubocop/runner.rb:57:in `inspect_files'
/Users/ben/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.40.0/lib/rubocop/runner.rb:35:in `run'
/Users/ben/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.40.0/lib/rubocop/cli.rb:30:in `run'
/Users/ben/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.40.0/bin/rubocop:14:in `block in <top (required)>'
/Users/ben/.rbenv/versions/2.2.2/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
/Users/ben/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.40.0/bin/rubocop:13:in `<top (required)>'
/Users/ben/.rbenv/versions/2.2.2/bin/rubocop:23:in `load'
/Users/ben/.rbenv/versions/2.2.2/bin/rubocop:23:in `<main>'
.

1 file inspected, no offenses detected

1 error occurred:
An error occurred while Style/MethodCallParentheses cop was inspecting /Users/ben/test.rb.
Errors are usually caused by RuboCop bugs.
Please, report your problems to RuboCop's issue tracker.
Mention the following information in the issue report:
0.40.0 (using Parser 2.3.1.0, running on ruby 2.2.2 x86_64-darwin14)
Finished in 0.1327448819647543 seconds
```

## Steps to reproduce the problem

I've narrowed it down to this minimal test file, which will reproduce the error:

```
_a, _b = c(d())
```

The error happens while processing the `d()` node. It looks like the `same_name_assignment?` method is assuming that because `d()` has an assignment type ancestor that it is at the top level of the RHS, rather than a parameter to another method call.

Obviously I should just remove the parentheses(!) and the error would go away but I hope the bug report is useful.

## RuboCop version

```
$ rubocop -V
0.40.0 (using Parser 2.3.1.0, running on ruby 2.2.2 x86_64-darwin14)
```

### PR DESCRIPTION
**Pull request by tejasbubane**
Closes #3129. 

`Style/MethodCallParenthesis` cop failed abruptly for multiple assignments. This PR fixes the issue.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Used the same coding conventions as the rest of the project.
* [x] Feature branch is up-to-date with `master` (if not - rebase it)
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] All tests are passing.
* [x] The new code doesn't generate RuboCop offenses.
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.

[1]: http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html

### CODE REVIEW

**Comment by tejasbubane** [comment]
Rebased.

File: lib/rubocop/cop/style/method_call_parentheses.rb [hunk 1]
```diff
@@ -50,6 +46,13 @@ def same_name_assignment?(node)
               return false if asgn_node.send_type?
             end
 
+            if asgn_node.masgn_type?
+              mlhs_node, _mrhs_node = *asgn_node
+              vars = mlhs_node.children.map(&:source)
```
Comment (bbatsov) [inline lib/rubocop/cop/style/method_call_parentheses.rb]: This is extremely expensive (mapping to the source). Consider just using the symbol identifiers or something like this.

Comment (tejasbubane) [inline lib/rubocop/cop/style/method_call_parentheses.rb]: @bbatsov Mapping to `children` instead of `source` now. Not sure how good this idea is compared to mapping to `source`. 

Actually, I did not get what you meant by `symbol identifiers`, hence came up with this.
If mapping is still a bad approach, can you point me to some existing code which uses `symbol identifiers`?

**Comment by tejasbubane** [comment]
@bbatsov Mapping to children instead of source now. Not sure how good this idea is compared to mapping to source.

Actually, I did not get what you meant by symbol identifiers in your comment, hence came up with this.
If mapping is still a bad approach, can you point me to some existing code which uses symbol identifiers?

File: lib/rubocop/cop/style/method_call_parentheses.rb [hunk 2]
```diff
@@ -50,6 +46,13 @@ def same_name_assignment?(node)
               return false if asgn_node.send_type?
             end
 
+            if asgn_node.masgn_type?
+              mlhs_node, _mrhs_node = *asgn_node
+              vars = mlhs_node.children.map(&:children).flatten
```
Comment (bbatsov) [inline lib/rubocop/cop/style/method_call_parentheses.rb]: I meant that using splatting is faster than using `.children`. So in the interest of performance you ca split this expression in two expressions.

File: CHANGELOG.md [hunk 3]
```diff
@@ -35,6 +35,7 @@
 * [#2944](https://github.com/bbatsov/rubocop/issues/2944): Don't crash on strings that span multiple lines but only have one pair of delimiters in `Style/StringLiterals`. ([@jonas054][])
 * [#3157](https://github.com/bbatsov/rubocop/issues/3157): Don't let `LineEndConcatenation` and `UnneededInterpolation` make changes to the same string during auto-correct. ([@jonas054][])
 * [#3187](https://github.com/bbatsov/rubocop/issues/3187): Let `Style/BlockDelimiters` ignore blocks in *all* method arguments. ([@jonas054][])
+* [#3129](https://github.com/bbatsov/rubocop/issues/3129): Fix `Style/MethodCallParentheses` to work with multiple assignments. ([@tejasbubane][])
```
Comment (bbatsov) [inline CHANGELOG.md]: This needs to be moved to the current `master` section.

**Comment by tejasbubane** [comment]
Fixed and rebased @bbatsov

**Comment by bbatsov** [comment]
Bad timing I guess. You'll have to rebase again.

**Comment by tejasbubane** [comment]
rebased @bbatsov
