### PR TITLE
[Fix #2449] Fix StabbyLambdaParentheses with lambda

### LINKED ISSUE #2449: An error occurred while Style/StabbyLambdaParentheses
Hello I'm getting this error:

*An error occurred while Style/StabbyLambdaParentheses* cop was inspecting xxxxx.rb

The code causing this error is below:
```
  def localize_value(value)
    case value
    when lambda(&:nil?)   # <-- this line is causing the error
      value
...
    else
      value
    end
  end
```

Here is the backtrace

```
Inspecting 1 file
Scanning /home/juris/src/expert/lib/version_change_formatter.rb
For /home/juris/src/expert: configuration from /home/juris/src/expert/.rubocop.yml
Inheriting configuration from /home/juris/src/expert/.rubocop_todo.yml
Default configuration from /home/juris/.rvm/gems/ruby-2.2.3/gems/rubocop-0.35.1/config/default.yml
Inheriting configuration from /home/juris/.rvm/gems/ruby-2.2.3/gems/rubocop-0.35.1/config/enabled.yml
Inheriting configuration from /home/juris/.rvm/gems/ruby-2.2.3/gems/rubocop-0.35.1/config/disabled.yml
An error occurred while Style/StabbyLambdaParentheses cop was inspecting /home/juris/src/expert/lib/version_change_formatter.rb.
undefined method `begin' for #<Parser::Source::Map::Variable:0x00000002364690>
/home/juris/.rvm/gems/ruby-2.2.3/gems/rubocop-0.35.1/lib/rubocop/cop/style/stabby_lambda_parentheses.rb:103:in `parentheses?'
/home/juris/.rvm/gems/ruby-2.2.3/gems/rubocop-0.35.1/lib/rubocop/cop/style/stabby_lambda_parentheses.rb:30:in `on_send'
/home/juris/.rvm/gems/ruby-2.2.3/gems/rubocop-0.35.1/lib/rubocop/cop/commissioner.rb:37:in `block (2 levels) in on_send'
/home/juris/.rvm/gems/ruby-2.2.3/gems/rubocop-0.35.1/lib/rubocop/cop/commissioner.rb:87:in `with_cop_error_handling'
/home/juris/.rvm/gems/ruby-2.2.3/gems/rubocop-0.35.1/lib/rubocop/cop/commissioner.rb:36:in `block in on_send'
/home/juris/.rvm/gems/ruby-2.2.3/gems/rubocop-0.35.1/lib/rubocop/cop/commissioner.rb:34:in `each'
/home/juris/.rvm/gems/ruby-2.2.3/gems/rubocop-0.35.1/lib/rubocop/cop/commissioner.rb:34:in `on_send'
/home/juris/.rvm/gems/ruby-2.2.3/gems/ast-2.1.0/lib/ast/processor/mixin.rb:259:in `process'
/home/juris/.rvm/gems/ruby-2.2.3/gems/ast-2.1.0/lib/ast/processor/mixin.rb:276:in `block in process_all'
/home/juris/.rvm/gems/ruby-2.2.3/gems/ast-2.1.0/lib/ast/processor/mixin.rb:275:in `map'
/home/juris/.rvm/gems/ruby-2.2.3/gems/ast-2.1.0/lib/ast/processor/mixin.rb:275:in `process_all'
/home/juris/.rvm/gems/ruby-2.2.3/gems/parser-2.2.3.0/lib/parser/ast/processor.rb:9:in `process_regular_node'
/home/juris/.rvm/gems/ruby-2.2.3/gems/rubocop-0.35.1/lib/rubocop/cop/commissioner.rb:41:in `on_when'
/home/juris/.rvm/gems/ruby-2.2.3/gems/ast-2.1.0/lib/ast/processor/mixin.rb:259:in `process'
/home/juris/.rvm/gems/ruby-2.2.3/gems/ast-2.1.0/lib/ast/processor/mixin.rb:276:in `block in process_all'
/home/juris/.rvm/gems/ruby-2.2.3/gems/ast-2.1.0/lib/ast/processor/mixin.rb:275:in `map'
/home/juris/.rvm/gems/ruby-2.2.3/gems/ast-2.1.0/lib/ast/processor/mixin.rb:275:in `process_all'
/home/juris/.rvm/gems/ruby-2.2.3/gems/parser-2.2.3.0/lib/parser/ast/processor.rb:9:in `process_regular_node'
/home/juris/.rvm/gems/ruby-2.2.3/gems/rubocop-0.35.1/lib/rubocop/cop/commissioner.rb:41:in `on_case'
/home/juris/.rvm/gems/ruby-2.2.3/gems/ast-2.1.0/lib/ast/processor/mixin.rb:259:in `process'
/home/juris/.rvm/gems/ruby-2.2.3/gems/parser-2.2.3.0/lib/parser/ast/processor.rb:122:in `on_def'
/home/juris/.rvm/gems/ruby-2.2.3/gems/rubocop-0.35.1/lib/rubocop/cop/commissioner.rb:41:in `on_def'
/home/juris/.rvm/gems/ruby-2.2.3/gems/ast-2.1.0/lib/ast/processor/mixin.rb:259:in `process'
/home/juris/.rvm/gems/ruby-2.2.3/gems/ast-2.1.0/lib/ast/processor/mixin.rb:276:in `block in process_all'
/home/juris/.rvm/gems/ruby-2.2.3/gems/ast-2.1.0/lib/ast/processor/mixin.rb:275:in `map'
/home/juris/.rvm/gems/ruby-2.2.3/gems/ast-2.1.0/lib/ast/processor/mixin.rb:275:in `process_all'
/home/juris/.rvm/gems/ruby-2.2.3/gems/parser-2.2.3.0/lib/parser/ast/processor.rb:9:in `process_regular_node'
/home/juris/.rvm/gems/ruby-2.2.3/gems/rubocop-0.35.1/lib/rubocop/cop/commissioner.rb:41:in `on_begin'
/home/juris/.rvm/gems/ruby-2.2.3/gems/ast-2.1.0/lib/ast/processor/mixin.rb:259:in `process'
/home/juris/.rvm/gems/ruby-2.2.3/gems/ast-2.1.0/lib/ast/processor/mixin.rb:276:in `block in process_all'
/home/juris/.rvm/gems/ruby-2.2.3/gems/ast-2.1.0/lib/ast/processor/mixin.rb:275:in `map'
/home/juris/.rvm/gems/ruby-2.2.3/gems/ast-2.1.0/lib/ast/processor/mixin.rb:275:in `process_all'
/home/juris/.rvm/gems/ruby-2.2.3/gems/parser-2.2.3.0/lib/parser/ast/processor.rb:9:in `process_regular_node'
/home/juris/.rvm/gems/ruby-2.2.3/gems/rubocop-0.35.1/lib/rubocop/cop/commissioner.rb:41:in `on_class'
/home/juris/.rvm/gems/ruby-2.2.3/gems/ast-2.1.0/lib/ast/processor/mixin.rb:259:in `process'
/home/juris/.rvm/gems/ruby-2.2.3/gems/rubocop-0.35.1/lib/rubocop/cop/commissioner.rb:53:in `investigate'
/home/juris/.rvm/gems/ruby-2.2.3/gems/rubocop-0.35.1/lib/rubocop/cop/team.rb:34:in `inspect_file'
/home/juris/.rvm/gems/ruby-2.2.3/gems/rubocop-0.35.1/lib/rubocop/runner.rb:190:in `inspect_file'
/home/juris/.rvm/gems/ruby-2.2.3/gems/rubocop-0.35.1/lib/rubocop/runner.rb:157:in `block in do_inspection_loop'
/home/juris/.rvm/gems/ruby-2.2.3/gems/rubocop-0.35.1/lib/rubocop/runner.rb:151:in `loop'
Inspecting 1 file
Scanning /home/juris/src/expert/lib/version_change_formatter.rb
For /home/juris/src/expert: configuration from /home/juris/src/expert/.rubocop.yml
Inheriting configuration from /home/juris/src/expert/.rubocop_todo.yml
Default configuration from /home/juris/.rvm/gems/ruby-2.2.3/gems/rubocop-0.35.1/config/default.yml
Inheriting configuration from /home/juris/.rvm/gems/ruby-2.2.3/gems/rubocop-0.35.1/config/enabled.yml
Inheriting configuration from /home/juris/.rvm/gems/ruby-2.2.3/gems/rubocop-0.35.1/config/disabled.yml
An error occurred while Style/StabbyLambdaParentheses cop was inspecting /home/juris/src/expert/lib/version_change_formatter.rb.
undefined method `begin' for #<Parser::Source::Map::Variable:0x00000002364690>
/home/juris/.rvm/gems/ruby-2.2.3/gems/rubocop-0.35.1/lib/rubocop/cop/style/stabby_lambda_parentheses.rb:103:in `parentheses?'
/home/juris/.rvm/gems/ruby-2.2.3/gems/rubocop-0.35.1/lib/rubocop/cop/style/stabby_lambda_parentheses.rb:30:in `on_send'
/home/juris/.rvm/gems/ruby-2.2.3/gems/rubocop-0.35.1/lib/rubocop/cop/commissioner.rb:37:in `block (2 levels) in on_send'
/home/juris/.rvm/gems/ruby-2.2.3/gems/rubocop-0.35.1/lib/rubocop/cop/commissioner.rb:87:in `with_cop_error_handling'
/home/juris/.rvm/gems/ruby-2.2.3/gems/rubocop-0.35.1/lib/rubocop/cop/commissioner.rb:36:in `block in on_send'
/home/juris/.rvm/gems/ruby-2.2.3/gems/rubocop-0.35.1/lib/rubocop/cop/commissioner.rb:34:in `each'
/home/juris/.rvm/gems/ruby-2.2.3/gems/rubocop-0.35.1/lib/rubocop/cop/commissioner.rb:34:in `on_send'
/home/juris/.rvm/gems/ruby-2.2.3/gems/ast-2.1.0/lib/ast/processor/mixin.rb:259:in `process'
/home/juris/.rvm/gems/ruby-2.2.3/gems/ast-2.1.0/lib/ast/processor/mixin.rb:276:in `block in process_all'
/home/juris/.rvm/gems/ruby-2.2.3/gems/ast-2.1.0/lib/ast/processor/mixin.rb:275:in `map'
/home/juris/.rvm/gems/ruby-2.2.3/gems/ast-2.1.0/lib/ast/processor/mixin.rb:275:in `process_all'
/home/juris/.rvm/gems/ruby-2.2.3/gems/parser-2.2.3.0/lib/parser/ast/processor.rb:9:in `process_regular_node'
/home/juris/.rvm/gems/ruby-2.2.3/gems/rubocop-0.35.1/lib/rubocop/cop/commissioner.rb:41:in `on_when'
/home/juris/.rvm/gems/ruby-2.2.3/gems/ast-2.1.0/lib/ast/processor/mixin.rb:259:in `process'
/home/juris/.rvm/gems/ruby-2.2.3/gems/ast-2.1.0/lib/ast/processor/mixin.rb:276:in `block in process_all'
/home/juris/.rvm/gems/ruby-2.2.3/gems/ast-2.1.0/lib/ast/processor/mixin.rb:275:in `map'
/home/juris/.rvm/gems/ruby-2.2.3/gems/ast-2.1.0/lib/ast/processor/mixin.rb:275:in `process_all'
/home/juris/.rvm/gems/ruby-2.2.3/gems/parser-2.2.3.0/lib/parser/ast/processor.rb:9:in `process_regular_node'
/home/juris/.rvm/gems/ruby-2.2.3/gems/rubocop-0.35.1/lib/rubocop/cop/commissioner.rb:41:in `on_case'
/home/juris/.rvm/gems/ruby-2.2.3/gems/ast-2.1.0/lib/ast/processor/mixin.rb:259:in `process'
/home/juris/.rvm/gems/ruby-2.2.3/gems/parser-2.2.3.0/lib/parser/ast/processor.rb:122:in `on_def'
/home/juris/.rvm/gems/ruby-2.2.3/gems/rubocop-0.35.1/lib/rubocop/cop/commissioner.rb:41:in `on_def'
/home/juris/.rvm/gems/ruby-2.2.3/gems/ast-2.1.0/lib/ast/processor/mixin.rb:259:in `process'
/home/juris/.rvm/gems/ruby-2.2.3/gems/ast-2.1.0/lib/ast/processor/mixin.rb:276:in `block in process_all'
/home/juris/.rvm/gems/ruby-2.2.3/gems/ast-2.1.0/lib/ast/processor/mixin.rb:275:in `map'
/home/juris/.rvm/gems/ruby-2.2.3/gems/ast-2.1.0/lib/ast/processor/mixin.rb:275:in `process_all'
/home/juris/.rvm/gems/ruby-2.2.3/gems/parser-2.2.3.0/lib/parser/ast/processor.rb:9:in `process_regular_node'
/home/juris/.rvm/gems/ruby-2.2.3/gems/rubocop-0.35.1/lib/rubocop/cop/commissioner.rb:41:in `on_begin'
/home/juris/.rvm/gems/ruby-2.2.3/gems/ast-2.1.0/lib/ast/processor/mixin.rb:259:in `process'
/home/juris/.rvm/gems/ruby-2.2.3/gems/ast-2.1.0/lib/ast/processor/mixin.rb:276:in `block in process_all'
/home/juris/.rvm/gems/ruby-2.2.3/gems/ast-2.1.0/lib/ast/processor/mixin.rb:275:in `map'
/home/juris/.rvm/gems/ruby-2.2.3/gems/ast-2.1.0/lib/ast/processor/mixin.rb:275:in `process_all'
/home/juris/.rvm/gems/ruby-2.2.3/gems/parser-2.2.3.0/lib/parser/ast/processor.rb:9:in `process_regular_node'
/home/juris/.rvm/gems/ruby-2.2.3/gems/rubocop-0.35.1/lib/rubocop/cop/commissioner.rb:41:in `on_class'
/home/juris/.rvm/gems/ruby-2.2.3/gems/ast-2.1.0/lib/ast/processor/mixin.rb:259:in `process'
/home/juris/.rvm/gems/ruby-2.2.3/gems/rubocop-0.35.1/lib/rubocop/cop/commissioner.rb:53:in `investigate'
/home/juris/.rvm/gems/ruby-2.2.3/gems/rubocop-0.35.1/lib/rubocop/cop/team.rb:34:in `inspect_file'
/home/juris/.rvm/gems/ruby-2.2.3/gems/rubocop-0.35.1/lib/rubocop/runner.rb:190:in `inspect_file'
/home/juris/.rvm/gems/ruby-2.2.3/gems/rubocop-0.35.1/lib/rubocop/runner.rb:157:in `block in do_inspection_loop'
/home/juris/.rvm/gems/ruby-2.2.3/gems/rubocop-0.35.1/lib/rubocop/runner.rb:151:in `loop'
```

### PR DESCRIPTION
**Pull request by lumeet**
`Style/StabbyLambdaParentheses` does not check lambdas that use the
old `lambda` method.

### CODE REVIEW

File: spec/rubocop/cop/style/stabby_lambda_parentheses_spec.rb [hunk 1]
```diff
@@ -4,9 +4,28 @@
 describe RuboCop::Cop::Style::StabbyLambdaParentheses, :config do
   subject(:cop) { described_class.new(config) }
 
+  shared_examples 'common' do
+    it 'does not check the lambda keyword' do
```
Comment (bbatsov) [inline spec/rubocop/cop/style/stabby_lambda_parentheses_spec.rb]: `lambda` is not a keyword - it's a regular method.

**Comment by lumeet** [comment]
So true, keyword stuff removed. Also rebased.

**Comment by bbatsov** [comment]
:+1:
