### PR TITLE
[Fix #4102] Fix `Security` cops ignoring ::Const

### LINKED ISSUE #4102: Security/MarshalLoad doesn't work for `::Marshel.load`
# Reproducing

```ruby
# test.rb
dump = Marshal.dump(1)
::Marshal.load dump
Marshal.load dump
```

```
$ rubocop --only Security/MarshalLoad test.rb
```

# Expected Behavior

```
Inspecting 1 file
C

Offenses:

test.rb:2:11: C: Avoid using Marshal.load.
::Marshal.load dump
          ^^^^
test.rb:3:9: C: Avoid using Marshal.load.
Marshal.load dump
        ^^^^

1 file inspected, 2 offenses detected
```

It should pass

# Actual Behavior

```
Inspecting 1 file
C

Offenses:

test.rb:3:9: C: Avoid using Marshal.load.
Marshal.load dump
        ^^^^

1 file inspected, 1 offense detected
```

# RuboCop version

0.47.1

### PR DESCRIPTION
**Pull request by musialik**
Fixes #4102. The issue describes `Security/MarshalLoad`, but it applies to other cops as well.

`Security/MarshalLoad`, `Security/JSONLoad` and `Security/YAMLLoad` weren't matching ::Const or Module::Const

This PR improves the patterns for each cop and adds specs for multiple combinations.

For example:
```ruby
# bad
Marshal.load("{}")
::Marshal.load("{}")
Module::Marshal.load("{}")

# okish - deep copy hack
Marshal.load(Marshal.dump({}))
Marshal.load(::Marshal.dump({}))
Marshal.load(Module::Marshal.dump({}))
::Marshal.load(Marshal.dump({}))
::Marshal.load(::Marshal.dump({}))
# etc.
```

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Used the same coding conventions as the rest of the project.
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] All tests are passing.
* [x] The new code doesn't generate RuboCop offenses.
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [ ] Updated cop documentation with `rake generate_cops_documentation` (required only when you've added a new cop or changed the configuration/documentation of an existing cop).

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/security/json_load.rb [hunk 1]
```diff
@@ -26,7 +26,7 @@ class JSONLoad < Cop
         MSG = 'Prefer `JSON.parse` over `JSON.%s`.'.freeze
 
         def_node_matcher :json_load, <<-END
-          (send (const nil :JSON) ${:load :restore} ...)
+          (send (const {nil cbase (const nil :Module)} :JSON) ${:load :restore} ...)
```
Comment (pocke) [inline lib/rubocop/cop/security/json_load.rb]: I guess we support `::Module::JSON` as well.

**Comment by pocke** [comment]
I think the `{nil cbase (const nil :Module)}` pattern should be used in other places as well. e.g. https://github.com/bbatsov/rubocop/blob/master/lib/rubocop/cop/lint/unified_integer.rb#L24
Maybe we can define a node matcher for the pattern in `Cop` super class.

**Comment by pocke** [comment]
I was misunderstanding. A parent module of a reference like `Module::JSON` is not limited to `Module`. Any module/class can be the parent class.
For example:

```sh
$ pry
[1] pry(main)> class Foo; end
=> nil
[2] pry(main)> class Bar; end
=> nil
[3] pry(main)> Foo::Bar
(pry):3: warning: toplevel constant Bar referenced by Foo::Bar
=> Bar
```

And a warning is occureed in the reference.
So, I think there is no point using `(const nil :Module)`,  `(const {nil cbase}` is enough.

**Comment by musialik** [comment]
Thanks for your input.

In `json_load_spec.rb` I found:
```ruby
it 'accepts Module::JSON.dump' do
  inspect_source(cop, 'Module::JSON.load({})')
  expect(cop.offenses).to be_empty
end
```
and assumed it's there for a reason, and that `Module::JSON` is a valid use.
But since `Module::JSON` triggers a warning, I agree we should stick to `{nil cbase}`.

@cyberdelia I wonder why the `it 'accepts Module::JSON.dump' do` was added.

**Comment by bbatsov** [comment]
> @cyberdelia I wonder why the it 'accepts Module::JSON.dump' do was added.

I guess the idea was that if it's not the top-level JSON constant it might be some unrelated constant. (`Module` is random module name here).

**Comment by bbatsov** [comment]
I meant to mention @musialik. Sorry about that.

**Comment by musialik** [comment]
I've changed the patterns to `{nil cbase}`, refactored the specs and added more to cover some edge cases.

**Comment by bbatsov** [comment]
👍
