### PR TITLE
[Fix #5333 & 5339] Resolve false positives in EmptyLineAroundArguments

### LINKED ISSUE #5333: False Positive in Layout/EmptyLinesAroundArguments with inline private
With the following code fragment using an inline access specifier:
```ruby
class Foo
  private def bar(baz)
    baz

    baz
  end
end
```
## Expected behavior

The Layout/EmptyLinesAroundArguments cop should report no offense.

## Actual behavior

`Layout/EmptyLinesAroundArguments: Empty line detected around arguments.`

## Steps to reproduce the problem

Run rubocop on the fragment above.

The false positive will also be raised when using other inline access specifiers like `protected`, `public`, `private_class_method`, etc. Presence or absence of actual arguments on the method declaration does not matter -- the cop appears to be complaining about the blank line in the method body.  Removing that blank line stops the complaint.

## RuboCop version
```
$ rubocop -V
0.52.1 (using Parser 2.4.0.2, running on ruby 2.4.3 x86_64-darwin16)
```

### PR DESCRIPTION
**Pull request by garettarrowood**
The two issues resolved here were two different problems in `Style/EmptyLineAroundArguments`, but this change resolves both. Check #5333 and #5339 for false positive details.

Currently, `Style/EmptyLineAroundArguments` checks for empty lines within the range of lines a method's arguments span. In addition to the issues linked here, this required special block argument logic. 

With this change, `Style/EmptyLineAroundArguments` will look for empty lines before and after arguments, but _NOT_ look inside an argument itself.

-----------------

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `rake default` or `rake parallel`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: spec/rubocop/cop/layout/empty_lines_around_arguments_spec.rb [hunk 1]
```diff
@@ -38,18 +38,6 @@
...
-      inspect_source(<<-RUBY.strip_indent)
-        do_stuff([
-          "some text",
-
-          "some more text"
-        ])
-      RUBY
-      expect(cop.messages)
-        .to eq(['Empty line detected around arguments.'])
-    end
```
Comment (garettarrowood) [inline spec/rubocop/cop/layout/empty_lines_around_arguments_spec.rb]: This is precisely the behavior that is getting removed.  `do_stuff` has one arg that is an array. There are no empty lines before or after the arg.  This cop no longer cares what happens inside the arg itself.

**Comment by jlfaber** [comment]
Thanks @garettarrowood! This addresses #5333 quite effectively.  👍

**Comment by garettarrowood** [comment]
There's one more edge case I want to add to these changes. Give me a few minutes and I'll update now.
