### PR TITLE
[Fix #4843] Fix shadow rescued Exceptions of same error code

### LINKED ISSUE #4843: Errno::EAGAIN != Errno::EWOULDBLOCK
## Expected behavior

Running RuboCop on a file with the contents

```ruby
begin
rescue Errno::EAGAIN, Errno::EWOULDBLOCK
  raise
end
```

should not show an error, since they *may* be the same, but don't have to be.

## Actual behavior

The following offense is detected:

```
errno.rb:2:1: W: Do not shadow rescued Exceptions.
rescue Errno::EAGAIN, Errno::EWOULDBLOCK
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

## RuboCop version

```
$ rubocop -V
0.50.0 (using Parser 2.4.0.0, running on ruby 2.3.3 universal.x86_64-darwin17)
```

### PR DESCRIPTION
**Pull request by koic**
This PR fixes #4843.
:memo: System dependent error code depends on runtime environment.

This PR also refactor against the following offenses arising from this change.
1db316c

```
% rubocop lib/rubocop/cop/lint/shadowed_exception.rb
Inspecting 1 file
C

Offenses:

lib/rubocop/cop/lint/shadowed_exception.rb:73:9: C: Cyclomatic complexity for contains_multiple_levels_of_exceptions? is too high. [8/6]
        def contains_multiple_levels_of_exceptions?(group)
        ^^^
lib/rubocop/cop/lint/shadowed_exception.rb:73:9: C: Perceived complexity for contains_multiple_levels_of_exceptions? is too high. [9/7]
        def contains_multiple_levels_of_exceptions?(group)
        ^^^
lib/rubocop/cop/lint/shadowed_exception.rb:80:37: C: Avoid using {...} for multi-line blocks.
          group.combination(2).any? { |a, b|
                                    ^

1 file inspected, 3 offenses detected
```

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Used the same coding conventions as the rest of the project.
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] All tests(`rake spec`) are passing.
* [x] The new code doesn't generate RuboCop offenses that are checked by `rake internal_investigation`.
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [ ] Updated cop documentation with `rake generate_cops_documentation` (required only when you've added a new cop or changed the configuration/documentation of an existing cop).

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/lint/shadowed_exception.rb [hunk 1]
```diff
@@ -77,7 +77,21 @@ def contains_multiple_levels_of_exceptions?(group)
...
 
-          group.combination(2).any? { |a, b| a && b && a <=> b }
+          group.combination(2).any? do |a, b|
+            compare_exceptions(a, b)
+          end
+        end
+
+        def compare_exceptions(a, b)
+          if system_call_error?(a) && system_call_error?(b)
+            a.const_get(:Errno) != b.const_get(:Errno)
```
Comment (reitermarkus) [inline lib/rubocop/cop/lint/shadowed_exception.rb]: I'm not sure this will work.

I have the following:

```ruby
begin
  something
rescue Errno::EAGAIN, Errno::EWOULDBLOCK, Errno::ECONNABORTED, Errno::EPROTO, Errno::EINTR
  handle_exception
end
```

Now it will report an offense, because i.e. `Errno::EAGAIN::Errno != Errno::ECONNABORTED`, or am I missing something?

Comment (koic) [reply lib/rubocop/cop/lint/shadowed_exception.rb]: Thanks for the feedback and reproduce code! This was not enough condition 💦 
I think that this issue could be solved with the following commit.
5b67c78

File: CHANGELOG.md [hunk 2]
```diff
@@ -29,6 +29,7 @@
 * [#4830](https://github.com/bbatsov/rubocop/issues/4830): Prevent `Lint/BooleanSymbol` from truncating symbol's value in the message when offense is located in the new syntax hash. ([@akhramov][])
 * [#4747](https://github.com/bbatsov/rubocop/issues/4747): Fix `Rails/HasManyOrHasOneDependent` cop incorrectly flags `with_options` blocks. ([@koic][])
 * [#4836](https://github.com/bbatsov/rubocop/issues/4836): Make `Rails/OutputSafety` aware of safe navigation operator. ([@drenmi][])
+* [#4843](https://github.com/bbatsov/rubocop/issues/4843): Fix `Lint/ShadowedException` cop aware of same system error code. ([@koic][])
```
Comment (bbatsov) [inline CHANGELOG.md]: Fix -> Make

File: spec/rubocop/cop/lint/shadowed_exception_spec.rb [hunk 3]
```diff
@@ -60,6 +60,21 @@
       RUBY
     end
 
+    it 'accepts rescuing contain multiple same error code exceptions' do
```
Comment (bbatsov) [inline spec/rubocop/cop/lint/shadowed_exception_spec.rb]: rescue containing

File: lib/rubocop/cop/lint/shadowed_exception.rb [hunk 4]
```diff
@@ -77,7 +77,21 @@ def contains_multiple_levels_of_exceptions?(group)
             return !(group.size == 2 && group.include?(NilClass))
           end
 
-          group.combination(2).any? { |a, b| a && b && a <=> b }
+          group.combination(2).any? do |a, b|
+            compare_exceptions(a, b)
+          end
+        end
+
+        def compare_exceptions(a, b)
```
Comment (bbatsov) [inline lib/rubocop/cop/lint/shadowed_exception.rb]: Not the biggest fan of params named `a` and `b`, even if here it's relatively clear what they mean.

File: lib/rubocop/cop/lint/shadowed_exception.rb [hunk 5]
```diff
@@ -77,7 +77,21 @@ def contains_multiple_levels_of_exceptions?(group)
...
+          if system_call_error?(a) && system_call_error?(b)
+            a.const_get(:Errno) != b.const_get(:Errno) && a <=> b
```
Comment (bbatsov) [inline lib/rubocop/cop/lint/shadowed_exception.rb]: I'd probably add a comment here explaining the need for this.

**Comment by bbatsov** [comment]
I'd also add something about all of this in the cop's documentation, as it's a pretty interesting special case.

File: spec/rubocop/cop/lint/shadowed_exception_spec.rb (hunk 3 above)
Comment (koic) [reply spec/rubocop/cop/lint/shadowed_exception_spec.rb]: I fixed typos in a94b6fb.

File: lib/rubocop/cop/lint/shadowed_exception.rb (hunk 4 above)
Comment (koic) [reply lib/rubocop/cop/lint/shadowed_exception.rb]: I changed the variable name in d88837e. Because the line becomes longer, I'm changing the method name a little.

**Comment by koic** [comment]
Thanks for the review. I added a explanation for this special case in 5909920. Also added source code comment to this commit.

File: lib/rubocop/cop/lint/shadowed_exception.rb [hunk 6]
```diff
@@ -30,6 +28,22 @@ module Lint
...
+      #
+      #   # good, however depending on runtime environment.
+      #   #
+      #   # This is a special case for system call errors.
+      #   # System dependent error code depends on runtime environment.
+      #   # For example, whether `Errno::EAGAIN` and `Errno::EWOULDBLOCK` are
+      #   # the same error code or different error code depends on environment.
+      #   # This good case is for `Errno::EAGAIN` and `Errno::EWOULDBLOCK` with
+      #   # the same error code.
+      #   # It is a bad case in different error code environment.
```
Comment (reitermarkus) [inline lib/rubocop/cop/lint/shadowed_exception.rb]: It shouldn't be a bad case in any environment.

Comment (koic) [reply lib/rubocop/cop/lint/shadowed_exception.rb]: Oops! This is my mistake. Thanks.

**Comment by bbatsov** [comment]
👍
