### PR TITLE
[FIX #4563] Style/TrailingUnderscoreVariable cop leaves an unclosed parentheses

### LINKED ISSUE #4563: Style/TrailingUnderscoreVariable cop leaves an unclosed parenthesis
`Style/TrailingUnderscoreVariable` cop wrongly fixes
```ruby
(foo, _) = [1, 2, 3]
```
into
```ruby
(foo, = [1, 2, 3]
```
and breaks the syntax.

Maybe the problem is not with this specific cop and the parenthesis should be removed first by another cop.

Otherwise, it should not remove the closing parenthesis.

--------

## Expected behavior

It should replace to `foo, = [1, 2, 3]` or `(foo, ) = [1, 2, 3]`

## Actual behavior

It leaves an unclosed parenthesis and breaks the syntax.

## Steps to reproduce the problem

```ruby
# test.rb
(foo, _) = [1, 2, 3]
puts foo
```

```shell
rubocop -a test.rb
```

## RuboCop version

```
$ rubocop -V
0.49.1 (using Parser 2.3.3.1, running on ruby 2.3.3 x86_64-darwin15)
```

### PR DESCRIPTION
**Pull request by smakagon**
This fixes autocorrect issue with `Style/TrailingUnderscoreVariable`.
Without this fix cop would autocorrect this code:
```
(foo, _) = [1, 2, 3]
```

To this: 
```
(foo, = [1, 2, 3]
```

With the fix it autocorrects this code:
```
(foo, _) = [1, 2, 3]
```  

To the following:
```
(foo,) = [1, 2, 3]
```

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Used the same coding conventions as the rest of the project.
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] All tests(`rake spec`) are passing.
* [x] The new code doesn't generate RuboCop offenses that are checked by `rake internal_investigation`.
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Updated cop documentation with `rake generate_cops_documentation` (required only when you've added a new cop or changed the configuration/documentation of an existing cop).

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: spec/rubocop/cop/style/trailing_underscore_variable_spec.rb [hunk 1]
```diff
@@ -169,6 +169,32 @@
...
       end
+
+      context 'with parentheses' do
+        it 'leaves parentheses but removes trailing underscores' do
+          new_source = autocorrect_source('(a, b, _) = foo()')
+
+          expect(new_source).to eq('(a, b,) = foo()')
+        end
+
+        it 'removes parentheses when every assignment is to `_`' do
```
Comment (Drenmi) [inline spec/rubocop/cop/style/trailing_underscore_variable_spec.rb]: I would change the description of this test case and the next to mention that it removes the entire assignment, not just the parentheses. 🙂

File: lib/rubocop/cop/style/trailing_underscore_variable.rb [hunk 2]
```diff
@@ -96,16 +96,35 @@ def unneeded_range(node)
...
+            return range_for_parentheses(first_offense, left)
+          end
+
+          range_between(
+            first_offense.source_range.begin_pos,
+            node.loc.operator.begin_pos
+          )
+        end
+
+        def unused_variable_only?(offense, variables)
```
Comment (Drenmi) [inline lib/rubocop/cop/style/trailing_underscore_variable.rb]: Method name should be pluralized as `#unused_variables_only?`? 🙂

**Comment by Drenmi** [comment]
Changes look good! I was a bit surprised by this cop's reliance on ranges, though, instead of working with the child nodes of `(mlhs)`. WDYT @smakagon?

File: lib/rubocop/cop/style/trailing_underscore_variable.rb (hunk 2 above)
Comment (smakagon) [inline lib/rubocop/cop/style/trailing_underscore_variable.rb]: Thanks, will rename.

File: spec/rubocop/cop/style/trailing_underscore_variable_spec.rb (hunk 1 above)
Comment (smakagon) [inline spec/rubocop/cop/style/trailing_underscore_variable_spec.rb]: Yes, makes sense, I'll change that.

**Comment by smakagon** [comment]
@Drenmi I was surprised too. This cop looked pretty simple to me, but when I started to look into implementation I figured out that it's not that easy.

I think it was implemented basing on ranges because we have to deal with commas and spaces (and parentheses now), but in general I feel like there is a room for improvement. 
Code I added is not the best one I ever wrote too, though.

I was focused mostly on the fix for autocorrect. Do you think we should refactor it?

**Comment by Drenmi** [comment]
@smakagon: I think the PR is great. Short and focused. I'd say no need to refactor. Was just curious why the original implementer used this approach. 🙂

**Comment by bbatsov** [comment]
> It might be nice to still refactor this cop down the road.
