### PR TITLE
[Fix #4252] Add new Style/TrailingBodyOnMethodDefinition cop

### LINKED ISSUE #4252: A semicolon in the same line as the method signature is allowed
A semicolon in the same line as the method signature isn’t violating any existing cop.

## Expected behavior

I expect RuboCop (Style/Semicolon) to complain about having a semicolon after `def foo`.

## Actual behavior

No offenses detected.

## Steps to reproduce the problem

Run `rubocop` on this file:

```rb
# frozen_string_literal: true

def foo; nil
end
```

## RuboCop version

```
$ rubocop -V
0.48.1 (using Parser 2.4.0.0, running on ruby 2.4.1 x86_64-darwin15)
```

### PR DESCRIPTION
**Pull request by garettarrowood**
Alternative approach to "fixing" `Style/SingleLineMethod` in #4849 .

As a fix to #4252, this PR introduces a new cop - `Style/TrailingBodyOnMethodDefinition`.

-----------------

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Used the same coding conventions as the rest of the project.
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] All tests(`rake spec`) are passing.
* [x] The new code doesn't generate RuboCop offenses that are checked by `rake internal_investigation`.
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Updated cop documentation with `rake generate_cops_documentation` (required only when you've added a new cop or changed the configuration/documentation of an existing cop).

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/style/trailing_body_on_method_definition.rb [hunk 1]
```diff
@@ -0,0 +1,79 @@
...
+          return unless node.body
+          return unless trailing_body?(node)
+
+          add_offense(node)
+        end
+        alias on_defs on_def
+
+        private
+
+        def trailing_body?(node)
```
Comment (garettarrowood) [inline lib/rubocop/cop/style/trailing_body_on_method_definition.rb]: Refactoring this logic and adding more tests - WIP.

Comment (Drenmi) [reply lib/rubocop/cop/style/trailing_body_on_method_definition.rb]: Ping me when you require a review. 🙂

Comment (garettarrowood) [reply lib/rubocop/cop/style/trailing_body_on_method_definition.rb]: @Drenmi - I believe this is ready now. I think I've found an accurate way to determine if it has a `trailing_body`.

File: lib/rubocop/cop/style/trailing_body_on_method_definition.rb [hunk 2]
```diff
@@ -0,0 +1,81 @@
...
+
+        MSG = 'Method body goes below definition.'.freeze
+
+        def on_def(node)
+          return unless node.body
+          return unless trailing_body?(node)
+
+          add_offense(node)
+        end
+        alias on_defs on_def
```
Comment (garettarrowood) [inline lib/rubocop/cop/style/trailing_body_on_method_definition.rb]: I am unsure about the need for this alias. I see it on a lot of cops but am yet not sure what it is achieving.

File: lib/rubocop/ast/node.rb [hunk 3]
```diff
@@ -314,13 +314,18 @@ def parent_module_name
       ## Predicates
 
       def multiline?
-        source_range && (source_range.first_line != source_range.last_line)
+        line_count > 1
       end
 
       def single_line?
         !multiline?
```
Comment (Drenmi) [inline lib/rubocop/ast/node.rb]: I think we can express this as `line_count.one?` now. Since if `source_range` for some reason is `nil`, that isn't a single-line node. WDYT?

File: lib/rubocop/cop/style/trailing_body_on_method_definition.rb (hunk 2 above)
Comment (Drenmi) [reply lib/rubocop/cop/style/trailing_body_on_method_definition.rb]: It applies the cop to class method definitions as well.

File: lib/rubocop/cop/style/trailing_body_on_method_definition.rb [hunk 4]
```diff
@@ -0,0 +1,81 @@
...
+      #
+      #   # good
+      #   def some_method
+      #     do_stuff
+      #   end
+      #
+      class TrailingBodyOnMethodDefinition < Cop
+        include AutocorrectAlignment
+
+        MSG = 'Method body goes below definition.'.freeze
```
Comment (Drenmi) [inline lib/rubocop/cop/style/trailing_body_on_method_definition.rb]: The message is normally expressed with an imperative verb that tells the user what to do or not to do. E.g.: "Put the method definition body on its own line."

File: lib/rubocop/cop/style/trailing_body_on_method_definition.rb [hunk 5]
```diff
@@ -0,0 +1,81 @@
...
+          return unless trailing_body?(node)
+
+          add_offense(node)
+        end
+        alias on_defs on_def
+
+        private
+
+        def trailing_body?(node)
+          node.line_count >= 2 && body_start_on_first_line?(node)
```
Comment (Drenmi) [inline lib/rubocop/cop/style/trailing_body_on_method_definition.rb]: `node.line_count >= 2` == `node.line_count > 1` == `node.multiline?` 🙂

File: lib/rubocop/cop/style/trailing_body_on_method_definition.rb (hunk 1 above)
Comment (Drenmi) [reply lib/rubocop/cop/style/trailing_body_on_method_definition.rb]: This method is incoherent if the `node.body` condition that is now in `#on_def` isn't moved inside. 🙂

File: lib/rubocop/cop/style/trailing_body_on_method_definition.rb [hunk 6]
```diff
@@ -0,0 +1,81 @@
...
+        end
+
+        def body_start_on_first_line?(node)
+          node.source_range.first_line == node.body.source_range.first_line
+        end
+
+        def autocorrect(node)
+          body = node.body
```
Comment (Drenmi) [inline lib/rubocop/cop/style/trailing_body_on_method_definition.rb]: I don't think this needs a local variable, as it doesn't add anything in terms of readability, and is only used once. 🙂

File: spec/rubocop/cop/style/trailing_body_on_method_definition_spec.rb [hunk 7]
```diff
@@ -0,0 +1,123 @@
...
+      def seven_times(stuff) 7.times { do_this(stuff) }
+      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Method body goes below definition.
+      end
+    RUBY
+  end
+
+  it 'registers when body starts on def line & continues one more line' do
+    expect_offense(<<-RUBY.strip_indent)
+      def some_method; foo = {}
+      ^^^^^^^^^^^^^^^^^^^^^^^^^ Method body goes below definition.
```
Comment (Drenmi) [inline spec/rubocop/cop/style/trailing_body_on_method_definition_spec.rb]: Ideally this would highlight the actual body expression. 🙂

File: spec/rubocop/cop/style/trailing_body_on_method_definition_spec.rb [hunk 8]
```diff
@@ -0,0 +1,123 @@
...
+    expect(corrected).to eq ['  def some_method; ',
+                             '    body',
+                             '  end'].join("\n")
+  end
+
+  it 'auto-corrects with comment after body' do
+    corrected = autocorrect_source(['  def some_method; body # stuff',
+                                    '  end'].join("\n"))
+    expect(corrected).to eq ['  # stuff',
+                             '  def some_method; ',
```
Comment (Drenmi) [inline spec/rubocop/cop/style/trailing_body_on_method_definition_spec.rb]: Could the auto-correct be enhanced to remove the trailing semicolon without too much added complexity?

File: lib/rubocop/ast/node.rb (hunk 3 above)
Comment (garettarrowood) [reply lib/rubocop/ast/node.rb]: While `Numeric` has the `zero?` method, `one?` doesn't seem native to the Ruby lib. How about `line_count == 1`?

File: spec/rubocop/cop/style/trailing_body_on_method_definition_spec.rb (hunk 8 above)
Comment (garettarrowood) [reply spec/rubocop/cop/style/trailing_body_on_method_definition_spec.rb]: Addressed all the other comments except this one. Will take a longer look at it later today. Thanks for the great review!

File: spec/rubocop/cop/style/trailing_body_on_method_definition_spec.rb [hunk 9]
```diff
@@ -0,0 +1,131 @@
...
+        more_stuff
+      end
+    RUBY
+  end
+
+  it 'does not register offense with trailing body on method end' do
+    expect_no_offenses(<<-RUBY.strip_indent)
+      def some_method
+        body
+      foo; end
```
Comment (garettarrowood) [inline spec/rubocop/cop/style/trailing_body_on_method_definition_spec.rb]: I'd be happy to add a sibling Cop to address this scenario. WDYT?

Comment (bbatsov) [reply spec/rubocop/cop/style/trailing_body_on_method_definition_spec.rb]: 👍 

Makes perfect sense to me.

File: lib/rubocop/ast/node.rb (hunk 3 above)
Comment (Drenmi) [reply lib/rubocop/ast/node.rb]: Right. Sorry. `#one?` is part of `Enumerable`. 🙂 `line_count == 1` is fine.

File: lib/rubocop/cop/style/trailing_body_on_method_definition.rb [hunk 10]
```diff
@@ -0,0 +1,91 @@
+# frozen_string_literal: true
+
+module RuboCop
+  module Cop
+    module Style
+      # This cop checks for trailing code after the method definition.
+      #
+      # @example
+      #   # bad
+      #   def some_method; do_stuff
```
Comment (bbatsov) [inline lib/rubocop/cop/style/trailing_body_on_method_definition.rb]: I think you should add some examples with more than one line of body here as well.

File: lib/rubocop/cop/style/trailing_body_on_method_definition.rb [hunk 11]
```diff
@@ -0,0 +1,91 @@
...
+      #
+      #   # good
+      #   def some_method
+      #     do_stuff
+      #   end
+      #
+      class TrailingBodyOnMethodDefinition < Cop
+        include AutocorrectAlignment
+
+        MSG = 'Put the method definition body on its own line.'.freeze
```
Comment (bbatsov) [inline lib/rubocop/cop/style/trailing_body_on_method_definition.rb]: Place the first line of a multi-line method definition's body on its own line.

File: lib/rubocop/cop/style/trailing_body_on_method_definition.rb [hunk 12]
```diff
@@ -0,0 +1,91 @@
...
+        end
+        alias on_defs on_def
+
+        private
+
+        def trailing_body?(node)
+          node.body && node.multiline? && body_starts_on_def?(node)
+        end
+
+        def body_starts_on_def?(node)
```
Comment (bbatsov) [inline lib/rubocop/cop/style/trailing_body_on_method_definition.rb]: on_def_line? perhaps?

File: lib/rubocop/cop/style/trailing_body_on_method_definition.rb (hunk 11 above)
Comment (garettarrowood) [reply lib/rubocop/cop/style/trailing_body_on_method_definition.rb]: Thanks! That's a very clear message.

File: lib/rubocop/cop/style/trailing_body_on_method_definition.rb (hunk 12 above)
Comment (garettarrowood) [reply lib/rubocop/cop/style/trailing_body_on_method_definition.rb]: Sounds good to me.

**Comment by garettarrowood** [comment]
Thanks for the awesome review comments, @Drenmi & @bbatsov !

I've completed another set of changes based off of this branch that adds a `Style/TrailingMethodEndStatement` cop.  When everyone is happy with this addition, and its merged, I'll rebase off master and open a new PR.

**Comment by bbatsov** [comment]
Thanks! 👍
