### PR TITLE
[Fix #5357] Fix `Lint/InterpolationCheck` false positives on escaped interpolations

### LINKED ISSUE #5357: False Positive: Lint/InterpolationCheck
## Expected behavior

The cop should understand matching things that look like string interpolations inside a Regex

## Actual behavior

Matching `\#{20}` is matching 20 `#` in a row, not a string interpolation for a variable named `20`

## Steps to reproduce the problem

```ruby
# baz.rb
class Foo
  def bar(qux)
    /\#{20}/
  end
end
```

    > rubocop --only='Lint/InterpolationCheck' baz.rb

## Output

```
Inspecting 1 file
W

Offenses:

baz.rb:3:6: W: Lint/InterpolationCheck: Interpolation in single quoted string detected. Use double quoted strings if you need interpolation.
    /\#{20}/
     ^^^^^^

1 file inspected, 1 offense detected
```

## RuboCop version

```
$ rubocop -V
0.52.1 (using Parser 2.4.0.2, running on ruby 2.4.3 x86_64-darwin16)
```

### PR DESCRIPTION
**Pull request by pocke**
See https://github.com/bbatsov/rubocop/issues/5357    

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `rake default` or `rake parallel`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/lint/interpolation_check.rb [hunk 1]
```diff
@@ -18,12 +18,13 @@ module Lint
       #   foo = "something with #{interpolation} inside"
       class InterpolationCheck < Cop
         MSG = 'Interpolation in single quoted string detected. '\
-	      'Use double quoted strings if you need interpolation.'.freeze
+              'Use double quoted strings if you need interpolation.'.freeze
```
Comment (bbatsov) [inline lib/rubocop/cop/lint/interpolation_check.rb]: We need a cop for that.
