### PR TITLE
[Fix #2369] Don't add trailing comma to multiline method chain which is sole arg

### LINKED ISSUE #2369: Issue with TrailingComma Cop
Here is the example spec I wrote for `spec/rubocop/cop/style/trailing_comma_spec.rb`

```ruby
    it 'accepts a method with an object with a multiline method call' do
      inspect_source(cop, <<-CODE)
        some_method(
          SomeObject
            .method
            .method
        )
      CODE
      expect(cop.offenses).to be_empty
    end
```

Test Output
```
Failures:

  1) RuboCop::Cop::Style::TrailingComma with single line list of values when EnforcedStyleForMultiline is comma accepts a method with an object with a multiline method call
     Failure/Error: expect(cop.offenses).to be_empty
       expected `[#<RuboCop::Cop::Offense:0x007f88ebb5a8f8 @severity=#<RuboCop::Cop::Severity:0x007f88ebb5a8d0 @name=:convention>, @location=#<Parser::Source::Range (string) 74...81>, @message="Put a comma after the last parameter of a multiline method call.", @cop_name="Style/TrailingComma", @corrected=false>].empty?` to return true, got false
     Shared Example Group: "single line lists" called from ./spec/rubocop/cop/style/trailing_comma_spec.rb:121
     # ./spec/rubocop/cop/style/trailing_comma_spec.rb:48:in `block (3 levels) in <top (required)>'

Finished in 13.66 seconds (files took 1.52 seconds to load)
3443 examples, 1 failure, 3 pending

Failed examples:

rspec ./spec/rubocop/cop/style/trailing_comma_spec.rb[1:1:2:5] # RuboCop::Cop::Style::TrailingComma with single line list of values when EnforcedStyleForMultiline is comma accepts a method with an object with a multiline method call

Randomized with seed 9208
```

I would expect it to detect that while I am multilining, I only have one parameter, and the need for a comma here is not relevant.

Alternatively, it would be great if this `TrailingComma` cop could be configured to apply to collection objects, or methods, or both.

### PR DESCRIPTION
**Pull request by alexdowad**
RuboCops, do you agree with #2369? Personally, I think adding a trailing comma in that case does look strange.

### CODE REVIEW

**Comment by bbatsov** [comment]
:+1: Can't argue with that.

As I mentioned in the ticket itself - I think that treating collection literals and method calls the same was a mistake, but I don't use trailing comma at all, so I didn't argue much about this.

File: lib/rubocop/cop/style/trailing_comma.rb [hunk 1]
```diff
@@ -92,11 +90,16 @@ def check(node, items, kind, begin_pos, end_pos)
...
+          elsif should_have_comma?(style, node, items)
             put_comma(items, kind, sb)
           end
         end
-        # rubocop:enable Metrics/MethodLength
+
+        def should_have_comma?(style, node, items)
+          [:comma, :consistent_comma].include?(style) &&
+            multiline?(node) &&
+            (items.size > 1 || items.last.hash_type?)
```
Comment (nikitug) [inline lib/rubocop/cop/style/trailing_comma.rb]: Not sure if `items.size > 1` should be applied to Hashes. Currently rubocop forces me to do:

```ruby
{
  'data' => [],
  'meta' => {
    'pagination' => {
      'offset' => offset,
      'count' => count,
      'limit' => limit,
      'total' => total,
    }
  },
}
```

instead of:

```ruby
{
  'data' => [],
  'meta' => {
    'pagination' => {
      'offset' => offset,
      'count' => count,
      'limit' => limit,
      'total' => total,
    },
  },
}
```

Comment (alexdowad) [inline lib/rubocop/cop/style/trailing_comma.rb]: Good point.

**Comment by alexdowad** [comment]
What is the intention of `comma` and `consistent_comma` for arrays and hashes with one element? I think both of them should add a comma in that case, right?

**Comment by alexdowad** [comment]
After studying the code a bit closer, I have to agree with @bbatsov that combining checks on method calls and literals into the same cop was a mistake.

**Comment by bbatsov** [comment]
> What is the intention of comma and consistent_comma for arrays and hashes with one element? I think both of them should add a comma in that case, right?

There was a debate whether trailing commas make sense for multi-line literals with more than one element per line. I think this is why we have two styles. I'm a believe that this trailing commas stuff doesn't make much sense if you have more than 1 element per line.

**Comment by alexdowad** [comment]
"More than one element per line" is meaningless when there is only one element in total. That is what I am asking about. Arrays like this:

```ruby
[
  "value"
]
```

Or Hashes like this:

```
{
  'key' => 'value'
}
```

...should they have a trailing comma using the `comma` style? How about `consistent_comma`?

**Comment by bbatsov** [comment]
> How about consistent_comma?

It would require a trailing comma in every array/hash literal, regardless of its structure.

**Comment by alexdowad** [comment]
> It would require a trailing comma in every array/hash literal, regardless of its structure.

But in all cases, this is bad, right?

```ruby
[1,]
```
