### PR TITLE
[Fix #4932] Accept configuration for `Lint/Syntax`

### LINKED ISSUE #4932: Syntax Cop Configuration Error
Recently upgraded rubocop to 0.51.0. We have our own `rubocop.yml` which is inherited from `.rubocop.enabled.yml`, `.rubocop.disabled.yml`, and `.rubocop.default.yml`. Each of them is the same as the `enabled.yml`, `disabled.yml`, `default.yml` in the release `0.51.0`.
However, we tried to run `rubocop file.rb` on command line and we got the following error message.
```
Error: configuration for Syntax cop found in .rubocop.enabled.yml
This cop cannot be configured.
```
When we look at the `config.rb` in the release `0.51.0`, it appears that [this cop](https://github.com/bbatsov/rubocop/blob/v0.51.0/config/enabled.yml#L1401-L1403) in our `.rubocop.enabled.yml` fails the validation [here](https://github.com/bbatsov/rubocop/blob/v0.51.0/lib/rubocop/config.rb#L384-L391) in `config.rb`.
The logic here seems kinda odd: it returns unless the `Lint/Syntax` or `Syntax` is included in `valid_cop_names`, otherwise raise an error. In another word, if `Lint/Syntax` or `Syntax` is included in `valid_cop_names` then raise an error.
Our temporary solution is to comment out `Syntax cop`.

## Steps to reproduce the problem
0. Upgrade rubocop to `0.51.0`

1. Copy `enabled.yml`, `disabled.yml`, and `default.yml` and rename them to `.rubocop.enabled.yml`, `.rubocop.disabled.yml`, and `.rubocop.default.yml`.

2. Create a new file name `.rubocop.yml` with the following content
```
inherit_from:
  - .rubocop.enabled.yml
  - .rubocop.disabled.yml
  - .rubocop.default.yml
```

3. Remove the following block in `.rubocop.default.yml` to avoid duplicate inheritance. 
```
inherit_from:
  - enabled.yml
  - disabled.yml
```

4. run rubocop on an arbitrary file

## Expected behavior

It should check that file without exceptions.

## Actual behavior

Got the following error
```
Error: configuration for Syntax cop found in .rubocop.enabled.yml
This cop cannot be configured.
```

## RuboCop version

```
$ rubocop -V
0.51.0 (using Parser 2.4.0.0, running on ruby 2.3.5 x86_64-darwin16)
```

### PR DESCRIPTION
**Pull request by tdeo**
Rubocop forbids configuration the `Lint/Syntax` cop so it doesn't
get disabled. This is failing when loading the default rubocop
configuration from rubocop. This changes it to accept configuration
that doesn't differ from the default.

-----------------

Before submitting the PR make sure the following are checked:

* [ ] Wrote [good commit messages][1].
* [ ] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [ ] Used the same coding conventions as the rest of the project.
* [ ] Feature branch is up-to-date with `master` (if not - rebase it).
* [ ] Squashed related commits together.
* [ ] Added tests.
* [ ] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [ ] All tests(`rake spec`) are passing.
* [ ] The new code doesn't generate RuboCop offenses that are checked by `rake internal_investigation`.
* [ ] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [ ] Updated cop documentation with `rake generate_cops_documentation` (required only when you've added a new cop or changed the configuration/documentation of an existing cop).

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/config.rb [hunk 1]
```diff
@@ -411,9 +411,12 @@ def warn_about_unrecognized_cops(invalid_cop_names)
...
     end
 
-    def validate_syntax_cop(valid_cop_names)
-      return unless valid_cop_names.include?('Lint/Syntax') ||
-                    valid_cop_names.include?('Syntax')
+    def validate_syntax_cop
+      syntax_config = self['Lint/Syntax'] || self['Syntax']
+      default_config = ConfigLoader.default_configuration['Lint/Syntax']
+
+      return unless syntax_config && \
```
Comment (pocke) [inline lib/rubocop/config.rb]: We can omit the `\`.
BTW we need a cop for this problem.

File: lib/rubocop/config.rb [hunk 2]
```diff
@@ -411,9 +411,12 @@ def warn_about_unrecognized_cops(invalid_cop_names)
       end
     end
 
-    def validate_syntax_cop(valid_cop_names)
-      return unless valid_cop_names.include?('Lint/Syntax') ||
-                    valid_cop_names.include?('Syntax')
+    def validate_syntax_cop
+      syntax_config = self['Lint/Syntax'] || self['Syntax']
```
Comment (bbatsov) [inline lib/rubocop/config.rb]: This reminds me that at some point we drop support for non-namespaced cop references. That's just a remnant of the past.

File: lib/rubocop/config.rb [hunk 3]
```diff
@@ -411,9 +411,12 @@ def warn_about_unrecognized_cops(invalid_cop_names)
...
+      default_config = ConfigLoader.default_configuration['Lint/Syntax']
+
+      return unless syntax_config &&
+                    default_config.merge(syntax_config) != default_config
 
       raise ValidationError,
```
Comment (bbatsov) [inline lib/rubocop/config.rb]: Shouldn't say something more meaningful here - like "It's not possible to disable this cop" or whatever?

**Comment by tdeo** [comment]
@bbatsov I see you reverted this PR. Would you mind giving a bit of context?

**Comment by bbatsov** [comment]
Hmm, I don't remember doing this at all. I wonder if I did some mistake or had something in mind...

**Comment by tdeo** [comment]
Actually you did it on a branch - I don't know why I didn't realize that in the first place: https://github.com/bbatsov/rubocop/commits/revert-5153-syntax_config. But I couldn't find any issue / anything else relating to this, that's why I was wondering if anything was wrong.
