### PR TITLE
[Fix #4130] Add a new cop Style/RedundantConditional

### LINKED ISSUE #4130: Introduce cop for redundant ternary condition
I'm working on fixing up a legacy project, and I keep seeing this over and over:

```ruby
foo == bar ? true : false
```

We should have a cop to detect this.

We could also detect the inverse:

```ruby
foo == bar ? false : true
```

and suggest:

```ruby
foo != bar
```

This should also work for this construct:

```ruby
foo? ? false : true
```

which can be replaced with:

```ruby
!foo?
```

I'm not sure how common this is for regular `if`-statements, but could also be extended to cover those.

--------

## Expected behavior

RuboCop registers an offense for:

```ruby
condition ? true : false
```

## Actual behavior

RuboCop does not register an offense.

## Steps to reproduce the problem

Run RuboCop on:

```ruby
condition ? true : false
```

## RuboCop version

Include the output of `rubocop -V`. Here's an example:

```
$ rubocop -V
0.47.1 (using Parser 2.3.3.1, running on ruby 2.3.3 x86_64-darwin15)
```

### PR DESCRIPTION
**Pull request by petehamilton**
Returning true/false from a conditional involving a boolean conditional
is unnecessary. Instead it makes more sense to just use the boolean
expression itself.

This cop identifies and autocorrects this in ternary, if/else and
modifier form.

See https://github.com/bbatsov/rubocop/issues/4130

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Used the same coding conventions as the rest of the project.
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [ ] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] All tests are passing.
* [x] The new code doesn't generate RuboCop offenses.
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Updated cop documentation with `rake generate_cops_documentation` (required only when you've added a new cop or changed the configuration/documentation of an existing cop).

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/style/redundant_ternary.rb [hunk 1]
```diff
@@ -0,0 +1,66 @@
...
+      #
+      #   # bad
+      #   x == y ? false : true
+      #
+      #   # good
+      #   x != y
+      class RedundantTernary < Cop
+        include ConfigurableEnforcedStyle
+
+        OPS = %w[== === != < > <= >= <=>].freeze
```
Comment (Drenmi) [inline lib/rubocop/cop/style/redundant_ternary.rb]: There should be a `COMPARISON_METHODS` constant available to you from `Cop`, I believe. 🙂

File: lib/rubocop/cop/style/redundant_ternary.rb [hunk 2]
```diff
@@ -0,0 +1,66 @@
...
+        MSG = 'Returning true/false from a conditional is unnecessary'.freeze
+
+        def on_if(node)
+          return unless node.ternary? && offense?(node)
+
+          add_offense(node, node.source_range, MSG)
```
Comment (Drenmi) [inline lib/rubocop/cop/style/redundant_ternary.rb]: `MSG` is passed automagically to `#add_offense` if you omit it. There are also keywords available for the second argument, giving:

```ruby
add_offense(node, :expression)
```

File: lib/rubocop/cop/style/redundant_ternary.rb [hunk 3]
```diff
@@ -0,0 +1,66 @@
...
+                         "(if (send _ {:#{OPS.join(' :')}} _) true false)"
+
+        def_node_matcher :redundant_ternary_inverted?,
+                         "(if (send _ {:#{OPS.join(' :')}} _) false true)"
+
+        def offense?(node)
+          redundant_ternary?(node) || redundant_ternary_inverted?(node)
+        end
+
+        def autocorrect(node)
```
Comment (Drenmi) [inline lib/rubocop/cop/style/redundant_ternary.rb]: There are two `#autocorrect` methods right now. 😅

File: spec/rubocop/cop/style/redundant_ternary_spec.rb [hunk 4]
```diff
@@ -0,0 +1,88 @@
...
+                  "x == y"
+
+  it_behaves_like "code with offense",
+                  "x == y ? false : true",
+                  "!(x == y)"
+
+  it_behaves_like "code without offense",
+                  "x == y ? 1 : 10"
+
+  xcontext "TODO" do
```
Comment (Drenmi) [inline spec/rubocop/cop/style/redundant_ternary_spec.rb]: We don't use code for project tracking. Leave a GitHub issue if you intend to do something later. 🙂

**Comment by bbatsov** [comment]
Btw, probably this cop can easily be extended to cover `if/else` as well. After all in the AST both `if` and the `ternary` op are represented similarly.

File: lib/rubocop/cop/style/redundant_ternary.rb (hunk 1 above)
Comment (petehamilton) [inline lib/rubocop/cop/style/redundant_ternary.rb]: Ah nice, I took this from the Lint/UselessComparison cop but good to know there's a constant, I can only see it used in Style/YodaCondition

File: lib/rubocop/cop/style/redundant_ternary.rb (hunk 2 above)
Comment (petehamilton) [inline lib/rubocop/cop/style/redundant_ternary.rb]: Nice, thanks! Took this from Style/TernaryParentheses, is `add_offense(node, :expression)` equivalent to `add_offense(node, node.source_range)`? Could you explain how?

File: lib/rubocop/cop/style/redundant_ternary.rb (hunk 3 above)
Comment (petehamilton) [inline lib/rubocop/cop/style/redundant_ternary.rb]: 🙈 👍

File: spec/rubocop/cop/style/redundant_ternary_spec.rb (hunk 4 above)
Comment (petehamilton) [inline spec/rubocop/cop/style/redundant_ternary_spec.rb]: For sure, I was planning to fill a few of these in before merging if possible then move the rest to issues and resolve in followup PRs, this was just my working copy at the time, should have made that clearer, sorry!

**Comment by petehamilton** [comment]
@bbatsov have updated this to cover the following cases:

```
x == y ? true : false

if x == y
  true
else
  false
end

true if x == y
```

File: spec/rubocop/cop/style/redundant_conditional_spec.rb [hunk 5]
```diff
@@ -0,0 +1,70 @@
...
+
+  it_behaves_like 'code with offense',
+                  'x == y ? false : true',
+                  '!(x == y)'
+
+  it_behaves_like 'code without offense',
+                  'x == y ? 1 : 10'
+
+  it_behaves_like 'code with offense',
+                  "if x == y\n  true\nelse\n  false\nend",
```
Comment (petehamilton) [inline spec/rubocop/cop/style/redundant_conditional_spec.rb]: Happy to change these to be heredocs or similar if preferred.

File: lib/rubocop/cop/style/redundant_conditional.rb [hunk 6]
```diff
@@ -0,0 +1,71 @@
...
+      #   x == y
+      #
+      #   # bad
+      #   x == y ? false : true
+      #
+      #   # good
+      #   x != y
+      class RedundantConditional < Cop
+        COMPARISON_OPERATORS = RuboCop::AST::Node::COMPARISON_OPERATORS
+                               .reject { |op| op == :! }.freeze
```
Comment (Drenmi) [inline lib/rubocop/cop/style/redundant_conditional.rb]: I think `:!` has been incorrectly lumped together with comparison operators in the constant in `Node`. It's okay to have a special case for it in your PR. I'll see if I can surgically remove it at a later point. 🙂

Comment (Drenmi) [inline lib/rubocop/cop/style/redundant_conditional.rb]: @petehamilton: Please see #4461. 🙂

Comment (petehamilton) [inline lib/rubocop/cop/style/redundant_conditional.rb]: 🙌

File: spec/rubocop/cop/style/redundant_conditional_spec.rb (hunk 5 above)
Comment (bbatsov) [inline spec/rubocop/cop/style/redundant_conditional_spec.rb]: They would read better for sure.

File: lib/rubocop/cop/style/redundant_conditional.rb [hunk 7]
```diff
@@ -0,0 +1,70 @@
...
+      #
+      #   # bad
+      #   x == y ? false : true
+      #
+      #   # good
+      #   x != y
+      class RedundantConditional < Cop
+        COMPARISON_OPERATORS = RuboCop::AST::Node::COMPARISON_OPERATORS
+
+        MSG = 'Returning true/false from a conditional is unnecessary.'.freeze
```
Comment (bbatsov) [inline lib/rubocop/cop/style/redundant_conditional.rb]: I'd check this to "This conditional expression can be replaced with its condition.".  Maybe you can interpolate the condition in the message.

File: lib/rubocop/cop/style/redundant_conditional.rb [hunk 8]
```diff
@@ -0,0 +1,70 @@
+# frozen_string_literal: true
+
+module RuboCop
+  module Cop
+    module Style
+      # This cop checks for redundant returning of true/false in conditionals
```
Comment (bbatsov) [inline lib/rubocop/cop/style/redundant_conditional.rb]: This should end with a `.`.

File: lib/rubocop/cop/style/redundant_conditional.rb (hunk 7 above)
Comment (petehamilton) [inline lib/rubocop/cop/style/redundant_conditional.rb]: Done. I haven't implemented interpolation as I figure we can't guarantee that the conditional will be short and a single-line string, which would presumably result in messy output?

File: lib/rubocop/cop/style/redundant_conditional.rb (hunk 8 above)
Comment (petehamilton) [inline lib/rubocop/cop/style/redundant_conditional.rb]: 👍

File: lib/rubocop/cop/style/redundant_conditional.rb (hunk 7 above)
Comment (bbatsov) [inline lib/rubocop/cop/style/redundant_conditional.rb]: While you're technically speaking true, most conditions are pretty short, so this might not be that big of a deal in practice.

Comment (petehamilton) [inline lib/rubocop/cop/style/redundant_conditional.rb]: Fair enough - happy to change.

File: spec/rubocop/cop/style/redundant_conditional_spec.rb [hunk 9]
```diff
@@ -0,0 +1,81 @@
...
+  it_behaves_like 'code with offense',
+                  <<-END.strip_indent,
+                    if x == y
+                      true
+                    else
+                      false
+                    end
+                  END
+                  "x == y\n",
+                  'x == y'
```
Comment (petehamilton) [inline spec/rubocop/cop/style/redundant_conditional_spec.rb]: @bbatsov not too happy with these specs now, they feel kind of messy with the trailing newline and then a repeat for the message. Any thoughts?

Could assume the message will be the expression stripped of any trailing newlines but that's not guaranteed to be true.

Comment (bbatsov) [inline spec/rubocop/cop/style/redundant_conditional_spec.rb]: There's some room for improvement for sure. I don't care much about the newlines, but I think you can pass some param which you'd interpolate in the `it` message, so it'd be more apparent which test is testing what. Right now the output would be pretty confusing.

File: spec/rubocop/cop/style/redundant_conditional_spec.rb [hunk 10]
```diff
@@ -0,0 +1,81 @@
...
+
+  it_behaves_like 'code with offense',
+                  <<-END.strip_indent,
```
Comment (bbatsov) [inline spec/rubocop/cop/style/redundant_conditional_spec.rb]: We typically use `RUBY` instead of `END` for ruby code snippets.

Comment (petehamilton) [inline spec/rubocop/cop/style/redundant_conditional_spec.rb]: Done.

**Comment by petehamilton** [comment]
@bbatsov hey, sorry for taking a little while to come back to this one. Keen to get it over the line.

Right now test output looks like this with `-f d` (i'm inspecting the code so the newlines don't screw up the output).

```
> be rspec spec/rubocop/cop/style/redundant_conditional_spec.rb -f d
Run options:
  include {:focus=>true}
  exclude {:broken=>#<Proc:./spec/spec_helper.rb:39>}

All examples were filtered out; ignoring {:focus=>true}

Randomized with seed 14967

RuboCop::Cop::Style::RedundantConditional
  behaves like code with offense
    when checking "if x == y\n  false\nelse\n  true\nend\n"
      auto-corrects
      registers an offense
      claims to auto-correct
  behaves like code without offense
    when checking "if x == y\n  1\nelse\n  2\nend\n"
      does not register an offense
  behaves like code with offense
    when checking "x == y ? true : false"
      claims to auto-correct
      auto-corrects
      registers an offense
  behaves like code with offense
    when checking "if x == y\n  true\nelse\n  false\nend\n"
      auto-corrects
      registers an offense
      claims to auto-correct
  behaves like code with offense
    when checking "x == y ? false : true"
      registers an offense
      claims to auto-correct
      auto-corrects
  behaves like code without offense
    when checking "x == y ? 1 : 10"
      does not register an offense

Finished in 0.10577 seconds (files took 1.23 seconds to load)
14 examples, 0 failures

Randomized with seed 14967
```

What are you suggesting as an alternative? Providing a description of each code snippet instead of the code inline? I was just following https://github.com/bbatsov/rubocop/blob/master/spec/rubocop/cop/style/ternary_parentheses_spec.rb as an example but happy to change!

**Comment by bbatsov** [comment]
> Right now test output looks like this with -f d (i'm inspecting the code so the newlines don't screw up the output).

The output is good enough for now. Just squash the commits together, rebase on top of `master` and get the build to pass.

**Comment by petehamilton** [comment]
@bbatsov on it.

**Comment by dobrynin** [comment]
Hi, I noticed this issue while using Rubocop as well. What's the status of the PR?

**Comment by petehamilton** [comment]
@dobrynin - totally my bad, I had it nearly ready to go and then started getting test failures after a rebase and totally dropped the ball.

Turned out they were coming from the change in test inspection methods introduced in https://github.com/bbatsov/rubocop/pull/4510. All fixed up and hopefully tests should go green now, at which point I think this should be good to merge.

**Comment by petehamilton** [comment]
@bbatsov @Drenmi all 👍 ?
