### PR TITLE
[Fix #5245] Make `Style/FormatStringToken` to allow regexp token

### LINKED ISSUE #5245: Style/FormatStringToken false positive
I came across the following false positive while doing rspec-puppet testing on an sshd module.
Sometimes contents of a file can include valid string tokens that look like unannotated Ruby tokens.
These are usually wrapped inside a RegEx for testing.

For example, `sshd_config` can include `%u` which is a valid username reference.

## Expected behavior

The following code shouldn't be flagged as offensive:

```
it {
  is_expected.to contain_file('/etc/ssh/sshd_config')
    .with_content(%r{^    ChrootDirectory /var/chroot/%u$})
}
```

## Actual behavior

RuboCop triggers `Style/FormatStringToken` error:

```
spec/classes/sshd_spec.rb:3:55: C: Style/FormatStringToken: Prefer annotated tokens (like %<foo>s) over unannotated tokens (like %s).
    .with_content(%r{^    ChrootDirectory /var/chroot/%u$})
                                                      ^^
```

## Steps to reproduce the problem

The snippet above triggers the described offense.

## RuboCop version

```
$ rubocop -V
0.52.0
```

### PR DESCRIPTION
**Pull request by pocke**
See #5245 

`regexp` node has `str` node. So the cop should ignore `regexp` node also.

```ruby
$ ruby-parse -e /%u/
(regexp
  (str "%u")
  (regopt))
```

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `rake default` or `rake parallel`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: spec/rubocop/cop/style/format_string_token_spec.rb [hunk 1]
```diff
@@ -85,6 +85,10 @@
     expect_no_offenses('`echo "%s %<annotated>s %{template}"`')
   end
 
+  it 'ignores regexp' do
+    expect_no_offenses('/foo bar %u/')
```
Comment (Drenmi) [inline spec/rubocop/cop/style/format_string_token_spec.rb]: Let's add a test for `%r` literal as well? 🙂

Comment (pocke) [reply spec/rubocop/cop/style/format_string_token_spec.rb]: added!
