### PR TITLE
 [Fix #5680] Support Layout/ElseAlignment in do/end blocks

### LINKED ISSUE #5680: Layout/ElseAlignment failed with "undefined method `line' for nil:NilClass"
## Expected behavior

rubocp should success without complaint. 

## Actual behavior

rubocp failed and "undefined method `line' for nil:NilClass" occurs.

## Steps to reproduce the problem

```
[jiku@centos7 rubocop_else_alignment_error]$ cat sample.rb 
# frozen_string_literal: true

SAMPLE_NUMBERS = [1, 2, 3].freeze

def execute
  SAMPLE_NUMBERS.each do |num|
    do_something(num)
  rescue StandardError
    logger.error('ERROR')
  else
    logger.info('OK')
  end
end
[jiku@centos7 rubocop_else_alignment_error]$ ruby -c sample.rb 
Syntax OK
```

```
[jiku@centos7 rubocop_else_alignment_error]$ bundle exec rubocop -d sample.rb                                                                                                                                      
For /home/jiku/rubocop_else_alignment_error: configuration from /home/jiku/rubocop_else_alignment_error/vendor/bundle/ruby/2.5.0/gems/rubocop-0.53.0/config/default.yml
Inheriting configuration from /home/jiku/rubocop_else_alignment_error/vendor/bundle/ruby/2.5.0/gems/rubocop-0.53.0/config/enabled.yml
Inheriting configuration from /home/jiku/rubocop_else_alignment_error/vendor/bundle/ruby/2.5.0/gems/rubocop-0.53.0/config/disabled.yml
Inspecting 1 file
Scanning /home/jiku/rubocop_else_alignment_error/sample.rb
An error occurred while Layout/ElseAlignment cop was inspecting /home/jiku/rubocop_else_alignment_error/sample.rb:7:4.
undefined method `line' for nil:NilClass
/home/jiku/rubocop_else_alignment_error/vendor/bundle/ruby/2.5.0/gems/rubocop-0.53.0/lib/rubocop/cop/mixin/end_keyword_alignment.rb:75:in `effective_column'
/home/jiku/rubocop_else_alignment_error/vendor/bundle/ruby/2.5.0/gems/rubocop-0.53.0/lib/rubocop/cop/layout/else_alignment.rb:117:in `check_alignment'
/home/jiku/rubocop_else_alignment_error/vendor/bundle/ruby/2.5.0/gems/rubocop-0.53.0/lib/rubocop/cop/layout/else_alignment.rb:60:in `on_rescue'
/home/jiku/rubocop_else_alignment_error/vendor/bundle/ruby/2.5.0/gems/rubocop-0.53.0/lib/rubocop/cop/commissioner.rb:44:in `block (2 levels) in on_rescue'
/home/jiku/rubocop_else_alignment_error/vendor/bundle/ruby/2.5.0/gems/rubocop-0.53.0/lib/rubocop/cop/commissioner.rb:109:in `with_cop_error_handling'
/home/jiku/rubocop_else_alignment_error/vendor/bundle/ruby/2.5.0/gems/rubocop-0.53.0/lib/rubocop/cop/commissioner.rb:43:in `block in on_rescue'
/home/jiku/rubocop_else_alignment_error/vendor/bundle/ruby/2.5.0/gems/rubocop-0.53.0/lib/rubocop/cop/commissioner.rb:42:in `each'
/home/jiku/rubocop_else_alignment_error/vendor/bundle/ruby/2.5.0/gems/rubocop-0.53.0/lib/rubocop/cop/commissioner.rb:42:in `on_rescue'
/home/jiku/rubocop_else_alignment_error/vendor/bundle/ruby/2.5.0/gems/rubocop-0.53.0/lib/rubocop/ast/traversal.rb:154:in `on_block'
/home/jiku/rubocop_else_alignment_error/vendor/bundle/ruby/2.5.0/gems/rubocop-0.53.0/lib/rubocop/cop/commissioner.rb:48:in `on_block'
/home/jiku/rubocop_else_alignment_error/vendor/bundle/ruby/2.5.0/gems/rubocop-0.53.0/lib/rubocop/ast/traversal.rb:95:in `on_def'
/home/jiku/rubocop_else_alignment_error/vendor/bundle/ruby/2.5.0/gems/rubocop-0.53.0/lib/rubocop/cop/commissioner.rb:48:in `on_def'
/home/jiku/rubocop_else_alignment_error/vendor/bundle/ruby/2.5.0/gems/rubocop-0.53.0/lib/rubocop/ast/traversal.rb:49:in `block in on_begin'
/home/jiku/rubocop_else_alignment_error/vendor/bundle/ruby/2.5.0/gems/rubocop-0.53.0/lib/rubocop/ast/traversal.rb:49:in `each'
/home/jiku/rubocop_else_alignment_error/vendor/bundle/ruby/2.5.0/gems/rubocop-0.53.0/lib/rubocop/ast/traversal.rb:49:in `on_begin'
/home/jiku/rubocop_else_alignment_error/vendor/bundle/ruby/2.5.0/gems/rubocop-0.53.0/lib/rubocop/cop/commissioner.rb:48:in `on_begin'
/home/jiku/rubocop_else_alignment_error/vendor/bundle/ruby/2.5.0/gems/rubocop-0.53.0/lib/rubocop/ast/traversal.rb:12:in `walk'
/home/jiku/rubocop_else_alignment_error/vendor/bundle/ruby/2.5.0/gems/rubocop-0.53.0/lib/rubocop/cop/commissioner.rb:60:in `investigate'
/home/jiku/rubocop_else_alignment_error/vendor/bundle/ruby/2.5.0/gems/rubocop-0.53.0/lib/rubocop/cop/team.rb:114:in `investigate'
/home/jiku/rubocop_else_alignment_error/vendor/bundle/ruby/2.5.0/gems/rubocop-0.53.0/lib/rubocop/cop/team.rb:102:in `offenses'
/home/jiku/rubocop_else_alignment_error/vendor/bundle/ruby/2.5.0/gems/rubocop-0.53.0/lib/rubocop/cop/team.rb:44:in `inspect_file'
/home/jiku/rubocop_else_alignment_error/vendor/bundle/ruby/2.5.0/gems/rubocop-0.53.0/lib/rubocop/runner.rb:259:in `inspect_file'
/home/jiku/rubocop_else_alignment_error/vendor/bundle/ruby/2.5.0/gems/rubocop-0.53.0/lib/rubocop/runner.rb:206:in `block in do_inspection_loop'
/home/jiku/rubocop_else_alignment_error/vendor/bundle/ruby/2.5.0/gems/rubocop-0.53.0/lib/rubocop/runner.rb:238:in `block in iterate_until_no_changes'
/home/jiku/rubocop_else_alignment_error/vendor/bundle/ruby/2.5.0/gems/rubocop-0.53.0/lib/rubocop/runner.rb:231:in `loop'
/home/jiku/rubocop_else_alignment_error/vendor/bundle/ruby/2.5.0/gems/rubocop-0.53.0/lib/rubocop/runner.rb:231:in `iterate_until_no_changes'
/home/jiku/rubocop_else_alignment_error/vendor/bundle/ruby/2.5.0/gems/rubocop-0.53.0/lib/rubocop/runner.rb:202:in `do_inspection_loop'
/home/jiku/rubocop_else_alignment_error/vendor/bundle/ruby/2.5.0/gems/rubocop-0.53.0/lib/rubocop/runner.rb:111:in `block in file_offenses'
/home/jiku/rubocop_else_alignment_error/vendor/bundle/ruby/2.5.0/gems/rubocop-0.53.0/lib/rubocop/runner.rb:121:in `file_offense_cache'
/home/jiku/rubocop_else_alignment_error/vendor/bundle/ruby/2.5.0/gems/rubocop-0.53.0/lib/rubocop/runner.rb:109:in `file_offenses'
/home/jiku/rubocop_else_alignment_error/vendor/bundle/ruby/2.5.0/gems/rubocop-0.53.0/lib/rubocop/runner.rb:100:in `process_file'
/home/jiku/rubocop_else_alignment_error/vendor/bundle/ruby/2.5.0/gems/rubocop-0.53.0/lib/rubocop/runner.rb:78:in `block in each_inspected_file'
/home/jiku/rubocop_else_alignment_error/vendor/bundle/ruby/2.5.0/gems/rubocop-0.53.0/lib/rubocop/runner.rb:75:in `each'
/home/jiku/rubocop_else_alignment_error/vendor/bundle/ruby/2.5.0/gems/rubocop-0.53.0/lib/rubocop/runner.rb:75:in `reduce'
/home/jiku/rubocop_else_alignment_error/vendor/bundle/ruby/2.5.0/gems/rubocop-0.53.0/lib/rubocop/runner.rb:75:in `each_inspected_file'
/home/jiku/rubocop_else_alignment_error/vendor/bundle/ruby/2.5.0/gems/rubocop-0.53.0/lib/rubocop/runner.rb:67:in `inspect_files'
/home/jiku/rubocop_else_alignment_error/vendor/bundle/ruby/2.5.0/gems/rubocop-0.53.0/lib/rubocop/runner.rb:39:in `run'
/home/jiku/rubocop_else_alignment_error/vendor/bundle/ruby/2.5.0/gems/rubocop-0.53.0/lib/rubocop/cli.rb:156:in `execute_runner'
/home/jiku/rubocop_else_alignment_error/vendor/bundle/ruby/2.5.0/gems/rubocop-0.53.0/lib/rubocop/cli.rb:84:in `execute_runners'
/home/jiku/rubocop_else_alignment_error/vendor/bundle/ruby/2.5.0/gems/rubocop-0.53.0/lib/rubocop/cli.rb:41:in `run'
/home/jiku/rubocop_else_alignment_error/vendor/bundle/ruby/2.5.0/gems/rubocop-0.53.0/bin/rubocop:13:in `block in <top (required)>'
/home/jiku/.rbenv/versions/2.5.0/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'
/home/jiku/rubocop_else_alignment_error/vendor/bundle/ruby/2.5.0/gems/rubocop-0.53.0/bin/rubocop:12:in `<top (required)>'
/home/jiku/rubocop_else_alignment_error/vendor/bundle/ruby/2.5.0/bin/rubocop:23:in `load'
/home/jiku/rubocop_else_alignment_error/vendor/bundle/ruby/2.5.0/bin/rubocop:23:in `<top (required)>'
/home/jiku/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `load'
/home/jiku/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `kernel_load'
/home/jiku/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:28:in `run'
/home/jiku/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/cli.rb:424:in `exec'
/home/jiku/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/jiku/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/home/jiku/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/home/jiku/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/cli.rb:27:in `dispatch'
/home/jiku/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/home/jiku/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/cli.rb:18:in `start'
/home/jiku/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/exe/bundle:30:in `block in <top (required)>'
/home/jiku/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/friendly_errors.rb:122:in `with_friendly_errors'
/home/jiku/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/exe/bundle:22:in `<top (required)>'
/home/jiku/.rbenv/versions/2.5.0/bin/bundle:23:in `load'
/home/jiku/.rbenv/versions/2.5.0/bin/bundle:23:in `<main>'
.

1 file inspected, no offenses detected

1 error occurred:
An error occurred while Layout/ElseAlignment cop was inspecting /home/jiku/rubocop_else_alignment_error/sample.rb:7:4.
Errors are usually caused by RuboCop bugs.
Please, report your problems to RuboCop's issue tracker.
Mention the following information in the issue report:
0.53.0 (using Parser 2.5.0.4, running on ruby 2.5.0 x86_64-linux)
Finished in 0.4670725599862635 seconds
```

## RuboCop version

```
[jiku@centos7 rubocop_else_alignment_error]$ bundle exec rubocop -V
0.53.0 (using Parser 2.5.0.4, running on ruby 2.5.0 x86_64-linux)
```

```
[jiku@centos7 rubocop_else_alignment_error]$ uname -a
Linux centos7 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
[jiku@centos7 rubocop_else_alignment_error]$ ruby -v
ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-linux]
```

memo https://bugs.ruby-lang.org/issues/12906

### PR DESCRIPTION
**Pull request by YukiJikumaru**
Ruby 2.5 introduces a new feature ["do/end blocks work with ensure/rescue/else"](https://bugs.ruby-lang.org/issues/12906).

However Layout/ElseAlignment cop did not support this syntax, and raise an error ["undefined method `line' for nil:NilClass"](https://github.com/bbatsov/rubocop/issues/5680).

This PR fixes the error and enable Layout/ElseAlignment cop to lint inside do/end blocks.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `rake default` or `rake parallel`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: spec/rubocop/cop/layout/else_alignment_spec.rb [hunk 1]
```diff
@@ -535,4 +535,36 @@ def my_func
       RUBY
     end
   end
+
+  context 'ensure/rescue/else in Block Argument' do
+    let(:ruby_version) { 2.5 }
```
Comment (pocke) [inline spec/rubocop/cop/layout/else_alignment_spec.rb]: You can use `ruby25` shared example. https://github.com/bbatsov/rubocop/blob/ef9dafce377aea7681b1db8591e130d076d73017/spec/rubocop/cop/layout/rescue_ensure_alignment_spec.rb#L101

File: spec/rubocop/cop/layout/else_alignment_spec.rb [hunk 2]
```diff
@@ -535,4 +535,36 @@ def my_func
...
+        rescue SomeException
+          puts 'error handling'
+        rescue
+          puts 'error handling'
+        else
+          puts 'normal handling'
+        end
+      RUBY
+    end
+    it 'registers an offense for misaligned else' do
```
Comment (pocke) [inline spec/rubocop/cop/layout/else_alignment_spec.rb]: I prefer inserting a new line between the examples.
For example:

```ruby
# bad
it 'something' do
end
it 'something2' do
end

# good
it 'something' do
end

it 'something2' do
end
```

Probably rubocop-rspec should detect the code.

**Comment by pocke** [comment]
Looks good to me. Can you fix the commented code and squash the commits?

**Comment by YukiJikumaru** [comment]
@pocke Thank you for you reviewing. I fixed and squash them.

**Comment by koic** [comment]
Good catch and this looks good, please squash into 1 commit including updated CHANGELOG.md 😃 

Refer https://github.com/bbatsov/rubocop/pull/5665/commits/36b757d8fa6163a3a2ac8d12de3a1e6881f9ad38.

**Comment by YukiJikumaru** [comment]
@koic DONE!
