### PR TITLE
[FIX #4723] RaiseArgs shouldn't autocorrect 3-args form

### LINKED ISSUE #4723: RaiseArgs shouldn't autocorrect 3-arg form
--------

## Expected behavior

```
$ cat /tmp/a.rb
begin
  1 / 0
rescue => e
  raise StandardError, 'hi', e.backtrace
end
$ ruby /tmp/a.rb
/tmp/a.rb:2:in `/': hi (StandardError)
	from /tmp/a.rb:2:in `<main>'
$ cat .rubocop.yml
RaiseArgs:
  EnforcedStyle: compact
```

No autocorrect. Or if you want to get fancy you can autocorrect to

```
$ cat /tmp/a.rb
begin
  1 / 0
rescue => e
  new_e = StandardError.new('hi')
  new_e.set_backtrace(e.backtrace)
  raise new_e
end
```

## Actual behavior

```
$ rubocop -a a.rb
Inspecting 1 file
C

Offenses:

a.rb:4:3: C: [Corrected] Provide an exception object as an argument to raise.
  raise StandardError, 'hi', e.backtrace
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

1 file inspected, 1 offense detected, 1 offense corrected
$ cat /tmp/a.rb
begin
  1 / 0
rescue => e
  raise StandardError.new('hi', e.backtrace)
end
$ ruby /tmp/a.rb
/tmp/a.rb:4:in `initialize': wrong number of arguments (given 2, expected 0..1) (ArgumentError)
	from /tmp/a.rb:4:in `new'
	from /tmp/a.rb:4:in `rescue in <main>'
	from /tmp/a.rb:1:in `<main>'
```

## Steps to reproduce the problem

See above

## RuboCop version

```
$ rubocop -V
0.49.1 (using Parser 2.4.0.0, running on ruby 2.4.1 x86_64-darwin16)
```

### PR DESCRIPTION
**Pull request by smakagon**
Fixes the auto-correction issue for `raise` with 3 arguments:

Without this fix, the following code: 
```ruby
begin
  1 / 0
rescue => e
  raise StandardError, 'hi', e.backtrace
end
```
would be auto-corrected to the broken one:

```ruby
begin
  1 / 0
rescue => e
  raise StandardError.new('hi', e.backtrace) # wrong number of arguments (given 2, expected 0..1) (ArgumentError)
end
```

With this fix, any `raise` with more than 2 arguments will not be autocorrected.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Used the same coding conventions as the rest of the project.
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] All tests(`rake spec`) are passing.
* [x] The new code doesn't generate RuboCop offenses that are checked by `rake internal_investigation`.
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [ ] Updated cop documentation with `rake generate_cops_documentation` (required only when you've added a new cop or changed the configuration/documentation of an existing cop).

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/style/raise_args.rb [hunk 1]
```diff
@@ -60,33 +60,32 @@ def on_send(node)
...
 
         def autocorrect(node)
-          new_exception = if style == :compact
-                            correction_exploded_to_compact(node.arguments)
-                          else
-                            correction_compact_to_exploded(node.first_argument)
-                          end
-          replacement = "#{node.method_name} #{new_exception}"
+          replacement = if style == :compact
+                          correction_exploded_to_compact(node)
```
Comment (Drenmi) [inline lib/rubocop/cop/style/raise_args.rb]: I like the unification of the arguments to these sister methods. 👍

**Comment by Drenmi** [comment]
I think the examples in the class documentation need to be updated. Other than that, all the changes look good! 🚀

**Comment by smakagon** [comment]
@Drenmi Thanks for the review. How would you like to change documentation? Do you want me to add a note for auto-correction behavior?

**Comment by Drenmi** [comment]
@smakagon: Hm. I thought this invalidated some example in the documentation, but now thinking I might've been wrong. 🙂
