### PR TITLE
[Fix #4268] Handle comments when correcting Style/EmptyLinesAroundAccessModifier

### LINKED ISSUE #4268: Style/EmptyLinesAroundAccessModifier autocorrection splits comment after access modifier
When an access modifier has a comment on the same line and is not followed by an empty line, the autocorrection for `Style/EmptyLinesAroundAccessModifier` inserts the newline *before* the comment. I would expect it to insert the newline after the comment.

(I discovered this while working on #4127 because this bug broke the `# rubocop:disable Lint/UselessAccessModifier` my change added to a line. I'm working on a fix.)

## Example
```rb
class Example
  something

  private # let's make the rest private
  def example; end
end
```

### Expected correction
```rb
class Example
  something

  private # let's make the rest private

  def example; end
end
```

### Actual correction
(one iteration)

```rb
class Example
  something

  private
 # let's make the rest private
  def example; end
end
```

## Steps to reproduce

From an updated `rubocop` clone:
1. `git checkout fd25562`
2. `curl https://gist.githubusercontent.com/vergenzt/ac933335208576084a9e464e42f12ad6/raw/f15b4b6cabbf603032e9cc111be9ba2e7f4a0c1f/spec.diff | git apply`
3. `rspec spec/rubocop/cop/style/empty_lines_around_access_modifier_spec.rb`

([Gist link](https://gist.github.com/vergenzt/ac933335208576084a9e464e42f12ad6))

## RuboCop version

```
$ rubocop -V
0.48.1 (using Parser 2.4.0.0, running on ruby 2.2.1 x86_64-darwin14)
```

### PR DESCRIPTION
**Pull request by vergenzt**
Previously the autocorrect implementation inserted a newline at the end of the access modifier _node_ instead of at the end of the line. This fixes that.

Fixes #4268.

-----------------

Before submitting the PR make sure the following are checked:

* [X] Wrote [good commit messages][1].
* [X] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [X] Used the same coding conventions as the rest of the project.
* [X] Feature branch is up-to-date with `master` (if not - rebase it).
* [X] Squashed related commits together.
* [X] Added tests.
* [X] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [X] All tests are passing.
* [X] The new code doesn't generate RuboCop offenses.
* [X] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [X] Updated cop documentation with `rake generate_cops_documentation` (required only when you've added a new cop or changed the configuration/documentation of an existing cop).

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/util.rb [hunk 1]
```diff
@@ -152,6 +152,22 @@ def range_with_surrounding_space(range, side = :both, with_newline = true)
         Parser::Source::Range.new(buffer, begin_pos, end_pos)
       end
 
+      def range_by_whole_lines(range, include_final_newline = false)
```
Comment (bbatsov) [inline lib/rubocop/cop/util.rb]: I'd make the second arg a keyword argument. Seems that now we can finally add a cop suggesting using keyword args over optional args, as those are much nicer to work with.

I also dislike the name of the method a bit, as I find it somewhat confusing. Why `range_by_whole_lines`?

File: lib/rubocop/cop/util.rb [hunk 2]
```diff
@@ -152,6 +152,22 @@ def range_with_surrounding_space(range, side = :both, with_newline = true)
...
+        begin_offset = range.column
+        begin_of_first_line = begin_pos - begin_offset
+
+        last_line = buffer.source_line(range.last_line)
+        end_pos = range.end_pos
+        end_offset = last_line.length - range.last_column
+        end_offset += 1 if include_final_newline
+        end_of_last_line = end_pos + end_offset
+
+        Parser::Source::Range.new(buffer, begin_of_first_line, end_of_last_line)
```
Comment (vergenzt) [inline lib/rubocop/cop/util.rb]: Also I'll replace this with a `range_between` call

File: lib/rubocop/cop/util.rb (hunk 1 above)
Comment (vergenzt) [inline lib/rubocop/cop/util.rb]: > I'd make the second arg a keyword argument.

Will do. 👍 

> I also dislike the name of the method a bit, as I find it somewhat confusing. Why `range_by_whole_lines`?

Yeah I had trouble coming up with a name I liked too, and I'm also not too hot on this one. I called it `range_by_lines` at first but thought that seemed too vague. I also considered `range_with_whole_lines` but thought it sounded weird.

Do either of those sound better to you?

Comment (vergenzt) [inline lib/rubocop/cop/util.rb]: The idea was kindof like with "visual" mode in Vim, this method expands the input range to include all of any lines it covers (optionally with the final newline per the arg).
