### PR TITLE
[#3263] Fix auto-correct of nested statements in ConditionalAssignment

### LINKED ISSUE #3263: Autocorrection broke code
rubocop 0.41.1 (ruby 1.9.3)

turned this code
```ruby
def unit_kmg(s)
    s = s.to_f
    unless(s.nil? || s.blank? || s == 0)
      if(s / 1024 / 1024 >=  1)
        speed = [s/1024/1024, "G"]
      elsif(s / 1024 >= 1)
        speed = [s/1024, "M"]
      else
        speed = [s, "k"]
      end
    else
      speed = [s, ""]
    end
    speed[0] = floating(speed[0]).to_s
    return speed
  end
```

to:
```ruby
def unit_kmg(s)
    s = s.to_f
    if(s / 1024 / 1024 >=  1)
        speed = [s/1024/1024, "G"]
      elsif(s / 1024 >= 1)
        speed = [s/1024, "M"]
      else
        speed = [s, "k"]
      endunless (s.nil? || s.blank? || s == 0)
      elsif(s / 1024 >= 1)
        speed = [s/1024, "M"]
      else
        speed = [s, "k"]
    else
      [s, ""]
                                                                                                                                                                       end
    speed[0] = floating(speed[0]).to_s
    speed
  end
```

And it doesn't work due to syntax error:
```
expected keyword_elsif, expecting keyword_end (SyntaxError)
      elsif (s / 1024 >= 1)
```

Not my code :-)

### PR DESCRIPTION
**Pull request by rrosenblum**
Fix #3263. The problem stemmed from if statements and unless statements parsing the if branch and the else branch in opposite orders.

Example from the issue
```ruby
def unit_kmg(s)
  s = s.to_f
  unless(s.nil? || s.blank? || s == 0)
    if(s / 1024 / 1024 >=  1)
      speed = [s/1024/1024, "G"]
    elsif(s / 1024 >= 1)
      speed = [s/1024, "M"]
    else
      speed = [s, "k"]
    end
  else
    speed = [s, ""]
  end
  speed[0] = floating(speed[0]).to_s
  return speed
end
```
Will no auto-correct to
```ruby
def unit_kmg(s)
  s = s.to_f
  if s.nil? || s.blank? || s == 0
    speed = [s, '']
  else
    speed = if s / 1024 / 1024 >= 1
              [s / 1024 / 1024, 'G']
            elsif s / 1024 >= 1
              [s / 1024, 'M']
            else
              [s, 'k']
            end
  end
  speed[0] = floating(speed[0]).to_s
  speed
end
```

### CODE REVIEW

File: lib/rubocop/cop/style/conditional_assignment.rb [hunk 1]
```diff
@@ -288,10 +293,6 @@ def assignment_node(node)
           assignment
         end
 
-        def condition?(node)
```
Comment (bbatsov) [inline lib/rubocop/cop/style/conditional_assignment.rb]: Changing this seems unrelated to me.

Comment (rrosenblum) [inline lib/rubocop/cop/style/conditional_assignment.rb]: It is unrelated to the fix. This was done to decrease the length of the class. Would you prefer that this change be removed all together and the increase the max class length to 172, or would you prefer that this change be placed into a different commit?

Comment (bbatsov) [inline lib/rubocop/cop/style/conditional_assignment.rb]: Increase the max class length.

**Comment by rrosenblum** [comment]
The commit has been updated to not inline the method in question.
