### PR TITLE
[Fix #5686] Fix first line spacing for symbol and word arrays with partial newlines

### LINKED ISSUE #5686: Style/SymbolArray autocorrect breaks code in partial-newline case
The `Style/SymbolArray` cop has autocorrect functionality to change, e.g., `[:one, :two]` to `%i(one two)`. This mostly works correctly, though there is one case where the autocorrect would change the functionality of the code. There is [already a test case](https://github.com/bbatsov/rubocop/blob/84156/spec/rubocop/cop/style/symbol_array_spec.rb#L39-L42) that tests for a similar case, though unfortunately does not catch this.

The existing test case (passes):
```rb
new_source = autocorrect_source("[:one,\n:two, :three,\n:four]")
expect(new_source).to eq("%i(one\ntwo three\nfour)")
```

A slightly modified version of the test case (fails on `master` at time of writing):
```rb
new_source = autocorrect_source("[:one, :two,\n:three,\n:four]")
expect(new_source).to eq("%i(one two\nthree\nfour)")
```

Test output:
```diff
expected: "%i(one two\nthree\nfour)"
     got: "%i(onetwo\nthree\nfour)"

(compared using ==)

Diff:
@@ -1,4 +1,4 @@
-%i(one two
+%i(onetwo
three
four)
```

I caught this because we had code similar to the following in our codebase:
```rb
SOME_CONSTANT = [:one, :two,
  :three,
  :four]
```

Which was incorrectly autocorrected (see expected/actual below).

--------

## Expected behavior

Rubocop should autocorrect into an array of the same symbols (preferably with the same or further autocorrected layout/indentation):
```rb
SOME_CONSTANT = %i(one two
  three
  four)
```

## Actual behavior

Rubocop merged the first two symbols:
```rb
SOME_CONSTANT = %i(onetwo
  three
  four)
```

## Steps to reproduce the problem

Add the above test to `spec/rubocop/cop/style/symbol_array_spec.rb` and observe it fail, or otherwise try to autocorrect the case provided above.

## RuboCop version

```
$ rubocop -V
0.53.0 (using Parser 2.5.0.0, running on ruby 2.4.1 x86_64-darwin17)
```

Tested via spec against `master` at commit `841569b30` (latest at time of writing).

### PR DESCRIPTION
**Pull request by istateside**
A regression was introduced in https://github.com/bbatsov/rubocop/commit/2ee27d2a55d44c973dc8c6eb57a8bec76b7b769e which caused the Style/SymbolArray and Style/WordArray to improperly autocorrect arrays that use partial newlines. In  RuboCop::Cop::PercentLiteral#line_breaks, when deciding whether to insert a space between entries on a line, we check if the current node's line number matches the previous node's line number. If we're handling the first line of an Array, we do not insert the space. However, this doesn't account for cases where there are multiple elements on the first line, like the following:
```ruby
number_array = ['one', 'two', 'three',
                'four', 'five',
                'six']
```

In this case, we would not add a space between "one" and "two", because we're still handling the first line. Autocorrecting would result in:
```ruby
number_array = %w(onetwothree
                  four five
                  six)
```

We can fix it by tracking the index of words in each line, and only skip adding the space for the very first word.

This seemed to be most minimal change that would make this work, but I'd be happy to take a different approach if we want to avoid passing another argument. Had to rename two other args to fit the fifth in with the line length.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `rake default` or `rake parallel`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/mixin/percent_literal.rb [hunk 1]
```diff
@@ -85,14 +86,14 @@ def autocorrect_words(node, escape, delimiters)
         end.join(' ')
       end
 
-      def line_breaks(node, source, previous_line_number, base_line_number)
+      def line_breaks(node, source, previous_line_num, base_line_num, node_idx)
```
Comment (rrosenblum) [inline lib/rubocop/cop/mixin/percent_literal.rb]: Why were the variables renamed from `number` to `num`?

Comment (istateside) [reply lib/rubocop/cop/mixin/percent_literal.rb]: Adding the new `node_idx` argument to the list pushed the line length too long. Would've preferred to keep `_number` as part of the names, but I figured this was a decent compromise to get the line length back under the limit.

**Comment by bbatsov** [comment]
The changes look good, but your branch has to be rebased on top of the current `master` branch due to merge conflicts.
