### PR TITLE
[Fix #4477] Add inherit_mode directive to support merging of arrays.

### LINKED ISSUE #4477: Exclude lists aren't deep merged
When merging 2 configurations, `Exclude` lists in the first one get overwritten by `Exclude` lists for the same cop in the second one.

--------

## Expected behavior

In the example below, I expect both a.rb and b.rb to be excluded, and only the Gemfile to be inspected.

## Actual behavior
The file listed in the inherited rubocop configuration (a.rb) is inspected.

```
$ rubocop 
Inspecting 2 files
.C

Offenses:

a.rb:1:1: C: Missing top-level class documentation comment.
class A
^^^^^

2 files inspected, 1 offense detected
```

## Steps to reproduce the problem

```
$ cat a.rb 
class A
  def my_method; end
end

$ cat b.rb 
class B
  def my_method; end
end

$ cat Gemfile
source 'https://rubygems.org'
gem 'rubocop', git: 'https://github.com/bbatsov/rubocop.git'

$ cat .rubocop.yml 
inherit_from: .rubocop_1.yml

AllCops:
  Exclude:
    - b.rb

$ cat .rubocop_1.yml 
AllCops:
  Exclude:
    - a.rb

```

## RuboCop version

```
$ rubocop -V
0.49.1 (using Parser 2.4.0.0, running on ruby 2.3.4 x86_64-linux)
```

### PR DESCRIPTION
**Pull request by leklund**
### add `inherit_mode` directive

This PR is based on a suggestion in #4477. It adds support for a new directive that conditionally merges array values on a per key basis. This is incredibly useful when using a shared config file that has several excludes and project inheriting the shared repo would like to add a single file to the exclude list without duplicating the entire list.

The implementation requires that you specify which keys you would like to merge so that not all arrays are merged blindly.

Given the following configs:
```yaml
# .rubocop.yml
inherit_from:
  - shared.yml

inherit_mode:
  merge:
    - Exclude

Style/For:
  Exclude:
    - bar.rb
```

```yaml
# .shared.yml
Style/For:
  Exclude:
    - foo.rb
  Include:
    - zoot.rb
```

The `inherit_mode` directive will be used to determine that the values of the `Exclude` keys will be merged instead of overwritten. The result is that the exclude list for `Style/For` is `['foo.rb', 'bar.rb']`.

The directive can be used on a per cop basis to override the global setting:

```yaml
# .rubocop.yml
inherit_from:
  - shared.yml

inherit_mode:
  override:
    - Exclude
  merge:
    - Include

Style/For:
  Exclude:
    - bar.rb
  Include:
    - boot.rb
```

The exclude list would be just `bar.rb` and the Include list would be `['zoot.rb', 'boot.rb']`.

Related issues: #5480 

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `rake default` or `rake parallel`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/config_loader_resolver.rb [hunk 1]
```diff
@@ -101,6 +103,32 @@ def duplicate_setting?(base_hash, derived_hash, key, inherited_file)
...
+                inherit_mode && inherit_mode.include?(key)
+
+      warn("#{PathUtil.smart_path(opts[:file])}: " \
+           "#{opts[:cop_name]}:#{key} overrides " \
+           "the same parameter in #{opts[:inherited_file]}")
+    end
+
+    def determine_inherit_mode(hash, key)
+      cop_cfg = hash[key]
+      local_inherit = cop_cfg.delete('inherit_mode') if cop_cfg.is_a?(Hash)
```
Comment (jonas054) [inline lib/rubocop/config_loader_resolver.rb]: Why do we need `delete` here? All specs still pass if I change it to `cop_cfg['inherit_mode']`.

**Comment by leklund** [comment]
> What about inheritance from the default configuration? For example, there's an exclude of vendor/**/* in default.yml. Do we want to be able to merge between default and user configuration too? I'd like to see a spec example that shows how that works.

That's a good question and I definitely should add a spec example. Because the `merge_with_default` happens after the `load_file`, the behavior is the same as the default: it will override the `default.yml` settings with any from the provided configuration. This is because the `inherit_mode` directives are removed from the config during loading. I'll add a spec for that behavior so that it's clear what's happening. (spec added in ffa936a)

As to whether we want to be able to merge between default and user configuration? My instinct is no but that might just be my use case. If that was supported I'd suggest making it a separate directive: `merge_with_defaults`.

File: spec/rubocop/config_loader_spec.rb [hunk 2]
```diff
@@ -230,6 +230,94 @@
...
+            Exclude:
+              - 'spec/models/expense_spec.rb'
+              - 'spec/models/group_spec.rb'
+        YAML
+      end
+
+      it 'unions the two lists of Excludes from the parent and child configs ' \
+          'for cops that do not override the inherit_mode' do
+        excludes = configuration_from_file['Style/For']['Exclude']
+        expect(excludes.sort)
```
[the remark this answers is not in the document]
Comment (leklund) [reply spec/rubocop/config_loader_spec.rb]: The warnings here are expected and I'll update the specs to expect the warning. (updated here: c00e35d)

It will warn here because the `Style/Dir` config is setting the `inherit_mode` back to the default of override for `Exclude`.

File: spec/rubocop/config_loader_spec.rb [hunk 3]
```diff
@@ -230,6 +230,94 @@
...
+          .to eq([File.expand_path('spec/requests/group_invite_spec.rb'),
+                  File.expand_path('spec/models/expense_spec.rb'),
+                  File.expand_path('spec/models/group_spec.rb')].sort)
+      end
+
+      it 'overwrites the Exclude from the parent when the cop overrides' \
+          'the global inherit_mode' do
+        excludes = configuration_from_file['Style/Dir']['Exclude']
+        expect(excludes)
```
[the remark this answers is not in the document]
Comment (leklund) [reply spec/rubocop/config_loader_spec.rb]: see my comment above. They are expected for the `Style/Dir` cop but not for the `Style/For` cop.

File: spec/rubocop/config_loader_spec.rb [hunk 4]
```diff
@@ -312,18 +312,24 @@
...
-                  File.expand_path('spec/models/expense_spec.rb'),
-                  File.expand_path('spec/models/group_spec.rb')].sort)
+        expect do
+          excludes = configuration_from_file['Style/For']['Exclude']
+          expect(excludes.sort)
+            .to eq([File.expand_path('spec/requests/group_invite_spec.rb'),
+                    File.expand_path('spec/models/expense_spec.rb'),
+                    File.expand_path('spec/models/group_spec.rb')].sort)
+        end.to output('.rubocop.yml: Style/Dir:Exclude overrides ' \
+        "the same parameter in .rubocop_parent.yml\n").to_stderr
```
Comment (jonas054) [inline spec/rubocop/config_loader_spec.rb]: I think we only want the warning when it's override by default. When `override` is explicitly selected for a parameter, we don't want a warning about it.

File: lib/rubocop/config_loader_resolver.rb (hunk 1 above)
Comment (jonas054) [reply lib/rubocop/config_loader_resolver.rb]: That makes sense. It's not necessary to implement `merge_with_default` at this point IMO. We can do one use case at a a time.

Thanks for the added spec example.

File: spec/rubocop/config_loader_spec.rb (hunk 4 above)
Comment (leklund) [reply spec/rubocop/config_loader_spec.rb]: > I think we only want the warning when it's override by default. When override is explicitly selected for a parameter, we don't want a warning about it.

Aha. I understand now. That makes perfect sense. I've addressed in c85d5f4.

**Comment by leklund** [comment]
Thank you for the review @jonas054. If you don't have any more changes/comments I'll do a rebase and squash.

**Comment by jonas054** [comment]
👍 Looks good!

**Comment by bbatsov** [comment]
Thanks!
