### PR TITLE
[Fix #2154] Fix auto-correct of StringReplacement with a backslash

### LINKED ISSUE #2154: gsub -> tr cop messes up escaped string
First off, thanks for rubocop!

So if I have a file like this:

```ruby
"".gsub('/', '\\')
```

rubocop (0.33.0 as well as GitHub `master`) transforms it to this:

```ruby
"".tr('/', '\')
```

This isn't good because Ruby sees the second single quote as being escaped and there syntax errors.

Here's the rubocop output:

```
$ rubocop -aD test.rb
Inspecting 1 file
F

Offenses:

test.rb:1:4: C: [Corrected] Performance/StringReplacement: Use tr instead of gsub.
"".gsub('/', '\\')
   ^^^^^^^^^^^^^^^
test.rb:1:12: F: unterminated string meets end of file
"".tr('/', '\')
           ^

1 file inspected, 2 offenses detected, 1 offense corrected
```

`rubocop -V`:

```
$ rubocop -V
0.33.0 (using Parser 2.2.2.6, running on ruby 2.0.0 x86_64-darwin14.3.0)
```

You can also see my `.rubocop.yml` and `.rubocop_todo.yml` here:

https://gist.github.com/cheerfulstoic/062fa3b79e8397b82c19

### PR DESCRIPTION
**Pull request by rrosenblum**
This fixes #2154. It was easier to not touch the second parameter rather than trying to properly escape it. In my mind, this is a slightly more simplistic solution. The only down fall is that when replacing with `delete`, 2 calls to corrector are needed.

Some general clean up made it in as well, let me know if I should break this out into a different commit/PR.

### CODE REVIEW

File: lib/rubocop/cop/performance/string_replacement.rb [hunk 1]
```diff
@@ -20,10 +20,15 @@ module Performance
       #   'a b c'.delete(' ')
       class StringReplacement < Cop
         MSG = 'Use `%s` instead of `%s`.'
-        DETERMINISTIC_REGEX = /^[\w\s\-,."']+$/
-        REGEXP_CONSTRUCTOR_METHODS = [:new, :compile]
-        GSUB_METHODS = [:gsub, :gsub!]
-        DETERMINISTIC_TYPES = [:regexp, :str, :send]
+        DETERMINISTIC_REGEX = /^[\w\s\-,."']+$/.freeze
```
Comment (bbatsov) [inline lib/rubocop/cop/performance/string_replacement.rb]: We should add a cop suggesting to freeze literal constants (and a rule to the style guide). This has been on my mind for a while now.

File: lib/rubocop/cop/performance/string_replacement.rb [hunk 2]
```diff
@@ -20,10 +20,15 @@ module Performance
...
+        REGEXP_CONSTRUCTOR_METHODS = [:new, :compile].freeze
+        GSUB_METHODS = [:gsub, :gsub!].freeze
+        DETERMINISTIC_TYPES = [:regexp, :str, :send].freeze
+        DELETE = 'delete'.freeze
+        TR = 'tr'.freeze
+        BANG = '!'.freeze
+        SINGLE_QUOTE = "'".freeze
```
Comment (bbatsov) [inline lib/rubocop/cop/performance/string_replacement.rb]: Such common constants might eventually be extracted to some other class/module.

**Comment by bbatsov** [comment]
:+1: Looks good.

File: lib/rubocop/cop/performance/string_replacement.rb (hunk 2 above)
Comment (rrosenblum) [inline lib/rubocop/cop/performance/string_replacement.rb]: I had the same thought as I was working on some performance/memory tweaks to the app. It is a slow process to convert everything. It could be broken up into small chunks though.
