### PR TITLE
[Fix #4633] Make metrics cops aware of `define_method`

### LINKED ISSUE #4633: Metrics/AbcSize cop for `define_method`
## Expected behavior

`Metrics/AbcSize` cop works for `define_method` content.

## Actual behavior

`Metrics/AbcSize` cop doesn't work for `define_method` content.

## Steps to reproduce the problem

Write `define_method` with block where ABC-size is more than 15.

## RuboCop version

```
$ rubocop -V
0.49.1 (using Parser 2.4.0.0, running on ruby 2.4.1 x86_64-linux)
```

### PR DESCRIPTION
**Pull request by pocke**
Problem
=======

`AbcSize`, `CyclomaticComplexity` and `PerceivedComplexity` cops ignore `define_method`.
See #4633 

Solution
====

Update `MethodComplexity` mix-in.
This change makes these cops aware of `define_method`.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Used the same coding conventions as the rest of the project.
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] All tests(`rake spec`) are passing.
* [x] The new code doesn't generate RuboCop offenses that are checked by `rake internal_investigation`.
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Updated cop documentation with `rake generate_cops_documentation` (required only when you've added a new cop or changed the configuration/documentation of an existing cop).

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by bbatsov** [comment]
👍

File: lib/rubocop/cop/mixin/method_complexity.rb [hunk 1]
```diff
@@ -5,25 +5,46 @@ module Cop
...
+        define_method?(node) do |name|
+          check_complexity(node, name)
+        end
+      end
+
+      private
+
+      def_node_matcher :define_method?, <<-PATTERN
+        (block
+         (send nil? :define_method ({sym str} $_))
```
Comment (Drenmi) [inline lib/rubocop/cop/mixin/method_complexity.rb]: Should we also apply this to `Object#define_singleton_method`? 🙂
