### PR TITLE
[Fix #2407] Use Etc.getpwuid.name to retrieve user login

### LINKED ISSUE #2407: no implicit conversion of nil into String
Hi,
The latest rubocop version fails to run in our Jenkins environment. It seems to be related to the user name context for the cache folder => https://github.com/bbatsov/rubocop/commit/88dc50741b7529c848bdd495506a8debcf6fa45e

`Etc.getlogin` returns nil, probably because `getlogin()` nor `ENV['USER']` are set http://ruby-doc.org/stdlib-2.2.0/libdoc/etc/rdoc/Etc.html#method-c-getlogin.

It seems `Etc.getpwuid.name` works even when `Etc.getlogin` fails.

Error : 
```
no implicit conversion of nil into String
/var/lib/jenkins/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rubocop-0.35.0/lib/rubocop/result_cache.rb:82:in `join'
/var/lib/jenkins/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rubocop-0.35.0/lib/rubocop/result_cache.rb:82:in `cache_root'
/var/lib/jenkins/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rubocop-0.35.0/lib/rubocop/result_cache.rb:54:in `cleanup'
/var/lib/jenkins/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rubocop-0.35.0/lib/rubocop/runner.rb:66:in `ensure in inspect_files'
/var/lib/jenkins/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rubocop-0.35.0/lib/rubocop/runner.rb:68:in `inspect_files'
/var/lib/jenkins/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rubocop-0.35.0/lib/rubocop/runner.rb:34:in `run'
/var/lib/jenkins/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rubocop-0.35.0/lib/rubocop/cli.rb:26:in `run'
```

### PR DESCRIPTION
**Pull request by jujugrrr**
#2407.

Might be a better approach than #2406 as it keeps the "per login" cache feature.
I'll close when any of the 2 PR got merged.

### CODE REVIEW

**Comment by martinb3** [comment]
:+1: https://github.com/bbatsov/rubocop/pull/2374 broke rubocop for us, since it missed some nil handling.

**Comment by bbatsov** [comment]
So, this is not going to return `nil` ever, right?

**Comment by jujugrrr** [comment]
> So, this is not going to return nil ever, right?

It will definitely help to fallback to some default values. Same thing for `Dir.tmpdir`. The original PR passed without the safeguard, so I'm just changing the used method to what seems (I'm not an expert in getting user login :wink: ) less likely to error.

If we set some default values, then we need to chose what they are. If #2406 is a better approach it's cool for me too. It seems there was no test for https://github.com/bbatsov/rubocop/commit/88dc50741b7529c848bdd495506a8debcf6fa45e before (or even the cache_root). Not sure how to test it easily. I've giving it a try

**Comment by alexdowad** [comment]
Just looked at the MRI source.

`Etc.getlogin` is a thin wrapper around `getlogin` (function prototype in `unistd.h`), `Etc.getpwuid` is a thin wrapper around `getpwuid` (function prototype in `pwd.h`).

The manpage on `getlogin` is very vague about how it gets its information. `getpwuid` is clear enough -- it reads from `/etc/passwd`.

**Comment by alexdowad** [comment]
The point here is to de-duplicate, right? It doesn't really matter if the file path uses the username or something else. Why don't you use a numeric UID? That won't require reading `/etc/passwd` or anything.

**Comment by bbatsov** [comment]
> Why don't you use a numeric UID? That won't require reading /etc/passwd or anything.

Fine by me.

**Comment by alexdowad** [comment]
You can do that using `Process.uid`.

**Comment by bbatsov** [comment]
We can also check for the username and fallback the uid if it's `nil`, as usernames definitely create easier to comprehend folder names. Not a biggie, but still someone might take a look at the folders.

**Comment by jujugrrr** [comment]
> We can also check for the username and fallback the uid if it's nil, as usernames definitely create easier to comprehend folder names

It's what I've done based on #2406. I've tried to add tests too, but you probably want stuffs to be moved around or renamed.

```
  the cache path when we cannot find the user name
    is created within the rubocop_cache folder
  the cache path when we can find the user name
    is created within a user name folder
```

**Comment by jujugrrr** [comment]
hum it seems, it's failing on jruby...

**Comment by alexdowad** [comment]
You're falling back to a blank string, not to a numeric UID.

**Comment by jujugrrr** [comment]
> You're falling back to a blank string, not to a numeric UID.

You want me to fallback to `Process.uid` ?

**Comment by jujugrrr** [comment]
> You want me to fallback to Process.uid ?

Actually it would defeat the purpose of the cache I guess as it will change every time you run it.

**Comment by alexdowad** [comment]
I got the following through e-mail:

> Actually it would defeat the purpose of the cache I guess as it will change every time you run it.

Your user ID number will not change every time you run RuboCop, unless you log out and log in again using a different account.

The point of using a user ID number is that the cache will still be per-user, rather than global. Every process has a user ID, and there is little that can go wrong when retrieving it. (Unlike retrieving the user name, which as we have seen, can be problematic sometimes.)

**Comment by jujugrrr** [comment]
> Your user ID number will not change every time you run RuboCop, unless you log out and log in again using a different account.

yep, my bad that's why I removed the comment :wink:

**Comment by jujugrrr** [comment]
I've pushed the fix.

**Comment by masarakki** [comment]
:+1:

**Comment by bbatsov** [comment]
@jujugrrr ping :-)

**Comment by jujugrrr** [comment]
> @bbatsov had suggested that a username is desirable when it is available... could you use Etc.getpwuid.name, and fall back to Process.uid.to_s if that is nil or empty?

`Etc.getpwuid.name` failed the test for jruby implementation, I've never used Jruby, Maybe using `getlogin` then falling back to Process.uid is enough and compatible with all the platforms.

> @jujugrrr ping :-)

@bbatsov Please comment above and I'm happy to submit a latest PR :wink:

**Comment by jujugrrr** [comment]
> continuous-integration/travis-ci/pr 

```
Gem::InstallError: tins requires Ruby version >= 2.0.
An error occurred while installing tins (1.7.0), and Bundler cannot continue.
Make sure that `gem install tins -v '1.7.0'` succeeds before bundling.
```
It seems `tins` new release (10th November) is not compatible with ruby 1.9.
I've pinned it in the gemspec.

No idea on how to fix the code coverage getting lower as I've added more tests...

**Comment by alexdowad** [comment]
Forget about the code coverage getting lower. Coveralls is the bane of this project.

**Comment by jujugrrr** [comment]
issues on jruby. Not sure how the original change passed

@alexdowad I let you investigate

**Comment by bbatsov** [comment]
I don't even know what `tins` is.

**Comment by alexdowad** [comment]
> I don't even know what tins is.

It's a dependency of my *favorite* gem, coveralls!

**Comment by alexdowad** [comment]
I suggest that we just use a numeric UID. All of this messing around just for making the name of a temp directory look pretty is not worth it.

**Comment by bbatsov** [comment]
Fair enough. 

I'd also appreciate an alternative of coveralls, so if someone can I find one I'm instantly getting rid of this junk.

**Comment by jujugrrr** [comment]
> I suggest that we just use a numeric UID. All of this messing around just for making the name of a temp directory look pretty is not worth it.


> Fair enough

Fair enough. 

I would suggest to review 3 things based on this PR though : 

* how did this change get in in the first place: If you wanted test and handle different cases, then the first PR should not have been merged
* how to deal with breaking changes : It's a breaking change for a lot of people using Jenkins or other CI environment (gitlab). By delaying rollback/fix you are forcing people to pin down to an old rubocop version
* how to deal with contributors : I've redone the PR 5 times because you changed your mind on the approach to follow and because you are asking for a much higher quality than the origin PR (I had to implement test for a method which has never been tested). 

My feedback is, most people will be reluctant to contribute again to the project after this kind of experience. Which is the shame :wink:. I let the branch there, feel free to use it or not.

**Comment by bbatsov** [comment]
> how did this change get in in the first place: If you wanted test and handle different cases, then the first PR should not have been merged

Obviously we didn't envision this would ever return `nil`. That's just a fact of life - errors do happen. :-)

> how to deal with breaking changes : It's a breaking change for a lot of people using Jenkins or other CI environment (gitlab). By delaying rollback/fix you are forcing people to pin down to an old rubocop version

Same here - this wasn't supposed to be a breaking change. It's regrettable that this happened, but RuboCop is not my life and I can't start jumping through hoops, so that everyone would be happy. I've invested an enormous amount of personal time in the project, so I really don't feel that I owe anything more to the users. I want to solve issues as fast as possible, but this is not always possible. 

> how to deal with contributors : I've redone the PR 5 times because you changed your mind on the approach to follow and because you are asking for a much higher quality than the origin PR (I had to implement test for a method which has never been tested).

That's just how open-source works - ideas get discussed, implemented, rethought. I don't see the problem with that. I definitely don't want to waste anyone's time, but I'm not always certain what be best course of action is until some ideas have been brought to the table. Everyone who has contributed to RuboCop knows that I'm pretty rigid and hard to please at times and still issues do manage to squeeze in. Imagine what would have happened otherwise. Let's just reopen this and wrap it.

File: lib/rubocop/result_cache.rb [hunk 1]
```diff
@@ -79,7 +79,12 @@ def self.cleanup(config_store, verbose, cache_root = nil)
 
     def self.cache_root(config_store)
       root = config_store.for('.')['AllCops']['CacheRootDirectory']
-      root = File.join(Dir.tmpdir, Etc.getlogin) if root == '/tmp'
+      if Etc.getlogin.nil? || Etc.getlogin.empty?
```
Comment (bbatsov) [inline lib/rubocop/result_cache.rb]: Let's just simplify this to using the UID and be done with it. We've wasted enough time already.

File: rubocop.gemspec [hunk 2]
```diff
@@ -43,6 +43,7 @@ Gem::Specification.new do |s|
   s.add_runtime_dependency('powerpack', '~> 0.1')
   s.add_runtime_dependency('astrolabe', '~> 1.3')
   s.add_runtime_dependency('ruby-progressbar', '~> 1.7')
+  s.add_runtime_dependency('tins', '<= 1.6.0')
```
Comment (bbatsov) [inline rubocop.gemspec]: Please, add a note here why this is needed.

**Comment by bbatsov** [comment]
I'm very thankful to every contributor and I most certainly appreciate their time and desire to help the project!

**Comment by jujugrrr** [comment]
> I'm very thankful to every contributor and I most certainly appreciate their time and desire to help the project!

hehe I know, it's just to make sure they have a good experience(or not a bad one). which is different from appreciating what they are doing.

File: rubocop.gemspec (hunk 2 above)
Comment (jujugrrr) [inline rubocop.gemspec]: sure

File: lib/rubocop/result_cache.rb (hunk 1 above)
Comment (jujugrrr) [inline lib/rubocop/result_cache.rb]: sure

**Comment by alexdowad** [comment]
Thanks @jujugrrr!

**Comment by jujugrrr** [comment]
Here it is

**Comment by bbatsov** [comment]
:+1:

**Comment by bbatsov** [comment]
0.35.1 is out.

**Comment by alexdowad** [comment]
Thanks @bbatsov!

**Comment by deivid-rodriguez** [comment]
> I'd also appreciate an alternative of coveralls, so if someone can I find one I'm instantly getting rid of this junk.

I use `codeclimate-test-reporter` myself, which has a smaller set of dependencies:

```
coveralls (0.8.5)
  json (~> 1.8)
  rest-client (>= 1.6.8, < 2)
   simplecov (~> 0.10.0)
   term-ansicolor (~> 1.3)
   thor (~> 0.19.
```

vs

```
codeclimate-test-reporter (0.4.8)
   simplecov (>= 0.7.1, < 1.0.0)
```
