### PR TITLE
[Fix #5652] Make `Style/OptionHash` aware of implicit parameter passing to super

### LINKED ISSUE #5652: OptionHash should accept reasonable usages
This is a case that override Rails `image_tag` for lazyload js. There is no need to expand options to keyword arguments. And the original method signature is exectly [image_tag(source, options = {})](http://api.rubyonrails.org/classes/ActionView/Helpers/AssetTagHelper.html#method-i-image_tag).

```ruby
module ApplicationHelper
  def image_tag(source, options = {})
    options['data-src'] = image_path(source).presence
    source = 'data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=='
    super
  end
end
```

So should we check if `options` is used only accessing values or not?

## Expected behavior

Don't flag an offense.

## Actual behavior

Flag an offense.

## Steps to reproduce the problem

```yaml
Style/OptionHash:
  Enabled: true
```

## RuboCop version

```
$ rubocop -V
0.53.0 (using Parser 2.5.0.2, running on ruby 2.5.0 x86_64-darwin17)
```

### PR DESCRIPTION
**Pull request by Wei-LiangChew**
Previously the cop would add an offense if a method is defined with an
options hash parameter, intended to be passed into a call to super.

The fix was to check if super is called in the method body, and not
register an offense if found.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `rake default` or `rake parallel`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/style/option_hash.rb [hunk 1]
```diff
@@ -38,6 +40,16 @@ def suspicious_name?(arg_name)
           cop_config.key?('SuspiciousParamNames') &&
             cop_config['SuspiciousParamNames'].include?(arg_name.to_s)
         end
+
+        def super_used?(node)
+          body = node.parent.body
+
+          if body.begin_type?
+            body.children.any?(&:zsuper_type?)
```
Comment (pocke) [inline lib/rubocop/cop/style/option_hash.rb]: `Node#children` contains only direct children. In other words, it does not contains grandchildren.
So the cop still add an offense below.

```ruby
def foo(opts = {})
  if cond
    super
  end
end
```

So we can use `Node#each_node` instead. And probably we can remove `if body.begin_type?` with using the method.
https://github.com/bbatsov/rubocop/blob/9acbec2a22f2dfe1773e63ffda258af50e41db1e/lib/rubocop/ast/node.rb#L233-L263

**Comment by Wei-LiangChew** [comment]
Sorry for the delay 😓 
PR updated! @pocke

File: spec/rubocop/cop/style/option_hash_spec.rb [hunk 2]
```diff
@@ -69,4 +69,34 @@ def cook(instructions, ingredients = { hot: [], cold: [] })
...
+  context 'when passing options hash to super' do
+    it 'does not register an offense' do
+      expect_no_offenses(<<-RUBY.strip_indent)
+        def allowed(foo, options = {})
+          super
+        end
+      RUBY
+    end
+
+    it 'does not register an offense when lines exist before call to super' do
```
Comment (bbatsov) [inline spec/rubocop/cop/style/option_hash_spec.rb]: "Lines exist" sounds strange to me. Perhaps you meant to say "When there's other code before the call to super"?

File: CHANGELOG.md [hunk 3]
```diff
@@ -18,6 +18,10 @@
 * [#5752](https://github.com/bbatsov/rubocop/pull/5752): Add `String#delete_{prefix,suffix}` to Lint/Void cop. ([@bdewater][])
 * [#5734](https://github.com/bbatsov/rubocop/pull/5734): Add `by`, `on`, `in` and `at` to allowed names of `Naming/UncommunicativeMethodParamName` cop in default config. ([@AlexWayfer][])
 
+### Changes
```
[the remark this answers is not in the document]
Comment (Wei-LiangChew) [reply CHANGELOG.md]: Ah right, my mistake 😅

File: spec/rubocop/cop/style/option_hash_spec.rb (hunk 2 above)
Comment (Wei-LiangChew) [reply spec/rubocop/cop/style/option_hash_spec.rb]: 👍

Comment (Wei-LiangChew) [reply spec/rubocop/cop/style/option_hash_spec.rb]: So rubocop's `Metrics/LineLength` cop triggered here when I gave more descriptive wording :/
Decided on "when code exists before call to super"
