### PR TITLE
[Fix #5670] Suggest valid memoized instance variable for bang method

### LINKED ISSUE #5670: MemoizedInstanceVariableName cop suggests syntactically invalid instance variable for predicate methods.
Continuation of https://github.com/bbatsov/rubocop/issues/5648

### Expected behavior
It should **not** suggest replacing `@full_name` with `@full_name!`

### Actual behavior

```
app/models/client.rb:93:5: C: Naming/MemoizedInstanceVariableName: Memoized variable @full_name does not match method name full_name!. Use @full_name! instead.
```

Rubocop wants me to change the instance variable to `@full_name!`, which is not valid.

### Steps to reproduce the problem
```ruby
def full_name!
  @full_name ||= 'fetch full name'
end
```

### RuboCop version
0.53.0

### PR DESCRIPTION
**Pull request by pocke**
See #5670 and #5648

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `rake default` or `rake parallel`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/naming/memoized_instance_variable_name.rb [hunk 1]
```diff
@@ -55,7 +55,7 @@ def on_def(node)
           msg = format(
             MSG,
             var: ivar_assign.children.first.to_s,
-            suggested_var: method_name.to_s.chomp('?'),
+            suggested_var: method_name.to_s.delete('!?'),
```
Comment (pocke) [inline lib/rubocop/cop/naming/memoized_instance_variable_name.rb]: Method name can contain `!` and `?` at the end of the name only. So we can use `String#delete` for this purpose.
