### PR TITLE
[Fix #3148] Make Rails/UniqBeforePluck more conservative

### LINKED ISSUE #3148: [BUG] Use uniq before pluck
In model i have
```
  def events_ids
    result = volunteer_roles.uniq.pluck(:event_id)
    result.any? ? result : nil
  end
```

`rubocop -a` returns

```
Offenses:

app/models/user.rb:157:47: C: [Corrected] Use uniq before pluck
    result = volunteer_roles.pluck(:event_id).uniq
                                              ^^^^
```

And in this case, it is wrong correction, because `uniq` or `distinct` methods return Array and `pluck` need Activerecord::Relation

### PR DESCRIPTION
**Pull request by tjwp**
This change is to address Issue https://github.com/bbatsov/rubocop/issues/3148

Autocorrect is disabled by default for this cop since it can potentially generate false positives.

Add offenses for `distinct` as well as `uniq`.

By default only add offenses for calls to `pluck` directly
on constants.

Add an 'aggressive' mode that adds all offenses as the cop did
originally.

* [x] Wrote [good commit messages][1].
* [x] Used the same coding conventions as the rest of the project.
* [x] Feature branch is up-to-date with `master` (if not - rebase it)
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] All tests are passing.
* [x] The new code doesn't generate RuboCop offenses.
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.

[1]: http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html

### CODE REVIEW

File: spec/rubocop/cop/rails/uniq_before_pluck_spec.rb [hunk 1]
```diff
@@ -3,55 +3,83 @@
...
 
-describe RuboCop::Cop::Rails::UniqBeforePluck do
-  let(:corrected) { 'Model.uniq.pluck(:id)' }
-  subject(:cop) { described_class.new }
+describe RuboCop::Cop::Rails::UniqBeforePluck, :config do
+  subject(:cop) { described_class.new(config) }
 
-  shared_examples_for 'UniqBeforePluck cop' do |source, action|
+  shared_examples_for 'UniqBeforePluck cop' do |method, source, action|
     if action == :correct
```
Comment (jonas054) [inline spec/rubocop/cop/rails/uniq_before_pluck_spec.rb]: The action should be called `:report` if we don't auto-correct. But I wonder if it's really necessary to remove auto-correct now that we have a conservative mode. I said in #3148 that it might be necessary to remove it, but then again, it might not be necessary. :smile: What do you think?

Comment (tjwp) [inline spec/rubocop/cop/rails/uniq_before_pluck_spec.rb]: I'm leaning towards restoring auto-correct, but making it disabled by default. Even with the conservative mode, I think there is a possibility of false positives because the cop only checks that `pluck` is called on a constant but it cannot verify that the constant refers to a model class.

Comment (jonas054) [inline spec/rubocop/cop/rails/uniq_before_pluck_spec.rb]: That's reasonable. It's difficult to guess what risk auto-correct poses in this case, so go with that idea.

**Comment by tjwp** [comment]
@jonas054 Restored auto-correct, including support for `distinct` and `uniq`, squashed, and rebased. Auto-correct is disabled by default for this cop.

File: lib/rubocop/cop/rails/uniq_before_pluck.rb [hunk 2]
```diff
@@ -4,61 +4,83 @@
...
+      # vs a call to pluck on an ActiveRecord::Associations::CollectionProxy.
+      #
+      # @example
+      #   # this will return a Relation that pluck is called on
+      #   Model.where(...).pluck(:id).uniq
+      #
+      #   # an association on an instance will return a CollectionProxy
+      #   instance.assoc.pluck(:id).uniq
+      #
+      # Autocorrect is disabled by default for this cop since it may generated
```
Comment (jonas054) [inline lib/rubocop/cop/rails/uniq_before_pluck.rb]: generated -> generate

Comment (tjwp) [inline lib/rubocop/cop/rails/uniq_before_pluck.rb]: Fixed typo.

**Comment by jonas054** [comment]
:+1: Changes look good. Just one more thing. Sorry I didn't mention it earlier. If this fixes #3148, which I think it does, you should start the commit message with `[Fix #3148]`.

**Comment by tjwp** [comment]
@jonas054 Updated the commit message to start with the issue being fixed. Thanks!

**Comment by bbatsov** [comment]
You'll have to rebase on top of the current `master`.

**Comment by tjwp** [comment]
@bbatsov rebased
