### PR TITLE
[Fix #2154] Fix auto-correct of StringReplacement with a backslash again

### LINKED ISSUE #2154: gsub -> tr cop messes up escaped string
First off, thanks for rubocop!

So if I have a file like this:

```ruby
"".gsub('/', '\\')
```

rubocop (0.33.0 as well as GitHub `master`) transforms it to this:

```ruby
"".tr('/', '\')
```

This isn't good because Ruby sees the second single quote as being escaped and there syntax errors.

Here's the rubocop output:

```
$ rubocop -aD test.rb
Inspecting 1 file
F

Offenses:

test.rb:1:4: C: [Corrected] Performance/StringReplacement: Use tr instead of gsub.
"".gsub('/', '\\')
   ^^^^^^^^^^^^^^^
test.rb:1:12: F: unterminated string meets end of file
"".tr('/', '\')
           ^

1 file inspected, 2 offenses detected, 1 offense corrected
```

`rubocop -V`:

```
$ rubocop -V
0.33.0 (using Parser 2.2.2.6, running on ruby 2.0.0 x86_64-darwin14.3.0)
```

You can also see my `.rubocop.yml` and `.rubocop_todo.yml` here:

https://gist.github.com/cheerfulstoic/062fa3b79e8397b82c19

### PR DESCRIPTION
**Pull request by rrosenblum**
It turns out I didn't fix all scenarios that include a backslash. @aevernon added a comment to #2154 that `''.gsub('\\', '')` was not auto-correcting properly.

The new solution does not touch the first parameter unless it is a regular expression.

### CODE REVIEW

File: spec/rubocop/cop/performance/string_replacement_spec.rb [hunk 1]
```diff
@@ -413,7 +419,7 @@
       it 'when deleteing an escape character' do
```
Comment (bbatsov) [inline spec/rubocop/cop/performance/string_replacement_spec.rb]: Just noticed the typo here.

File: spec/rubocop/cop/performance/string_replacement_spec.rb [hunk 2]
```diff
@@ -381,19 +381,25 @@
       it 'when the pattern contains an escape character' do
         new_source = autocorrect_source(cop, "'abc'.gsub('\n', ',')")
 
-        expect(new_source).to eq("'abc'.tr(\"\\n\", ',')")
+        expect(new_source).to eq("'abc'.tr('\n', ',')")
+      end
+
+      it 'when the pattern contains double backslash' do
```
Comment (bbatsov) [inline spec/rubocop/cop/performance/string_replacement_spec.rb]: Btw, the descriptions of all examples here sound pretty strange. They should read like sentences (with `it` being the start of the sentence). I'd suggest tweaking them in a an extra commit. See http://betterspecs.org.

**Comment by rrosenblum** [comment]
Spelling has been fixed. I have also made the test names better.

**Comment by cthiel** [comment]
This (or a change recently introduced in master) still seems to be producing wrong corrections. Also, the message displayed was a bit misleading.

I had code like:

```
  a = somestring.gsub(/\n/,'')
```

The cop mentioned:
C: Use delete instead of gsub.

auto-correct turned the code into:

```
  a = somestring.tr('\\n', '')
```

which is neither using delete, nor is is producing the expected (same) result.

**Comment by alexdowad** [comment]
@cthiel Please open a new issue.

**Comment by cthiel** [comment]
Done. Created issue #2580.
