### PR TITLE
Fix ForceEqualSignAlignment check

### LINKED ISSUE #2912: rubocop reports false positives.
## Expected behavior

rubocop should not report any errors.

## Actual behavior

rubocop reports errors, which do not exist, even after running `rubocop -a`

## Steps to reproduce the problem
```
$ rubocop -a app/controllers/api/wishes_controller.rb
Inspecting 1 file
C

Offenses:

app/controllers/api/wishes_controller.rb:9:15: C: [Corrected] = is not aligned with the following assignment.
    wish      = Wish.where(text: params[:text]).first
              ^
app/controllers/api/wishes_controller.rb:17:28: C: [Corrected] = is not aligned with the following assignment.
        initial_wishes     = sugg.initial_wishes
                           ^
app/controllers/api/wishes_controller.rb:47:14: C: [Corrected] = is not aligned with the following assignment.
    user_ids = Wish.find(params[:id]).user_ids
             ^
app/controllers/api/wishes_controller.rb:53:14: C: [Corrected] = is not aligned with the following assignment.
    user_ids = Wish.find(params[:id]).user_ids
             ^
app/controllers/api/wishes_controller.rb:71:11: C: [Corrected] = is not aligned with the following assignment.
    wish  = Wish.find(params[:id])
          ^
app/controllers/api/wishes_controller.rb:94:12: C: [Corrected] = is not aligned with the following assignment.
      user = wish.users.where.not('users.avatar' => nil).sample
           ^
app/controllers/api/wishes_controller.rb:121:18: C: [Corrected] = is not aligned with the following assignment.
      params[:q] = params[:q].gsub(/ich würde/i,'')
                 ^
app/controllers/api/wishes_controller.rb:142:12: C: [Corrected] = is not aligned with the following assignment.
      user = wish.users.where.not('users.avatar' => nil).sample unless params[:q]
           ^

1 file inspected, 8 offenses detected, 8 offenses corrected

$ git status
On branch develop
nothing to commit, working directory clean

$ rubocop -a app/controllers/api/wishes_controller.rb
Inspecting 1 file

[....]

1 file inspected, 8 offenses detected, 8 offenses corrected

```
As you can see, the same errors are reported, even after rubocop claims to have fixed them. 
Here's a snippet of the first offense reported by rubocop: 

```
# wishes_controller.rb line 9-10
 wish      = Wish.where(text: params[:text]).first
 wish      = Wish.create(params.permit(:text)) unless wish

```
As you can see, the alignments __are__ properly aligned.

## RuboCop version

Include the output of `rubocop -V`:

```
$ rubocop -V
0.16.0 (using Parser 2.1.2, running on ruby 2.0.0 x86_64-darwin12.4.0)
```

### PR DESCRIPTION
**Pull request by akihiro17**
We should check whther a line is aligned with the following line if the preceding line is not an assignment statement.

This fixes #2912

Before submitting a PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Used the same coding conventions as the rest of the project.
* [x] Feature branch is up-to-date with `master` (if not - rebase it)
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../CONTRIBUTING.md#changelog-entry-format).
* [x] All tests are passing.
* [x] The new code doesn't generate RuboCop offenses.
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.

[1]: http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html

### CODE REVIEW

File: spec/rubocop/cop/style/extra_spacing_spec.rb [hunk 1]
```diff
@@ -247,7 +247,8 @@
     end
 
     it 'does not register an offense if assignments are aligned' do
-      inspect_source(cop, ['a   = 1',
+      inspect_source(cop, ['# comment',
```
Comment (bbatsov) [inline spec/rubocop/cop/style/extra_spacing_spec.rb]: I think this should probably be a separate example to illustrate what we're testing in a clearer manner.

File: lib/rubocop/cop/style/extra_spacing.rb [hunk 2]
```diff
@@ -67,11 +67,14 @@ def check_tokens(ast, t1, t2)
         end
 
         def check_assignment(token)
-          # minus 2 is because pos.line is zero-based
-          line = processed_source.lines[token.pos.line - 2]
+          preceding = @asgn_lines.include?(token.pos.line - 1)
```
Comment (bbatsov) [inline lib/rubocop/cop/style/extra_spacing.rb]: preceding what? :-)

File: lib/rubocop/cop/style/extra_spacing.rb [hunk 3]
```diff
@@ -67,11 +67,14 @@ def check_tokens(ast, t1, t2)
...
+          line = if preceding
```
Comment (bbatsov) [inline lib/rubocop/cop/style/extra_spacing.rb]: what line? :-)

I'm guessing that in the interest of clarity some helper method can be extracted here.

**Comment by bbatsov** [comment]
Thanks for looking into this. A few remarks:

* Prefix the commit's title with `[Fix #2912]`, as we typically do.
* Rebase on top of the current `master` branch

File: spec/rubocop/cop/style/extra_spacing_spec.rb (hunk 1 above)
Comment (Drenmi) [inline spec/rubocop/cop/style/extra_spacing_spec.rb]: I actually created a fix for this same issue, but stumbled a bit to figure out what the exact issue was, but I'm pretty sure [this guard clause](https://github.com/akihiro17/rubocop/blob/fix-equal-sign-alignment/lib/rubocop/cop/style/extra_spacing.rb#L57) is involved. (Adding a new-line to the end of the `#inspect_source` argument made the test function correctly.) It would be great if the updated test could reflect what's going on here.

File: lib/rubocop/cop/style/extra_spacing.rb (hunk 2 above)
Comment (akihiro17) [inline lib/rubocop/cop/style/extra_spacing.rb]: Does 'preceding what?' mean that I should change the variable name to clarify what the code does?

File: lib/rubocop/cop/style/extra_spacing.rb (hunk 3 above)
Comment (bbatsov) [inline lib/rubocop/cop/style/extra_spacing.rb]: Yeah. I know the name was there before your PR, but I feel this is an opportunity to improve it.

**Comment by akihiro17** [comment]
@bbatsov 

I have updated the commit.

**Comment by bbatsov** [comment]
@akihiro17 Can you rebase one more time?

**Comment by akihiro17** [comment]
@bbatsov rebased
