### PR TITLE
[FIX #3931] Implement a cop checking for ambiguous block association …

### LINKED ISSUE #3931: Implement a cop checking for ambiguous block association with a method
Passing a single param to some method and a block (with no parens around the param) should yield a warning. Many people would confusingly believe the block would be associated with the first method, but it's actually going to be associated with its parameter. 

See https://github.com/bbatsov/rubocop/issues/3928 as a reference.

Here's an example:

```ruby
def some_method(x)
  yield x
end

def bar(a)
  some_method a { puts 1 }
end
```
--------

## Expected behavior

This code should produce a warning saying you should use parens to disambiguate the meaning of your code.

## Actual behavior

No warning is raised.

## Steps to reproduce the problem

Just run RuboCop over the example code.

## RuboCop version

```
$ rubocop -V
0.47.0 (using Parser 2.3.3.1, running on ruby 2.3.3 x86_64-linux)
```

### PR DESCRIPTION
**Pull request by smakagon**
…with a method

This cop checks for ambiguous block association with method when param passed without parentheses.

Example:
It's ambiguous because there is no parentheses around `a` param:
`some_method a { |val| puts val }`

With parentheses, there's no ambiguity:
`some_method(a) { |val| puts val }`

Cop will add warning message:
Parenthesize the param to make sure that block will be associated with method call.

### CODE REVIEW

File: lib/rubocop/cop/lint/ambiguous_block_association.rb [hunk 1]
```diff
@@ -0,0 +1,41 @@
...
+      #   some_method a { |val| puts val }
+      #
+      # @example
+      #
+      #   # good
+      #
+      #   # With parentheses, there's no ambiguity.
+      #   some_method(a) { |val| puts val }
+      class AmbiguousBlockAssociation < Cop
+        MSG = 'Parenthesize the param to make sure that block will be '\
```
Comment (bbatsov) [inline lib/rubocop/cop/lint/ambiguous_block_association.rb]: Perhaps it'd be better to mention the param name and the method name explicitly in the message.

File: spec/rubocop/cop/lint/ambiguous_block_association_spec.rb [hunk 2]
```diff
@@ -0,0 +1,63 @@
...
+          'Foo.some_method a { |el| puts el }'
+        end
+
+        it 'registers an offense' do
+          expect(cop.offenses.size).to eq(1)
+          expect(cop.offenses.first.message).to eq(error_message)
+        end
+      end
+
+      context 'with a parentheses' do
```
Comment (bbatsov) [inline spec/rubocop/cop/lint/ambiguous_block_association_spec.rb]: - a

File: .gitignore [hunk 3]
```diff
@@ -20,6 +20,7 @@ pkg
 # etags
 TAGS
 
+*.swp
```
Comment (bbatsov) [inline .gitignore]: Is this some vim tmp file extension? If so - move it down the file.

**Comment by bbatsov** [comment]
Your code currently produces a ton of false positives. Guess now you have plenty of ideas about new test cases. :-)

File: .gitignore (hunk 3 above)
Comment (smakagon) [inline .gitignore]: Yes. Will move. Thanks.

File: lib/rubocop/cop/lint/ambiguous_block_association.rb [hunk 4]
```diff
@@ -0,0 +1,59 @@
...
+      #   # good
+      #
+      #   # With parentheses, there's no ambiguity.
+      #   some_method(a) { |val| puts val }
+      class AmbiguousBlockAssociation < Cop
+        MSG = 'Parenthesize the param `%s` to make sure that block will be '\
+              'associated with `%s` method call.'.freeze
+
+        def on_send(node)
+          _klass, method_name, args = node.children
```
Comment (Drenmi) [inline lib/rubocop/cop/lint/ambiguous_block_association.rb]: There's a `SendNode` extension, so you no longer need to destructure send nodes. I'll highlight below how to use it. 🙂

File: lib/rubocop/cop/lint/ambiguous_block_association.rb [hunk 5]
```diff
@@ -0,0 +1,59 @@
...
+
+          return if method_name == :[]
```
Comment (Drenmi) [inline lib/rubocop/cop/lint/ambiguous_block_association.rb]:
```ruby
return if node.method?(:[])
```

File: lib/rubocop/cop/lint/ambiguous_block_association.rb [hunk 6]
```diff
@@ -0,0 +1,59 @@
...
+          return if node.parenthesized? || node.assignment?
+          return unless method_with_block?(args)
+
+          first_param = args.children.first
```
Comment (Drenmi) [inline lib/rubocop/cop/lint/ambiguous_block_association.rb]: This should work:

```ruby
node.first_argument
```

File: lib/rubocop/cop/lint/ambiguous_block_association.rb [hunk 7]
```diff
@@ -0,0 +1,59 @@
...
+        def method_with_block?(args)
+          return false unless args
+
+          args.block_type?
+        end
+
+        def method_as_param?(node)
+          return false unless node.is_a?(RuboCop::AST::Node)
+
+          node.send_type? && node.children.size <= 2
```
Comment (Drenmi) [inline lib/rubocop/cop/lint/ambiguous_block_association.rb]:
```ruby
node.send_type? && !node.arguments?
```

File: lib/rubocop/cop/lint/ambiguous_block_association.rb (hunk 5 above)
Comment (smakagon) [inline lib/rubocop/cop/lint/ambiguous_block_association.rb]: Thanks, that looks better.

File: lib/rubocop/cop/lint/ambiguous_block_association.rb (hunk 6 above)
Comment (smakagon) [inline lib/rubocop/cop/lint/ambiguous_block_association.rb]: @Drenmi thanks for review!
Unfortunately it doesn't work with `node.first_argument`. 
Here is example:
`node.source => "some_method a { |el| puts el }"`

Here is what we have in `node.first_argument`:
> => s(:block,
  s(:send, nil, :a),
  s(:args,
    s(:arg, :el)),
  s(:send, nil, :puts,
    s(:lvar, :el)))

If I use `args.children.first` I'll get:
> => s(:send, nil, :a)

File: lib/rubocop/cop/lint/ambiguous_block_association.rb (hunk 7 above)
Comment (smakagon) [inline lib/rubocop/cop/lint/ambiguous_block_association.rb]: @Drenmi yep, that works.

File: lib/rubocop/cop/lint/ambiguous_block_association.rb [hunk 8]
```diff
@@ -0,0 +1,58 @@
...
+  module Cop
+    module Lint
+      # This cop checks for ambiguous block association with method
+      # when param passed without parentheses.
+      #
+      # @example
+      #
+      #   # bad
+      #
+      #   # It's ambiguous because there is no parentheses around `a` param
```
Comment (bbatsov) [inline lib/rubocop/cop/lint/ambiguous_block_association.rb]: I think this explanation is redundant. Also it's strange there's an empty line between `bad` and the rest of the explanation.

File: lib/rubocop/cop/lint/ambiguous_block_association.rb [hunk 9]
```diff
@@ -0,0 +1,58 @@
...
+      #
+      # @example
+      #
+      #   # good
+      #
+      #   # With parentheses, there's no ambiguity.
+      #   some_method(a) { |val| puts val }
+      class AmbiguousBlockAssociation < Cop
+        MSG = 'Parenthesize the param `%s` to make sure that block will be '\
+              'associated with `%s` method call.'.freeze
```
Comment (bbatsov) [inline lib/rubocop/cop/lint/ambiguous_block_association.rb]: with the

File: lib/rubocop/cop/lint/ambiguous_block_association.rb [hunk 10]
```diff
@@ -0,0 +1,58 @@
...
+          return unless method_as_param?(first_child)
+
+          add_offense(
+            node, :expression, format_error(first_child, node.method_name)
+          )
+        end
+
+        private
+
+        def method_with_block?(args)
```
Comment (bbatsov) [inline lib/rubocop/cop/lint/ambiguous_block_association.rb]: args or arg?

File: lib/rubocop/cop/lint/ambiguous_block_association.rb [hunk 11]
```diff
@@ -0,0 +1,58 @@
...
+      #   some_method(a) { |val| puts val }
+      class AmbiguousBlockAssociation < Cop
+        MSG = 'Parenthesize the param `%s` to make sure that block will be '\
+              'associated with `%s` method call.'.freeze
+
+        def on_send(node)
+          return if node.parenthesized? || node.assignment? || node.method?(:[])
+
+          return unless method_with_block?(node.first_argument)
+          first_child = node.first_argument.children.first
```
Comment (bbatsov) [inline lib/rubocop/cop/lint/ambiguous_block_association.rb]: first_child is a non-descriptive variable name

File: lib/rubocop/cop/lint/ambiguous_block_association.rb [hunk 12]
```diff
@@ -0,0 +1,58 @@
...
+          args.block_type?
+        end
+
+        def method_as_param?(node)
+          return false unless node.is_a?(RuboCop::AST::Node)
+
+          node.send_type? && !node.arguments?
+        end
+
+        def format_error(param, method_name)
```
Comment (bbatsov) [inline lib/rubocop/cop/lint/ambiguous_block_association.rb]: param might not be the best name here

File: spec/rubocop/cop/lint/ambiguous_block_association_spec.rb [hunk 13]
```diff
@@ -0,0 +1,199 @@
...
+  end
+
+  before do
+    inspect_source(cop, source)
+  end
+
+  context 'method without params and block' do
+    context 'without receiver' do
+      context 'without parentheses' do
+        let(:source) { 'some_method a { |el| puts el }' }
```
Comment (bbatsov) [inline spec/rubocop/cop/lint/ambiguous_block_association_spec.rb]: This contradicts the top-level context.

File: spec/rubocop/cop/lint/ambiguous_block_association_spec.rb [hunk 14]
```diff
@@ -0,0 +1,199 @@
...
+    context 'without parantheses' do
+      context 'with receiver' do
+        let(:source) { 'environment ENV.fetch("RAILS_ENV") { "development" }' }
+
+        it 'accepts' do
+          expect(cop.offenses).to be_empty
+        end
+      end
+
+      context 'witout receiver' do
```
Comment (bbatsov) [inline spec/rubocop/cop/lint/ambiguous_block_association_spec.rb]: I've noticed this typo here and there

File: spec/rubocop/cop/lint/ambiguous_block_association_spec.rb [hunk 15]
```diff
@@ -0,0 +1,199 @@
...
+
+        it 'accepts' do
+          expect(cop.offenses).to be_empty
+        end
+      end
+    end
+  end
+
+  context 'method with arguments and block' do
+    context 'without parantheses' do
```
Comment (bbatsov) [inline spec/rubocop/cop/lint/ambiguous_block_association_spec.rb]: typo

File: spec/rubocop/cop/lint/ambiguous_block_association_spec.rb [hunk 16]
```diff
@@ -0,0 +1,199 @@
...
+          expect(cop.offenses).to be_empty
+        end
+      end
+    end
+  end
+
+  context 'multiline blocks' do
+    context 'without parentheses' do
+      context 'without block param' do
+        let(:source) { ['some_method a do', 'puts "here"', 'end'] }
```
Comment (bbatsov) [inline spec/rubocop/cop/lint/ambiguous_block_association_spec.rb]: Using a heredoc yields prettier results and more readable code.

File: lib/rubocop/cop/lint/ambiguous_block_association.rb (hunk 8 above)
Comment (smakagon) [inline lib/rubocop/cop/lint/ambiguous_block_association.rb]: @bbatsov many cops in `lint` folder have this empty line between `#good` or `#bad` and explanation. I thought it's sort of standard. Ok, will remove description for bad and empty lines between. Thanks.

File: lib/rubocop/cop/lint/ambiguous_block_association.rb (hunk 11 above)
Comment (smakagon) [inline lib/rubocop/cop/lint/ambiguous_block_association.rb]: I'm going to rename `first_child` to `first_param` and stick to `param` naming instead of `args`. Just to be consistent.

File: lib/rubocop/cop/lint/ambiguous_block_association.rb [hunk 17]
```diff
@@ -0,0 +1,55 @@
...
+      #   # bad
+      #   some_method a { |val| puts val }
+      #
+      # @example
+      #
+      #   # good
+      #   # With parentheses, there's no ambiguity.
+      #   some_method(a) { |val| puts val }
+      class AmbiguousBlockAssociation < Cop
+        MSG = 'Parenthesize the param `%s` to make sure that block will be '\
```
Comment (bbatsov) [inline lib/rubocop/cop/lint/ambiguous_block_association.rb]: that the block

Comment (bbatsov) [inline lib/rubocop/cop/lint/ambiguous_block_association.rb]: Btw, I'm not sure about this message in general - sounds a bit vague to me. @Drenmi @pocke @jonas054 WDYT?

File: spec/rubocop/formatter/offense_count_formatter_spec.rb [hunk 18]
```diff
@@ -20,14 +20,14 @@ module Formatter
         context 'when no offenses are detected' do
           let(:offenses) { [] }
           it 'does not add to offense_counts' do
-            expect { finish }.not_to change { formatter.offense_counts }
+            expect { finish }.not_to(change { formatter.offense_counts })
```
Comment (bbatsov) [inline spec/rubocop/formatter/offense_count_formatter_spec.rb]: Maybe we should add some exceptions (or simply disable this cop here) as I prefer the original version of the code. DSL make heavy use of this, aiming to produce a more natural code.

File: lib/rubocop/cop/lint/ambiguous_block_association.rb (hunk 17 above)
Comment (jonas054) [inline lib/rubocop/cop/lint/ambiguous_block_association.rb]: The message seems clear to me. It's quite detailed, telling the user what to do.

Comment (bbatsov) [inline lib/rubocop/cop/lint/ambiguous_block_association.rb]: Well, it doesn't tell them what the actual issue is. :-) Anyways, I guess it will do.

File: spec/rubocop/formatter/offense_count_formatter_spec.rb (hunk 18 above)
Comment (smakagon) [inline spec/rubocop/formatter/offense_count_formatter_spec.rb]: @bbatsov I definitely agree with that. It's better not to break this nice DSL: `expect {}.to change {}`
Many RSpec users would want to disable this cop for their specs.
What do you think the best way to handle that?

File: lib/rubocop/cop/lint/ambiguous_block_association.rb [hunk 19]
```diff
@@ -0,0 +1,55 @@
...
+        private
+
+        def method_with_block?(param)
+          return false unless param
+
+          param.block_type?
+        end
+
+        def method_as_param?(param)
+          return false unless param.is_a?(RuboCop::AST::Node)
```
Comment (smakagon) [inline lib/rubocop/cop/lint/ambiguous_block_association.rb]: @bbatsov That method checks if param it's a method call and it doesn't have arguments.

For example we accept this code (because `receive` accepts `:on_init` argument):
`allow(cop).to receive(:on_int) { raise RuntimeError }`

But we add offense to this one (because `a` called without params):
`some_method a { |el| puts el }`

If we would like to mark them both as offense - we could check only for `nil` in that method and that would be fine.
Should we mark both these examples as offenses?

File: spec/rubocop/formatter/offense_count_formatter_spec.rb (hunk 18 above)
Comment (bbatsov) [inline spec/rubocop/formatter/offense_count_formatter_spec.rb]: We can probably disable this cop completely for the `spec` folder in RuboCop and users might opt to do the same.

Comment (smakagon) [inline spec/rubocop/formatter/offense_count_formatter_spec.rb]: @bbatsov  Done

File: lib/rubocop/cop/lint/ambiguous_block_association.rb (hunk 19 above)
Comment (Drenmi) [inline lib/rubocop/cop/lint/ambiguous_block_association.rb]: It is extremely rare that a destructured node has something other than a `Node` or `nil` in its node parts.

I think what @bbatsov is hinting at is you should remove the type check, and do something like:

```ruby
return false unless param
```

🙂

File: lib/rubocop/cop/lint/ambiguous_block_association.rb [hunk 20]
```diff
@@ -0,0 +1,55 @@
...
+
+          param.send_type? && !param.arguments?
+        end
+
+        def format_error(param, method_name)
```
Comment (Drenmi) [inline lib/rubocop/cop/lint/ambiguous_block_association.rb]: Conventionally, the other cops name this `#message`. This is because there is some code in `Cop` that implicitly uses that method unless you call it in `#add_offense`. (The implicit form only works when the method has no parameters, I believe.)

File: lib/rubocop/cop/lint/ambiguous_block_association.rb (hunk 19 above)
Comment (smakagon) [inline lib/rubocop/cop/lint/ambiguous_block_association.rb]: @Drenmi @bbatsov got your idea guys, changing it right now.

File: lib/rubocop/cop/lint/ambiguous_block_association.rb (hunk 20 above)
Comment (smakagon) [inline lib/rubocop/cop/lint/ambiguous_block_association.rb]: @Drenmi thanks, will rename that method to `message`

Comment (Drenmi) [inline lib/rubocop/cop/lint/ambiguous_block_association.rb]: No worries. 🙂 There's no way you would know this without digging through the code a lot. 😅  I've been meaning to improve the documentation for creating new cops for a while, but I never seem to have time to get around to it.

Comment (smakagon) [inline lib/rubocop/cop/lint/ambiguous_block_association.rb]: I want to contribute to open source. And RuboCop it's a great way to start doing that because I use it in all my projects. I feel support from you guys here, so I'm pretty excited. Thanks.
Also I met @bbatsov in RubyC (Kiev, Ukraine) and enjoyed his talk there.

Comment (Drenmi) [inline lib/rubocop/cop/lint/ambiguous_block_association.rb]: This is great work @smakagon, and thanks for being so responsive. Would love to see more PRs from you. 😀
