### PR TITLE
[Fix #3510] Various bug fixes for SafeNavigation

### LINKED ISSUE #3510: Style/SafeNavigation cop crashes when auto correct
cc: @rrosenblum 

## Expected behavior

Don't crash

## Actual behavior

RuboCop crashes.

## Steps to reproduce the problem

Put the following files.

`test.rb`

```ruby
if foo
  foo.bar
end
```

`.rubocop.yml`

```yaml
AllCops:
  TargetRubyVersion: 2.3
```

And run RuboCop with auto correction.

```sh
$ rubocop -d -a --only Style/SafeNavigation
For /tmp/tmp.GoBYI5sfic: configuration from /tmp/tmp.GoBYI5sfic/.rubocop.yml
Default configuration from /home/pocke/.gem/ruby/2.3.0/gems/rubocop-0.43.0/config/default.yml
Inheriting configuration from /home/pocke/.gem/ruby/2.3.0/gems/rubocop-0.43.0/config/enabled.yml
Inheriting configuration from /home/pocke/.gem/ruby/2.3.0/gems/rubocop-0.43.0/config/disabled.yml
Inspecting 1 file
Scanning /tmp/tmp.GoBYI5sfic/test.rb
E

Offenses:

test.rb:1:1: C: [Corrected] Style/SafeNavigation: Use safe navigation (&.) instead of checking if an object exists before calling the method.
if foo ...
^^^^^^
test.rb:3:1: E: unexpected token $end
(Using Ruby 2.3 parser; configure using TargetRubyVersion parameter, under AllCops)

1 file inspected, 2 offenses detected, 1 offense corrected
Finished in 0.0491263820003951 seconds

$ cat test.rb
if foo
  foo&.bar
```

## RuboCop version

```
$ rubocop -V
0.43.0 (using Parser 2.3.1.3, running on ruby 2.3.1 x86_64-linux)
```

### PR DESCRIPTION
**Pull request by rrosenblum**
This fixes #3510. Stop registering an offense for ternary operators, non modifier if statements, and scenarios using `||`.

There is an outstanding enhancement to register an offense for and correct simple multiline if statements.
```ruby
if foo
  foo.bar
end
```
Registering an offense for this scenario is easy. The auto-correct is bit difficult compared to what is being done in the other scenarios. It is taking a little longer than I expected it to, and I know that this cop is broken for people so the fix seems more important than the enhancement.

### CODE REVIEW

**Comment by rrosenblum** [comment]
I have added a new configuration to `Style/SafeNavigation`. The name is `ConvertCodeThatCanStartToReturnNil` and it is defaulted to `false`. It was realized that code in the format of `!foo.nil? && foo.bar` could start returning `nil` if safe navigation is used. Without safe navigation, this example is limited to `false` and the return value of `foo.bar` (most likely `true` or `false`).

File: lib/rubocop/cop/style/safe_navigation.rb [hunk 1]
```diff
@@ -51,18 +61,18 @@ class SafeNavigation < Cop
...
 
+        def_node_matcher :candidate_that_may_introduce_nil, <<-PATTERN
+          (and
+            {(send (send $_ :nil?) :!) $_}
+            {(send $_ $_ ...) (block (send $_ $_ ...) ...)}
+          ...)
+        PATTERN
+
         def on_if(node)
+          return unless modifier_if?(node)
```
Comment (pocke) [inline lib/rubocop/cop/style/safe_navigation.rb]: Can we move the check to `auto_correct` method?
If move, the cop can detect non modifier if, and the cop doesn't apply auto-correction.

Comment (rrosenblum) [inline lib/rubocop/cop/style/safe_navigation.rb]: I removed the check all together. I was able to get some time to finally figure out how to handle the auto correct properly.

File: CHANGELOG.md [hunk 2]
```diff
@@ -2,6 +2,10 @@
 
 ## master (unreleased)
 
+### Bug fixes
+
+* [#3510](https://github.com/bbatsov/rubocop/issues/3510): Fix some issues with `Style/SafeNavigation`. Do not register an offense for scenarios using `||`, ternary if statements, and non modifier if statements. ([@rrosenblum][])
```
Comment (rrosenblum) [inline CHANGELOG.md]: Updated. I guess github's new system doesn't hide outdated diffs anymore.

File: spec/rubocop/cop/style/safe_navigation_spec.rb [hunk 3]
```diff
@@ -172,6 +172,81 @@
         end
       end
 
+      context 'if statements' do
```
Comment (rrosenblum) [inline spec/rubocop/cop/style/safe_navigation_spec.rb]: Updated

File: spec/rubocop/cop/style/safe_navigation_spec.rb [hunk 4]
```diff
@@ -172,6 +172,81 @@
...
+        it 'accepts a single method call inside of a check for the object' do
+          inspect_source(cop, ["if #{variable}",
```
Comment (rrosenblum) [inline spec/rubocop/cop/style/safe_navigation_spec.rb]: It shouldn't have been. I was having trouble with the auto-correct, but I was able to get it working.

**Comment by bbatsov** [comment]
Are you going to squash those commits or you'd prefer to keep them separated?

**Comment by rrosenblum** [comment]
I initially was going to try to keep everything in separate commits. Given the change set, I am not sure that there is much value in having them separate. I will squash them.
