### PR TITLE
[Fix #2654] Fix unary in RedundantParentheses

### LINKED ISSUE #2654: Incorrect auto-correction
When run on this code:

```ruby
netmask = (~IPAddr.new(address).mask(0)).mask(prefix)
```

rubocop reports:

```
cookbooks/networking/recipes/default.rb:38:56: C: Don't use parentheses around a method call.
```

and corrects it to:

```ruby
netmask = ~IPAddr.new(address).mask(0).mask(prefix)
```

but removing the parentheses means than the `~` is applied after the call to the `mask` method instead of before it.

This is a change between 0.34.2 and 0.36.0 as the earlier version didn't complain about this code.

### PR DESCRIPTION
**Pull request by lumeet**
Handle unary operations in `Style/RedundantParentheses` and refactor slightly to avoid duplication.

### CODE REVIEW

**Comment by lumeet** [comment]
Updated, although Github seems to have some troubles with the diff.

File: lib/rubocop/ast_node.rb [hunk 1]
```diff
@@ -403,6 +403,18 @@ def keyword_not?
...
 
+    def unary_operation?
+      return false unless loc.respond_to?(:selector) && loc.selector
+      Cop::Util.operator?(loc.selector.source.to_sym) &&
+        source_range.begin_pos == loc.selector.begin_pos
+    end
+
+    def chained?
+      return false if parent.nil? || !parent.send_type?
+      receiver, _method_name, *_args = *parent
```
Comment (bbatsov) [inline lib/rubocop/ast_node.rb]: You could have also done just `receiver, = *parent`, but that's OK.
