### PR TITLE
[Fix #1769] LiteralInInterpolation registers an offense for __LINE__

### LINKED ISSUE #1769: LiteralInInterpolation false positive when interpolating "#{__LINE__}"
I just upgraded to RuboCop 0.30.0 and ran into a false positive when running LiteralInInterpolation.

Here is a test that exercises the bug.
```ruby
it 'accepts strings like __LINE__' do
  inspect_source(cop, '"this is #{__LINE__} silly"')
  expect(cop.offenses).to be_empty
end


1) RuboCop::Cop::Lint::LiteralInInterpolation accepts strings like __LINE__
     Failure/Error: expect(cop.offenses).to be_empty
       expected `[W:  1: 12: Literal interpolation detected.].empty?` to return true, got false
```

I will try to find a fix for the issue, but in the mean time, I wanted to bring exposure to the bug.

### PR DESCRIPTION
**Pull request by rrosenblum**
This fixes #1769. I added in a bunch of other test cases as well.

### CODE REVIEW

File: lib/rubocop/cop/lint/literal_in_interpolation.rb [hunk 1]
```diff
@@ -18,7 +18,6 @@ def on_dstr(node)
           node.children.select { |n| n.type == :begin }.each do |begin_node|
             final_node = begin_node.children.last
             next unless final_node
-            # handle strings like __FILE__
```
Comment (bbatsov) [inline lib/rubocop/cop/lint/literal_in_interpolation.rb]: Why did you remove this?

File: lib/rubocop/cop/lint/literal_in_interpolation.rb [hunk 2]
```diff
@@ -29,7 +28,9 @@ def on_dstr(node)
         private
 
         def special_string?(node)
-          node.type == :str && !node.loc.respond_to?(:begin)
+          # handle strings like __FILE__
```
Comment (bbatsov) [inline lib/rubocop/cop/lint/literal_in_interpolation.rb]: This partially answers my previous question. :-)

File: lib/rubocop/cop/lint/literal_in_interpolation.rb [hunk 3]
```diff
@@ -29,7 +28,9 @@ def on_dstr(node)
...
+          (node.type == :str && !node.loc.respond_to?(:begin)) ||
+            node.loc.expression.is?('__LINE__')
```
Comment (bbatsov) [inline lib/rubocop/cop/lint/literal_in_interpolation.rb]: __LINE__ is not a string, so handling it in a method called `special_string?` is kinda confusing.

File: lib/rubocop/cop/lint/literal_in_interpolation.rb (hunk 2 above)
Comment (rrosenblum) [inline lib/rubocop/cop/lint/literal_in_interpolation.rb]: The comment felt a bit misplaced to me.

File: lib/rubocop/cop/lint/literal_in_interpolation.rb (hunk 3 above)
Comment (rrosenblum) [inline lib/rubocop/cop/lint/literal_in_interpolation.rb]: I interpreted `special_string?` as the handler for special keywords (`__FILE__`, `__LINE__`, `__method__`, ...). 

My thoughts on cleanup for this would be refactor the naming of the method to make more sense, or create a new method `special_int?` to handle `__LINE__`.

What do you think?

Comment (bbatsov) [inline lib/rubocop/cop/lint/literal_in_interpolation.rb]: `__method__` is just a `Kernel` method. 

Not sure what the technical term for something like `__FILE__` and `__LINE__` is. If there's something common we can use it, otherwise `special_string?` and `special_int?` will do. I came up with `special_string?` just because I didn't know how exactly to name this...

**Comment by rrosenblum** [comment]
I couldn't find exactly what to call `__FILE__` and `__LINE__`, but I did find some interesting information about them. Those keywords are [replaced directly by the parser](http://stackoverflow.com/questions/16626980/how-is-the-line-and-file-constants-implemented-in-ruby). Ruby documented them under [keywords](https://github.com/ruby/ruby/blob/trunk/doc/keywords.rdoc).

I like calling them keywords, and I went with the method name `special_keyword?`.

**Comment by bbatsov** [comment]
:+1:
