### PR TITLE
[Fix #3923] Allow asciibetical gem ordering

### LINKED ISSUE #3923: `Bundler/OrderedGems` cop should respect ASCII order when gem name has symbols
## Expected behavior

`Bundler/OrderedGems` cop ([PR](https://github.com/bbatsov/rubocop/pull/3657)) should respect ASCII order.

## Actual behavior

I have the following gems in my Gemfile:

```
gem 'paper_trail'
gem 'paperclip'
```

Vim orders it this way, which is correct: `_` symbol comes before letters in ASCII table. However, this cop complains: `Gemfile:27:1: C: Bundler/OrderedGems: Gems should be sorted in an alphabetical order within their section of the Gemfile. Gem paperclip should appear before paper_trail`.

Reference:
* https://en.wikipedia.org/wiki/ASCII
* https://en.wikipedia.org/wiki/Collation

## Steps to reproduce the problem

Add the gems in the same order mentioned in the previous step and run `$ rubocop`.

## RuboCop version

```
$ rubocop -V
0.47.0 (using Parser 2.3.3.1, running on ruby 2.3.3 x86_64-darwin16)
```

### PR DESCRIPTION
**Pull request by mikegee**
The underscore character is between the uppercase and lowercase alphabetical characters in ASCII.

Folks expect "\_" to come before "a", but `String#casecmp` is implemented by uppercasing the inputs before comparing them. This leads to "\_" coming after alphabetical characters.

fixes #3923  

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Used the same coding conventions as the rest of the project.
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] All tests are passing.
* [x] The new code doesn't generate RuboCop offenses.
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [ ] Updated cop documentation with `rake generate_cops_documentation` (required only when you've added a new cop or changed the configuration/documentation of an existing cop).

[1]: http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html

### CODE REVIEW

File: lib/rubocop/cop/bundler/ordered_gems.rb [hunk 1]
```diff
@@ -34,7 +34,7 @@ def investigate(processed_source)
         end
 
         def case_insensitive_out_of_order?(string_a, string_b)
-          1 > string_a.casecmp(string_b)
+          string_a.downcase < string_b.downcase
```
Comment (bbatsov) [inline lib/rubocop/cop/bundler/ordered_gems.rb]: This turned out to be a simple fix. :-)

File: CHANGELOG.md [hunk 2]
```diff
@@ -11,6 +11,7 @@
 * [#3846](https://github.com/bbatsov/rubocop/issues/3846): `NodePattern` works for hyphenated node types. ([@alexdowad][])
 * [#3922](https://github.com/bbatsov/rubocop/issues/3922): Prevent `Style/NegatedIf` from breaking on negated ternary. ([@drenmi][])
 * [#3915](https://github.com/bbatsov/rubocop/issues/3915): Fix a false positive in `Lint/SafeNavigationChain` cop with `try` method. ([@pocke][])
+* [#3923](https://github.com/bbatsov/rubocop/issues/3923): Allow asciibetical sorting in `Bundler/OrderedGems`. ([@mikegee][])
```
Comment (bbatsov) [inline CHANGELOG.md]: Unfortunately I've cut 0.47.1 earlier today. You'll have to move this to the proper section of the changelog.

Comment (mikegee) [inline CHANGELOG.md]: Oops. I was more focused on getting the format of the line correct than where to put it.

File: CHANGELOG.md [hunk 3]
```diff
@@ -2,6 +2,8 @@
 
 ## master (unreleased)
 
+* [#3923](https://github.com/bbatsov/rubocop/issues/3923): Allow asciibetical sorting in `Bundler/OrderedGems`. ([@mikegee][])
```
Comment (bbatsov) [inline CHANGELOG.md]: Add a `Bug fixes` section above this (see past releases).

Comment (mikegee) [inline CHANGELOG.md]: done
