### PR TITLE
[Fix #5075] Fix auto-correct for `Style/RedundantParentheses`

### LINKED ISSUE #5075: `Style/RedundantParentheses` makes wrong ternary autocorrection
While cleaning up a large codebase, I stumbled upon the autocorrection plunder below.

--------

## Expected behavior

`Style/RedundantParentheses` should autocorrect this line of code:

```ruby
(user.active)? "Y" : "N"
```

to

```ruby
user.active ? "Y" : "N"
```

## Actual behavior

However, what actually happens is that the necessary whitespace is not added. And non-executable code is produced in place of the ternary.

```ruby
-  (user.active)? "Y" : "N"
+  user.active? "Y" : "N"
```

Attempting to execute the corrected line (where `active?` is also a defined method):

```
SyntaxError: unexpected ':', expecting end-of-input
```

## Steps to reproduce the problem

Run rubocop autocorrection on this snippet to produce the results described above.

```ruby
(user.active)? "Y" : "N"
```

## RuboCop version

```
0.51.0 (using Parser 2.4.0.0, running on ruby 2.3.3 x86_64-darwin15)
```

### PR DESCRIPTION
**Pull request by tiagotex**
Fix #5075

`Style/RedundantParentheses` tried to autocorrect redundant parentheses in a unspaced ternary operation by removing the parenthesis but didn't add an extra space.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Used the same coding conventions as the rest of the project.
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] All tests(`rake spec`) are passing.
* [x] The new code doesn't generate RuboCop offenses that are checked by `rake internal_investigation`.
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Updated cop documentation with `rake generate_cops_documentation` (required only when you've added a new cop or changed the configuration/documentation of an existing cop).

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/mixin/parentheses.rb [hunk 1]
```diff
@@ -15,8 +15,20 @@ def autocorrect(node)
...
           corrector.remove(node.loc.begin)
           corrector.remove(node.loc.end)
+
+          if ternary_operation?(node) && next_char_is_question_mark?(node)
+            corrector.insert_after(node.loc.end, ' ')
+          end
         end
       end
+
+      def ternary_operation?(node)
```
Comment (Drenmi) [inline lib/rubocop/cop/mixin/parentheses.rb]: This checks if `node` is the ternary *condition*, I think. 🙂

Comment (bbatsov) [reply lib/rubocop/cop/mixin/parentheses.rb]: Don't we already have some util or extension for this?

File: lib/rubocop/cop/mixin/parentheses.rb [hunk 2]
```diff
@@ -15,8 +15,20 @@ def autocorrect(node)
...
+        node.parent && node.parent.if_type? && node.parent.ternary?
```
Comment (bbatsov) [inline lib/rubocop/cop/mixin/parentheses.rb]: Ah, I answered this quickly for myself. :-)

**Comment by tiagotex** [comment]
Updated PR with feedback. Thank you for the fast replies 🙂

**Comment by bbatsov** [comment]
👍

**Comment by asherkach** [comment]
Though this change fixes the particular snippet in the issue, it doesn't resolve the wider issue that parentheses interact with the parser in ways beyond order of operations. For example, the snippet `true ? (true): false` still auto-corrects [incorrectly] to `true ? true: false`. It may be appropriate to replace the parentheses with spaces, then use the spacing cop auto-corrects to remove the extra space (if it is indeed extra).

```
cosmiccrisp:rubocop asherkach$ cat test.rb 
true ? (true): false
cosmiccrisp:rubocop asherkach$ bundle exec rubocop test.rb --only Style/RedundantParentheses --auto-correct
Inspecting 1 file
C

Offenses:

test.rb:1:8: C: [Corrected] Style/RedundantParentheses: Don't use parentheses around a literal.
true ? (true): false
       ^^^^^^

1 file inspected, 1 offense detected, 1 offense corrected
cosmiccrisp:rubocop asherkach$ cat test.rb 
true ? true: false
```

**Comment by asherkach** [comment]
Another example, showing the issue is widespread (not just ternaries).
```
cosmiccrisp:rubocop asherkach$ cat test.rb 
(true)&& false
cosmiccrisp:rubocop asherkach$ bundle exec rubocop test.rb --only Style/RedundantParentheses --auto-correct
Inspecting 1 file
C

Offenses:

test.rb:1:1: C: [Corrected] Style/RedundantParentheses: Don't use parentheses around a literal.
(true)&& false
^^^^^^

1 file inspected, 1 offense detected, 1 offense corrected
cosmiccrisp:rubocop asherkach$ cat test.rb 
true&& false
```

**Comment by asherkach** [comment]
👍
