### PR TITLE
[Fix #5224] Solve false EmptyLinesAroundArgument offenses

### LINKED ISSUE #5224: False positive for the Layout/EmptyLinesAroundArguments cop
Use this file and run latest rubocop against it:
https://github.com/airbrake/airbrake/blob/v7.1.0/lib/airbrake/capistrano/capistrano2.rb

--------

## Expected behavior

No offence of the `Layout/EmptyLinesAroundArguments` cop

## Actual behavior

```
lib/airbrake/capistrano/capistrano2.rb:4:1: C: Layout/EmptyLinesAroundArguments: Empty line detected around arguments.
    # rubocop:disable Metrics/AbcSize
^
lib/airbrake/capistrano/capistrano2.rb:7:1: C: Layout/EmptyLinesAroundArguments: Empty line detected around arguments.
        after 'deploy', 'airbrake:deploy'
^
```

The offending lines are actually L18 & L21. I believe it's wrong to force me to format my strings how I want.

## RuboCop version

```
$ rubocop -V
0.52.0 (using Parser 2.4.0.2, running on ruby 2.4.2 x86_64-darwin16)
```

### PR DESCRIPTION
**Pull request by garettarrowood**
This resolves all the odd bugs reported in #5229 & #5224 .

The problems can be boiled down to 2 things.

1. This line of code, `lines = source_lines(node).map.with_index(1).to_a`, was attaching lines to each string of source code in the `send` starting with `1`.  Then this arbitrary line number was getting passed to `range = source_range(processed_source.buffer, line, 0)` and thus grabbing an entirely wrong line to report an offense/autocorrect.

The reason we didn't see this in the tests is that every example, every `processed_source`, started on line 1. I was blind to the issue.

[This test](https://github.com/bbatsov/rubocop/pull/5231/files#diff-569b9b5f892ab8676c337e5048b56ebbR67) has been added to verify the issue is now resolved.

2. Even with reporting wrong line numbers, this cop was also grabbing too many lines of code.

Grabbing the source based on the start and stop of the `send` node itself meant the range included all the previous methods it was chained to. [This `first_line(node)` method](https://github.com/bbatsov/rubocop/pull/5231/files#diff-569b9b5f892ab8676c337e5048b56ebbR67) checks if the `send` has a receiver. If so, it starts the check at that last of the receiver. [`last_line(node`)](https://github.com/bbatsov/rubocop/pull/5231/files#diff-569b9b5f892ab8676c337e5048b56ebbR67) reports an earlier end line if the last/only arg is a block.

This bugfix picked up 2 offenses in rubocop that were missed before. Happy to see that the lines were reported accurately :).

```
Offenses:

spec/rubocop/cop/layout/indent_array_spec.rb:301:1: C: Layout/EmptyLinesAroundArguments: Empty line detected around arguments.
spec/rubocop/cop/layout/indent_hash_spec.rb:376:1: C: Layout/EmptyLinesAroundArguments: Empty line detected around arguments.

1071 files inspected, 2 offenses detected
```

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `rake default` or `rake parallel`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by garettarrowood** [comment]
There are now more examples of false positives. When I have time, I will look into a larger rewrite of this Cop. This is WIP.

**Comment by garettarrowood** [comment]
This is ready for review now.

File: spec/rubocop/cop/layout/empty_lines_around_arguments_spec.rb [hunk 1]
```diff
@@ -64,6 +64,29 @@
         .to eq(['Empty line detected around arguments.'])
     end
 
+    it 'on correct lines' do
```
Comment (bbatsov) [inline spec/rubocop/cop/layout/empty_lines_around_arguments_spec.rb]: I think you probably wanted to use `context` here. After it `it` you should normally have some action. I notice the same for the previous example.

Comment (bbatsov) [reply spec/rubocop/cop/layout/empty_lines_around_arguments_spec.rb]: http://www.betterspecs.org/#contexts

Comment (garettarrowood) [reply spec/rubocop/cop/layout/empty_lines_around_arguments_spec.rb]: Thanks! Fixed, and added one more example for good measure.

File: spec/rubocop/cop/layout/empty_lines_around_arguments_spec.rb [hunk 2]
```diff
@@ -80,6 +80,52 @@ def anything; end
       expect(cop.messages)
         .to eq(['Empty line detected around arguments.'])
     end
+
+    context 'on correct lines' do
+      it 'for single offense example' do
```
Comment (bbatsov) [inline spec/rubocop/cop/layout/empty_lines_around_arguments_spec.rb]: All of those should read like sentences - `it does this and that`. :-) Otherwise the RSpec reports look very confusing. You might want to consult other RuboCop spec files.

File: spec/rubocop/cop/layout/empty_lines_around_arguments_spec.rb [hunk 3]
```diff
@@ -121,6 +167,29 @@ def anything; end
       RUBY
       expect(cop.offenses.empty?).to be(true)
     end
+
+    it 'when trailing off of block' do
```
Comment (bbatsov) [inline spec/rubocop/cop/layout/empty_lines_around_arguments_spec.rb]: That should be a context imo - at least it sounds like one.

File: spec/rubocop/cop/layout/empty_lines_around_arguments_spec.rb [hunk 4]
```diff
@@ -121,6 +167,29 @@ def anything; end
...
+            bar
+
+            foo
+          EOT
+        end.join("\n")
+      RUBY
+      expect(cop.offenses.empty?).to be(true)
+    end
+
+    it 'when method has no arguments' do
```
Comment (bbatsov) [inline spec/rubocop/cop/layout/empty_lines_around_arguments_spec.rb]: or reworded to "it 'does not register an offense for a method with no arguments". I hope this makes sense to you.

File: lib/rubocop/cop/layout/empty_lines_around_arguments.rb [hunk 5]
```diff
@@ -56,21 +55,9 @@ def autocorrect(node)
...
-        def source_lines(node)
-          source =
-            if node.arguments.last && node.arguments.last.block_type?
-              source_without_block(node, node.arguments.last)
-            else
-              node.source
-            end
-          source.lines.map { |line| line.delete("\n") }
+          lines = processed_lines(node).map.with_index(first_line(node)).to_a
+          lines.select! { |code, _| code == '' }
```
Comment (bbatsov) [inline lib/rubocop/cop/layout/empty_lines_around_arguments.rb]: `code.empty?` perhaps?

File: spec/rubocop/cop/layout/empty_lines_around_arguments_spec.rb (hunk 4 above)
Comment (garettarrowood) [reply spec/rubocop/cop/layout/empty_lines_around_arguments_spec.rb]: This does make more sense now. Thanks for your persistence!

My mindset with the `context` organization was to reduce text duplication. Dry descriptions I guess? 

This test file looks like this for `--format-documentation` output:

```
RuboCop::Cop::Layout::EmptyLinesAroundArguments
  autocorrects
    when empty line detected at bottom
    when args start on defintion line
    when empty line detected at top
    when empty line detected in the middle
    when multiple empty lines are detected
  does not register offense
    for multiple correctly listed mixed args
    for one line methods
    for correctly listed args starting on defintion line
    when trailing off of block
    when method has no arguments
    when passed block argument with empty line
  registers offense
    when multiple empty lines are detected
    when empty line detected at top
    when args start on defintion line
    when empty line detected at bottom
    when empty line detected in the middle
    when empty line before a block argument
    on correct lines
      for single offense example
      for multi-offense example
```

But this definitely conflicts with the principles in the Better Specs guide. And it also breaks from the standard we've established in the rest of the test suite. So a change is definitely warranted.  

I'll have an edit up shortly :).

Comment (garettarrowood) [reply spec/rubocop/cop/layout/empty_lines_around_arguments_spec.rb]: Here is the new look (randomized like the one above):

```
RuboCop::Cop::Layout::EmptyLinesAroundArguments
  when no extra lines
    accepts listed args starting on defintion line
    accepts block argument with empty line
    accepts multiple listed mixed args
    accpets one line methods
    accepts method with argument that trails off block
    accepts method with no arguments that trails off block
  when extra lines
    registers offense on correct line for single offense example
    registers offense for empty line between args
    registers offense when args start on definition line
    registers offense for empty line after arg
    registers offenses when multiple empty lines are detected
    autocorrects empty line detected at top
    registers offense on correct lines for multi-offense example
    registers offense for empty line in-between one arg
    registers offense when empty line between normal arg & block arg
    autocorrects multiple empty lines
    registers offense for empty line before arg
    autocorrects empty line in-between one arg
    autocorrects empty line detected at bottom
    autocorrects empty line detected in the middle
    autocorrects args that start on definition line
```

Comment (bbatsov) [reply spec/rubocop/cop/layout/empty_lines_around_arguments_spec.rb]: 👍

**Comment by radar** [comment]
Thanks for the fix @garettarrowood! I came across the same issue today and I am glad that you have taken the time to fix it.
