### PR TITLE
[Fix #4322] Fix Style/MultilineMemoization autocorrection

### LINKED ISSUE #4322: Style/MultilineMemoization autocorrects to invalid ruby
## Expected behavior

Style/MultilineMemoization auto-corrects when the `(` are not on new lines by replacing them with `begin` 

## Actual behavior

If `(` is not on its own line then a new line should be added.  

## Steps to reproduce the problem

Autocorreting
```ruby
class MyClass
  def my_method
    @my_method ||= (true ||
                    true ||
                    false)
  end
end
```
becomes
```ruby
class MyClass
  def my_method
    @my_method ||= begintrue ||
                    true ||
                    falseend
  end
end
```

## RuboCop version

```
$ rubocop -V
0.43.0 (using Parser 2.4.0.0, running on ruby 2.2.4 x86_64-linux)
```

### PR DESCRIPTION
**Pull request by dpostorivo**
Fixes the issue seen in [#4322](https://github.com/bbatsov/rubocop/issues/4322) where the auto correct for Style/MultilineMemoization cop would break code. Specifically this where:

```
foo ||= (bar ||
            baz)
```
becomes:
```
foo ||= beginbar ||
            bazend

```

and now corrects to:

```
foo ||= begin
             bar ||
             baz
        end
```

This is the first autocorrect I've done so far so let me know if anything needs to be done differently or more test cases are needed.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Used the same coding conventions as the rest of the project.
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] All tests(`rake spec`) are passing.
* [x] The new code doesn't generate RuboCop offenses that are checked by `rake internal_investigation`.
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [ ] Updated cop documentation with `rake generate_cops_documentation` (required only when you've added a new cop or changed the configuration/documentation of an existing cop).

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: spec/rubocop/cop/style/multiline_memoization_spec.rb [hunk 1]
```diff
@@ -121,6 +121,18 @@
...
+          it_behaves_like 'code with offense',
+                          <<-RUBY.strip_indent,
+                            foo ||= (bar ||
+                                     baz)
+                          RUBY
+                          <<-RUBY.strip_indent
+                             foo ||= begin
+                                       bar ||
+                                      baz
+                                     end
```
Comment (bbatsov) [inline spec/rubocop/cop/style/multiline_memoization_spec.rb]: The identation here seems incorrect. I guess the assumption is that another cop is supposed to fix it, right?

Comment (dpostorivo) [reply spec/rubocop/cop/style/multiline_memoization_spec.rb]: Yeah, this was the best I could get it without having to check the indentation of each line.

Comment (bbatsov) [reply spec/rubocop/cop/style/multiline_memoization_spec.rb]: Got it.
