### PR TITLE
[Fix #5226] Suppress false positives for `Rails/RedundantReceiverInWithOptions`

### LINKED ISSUE #5226: Rails/RedundantReceiverInWithOptions crashes rubocop for some inputs
## Expected behavior

Should not abort with an error, possibly auto correct the code.

## Actual behavior

The following exception is thrown:

```
$ rubocop -a --only Rails/RedundantReceiverInWithOptions example.rb
Inspecting 1 file


0 files inspected, no offenses detected
undefined method `loc' for :to:Symbol
/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.0/lib/rubocop/cop/rails/redundant_receiver_in_with_options.rb:69:in `block_argument_range'
/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.0/lib/rubocop/cop/rails/redundant_receiver_in_with_options.rb:62:in `block in autocorrect'
/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.0/lib/rubocop/cop/corrector.rb:56:in `block (2 levels) in rewrite'
/2.4.2/lib/ruby/gems/2.4.0/gems/parser-2.4.0.2/lib/parser/source/rewriter.rb:198:in `transaction'
/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.0/lib/rubocop/cop/corrector.rb:55:in `block in rewrite'
/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.0/lib/rubocop/cop/corrector.rb:53:in `each'
/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.0/lib/rubocop/cop/corrector.rb:53:in `rewrite'
/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.0/lib/rubocop/cop/team.rb:126:in `autocorrect_all_cops'
/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.0/lib/rubocop/cop/team.rb:70:in `autocorrect'
/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.0/lib/rubocop/cop/team.rb:98:in `block in offenses'
/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.0/lib/rubocop/cop/team.rb:115:in `investigate'
/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.0/lib/rubocop/cop/team.rb:94:in `offenses'
/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.0/lib/rubocop/cop/team.rb:44:in `inspect_file'
/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.0/lib/rubocop/runner.rb:258:in `inspect_file'
/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.0/lib/rubocop/runner.rb:205:in `block in do_inspection_loop'
/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.0/lib/rubocop/runner.rb:237:in `block in iterate_until_no_changes'
/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.0/lib/rubocop/runner.rb:230:in `loop'
/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.0/lib/rubocop/runner.rb:230:in `iterate_until_no_changes'
/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.0/lib/rubocop/runner.rb:201:in `do_inspection_loop'
/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.0/lib/rubocop/runner.rb:111:in `block in file_offenses'
/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.0/lib/rubocop/runner.rb:121:in `file_offense_cache'
/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.0/lib/rubocop/runner.rb:109:in `file_offenses'
/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.0/lib/rubocop/runner.rb:100:in `process_file'
/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.0/lib/rubocop/runner.rb:78:in `block in each_inspected_file'
/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.0/lib/rubocop/runner.rb:75:in `each'
/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.0/lib/rubocop/runner.rb:75:in `reduce'
/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.0/lib/rubocop/runner.rb:75:in `each_inspected_file'
/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.0/lib/rubocop/runner.rb:67:in `inspect_files'
/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.0/lib/rubocop/runner.rb:39:in `run'
/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.0/lib/rubocop/cli.rb:128:in `execute_runner'
/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.0/lib/rubocop/cli.rb:60:in `execute_runners'
/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.0/lib/rubocop/cli.rb:31:in `run'
/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.0/bin/rubocop:13:in `block in <top (required)>'
/2.4.2/lib/ruby/2.4.0/benchmark.rb:308:in `realtime'
/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.52.0/bin/rubocop:12:in `<top (required)>'
/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:286:in `load'
/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:286:in `block in load'
/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:286:in `load'
/dev/rubocop-issue/bin/rubocop:21:in `<top (required)>'
/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:286:in `load'
/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:286:in `block in load'
/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:286:in `load'
/2.4.2/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/command_wrapper.rb:40:in `call'
/2.4.2/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/application.rb:201:in `block in serve'
/2.4.2/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/application.rb:171:in `fork'
/2.4.2/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/application.rb:171:in `serve'
/2.4.2/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/application.rb:141:in `block in run'
/2.4.2/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/application.rb:135:in `loop'
/2.4.2/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/application.rb:135:in `run'
/2.4.2/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/application/boot.rb:19:in `<top (required)>'
/2.4.2/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/2.4.2/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:59:in `require'
-e:1:in `<main>'
```

## Steps to reproduce the problem

Run `rubocop -a --only Rails/RedundantReceiverInWithOptions example.rb`

```
# example.rb
require 'rails_helper'

RSpec.describe 'Example pages', type: :request do
  it 'checks things' do
    with_options scope: 'activerecord.attributes' do |i18n|
      expect(subject).to have_field i18n.t('foo.bar')
    end
  end
end
```

## RuboCop version

```
$ rubocop -V
0.52.0 (using Parser 2.4.0.2, running on ruby 2.4.2 x86_64-darwin16)
```

### PR DESCRIPTION
**Pull request by wata727**
Fixes #5226

For example, if it has another receiver in `with_options`, should not omit the receiver of argument.

```ruby
require 'active_support'
require 'active_support/core_ext'

def self.options(opts = {})
  opts
end

with_options hello: :world do |merger|
  self.class     # => Object
  merger.options # => {:hello=>:world}
  options        # => {}
end

with_options hello: :world do
  self.class # => ActiveSupport::OptionMerger
  options    # => {:hello=>:world}
end
```

Therefore, all method calls in `with_options` must check for the same receiver.

Also, this Cop can get the position of the argument regardless of the position of receivers for auto-correct.

-----------------

Before submitting the PR make sure the following are checked:

* [ ] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `rake default` or `rake parallel`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/rails/redundant_receiver_in_with_options.rb [hunk 1]
```diff
@@ -66,7 +70,8 @@ def autocorrect(node)
         private
 
         def block_argument_range(node)
-          block_argument = node.parent.parent.children[1].loc.expression
+          block_node = node.each_ancestor(:block).first
+          block_argument = block_node.children[1].loc.expression
```
Comment (garettarrowood) [inline lib/rubocop/cop/rails/redundant_receiver_in_with_options.rb]: Instead of `.loc.expression`, I believe you abbreviate the chain by using  `.source_range`.

File: lib/rubocop/cop/rails/redundant_receiver_in_with_options.rb [hunk 2]
```diff
@@ -38,19 +38,23 @@ class RedundantReceiverInWithOptions < Cop
...
-          with_options?(node) do
-            assoc_has_redundant_receiver(node).each do |assoc|
-              add_offense(assoc, location: assoc.receiver.loc.expression)
+          with_options?(node) do |arg, body|
+            send_nodes = all_send_nodes_in(body)
+
+            if send_nodes.all? { |n| same_value?(arg, n.receiver) }
+              send_nodes.each do |send_node|
+                receiver = send_node.receiver
+                add_offense(send_node, location: receiver.loc.expression)
```
Comment (garettarrowood) [inline lib/rubocop/cop/rails/redundant_receiver_in_with_options.rb]: Same thing here.

**Comment by garettarrowood** [comment]
Nice work! Thanks sorting this out.

Could you include an additional example for this Cop as well? Your [test here](https://github.com/bbatsov/rubocop/pull/5268/files#diff-3c66cc2a60077e409097d6a570169aa8R85) looks like it'd be a great good/bad example.

**Comment by wata727** [comment]
Oh, sorry. I noticed some problems left in the pull request.

## false negative
The example below is inside the scope of this Cop, but it is not pointed out that it is the current implementation.

```ruby
with_options hello: :world do |merger|
  merger.options
  merger.yield_option do |option|
    option.options
  end
end
```

It is because it becomes another scope in yield block.

```ruby
require 'active_support'
require 'active_support/core_ext'

def self.options(opts = {})
  opts
end

class Option
  def options(opts = {})
    opts
  end
end

def self.yield_option(opts = {})
  yield Option.new
end

with_options hello: :world do |merger|
  merger.options                  # => {:hello=>:world}
  merger.yield_option do |option|
    option.options                # => {}
  end
end

with_options hello: :world do
  options                         # => {:hello=>:world}
  yield_option do |option|
    option.options                # => {}
  end
end
```

## incorrect auto-correct

The following code is a victim of incorrect auto-correct.

```ruby
with_options hello: :world do |merger|
  merger.with_database do |db|
    merger.initialize(db)
  end
end
```

```ruby
with_options hello: :world do |merger|
  with_database do
    initialize(db) # Where did `db` go?
  end
end
```

**Comment by wata727** [comment]
As a result of thinking, I thought it was difficult to avoid this false negative...
If there is a block in `with_options`, it is difficult to determine if the receiver is redundant within that block. 

For example, the following receivers are not redundant:

```ruby
with_options hello: :world do |merger|
  merger.options
  merger.yield_option do |option|
    options
  end
end
```

```ruby
require 'active_support'
require 'active_support/core_ext'

def self.options(opts = {})
  opts
end

def self.yield_option(opts = {})
  yield self
end

with_options hello: :world do |merger|
  merger.options                  # => {:hello=>:world}
  merger.yield_option do |option|
    options                       # => {}
  end
end

with_options hello: :world do
  options                         # => {:hello=>:world}
  yield_option do |option|
    options                       # => {:hello=>:world}
  end
end
```

Considering such an example, when including a block, I chose to make it outside the scope of this Cop. wdyt?

File: lib/rubocop/cop/rails/redundant_receiver_in_with_options.rb [hunk 3]
```diff
@@ -26,6 +30,31 @@ module Rails
...
+      #
+      #   # good
+      #   with_options options: false do
+      #     invoke(something)
+      #   end
+      #
+      #   # good
+      #   client = Client.new
+      #   with_options options: false do |merger|
+      #     clinent.invoke(merger.something, something)
```
Comment (garettarrowood) [inline lib/rubocop/cop/rails/redundant_receiver_in_with_options.rb]: Nit: Spelling for client

File: lib/rubocop/cop/rails/redundant_receiver_in_with_options.rb [hunk 4]
```diff
@@ -26,6 +30,31 @@ module Rails
...
+      #   end
+      #
+      #   # maybe good
+      #   with_options options: false do |merger|
+      #     merger.invoke do
+      #       merge.call
```
Comment (garettarrowood) [inline lib/rubocop/cop/rails/redundant_receiver_in_with_options.rb]: Maybe use something other than `merge` here?  A name/obj that couldn't be confused for the `merger` obj.

**Comment by garettarrowood** [comment]
Nice work sorting this out! I agree with you assessment. This seems like a very difficult scenario to account for all possibilities inside a `with_options` block, and these changes are a large improvement.
