### PR TITLE
[Fix #1647] Skip Style/SpaceAroundBlockParameters when lambda has no argument

### LINKED ISSUE #1647: Style/StyleAroundBlockParameters failing
output of rubocop:

```
~/yast/yast2> rubocop.ruby2.1 -d /home/jreidinger/yast/yast2/library/control/testsuite/tests/restore.rb

Inspecting 1 file
Scanning /home/jreidinger/yast/yast2/library/control/testsuite/tests/restore.rb
For /home/jreidinger/yast/yast2/library/control/testsuite/tests: configuration from /home/jreidinger/yast/yast2/.rubocop.yml
Inheriting configuration from /usr/share/YaST2/data/devtools/data/rubocop_yast_style.yml
Default configuration from /usr/lib64/ruby/gems/2.1.0/gems/rubocop-0.29.0/config/default.yml
Inheriting configuration from /usr/lib64/ruby/gems/2.1.0/gems/rubocop-0.29.0/config/enabled.yml
Inheriting configuration from /usr/lib64/ruby/gems/2.1.0/gems/rubocop-0.29.0/config/disabled.yml
An error occurred while Style/SpaceAroundBlockParameters cop was inspecting /home/jreidinger/yast/yast2/library/control/testsuite/tests/restore.rb.
undefined method `loc' for nil:NilClass
/usr/lib64/ruby/gems/2.1.0/gems/rubocop-0.29.0/lib/rubocop/cop/style/space_around_block_parameters.rb:40:in `check_inside_pipes'
/usr/lib64/ruby/gems/2.1.0/gems/rubocop-0.29.0/lib/rubocop/cop/style/space_around_block_parameters.rb:23:in `on_block'
(eval):5:in `block (2 levels) in on_block'
/usr/lib64/ruby/gems/2.1.0/gems/rubocop-0.29.0/lib/rubocop/cop/commissioner.rb:92:in `with_cop_error_handling'
(eval):4:in `block in on_block'
(eval):2:in `each'
(eval):2:in `on_block'
/usr/lib64/ruby/gems/2.1.0/gems/ast-2.0.0/lib/ast/processor.rb:239:in `process'
/usr/lib64/ruby/gems/2.1.0/gems/ast-2.0.0/lib/ast/processor.rb:255:in `block in process_all'
/usr/lib64/ruby/gems/2.1.0/gems/ast-2.0.0/lib/ast/processor.rb:254:in `map'
/usr/lib64/ruby/gems/2.1.0/gems/ast-2.0.0/lib/ast/processor.rb:254:in `process_all'
/usr/lib64/ruby/gems/2.1.0/gems/parser-2.2.0.2/lib/parser/ast/processor.rb:142:in `on_send'
(eval):9:in `on_send'
/usr/lib64/ruby/gems/2.1.0/gems/ast-2.0.0/lib/ast/processor.rb:239:in `process'
/usr/lib64/ruby/gems/2.1.0/gems/ast-2.0.0/lib/ast/processor.rb:255:in `block in process_all'
/usr/lib64/ruby/gems/2.1.0/gems/ast-2.0.0/lib/ast/processor.rb:254:in `map'
/usr/lib64/ruby/gems/2.1.0/gems/ast-2.0.0/lib/ast/processor.rb:254:in `process_all'
/usr/lib64/ruby/gems/2.1.0/gems/parser-2.2.0.2/lib/parser/ast/processor.rb:9:in `process_regular_node'
(eval):9:in `on_begin'
/usr/lib64/ruby/gems/2.1.0/gems/ast-2.0.0/lib/ast/processor.rb:239:in `process'
/usr/lib64/ruby/gems/2.1.0/gems/parser-2.2.0.2/lib/parser/ast/processor.rb:121:in `on_def'
(eval):9:in `on_def'
/usr/lib64/ruby/gems/2.1.0/gems/ast-2.0.0/lib/ast/processor.rb:239:in `process'
/usr/lib64/ruby/gems/2.1.0/gems/ast-2.0.0/lib/ast/processor.rb:255:in `block in process_all'
/usr/lib64/ruby/gems/2.1.0/gems/ast-2.0.0/lib/ast/processor.rb:254:in `map'
/usr/lib64/ruby/gems/2.1.0/gems/ast-2.0.0/lib/ast/processor.rb:254:in `process_all'
/usr/lib64/ruby/gems/2.1.0/gems/parser-2.2.0.2/lib/parser/ast/processor.rb:9:in `process_regular_node'
(eval):9:in `on_class'
/usr/lib64/ruby/gems/2.1.0/gems/ast-2.0.0/lib/ast/processor.rb:239:in `process'
/usr/lib64/ruby/gems/2.1.0/gems/ast-2.0.0/lib/ast/processor.rb:255:in `block in process_all'
/usr/lib64/ruby/gems/2.1.0/gems/ast-2.0.0/lib/ast/processor.rb:254:in `map'
/usr/lib64/ruby/gems/2.1.0/gems/ast-2.0.0/lib/ast/processor.rb:254:in `process_all'
/usr/lib64/ruby/gems/2.1.0/gems/parser-2.2.0.2/lib/parser/ast/processor.rb:9:in `process_regular_node'
(eval):9:in `on_module'
/usr/lib64/ruby/gems/2.1.0/gems/ast-2.0.0/lib/ast/processor.rb:239:in `process'
/usr/lib64/ruby/gems/2.1.0/gems/ast-2.0.0/lib/ast/processor.rb:255:in `block in process_all'
/usr/lib64/ruby/gems/2.1.0/gems/ast-2.0.0/lib/ast/processor.rb:254:in `map'
/usr/lib64/ruby/gems/2.1.0/gems/ast-2.0.0/lib/ast/processor.rb:254:in `process_all'
/usr/lib64/ruby/gems/2.1.0/gems/parser-2.2.0.2/lib/parser/ast/processor.rb:9:in `process_regular_node'
(eval):9:in `on_begin'
/usr/lib64/ruby/gems/2.1.0/gems/ast-2.0.0/lib/ast/processor.rb:239:in `process'
/usr/lib64/ruby/gems/2.1.0/gems/rubocop-0.29.0/lib/rubocop/cop/commissioner.rb:52:in `investigate'
/usr/lib64/ruby/gems/2.1.0/gems/rubocop-0.29.0/lib/rubocop/cop/team.rb:33:in `inspect_file'
/usr/lib64/ruby/gems/2.1.0/gems/rubocop-0.29.0/lib/rubocop/runner.rb:126:in `inspect_file'
/usr/lib64/ruby/gems/2.1.0/gems/rubocop-0.29.0/lib/rubocop/runner.rb:97:in `block in do_inspection_loop'
/usr/lib64/ruby/gems/2.1.0/gems/rubocop-0.29.0/lib/rubocop/runner.rb:91:in `loop'
/usr/lib64/ruby/gems/2.1.0/gems/rubocop-0.29.0/lib/rubocop/runner.rb:91:in `do_inspection_loop'
/usr/lib64/ruby/gems/2.1.0/gems/rubocop-0.29.0/lib/rubocop/runner.rb:69:in `process_file'
/usr/lib64/ruby/gems/2.1.0/gems/rubocop-0.29.0/lib/rubocop/runner.rb:38:in `block in run'
/usr/lib64/ruby/gems/2.1.0/gems/rubocop-0.29.0/lib/rubocop/runner.rb:36:in `each'
/usr/lib64/ruby/gems/2.1.0/gems/rubocop-0.29.0/lib/rubocop/runner.rb:36:in `run'
/usr/lib64/ruby/gems/2.1.0/gems/rubocop-0.29.0/lib/rubocop/cli.rb:24:in `run'
/usr/lib64/ruby/gems/2.1.0/gems/rubocop-0.29.0/bin/rubocop:13:in `block in <top (required)>'
/usr/lib64/ruby/2.1.0/benchmark.rb:294:in `realtime'
/usr/lib64/ruby/gems/2.1.0/gems/rubocop-0.29.0/bin/rubocop:12:in `<top (required)>'
/usr/bin/rubocop.ruby2.1:23:in `load'
/usr/bin/rubocop.ruby2.1:23:in `<main>'
.

1 file inspected, no offenses detected

1 error occurred:
An error occurred while Style/SpaceAroundBlockParameters cop was inspecting /home/jreidinger/yast/yast2/library/control/testsuite/tests/restore.rb.
Errors are usually caused by RuboCop bugs.
Please, report your problems to RuboCop's issue tracker.
Mention the following information in the issue report:
0.29.0 (using Parser 2.2.0.2, running on ruby 2.1.5 x86_64-linux-gnu)
Finished in 0.04652044 seconds
```

content of file on which it failed:
```
module Yast
  class RestoreClient < Client
    def main
      Yast.include self, "testsuite.rb"
      Yast.import "ProductFeatures"

      @READ = {
        "product" => {
          "features" => {
            "USE_DESKTOP_SCHEDULER"           => "0",
            "ENABLE_AUTOLOGIN"                => "yes",
            "EVMS_CONFIG"                     => "0",
            "IO_SCHEDULER"                    => "cfg",
            "UI_MODE"                         => "expert",
            "INCOMPLETE_TRANSLATION_TRESHOLD" => "95"
          }
        }
      }

      TEST(->() { ProductFeatures.GetStringFeature("globals", "ui_mode") }, [
        @READ
      ], 0)
      TEST(lambda do
        ProductFeatures.GetStringFeature("globals", "enable_autologin")
      end, [
        @READ
      ], 0)
      TEST(lambda do
        ProductFeatures.GetBooleanFeature("globals", "enable_autologin")
      end, [
        @READ
      ], 0)
      TEST(lambda do
        ProductFeatures.GetIntegerFeature(
          "globals",
          "incomplete_translation_treshold"
        )
      end, [
        @READ
      ], 95)

      nil
    end
  end
end
```

We hit this issue on much more files, but this one is quite small

### PR DESCRIPTION
**Pull request by eitoball**
Style/SpaceAroundBlockParameters cop raises exception when lambda has no argument like:

```ruby
->() { puts "a" }
```

This PR should fix this problem.

---
Rubocop Version: 0.29.0 (using Parser 2.2.0.2, running on ruby 2.1.5 x86_64-darwin14.0)

### CODE REVIEW

File: spec/rubocop/cop/style/space_around_block_parameters_spec.rb [hunk 1]
```diff
@@ -10,6 +10,11 @@
       inspect_source(cop, '{}.each {}')
       expect(cop.offenses).to be_empty
     end
+
+    it 'skips when lambda without args' do
```
Comment (bbatsov) [inline spec/rubocop/cop/style/space_around_block_parameters_spec.rb]: Change this to 'skips lambda without args'.

**Comment by bbatsov** [comment]
Mention in the commit and the changelog that this fixes #1647. Please, follow our convetions for the format of the commit messages.

File: spec/rubocop/cop/style/space_around_block_parameters_spec.rb (hunk 1 above)
Comment (eitoball) [inline spec/rubocop/cop/style/space_around_block_parameters_spec.rb]: Changed. Thank you for reviewing.

**Comment by eitoball** [comment]
I was not aware that there was an issue. Anyway, I changed commit message and added changelog entry. Thank you.

**Comment by bbatsov** [comment]
:+1: Thanks!
