### PR TITLE
[Fix #5250] Fix incorrect autocorrection for `Rails/Presence`

### LINKED ISSUE #5250: Autocorrect for Rails/Presence corrupts code when there's an `elsif` block
## Expected behavior

I would expect rubocop to leave this code unchanged

## Actual behavior

The autocorrect is corrupting the surrounding code, by misplacing the `elsif` clause

## Steps to reproduce the problem

```
$ cat test.rb
```
```ruby
class TestModel < ActiveRecord::Base
  def foo?
    attr1.present? || attr2.present?
  end

  def testcase
    if attr3.present?
      attr3
    elsif foo?
      "something"
    else
      raise "Invalid"
    end
  end
end
```

```
$ rubocop -a --only "Rails/Presence" ./test.rb
Inspecting 1 file
E

Offenses:

test.rb:9:5: C: [Corrected] Rails/Presence: Use attr3.presence || elsif foo?
      "something"
    else
      raise "Invalid" instead of if attr3.present?
      attr3
    elsif foo?
      "something"
    else
      raise "Invalid"
    end.
    if attr3.present? ...
    ^^^^^^^^^^^^^^^^^
test.rb:9:23: E: Lint/Syntax: unexpected token kELSIF
(Using Ruby 2.4 parser; configure using TargetRubyVersion parameter, under AllCops)
    attr3.presence || elsif foo?
                      ^^^^^
test.rb:11:5: W: Lint/Syntax: else without rescue is useless
(Using Ruby 2.4 parser; configure using TargetRubyVersion parameter, under AllCops)
    else
    ^^^^

1 file inspected, 3 offenses detected, 1 offense corrected
```

```
$ cat ./test.rb
```
```ruby
class TestModel < ActiveRecord::Base
  def foo?
    attr1.present? || attr2.present?
  end

  def testcase
    attr3.presence || elsif foo?
      "something"
    else
      raise "Invalid"
  end
end
```

## RuboCop version

`0.52.0 (using Parser 2.4.0.2, running on ruby 2.4.2 x86_64-darwin16)`

### PR DESCRIPTION
**Pull request by wata727**
Fixes #5250 

When an else block is multiline, the syntax is broken by autocorrection, so it must be ignored.

**Original**

```ruby
if a.present?
  a
else
  something
  something
  something
end
```

**Auto Fixed**

```ruby
a.presence || something # This is obviously broken... :(
  something
  something
```

Also, note postfix if and postfix rescue. If it applies autocorrection to these, the return value may change.

**Original**

```ruby
if 1.present?
  1
else
  2 if false
end
# => 1
```

**Auto Fixed**

```ruby
1.presence || 2 if false
# => nil
```

Unfortunately, this cop still includes another bug... But this will be fixed in https://github.com/bbatsov/rubocop/pull/5238.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `rake default` or `rake parallel`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: spec/rubocop/cop/rails/presence_spec.rb [hunk 1]
```diff
@@ -50,6 +50,19 @@
...
+    if [1, 2, 3].map { |num| num + 1 }
+                .map { |num| num + 2 }
+                .present?
+      [1, 2, 3].map { |num| num + 1 }.map { |num| num + 2 }
+    else
+      b
+    end
+  RUBY
+    [1, 2, 3].map { |num| num + 1 }
+                .map { |num| num + 2 }.presence || b
```
Comment (wata727) [inline spec/rubocop/cop/rails/presence_spec.rb]: I think this is fixable, but I don't think this is good...

File: lib/rubocop/cop/rails/presence.rb [hunk 2]
```diff
@@ -76,6 +76,8 @@ def on_if(node)
             receiver, other = redundant_negative_receiver_and_other(node)
           end
           return unless receiver
+          return if other.multiline? || other.if_type? || other.rescue_type?
```
Comment (pocke) [inline lib/rubocop/cop/rails/presence.rb]: Do not use `other.multiline?`. Probably the cop breaks on multiple statement on one line. For example:

```ruby
if a.present?
  a
else
  something; something; something
end
```


We can check `begin` type for other node instead.

```ruby
          {
            (if
              (send $_recv :present?)
              _recv
              $!begin
            )
...
```

Because if `if` body has multiple statements, the body is a `begin` node.

```bash
$ ruby-parse -e if cond then foo end
(if
  (send nil :cond)
  (send nil :foo) nil)

$ ruby-parse -e if cond then foo; foo end
(if
  (send nil :cond)
  (begin
    (send nil :foo)
    (send nil :foo)) nil)
```

Comment (pocke) [inline lib/rubocop/cop/rails/presence.rb]: > `other.rescue_type?`

I'm not sure why you add the check, that is for `rescue` type. Can you add a test case(s) for the check? I can't find any test cases.

File: spec/rubocop/cop/rails/presence_spec.rb [hunk 3]
```diff
@@ -67,4 +80,46 @@
...
+      end
+    RUBY
+  end
+
+  it 'does not register an offense when the else block has `rescue` node' do
+    expect_no_offenses(<<-RUBY.strip_indent)
+      if a.present?
+        a
+      else
+        b rescue a
```
Comment (pocke) [inline spec/rubocop/cop/rails/presence_spec.rb]: Also `b while a`?

**Comment by bbatsov** [comment]
This should be rebased on top of `master`.

**Comment by wata727** [comment]
@bbatsov Rebased!
