### PR TITLE
[Fix #4628] Add new NestedPercentLiteral cop

### LINKED ISSUE #4628: Detect Nested percent literals
Detect Nested percent literals
--------
Nesting Percent Literals silently does the wrong thing.   It would be nice for Rubocop to catch this error
## Expected behavior

Emit an offense when a percent literal is used inside of another percent literal

## Actual behavior

No offense is emitted

## Steps to reproduce the problem
```ruby
#! /bin/env ruby
# test_percent_literals.rb
require 'json'

attributes = [
  valid_attributes: %i[name content],
  nested_attributes: %i[name department
    incorrectly_nested_attributes %i[
    name organization etc]]
]

puts JSON.pretty_generate(attributes)
``` 
`rubocop test_percent_literals.rb`

## RuboCop version
```
$ rubocop -V
0.49.1 (using Parser 2.4.0.0, running on ruby 2.4.1 x86_64-linux)
```

### PR DESCRIPTION
**Pull request by asherkach**
Adds the new `NestedPercentLiteral` cop as discussed in #4628.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Used the same coding conventions as the rest of the project.
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] All tests(`rake spec`) are passing.
* [x] The new code doesn't generate RuboCop offenses that are checked by `rake internal_investigation`.
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Updated cop documentation with `rake generate_cops_documentation` (required only when you've added a new cop or changed the configuration/documentation of an existing cop).

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/lint/nested_percent_literal.rb [hunk 1]
```diff
@@ -0,0 +1,51 @@
...
+        end
+
+        private
+
+        # Returns whether node contains any tokens that match a percent literal
+        # invokation.
+        def contains_percent_literals?(node)
+          node.children.any? do |child|
+            literal = child.children.first.to_s
+            REGEXES.any? { |regex| literal.match? regex }
```
Comment (Drenmi) [inline lib/rubocop/cop/lint/nested_percent_literal.rb]: We support running RuboCop on old rubies (2.0.0 and above) which means you can't use newer features like `#match?` in the codebase. 🙂

File: lib/rubocop/cop/lint/nested_percent_literal.rb [hunk 2]
```diff
@@ -0,0 +1,51 @@
...
+        def on_percent_literal(node)
+          add_offense(node) if contains_percent_literals?(node)
+        end
+
+        private
+
+        # Returns whether node contains any tokens that match a percent literal
+        # invokation.
+        def contains_percent_literals?(node)
+          node.children.any? do |child|
```
Comment (Drenmi) [inline lib/rubocop/cop/lint/nested_percent_literal.rb]: Check the `ArrayNode` node extension. There should be a method to check if a node is a percent literal. Then your check can be something like:

```ruby
node.each_child(:array).any? { |child| child.percent_literal? }
```

File: lib/rubocop/cop/lint/nested_percent_literal.rb [hunk 3]
```diff
@@ -0,0 +1,51 @@
...
+          process(node, *PercentLiteral::PERCENT_LITERAL_TYPES)
+        end
+
+        def on_percent_literal(node)
+          add_offense(node) if contains_percent_literals?(node)
+        end
+
+        private
+
+        # Returns whether node contains any tokens that match a percent literal
```
Comment (Drenmi) [inline lib/rubocop/cop/lint/nested_percent_literal.rb]: This comment is probably less descriptive than the method name itself. 😉 I would ✂️ it.

File: lib/rubocop/cop/lint/nested_percent_literal.rb (hunk 1 above)
Comment (asherkach) [reply lib/rubocop/cop/lint/nested_percent_literal.rb]: Yep, I see from the Travis CI failures. Updating to use `String#match` rather than `String#match?`.

File: lib/rubocop/cop/lint/nested_percent_literal.rb (hunk 2 above)
Comment (asherkach) [reply lib/rubocop/cop/lint/nested_percent_literal.rb]: This doesn't seem to work (at the very least, as written, offenses no longer get emitted), presumably because the AST parses the nested percent literals differently (being tokens to the outer nested percent literal). See the TODO in the last test, I think it is related.

File: lib/rubocop/cop/lint/nested_percent_literal.rb (hunk 3 above)
Comment (asherkach) [reply lib/rubocop/cop/lint/nested_percent_literal.rb]: Done.

File: lib/rubocop/cop/lint/nested_percent_literal.rb (hunk 2 above)
Comment (Drenmi) [reply lib/rubocop/cop/lint/nested_percent_literal.rb]: Alas. I forgot the parser does this. Check if there's a `Node#str_content` method though. 🙂

File: lib/rubocop/cop/lint/nested_percent_literal.rb [hunk 4]
```diff
@@ -0,0 +1,49 @@
...
+        def on_percent_literal(node)
+          add_offense(node) if contains_percent_literals?(node)
+        end
+
+        private
+
+        def contains_percent_literals?(node)
+          node.children.any? do |child|
+            literal = child.children.first.to_s
+            REGEXES.any? { |regex| literal.match(regex) }
```
Comment (pocke) [inline lib/rubocop/cop/lint/nested_percent_literal.rb]: This cop  crashes with `%W[\xff]`. 

```bash
$ rubocop --cache false --only NestedPercentLiteral
An error occurred while Lint/NestedPercentLiteral cop was inspecting /tmp/tmp.zzU24B1UWS/test.rb:1:4.
To see the complete backtrace run rubocop -d.

1 error occurred:
An error occurred while Lint/NestedPercentLiteral cop was inspecting /tmp/tmp.zzU24B1UWS/test.rb:1:4.
Errors are usually caused by RuboCop bugs.
Please, report your problems to RuboCop's issue tracker.
Mention the following information in the issue report:
0.49.1 (using Parser 2.4.0.0, running on ruby 2.4.1 x86_64-linux)
Inspecting 1 file
.

1 file inspected, no offenses detected
```


Could you use `scrub` like https://github.com/bbatsov/rubocop/blob/6cc91fc8f0305cff3a3182934cf4b786c7f619dc/lib/rubocop/cop/layout/indent_heredoc.rb#L163

File: lib/rubocop/cop/lint/nested_percent_literal.rb [hunk 5]
```diff
@@ -0,0 +1,49 @@
...
+      #   # The percent literal for nested_attributes is parsed as four tokens,
+      #   # yielding the array [:name, :content, :"%i[incorrectly", :"nested]"].
+      #   attributes = {
+      #     valid_attributes: %i[name content],
+      #     nested_attributes: %i[name content %i[incorrectly nested]]
+      #   }
+      class NestedPercentLiteral < Cop
+        include PercentLiteral
+
+        MSG = 'Do not nest percent literals.'.freeze
```
Comment (pocke) [inline lib/rubocop/cop/lint/nested_percent_literal.rb]: [IMO] I think this message is not good, this seems to mention to style problems. 
Users need more descriptive message.
For example:

https://github.com/bbatsov/rubocop/blob/6cc91fc8f0305cff3a3182934cf4b786c7f619dc/lib/rubocop/cop/lint/percent_string_array.rb#L30-L31

File: spec/rubocop/cop/lint/nested_percent_literal_spec.rb [hunk 6]
```diff
@@ -0,0 +1,48 @@
+# frozen_string_literal: true
+
+describe RuboCop::Cop::Lint::NestedPercentLiteral do
+  subject(:cop) { described_class.new }
+
+  let(:message) { 'Do not nest percent literals.' }
+
+  def expect_offense(source)
```
Comment (bbatsov) [inline spec/rubocop/cop/lint/nested_percent_literal_spec.rb]: Why are you defining this instead of using the existing helper?

File: spec/rubocop/cop/lint/nested_percent_literal_spec.rb [hunk 7]
```diff
@@ -0,0 +1,48 @@
...
+    inspect_source(source)
+
+    expect(cop.offenses.map(&:message)).to eq([message])
+    expect(cop.highlights).to eq([source])
+  end
+
+  context 'when using percent literals' do
```
Comment (bbatsov) [inline spec/rubocop/cop/lint/nested_percent_literal_spec.rb]: This context seems rather useless to me.

File: spec/rubocop/cop/lint/nested_percent_literal_spec.rb (hunk 6 above)
Comment (asherkach) [reply spec/rubocop/cop/lint/nested_percent_literal_spec.rb]: Following the pattern [here](https://github.com/bbatsov/rubocop/blob/master/spec/rubocop/cop/lint/percent_string_array_spec.rb#L11-L16), it seems useful to define a method so as to not repeat myself throughout this file. Most likely, this should be a more-widely scoped method, though that refactoring seems appropriate for another PR.

File: lib/rubocop/cop/lint/nested_percent_literal.rb (hunk 5 above)
Comment (asherkach) [reply lib/rubocop/cop/lint/nested_percent_literal.rb]: Done (next commit).

File: lib/rubocop/cop/lint/nested_percent_literal.rb (hunk 4 above)
Comment (asherkach) [reply lib/rubocop/cop/lint/nested_percent_literal.rb]: Done (next commit).

File: lib/rubocop/cop/lint/nested_percent_literal.rb (hunk 2 above)
Comment (asherkach) [reply lib/rubocop/cop/lint/nested_percent_literal.rb]: There is. But it isn't clear to me how it makes sense to use it. Converting the tokens into strings, joining them, and reparsing them doesn't seem appropriate. Is this what you were thinking?

File: spec/rubocop/cop/lint/nested_percent_literal_spec.rb (hunk 7 above)
Comment (asherkach) [reply spec/rubocop/cop/lint/nested_percent_literal_spec.rb]: Removed (next commit).

**Comment by asherkach** [comment]
Think I've addressed all feedback, excepting this [comment](https://github.com/bbatsov/rubocop/pull/4712#discussion_r138340471). Let me know what you are thinking in that regard.

**Comment by bbatsov** [comment]
@asherkach This has to be rebased on top of the current master. Sorry for dropping the ball on you - I've been crazy busy.

**Comment by asherkach** [comment]
No worries. PTAL, @bbatsov, my apologies it took so long to get it rebased with tests fixed.
