### PR TITLE
[Fix #5236] Fix false positives for `Rails/InverseOf`

### LINKED ISSUE #5236: Rails/InverseOf false positive
Same as #5235 but for InverseOf.

```ruby
  with_options inverse_of: :user do
    has_many :portfolio_items, through: :portfolios
  end
  has_many :portfolio_items, through: :portfolios, inverse_of: :user
```

=>

```
app/models/user.rb:11:5: C: Rails/InverseOf: Specify an :inverse_of option.
    has_many :portfolio_items, through: :portfolios
    ^^^^^^^^
```

### PR DESCRIPTION
**Pull request by wata727**
Fixes #5236

When using `Object#with_options`, `:inverse_of` works even if doesn't declare it directly in associations.

```ruby
class Blog < ApplicationRecord
  with_options inverse_of: :blog do # good
    has_many :posts, -> { order(published_at: :desc) }
  end
end
```

So if the association is in a block with `with_options`, this Cop check that options.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `rake default` or `rake parallel`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: spec/rubocop/cop/rails/inverse_of_spec.rb [hunk 1]
```diff
@@ -142,4 +142,92 @@ class Picture < ApplicationRecord
       RUBY
     end
   end
+
+  context 'with valid options in `with_options`' do
+    it 'does not register an offense' do
+      expect_no_offenses(<<-RUBY.strip_indent)
+      class Person
```
Comment (koic) [inline spec/rubocop/cop/rails/inverse_of_spec.rb]: I think that it is easier to read indents after heredoc.

```ruby
expect_no_offenses(<<-RUBY.strip_indent)
  class Person
    ...
  end
RUBY
```

Comment (bbatsov) [reply spec/rubocop/cop/rails/inverse_of_spec.rb]: 👍

Comment (wata727) [reply spec/rubocop/cop/rails/inverse_of_spec.rb]: I think so, too. I will also fix indents of other examples.

**Comment by bbatsov** [comment]
👍
