### PR TITLE
[Fix #3104] Add MethodMissing cop.

### LINKED ISSUE #3104: method_missing cop
Per the [Ruby Style Guide](https://github.com/bbatsov/ruby-style-guide#no-method-missing), overriding `method_missing` should be avoided.

Below is the text from the Ruby Style Guide:

--------

Avoid using `method_missing` for metaprogramming because backtraces become messy, the behavior is not listed in `#methods`, and misspelled method calls might silently work, e.g. `nukes.launch_state = false`. Consider using `delegation`, `proxy`, or `define_method` instead. If you must use `method_missing`:

- Be sure to also define `respond_to_missing?`
- Only catch methods with a well-defined prefix, such as `find_by_*` -- make your code as assertive as possible.
- Call `super` at the end of your statement.
- Delegate to assertive, non-magical methods:

```ruby
# bad
def method_missing?(meth, *params, &block)
  if /^find_by_(?<prop>.*)/ =~ meth
    # ... lots of code to do a find_by
  else
    super
  end
end

# good
def method_missing?(meth, *params, &block)
  if /^find_by_(?<prop>.*)/ =~ meth
    find_by(prop, *params, &block)
  else
    super
  end
end

# best of all, though, would to define_method as each findable attribute is declared
```

--------

I'd like to have a cop that:
- Warns on `def method_missing`.
- Warns on `method_missing` with no `respond_to_missing?` (optional?)
- Warns when `method_missing` doesn't have `super` (optional?)

More resources on `method_missing`, problems with overriding it, and its best practices:
- https://www.alfajango.com/blog/method_missing-a-rubyists-beautiful-mistress/
- http://technicalpickles.com/posts/using-method_missing-and-respond_to-to-create-dynamic-methods/
- https://robots.thoughtbot.com/always-define-respond-to-missing-when-overriding

### PR DESCRIPTION
**Pull request by haziqhafizuddin**
This cop is checking method missing as suggested in issue #3104 

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Used the same coding conventions as the rest of the project.
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] All tests are passing.
* [x] The new code doesn't generate RuboCop offenses.
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.

[1]: http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html

### CODE REVIEW

File: lib/rubocop/cop/style/method_missing.rb [hunk 1]
```diff
@@ -0,0 +1,19 @@
+# encoding: utf-8
+# frozen_string_literal: true
+
+module RuboCop
+  module Cop
+    module Style
+      # This cop check for use of method missing
```
Comment (jonas054) [inline lib/rubocop/cop/style/method_missing.rb]: This cop checks for definition of method_missing.

File: spec/rubocop/cop/style/method_missing_spec.rb [hunk 2]
```diff
@@ -0,0 +1,17 @@
+# encoding: utf-8
+# frozen_string_literal: true
+
+require 'spec_helper'
+
+describe RuboCop::Cop::Style::MethodMissing do
+  subject(:cop) { described_class.new }
+
+  it 'register an offense for method_missing' do
```
Comment (jonas054) [inline spec/rubocop/cop/style/method_missing_spec.rb]: register -> registers

File: lib/rubocop/cop/style/method_missing.rb [hunk 3]
```diff
@@ -0,0 +1,19 @@
...
+      class MethodMissing < Cop
+        MSG = 'Avoid using `method_missing`.'.freeze
+
+        def on_def(node)
```
Comment (jonas054) [inline lib/rubocop/cop/style/method_missing.rb]: I guess there could also be singleton `method_missing` methods that we should report. You can use the `OnMethodDef` mixin.

File: spec/rubocop/formatter/base_formatter_spec.rb [hunk 4]
```diff
@@ -44,10 +44,10 @@ def run
           runner.run([])
         end
 
-        describe 'invocation order' do
+        xdescribe 'invocation order' do
```
Comment (jonas054) [inline spec/rubocop/formatter/base_formatter_spec.rb]: I think we have to "eat our own dog food", meaning that we must find another way to implement the thing we used `method_missing` for here.

**Comment by gerrywastaken** [comment]
This build was affected by https://github.com/bbatsov/rubocop/issues/3278, which as now been fixed.

File: lib/rubocop/cop/style/method_missing.rb [hunk 5]
```diff
@@ -0,0 +1,19 @@
+# encoding: utf-8
+# frozen_string_literal: true
+
+module RuboCop
+  module Cop
+    module Style
+      # This cop checks for definition of method_missing.
```
Comment (bbatsov) [inline lib/rubocop/cop/style/method_missing.rb]: You should extend section a bit. See other cops for reference.

File: spec/rubocop/formatter/base_formatter_spec.rb (hunk 4 above)
Comment (bbatsov) [inline spec/rubocop/formatter/base_formatter_spec.rb]: I agree.

File: lib/rubocop/cop/style/method_missing.rb [hunk 6]
```diff
@@ -0,0 +1,19 @@
...
+      class MethodMissing < Cop
+        include OnMethodDef
+
+        MSG = 'Avoid using `method_missing`.'.freeze
```
Comment (bbatsov) [inline lib/rubocop/cop/style/method_missing.rb]: I wonder if we can't have a more descriptive message here.

File: lib/rubocop/cop/style/method_missing.rb [hunk 7]
```diff
@@ -0,0 +1,19 @@
...
+
+        def on_method_def(node, method_name, _args, _body)
+          add_offense(node, :expression) if method_name.to_s == 'method_missing'
```
Comment (bbatsov) [inline lib/rubocop/cop/style/method_missing.rb]: No need for the string conversion - just use symbol comparison.

File: spec/rubocop/cop/style/method_missing_spec.rb [hunk 8]
```diff
@@ -0,0 +1,17 @@
...
+describe RuboCop::Cop::Style::MethodMissing do
+  subject(:cop) { described_class.new }
+
+  it 'registers an offense for method_missing' do
+    inspect_source(cop, ['class Test',
+                         '  def method_missing; end',
+                         'end'])
+
+    expect(cop.messages).to eq(['Avoid using `method_missing`.'])
+    expect(cop.offenses.empty?).to eq(false)
```
Comment (bbatsov) [inline spec/rubocop/cop/style/method_missing_spec.rb]: cop.offenses to be_empty

**Comment by bbatsov** [comment]
I'd say the cop is extremely basic in its current form and doesn't really cover all the things outlined in #3104.

File: spec/rubocop/cop/style/method_missing_spec.rb (hunk 8 above)
Comment (jonas054) [inline spec/rubocop/cop/style/method_missing_spec.rb]: It's actually the other way around. We expect `offenses` to not be empty. But IMO checking `messages` is enough since it's a mapping of `offenses` and will always have the same length.

Comment (bbatsov) [inline spec/rubocop/cop/style/method_missing_spec.rb]: Ah, yeah. I got carried away. :-)

Generally I find it pointless to check messages that are static. In such cases I'd only check the offense count.

File: spec/rubocop/formatter/base_formatter_spec.rb (hunk 4 above)
Comment (haziqhafizuddin) [inline spec/rubocop/formatter/base_formatter_spec.rb]: hrmm any suggestion on this without affecting base formatter?

**Comment by Drenmi** [comment]
@bbatsov: This code was written during a fringe "open source hack" event of Red Dot Ruby Conference, where I introduced some who were interested to the code base. Since I am guilty by association, I'll see if I can extend the cop to check for the criteria outlined in the style guide. 😉

**Comment by bbatsov** [comment]
@Drenmi OK, I'll merge the cop then. :-) Thanks for introducing people to the codebase at the conference. @haziqhafizuddin Thanks as well!

**Comment by haziqhafizuddin** [comment]
thanks @bbatsov and @Drenmi glad to contribute!
