### PR TITLE
[Fix #2546] Handle double rubocop:disable of a cop

### LINKED ISSUE #2546: Extra rubocop:disable makes cop enabled
In #1690, @HaleTom wrote

> I have seen redundant disable comments being flagged. What I don't get is that second one here is not flagged though... and it actually CAUSES a warning???!!!

```ruby
# make rubocop happy
class Passes
  # rubocop:disable Style/ClassVars
  @@class_var = 'no problems here'
end

# make rubocopy sad
class Offensive
  # Removing the next comment line makes for a happy rubocop - why?
  # rubocop:disable Style/ClassVars
  @@class_var = 'broken?'
end
```

### PR DESCRIPTION
**Pull request by jonas054**
When a comment tries to disable a cop that was already disabled by an earlier comment in the same file, we make it into a new disabled range. So the given cop is disabled as would be expected.

The disabled ranges can then be analyzed by `Lint/UnneededDisable` and the second disable will be flagged as unnecessary.

### CODE REVIEW

**Comment by alexdowad** [comment]
Nice!

**Comment by bbatsov** [comment]
Looks good, but has to be rebased.

File: lib/rubocop/cop/lint/unneeded_disable.rb [hunk 1]
```diff
@@ -22,6 +22,16 @@ def check(offenses, cop_disabled_line_ranges, comments)
           disabled_ranges = cop_disabled_line_ranges[COP_NAME] || [0..0]
 
           cop_disabled_line_ranges.each do |cop, line_ranges|
+            line_ranges.each_cons(2) do |a, b|
```
Comment (bbatsov) [inline lib/rubocop/cop/lint/unneeded_disable.rb]: `a` and `b` are not great names. :-)

**Comment by jonas054** [comment]
Rebased and improved argument names.

**Comment by bbatsov** [comment]
:+1:
