### PR TITLE
Only write valid YAML when auto-generating config

### LINKED ISSUE #5281: --auto-gen-config can fail with "Error: empty section found in .rubocop_todo.yml"
When running Rubocop with the `--auto-gen-config` option, the part-built output file `.rubocop_todo.yml` is loaded and checked during the processing of each cop (because the generated excludes are added to any defined manually in `.rubocop.yml` and when `rubocop.yml` is loaded it follows the inheritance down to `.rubocop_todo.yml`).

One [validation check is for an empty section](https://github.com/bbatsov/rubocop/blob/v0.52.0/lib/rubocop/config.rb#L426).

The output file is built up cop-by-cop during this process by writing to it after each cop using [`puts`](https://github.com/bbatsov/rubocop/blob/v0.52.0/lib/rubocop/formatter/disabled_config_formatter.rb#L79). Ruby's caching of these writes means that sometimes only a partial image of the offences is written to the file and this partial image is what is read during the next check.

Occasionally, by coincidence, the end of the buffer is the beginning of a cop section like this:

``` yaml
Style/CaseEquality:
  Exclude:
```

and the empty `Exclude` section causes the validation error

```
Error: empty section Style/CaseEquality found in .rubocop_todo.yml
```

### Possible solutions

1.  Add an `output.flush` after each `output.puts`. This works and is easy to implement but is maybe slows things down a bit.
1.  Do not write `.rubocop_todo.yml` while it's being built. Instead write to a temporary file and rename it after building has finished.
1.  Add a config load option that ignores the part-built todo file.

--------

## Expected behavior

I expect `rubocop --auto-gen-config` to complete successfully.

## Actual behavior

Instead, `rubocop --auto-gen-config` exits with an error status and is truncated at the end of the output buffer last written.

## Steps to reproduce the problem

It's going to be difficult to reproduce this because it depends on the flushing behaviour of Ruby's `IO` class. It happened to me with my repository which is large and contains many offences, but it's private unfortunately.

I'm happy to help reproduce this any way I can

## RuboCop version

```
$ rubocop -V
0.52.0 (using Parser 2.4.0.2, running on ruby 2.2.2 x86_64-darwin16)
```

### PR DESCRIPTION
**Pull request by bquorning**
Fixes #5281.

In `DisabledConfigFormatter#excludes` we may end up reading the very same YAML file that is currently being generated. It is therefore important that we always only write "chunks" of valid YAML to it, so the resulting file itself is always valid YAML.

I am not complete sure under what conditions the error occurs, so I would appreciate any help I could get in writing a test case.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [ ] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `rake default` or `rake parallel`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/formatter/disabled_config_formatter.rb [hunk 1]
```diff
@@ -79,8 +79,13 @@ def output_cop(cop_name, offense_count)
...
+        # To avoid malformed YAML when potentially reading the config in
+        # #excludes, we use an output buffer and append it to the actual output
+        # only when it results in valid YAML.
+        buffer = StringIO.new
+        output_cop_comments(buffer, cfg, cop_name, offense_count)
+        output_cop_config(buffer, cfg, cop_name)
+        output.puts(buffer.string)
       end
 
       def output_cop_comments(output, cfg, cop_name, offense_count)
```
Comment (bquorning) [inline lib/rubocop/formatter/disabled_config_formatter.rb]: Should the parameter (here, and in several methods below) still be called `output`, or should I rename them e.g. `buffer`?

Comment (bbatsov) [reply lib/rubocop/formatter/disabled_config_formatter.rb]: Or `output_buffer`? 😉

Comment (bquorning) [reply lib/rubocop/formatter/disabled_config_formatter.rb]: Done

Comment (bbatsov) [reply lib/rubocop/formatter/disabled_config_formatter.rb]: I don't see any changes.

Comment (bquorning) [reply lib/rubocop/formatter/disabled_config_formatter.rb]: Seems I forgot to push. Sorry.

**Comment by bbatsov** [comment]
Can you rebase on top of `master`?

**Comment by bquorning** [comment]
Rebased

**Comment by dominicsayers** [comment]
👍 Thanks dudes
