### PR TITLE
[Fix #4434] Prevent bad auto-correct in `Style/Alias` for non-literal arguments

### LINKED ISSUE #4434: Rubocop Style/Alias cop breaks code with nonsensical fix when autocorrecting
Rubocop Style/Alias cop breaks working ruby code with nonsensical fix when autocorrecting.

The following working code:

```
# frozen_string_literal: true

# Sample class
class SampleClass
  MY_CONSTANT = 1

  CONSTANT_HASH = {
    MY_CONSTANT => :sample
  }.freeze

  class << self
    def sample?
      (1..100).to_a.sample
    end
    alias_method CONSTANT_HASH[MY_CONSTANT], :'sample?'
  end
end

puts SampleClass.sample?
puts SampleClass.sample
```

Is autocorrected to following broken code:

```
# frozen_string_literal: true

# Sample class
class SampleClass
  MY_CONSTANT = 1

  CONSTANT_HASH = {
    MY_CONSTANT => :sample
  }.freeze

  class << self
    def sample?
      (1..100).to_a.sample
    end
    alias (const nil :CONSTANT_HASH) sample?
  end
end

puts SampleClass.sample?
puts SampleClass.sample
```

When using the following rubocop configuration (`.rubocop.yml` in same directory as source file):

```
AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.4
```

--------

## Expected behavior

Rubocop (when autocorrecting) should not attempt to replace `alias_method` with `alias` when the first argument to `alias_method` is not a literal.

## Actual behavior

Rubocop attempts (when autocorrecting) to replace `alias_method` with `alias` even the first argument to `alias_method` is not a literal. It converts `alias_method CONSTANT_HASH[MY_CONSTANT], :'sample?'` to `alias (const nil :CONSTANT_HASH) sample?` which is not valid code.

## Steps to reproduce the problem

Full command line session (on Windows 10 in Emacs eshell using the Ruby from [RubyInstaller2](https://github.com/oneclick/rubyinstaller2); this should not matter though) shown below to reproduce:

```
~/Projects/TMP $ cat .rubocop.yml 

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.4
~/Projects/TMP $ ruby -v
ruby 2.4.1p111 (2017-03-22 revision 58053) [x64-mingw32]
~/Projects/TMP $ cat alias_rubocop_test_case.rb 
# frozen_string_literal: true

# Sample class
class SampleClass
  MY_CONSTANT = 1

  CONSTANT_HASH = {
    MY_CONSTANT => :sample
  }.freeze

  class << self
    def sample?
      (1..100).to_a.sample
    end
    alias_method CONSTANT_HASH[MY_CONSTANT], :'sample?'
  end
end

puts SampleClass.sample?
puts SampleClass.sample
~/Projects/TMP $ rubocop --version
0.49.0
~/Projects/TMP $ ruby alias_rubocop_test_case.rb 
35
79
~/Projects/TMP $ rubocop -a alias_rubocop_test_case.rb 
Inspecting 1 file
E

Offenses:

alias_rubocop_test_case.rb:15:5: C: [Corrected] Style/Alias: Use alias instead of alias_method in a class body. (https://github.com/bbatsov/ruby-style-guide#alias-method)
    alias_method CONSTANT_HASH[MY_CONSTANT], :'sample?'
    ^^^^^^^^^^^^
alias_rubocop_test_case.rb:15:11: E: unexpected token tLPAREN2
(Using Ruby 2.4 parser; configure using TargetRubyVersion parameter, under AllCops)
    alias (const nil :CONSTANT_HASH) sample?
          ^

1 file inspected, 2 offenses detected, 1 offense corrected
~/Projects/TMP $ cat alias_rubocop_test_case.rb 
# frozen_string_literal: true

# Sample class
class SampleClass
  MY_CONSTANT = 1

  CONSTANT_HASH = {
    MY_CONSTANT => :sample
  }.freeze

  class << self
    def sample?
      (1..100).to_a.sample
    end
    alias (const nil :CONSTANT_HASH) sample?
  end
end

puts SampleClass.sample?
puts SampleClass.sample
~/Projects/TMP $ ruby alias_rubocop_test_case.rb 
alias_rubocop_test_case.rb:15: syntax error, unexpected '('
    alias (const nil :CONSTANT_HASH) samp
           ^
~/Projects/TMP $ 
```

## RuboCop version

```
~/Projects/TMP $ rubocop -V
0.49.0 (using Parser 2.4.0.0, running on ruby 2.4.1 x64-mingw32)
```

### PR DESCRIPTION
**Pull request by Drenmi**
This cop would have a bad auto-correct when configured style is `prefer_alias`, and the originating `#alias_method` has a non-literal argument, e.g.:

```
class Foo
  alias_method :foo, BAR
end
```

This change fixes that, and also adds some examples to the documentation.

-----------------

Before submitting the PR make sure the following are checked:

* [X] Wrote [good commit messages][1].
* [X] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [X] Used the same coding conventions as the rest of the project.
* [X] Feature branch is up-to-date with `master` (if not - rebase it).
* [X] Squashed related commits together.
* [X] Added tests.
* [X] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [X] All tests are passing.
* [X] The new code doesn't generate RuboCop offenses.
* [X] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [ ] Updated cop documentation with `rake generate_cops_documentation` (required only when you've added a new cop or changed the configuration/documentation of an existing cop).

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/style/alias.rb [hunk 1]
```diff
@@ -3,10 +3,30 @@
 module RuboCop
   module Cop
     module Style
-      # This cop finds uses of `alias` where `alias_method` would be more
-      # appropriate (or is simply preferred due to configuration), and vice
-      # versa.
-      # It also finds uses of `alias :symbol` rather than `alias bareword`.
+      # This cop enforces the use of either `#alias` or `#alias_method`
+      # depending on configuration.
+      # It also flags uses of `alias :symbol` rather than `alias bareword`.
```
Comment (Drenmi) [inline lib/rubocop/cop/style/alias.rb]: This check should be a separate cop, IMHO. 🙂

File: CHANGELOG.md [hunk 2]
```diff
@@ -25,6 +25,7 @@
 * [#4420](https://github.com/bbatsov/rubocop/issues/4420): Ensure `Style/EmptyMethod` honours indentation when auto-correcting. ([@drenmi][])
 * [#4442](https://github.com/bbatsov/rubocop/pull/4442): Prevent `Style/WordArray` from breaking on strings that aren't valid UTF-8. ([@pocke][])
 * [#4441](https://github.com/bbatsov/rubocop/pull/4441): Prevent `Layout/SpaceAroundBlockParameters` from breaking on lambda. ([@pocke][])
+* [#4434](https://github.com/bbatsov/rubocop/issues/4434): Prevent bad auto-correct in `Style/Alias` for non-literal arguments. ([@drenmi][])
```
Comment (bbatsov) [inline CHANGELOG.md]: This should be under `master`.

File: lib/rubocop/cop/style/alias.rb (hunk 1 above)
Comment (bbatsov) [inline lib/rubocop/cop/style/alias.rb]: True. Classic feature creep. :-)

File: CHANGELOG.md (hunk 2 above)
Comment (Drenmi) [inline CHANGELOG.md]: Fixed!
