### PR TITLE
[Fix #5261] Fix false positive for `Style/MixinUsage` when using inside module

### LINKED ISSUE #5261: false positive for Style/Mixin
I get a complaint for the following code:

```
module X
  def foo
    include Bar
  end
end
```

"Style/MixinUsage: include is used at the top level. Use inside class or module"

No, it's *not* used at the top level.

```
$ rubocop -v
0.52.0
```

### PR DESCRIPTION
**Pull request by koic**
Fixes #5261.

Correspondence to use case for `include` belonging to module was insufficient. This PR added a reproduction test and fixed it.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `rake default` or `rake parallel`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: spec/rubocop/cop/style/mixin_usage_spec.rb [hunk 1]
```diff
@@ -58,6 +68,28 @@ class C
       RUBY
     end
 
+    it 'registers an offense when using `include` in method definition ' \
```
Comment (bbatsov) [inline spec/rubocop/cop/style/mixin_usage_spec.rb]: does *not* register :-)

File: spec/rubocop/cop/style/mixin_usage_spec.rb [hunk 2]
```diff
@@ -58,6 +68,28 @@ class C
...
+      expect_no_offenses(<<-RUBY.strip_indent)
+        class X
+          def foo
+            include M
+          end
+        end
+      RUBY
+    end
+
+    it 'registers an offense when using `include` in method definition ' \
```
Comment (bbatsov) [inline spec/rubocop/cop/style/mixin_usage_spec.rb]: does *not* register :-)

File: spec/rubocop/cop/style/mixin_usage_spec.rb (hunk 1 above)
Comment (koic) [reply spec/rubocop/cop/style/mixin_usage_spec.rb]: Oops! I fixed it 💦

Comment (koic) [reply spec/rubocop/cop/style/mixin_usage_spec.rb]: There was a slight misunderstanding. This was good with `registers`, the other was not good. https://github.com/bbatsov/rubocop/pull/5272#discussion_r157417483

Thank you for pointing out.

**Comment by buehmann** [comment]
For the record: This PR also seems to fix false positives that we're seeing with 0.52.0 on code like
```ruby
class Foo
  if GlobalConfig.special_logging?
    include LogInstrumentation
  end
end
```
