### PR TITLE
[fix #3445] by special casing setter methods

### LINKED ISSUE #3445: Style/AndOr autocorrect failing for assignment operation
## Steps to reproduce the problem

Given a file `rubocop.rb`:
````ruby
foo.bar = 'baz' and bang
````

Run:
````
rubocop -a rubocop.rb
````

## Expected behavior

Autocorrection for `Style/AndOr` does not break syntax of assignment operations, e.g.:
````ruby
(foo.bar = 'baz') && bang
````

## Actual behavior

Autocorrection for `Style/AndOr` does break syntax of assignment operations:
````ruby
foo.bar(= 'baz') && bang
````

## RuboCop version
```
$ rubocop -V
0.42.0 (using Parser 2.3.1.2, running on ruby 2.3.0 x86_64-linux)
```

### PR DESCRIPTION
**Pull request by mikezter**
Style/AndOr breaks for setter-methods as described in #3445. 

This PR fixes this by adding parens around the method call expression.

### CODE REVIEW

File: lib/rubocop/cop/style/and_or.rb [hunk 1]
```diff
@@ -78,12 +78,21 @@ def autocorrect(node)
         def correct_send(node, corrector)
           receiver, method_name, *args = *node
           return correct_not(node, receiver, corrector) if method_name == :!
+          if method_name.to_s.end_with?('=')
```
Comment (bbatsov) [inline lib/rubocop/cop/style/and_or.rb]: I'd introduce some helper `setter_method?` or something like this here.
