### PR TITLE
[Fix #2729] Fix hash bug in RedundantParentheses

### LINKED ISSUE #2729: False-positive and broken autocorrect in Style/RedundantParentheses
The following code gives "don't use parentheses around a literal":
`assert_equal ({ id: 1 }), some_method_call`

The parentheses here are needed and when autocorrect removes them we're left with a syntax error.

Whether or not this is a false-positive might be up for debate, I imagine some would want to force this literal into a variable declaration because it is pretty ugly, but the autocorrect is definitely broken.

### PR DESCRIPTION
**Pull request by lumeet**
Accept parentheses around a hash literal if it's the first argument in
a method call and the argument list isn't parenthesized. This will
prevent invalid syntax or changed AST after auto-correction.

### CODE REVIEW

File: spec/rubocop/cop/style/redundant_parentheses_spec.rb [hunk 1]
```diff
@@ -143,4 +143,16 @@
     inspect_source(cop, 'if x; y else (1)end')
     expect(cop.offenses).to be_empty
   end
+
+  context 'when a hash literal is the first argument in a method call' do
+    it 'accepts parentheses if the argument list is not parenthesized ' do
+      inspect_source(cop, 'x ({ y: 1 }), z')
```
Comment (bbatsov) [inline spec/rubocop/cop/style/redundant_parentheses_spec.rb]: Not sure if the space after `x` is intentional - probably it's not.

File: lib/rubocop/cop/style/redundant_parentheses.rb [hunk 2]
```diff
@@ -81,6 +87,14 @@ def method_call_with_redundant_parentheses?(node)
 
           args.empty? || parentheses?(send_node) || square_brackets?(send_node)
         end
+
+        def first_argument?(node)
```
Comment (bbatsov) [inline lib/rubocop/cop/style/redundant_parentheses.rb]: I wonder if we're not using a similar method in other cops. Seems generic enough.

File: spec/rubocop/cop/style/redundant_parentheses_spec.rb (hunk 1 above)
Comment (savef) [inline spec/rubocop/cop/style/redundant_parentheses_spec.rb]: It is intentional, this matches the format where this cop used to give an offence, as describe [here](https://github.com/bbatsov/rubocop/issues/2729#issue-129258790).
