### PR TITLE
[Fix #2045] Fix error on class method definition with modifier

### LINKED ISSUE #2045: Style/IndentationWidth fails with private_class_method
Rubocop cop Style/IndentationWidth is failing with private_class_method syntax.

The class to test:
```ruby
class Foo
  private_class_method def self.bar
    'bar'
  end
end
```

Error trace:
```
An error occurred while Style/IndentationWidth cop was inspecting /Users/mseppae/foo.rb.
undefined method `line' for nil:NilClass
/Users/mseppae/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/parser-2.2.2.6/lib/parser/source/map.rb:98:in `line'
/Users/mseppae/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rubocop-0.32.1/lib/rubocop/cop/style/indentation_width.rb:225:in `indentation_to_check?'
/Users/mseppae/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rubocop-0.32.1/lib/rubocop/cop/style/indentation_width.rb:201:in `check_indentation'
/Users/mseppae/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rubocop-0.32.1/lib/rubocop/cop/style/indentation_width.rb:97:in `on_send'
(eval):5:in `block (2 levels) in on_send'
```

System information:
```
Mention the following information in the issue report:
0.32.1 (using Parser 2.2.2.6, running on ruby 2.2.0 x86_64-darwin14)
```

### PR DESCRIPTION
**Pull request by unmanbearpig**
We were assuming that method body is always the third element of a
method definition node

```
_method_name, _args, body = *args.first
```

and here is an example how args.first looks in case of regular methods:
```
(def :test
  (args)
  (send nil :body))
```

but in case of class methods, for example in this code
```
private_class_method def self.bar
```

there is an extra `(self)` element:
```
(defs
  (self) :bar
  (args)
  (send nil :body))
```

So the body becomes the fourth element instead.

Always taking the last element takes care
of the issue.

### CODE REVIEW

File: lib/rubocop/cop/style/indentation_width.rb [hunk 1]
```diff
@@ -85,7 +85,8 @@ def on_send(node)
           return unless modifier_and_def_on_same_line?(receiver, method_name,
                                                        args)
 
-          _method_name, _args, body = *args.first
+          body = args.first.to_a.last
```
Comment (bbatsov) [inline lib/rubocop/cop/style/indentation_width.rb]: Generally, I prefer us to use splatting. You can use `*_, body = *args.first` to achieve the same thing.

Comment (bbatsov) [inline lib/rubocop/cop/style/indentation_width.rb]: Alternatively we can check if the node is `def` or `defs`.

**Comment by unmanbearpig** [comment]
You're right! I completely forgot that I can use splat on the left side of '=' as well.

**Comment by bbatsov** [comment]
Looks good. I'm not sure whether we should add tests include class methods for all indentation style (as we're clearly short on those), but I'm sure these commits have to be squashed before we can merge the PR. :-)

**Comment by unmanbearpig** [comment]
I'm not sure about the test as well, do you think it would be better to delete it?

**Comment by bbatsov** [comment]
Well, the real problem is not `private_class_method`. The problem is that there are no tests using class methods, so adding a few of those would be beneficial.

**Comment by unmanbearpig** [comment]
Good point. I'll see what I can come up with when I get back to my computer.

**Comment by bbatsov** [comment]
You'll also have to rebase on top of the current `master`.

**Comment by unmanbearpig** [comment]
I've deleted my original test and added tests for cases where there was a test for def but not for defs. Not sure if all of them are necessary though. 
What do you think?

I've also verified that my new tests catch the original bug.

**Comment by bbatsov** [comment]
:+1: Looks great. Thanks!

**Comment by unmanbearpig** [comment]
Awesome! I'm happy to help :)
