### PR TITLE
[Fix #5019] Fix auto-correct for `Style/HashSyntax` cop when hash is used as unspaced argument

### LINKED ISSUE #5019: Auto-correct compressed hash syntax incorrect
An issue with compressed hash syntax being incorrectly auto-corrected.

--------

## Expected behavior

`model.save(validate:true)`

## Actual behavior

`model.savevalidate: true`

## Steps to reproduce the problem

```
user = User.new
user.save:validate=>true
```

then run `rubocop --auto-correct`

## RuboCop version

```
$ rubocop -V
0.51.0 (using Parser 2.4.0.0, running on ruby 2.4.1 x86_64-darwin16)
```

### PR DESCRIPTION
**Pull request by Drenmi**
This cop's' auto-correct would result in invalid syntax when hash rocket hashes are used as unspaced arguments. This change fixes that.

-----------------

Before submitting the PR make sure the following are checked:

* [X] Wrote [good commit messages][1].
* [X] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [X] Used the same coding conventions as the rest of the project.
* [X] Feature branch is up-to-date with `master` (if not - rebase it).
* [X] Squashed related commits together.
* [X] Added tests.
* [X] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [X] All tests(`rake spec`) are passing.
* [X] The new code doesn't generate RuboCop offenses that are checked by `rake internal_investigation`.
* [X] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [ ] Updated cop documentation with `rake generate_cops_documentation` (required only when you've added a new cop or changed the configuration/documentation of an existing cop).

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: spec/rubocop/cop/style/hash_syntax_spec.rb [hunk 1]
```diff
@@ -135,6 +135,12 @@
         new_source = autocorrect_source('{ :a=>1, :b=>2 }')
         expect(new_source).to eq('{ a: 1, b: 2 }')
       end
+
+      # Bug: https://github.com/bbatsov/rubocop/issues/5019
+      it 'auto-corrects a missing space when hash is used as argument' do
+        new_source = autocorrect_source('foo:bar => 1')
```
Comment (bbatsov) [inline spec/rubocop/cop/style/hash_syntax_spec.rb]: I really hope we have some lint for this crazy, but valid, syntax.

Comment (Drenmi) [reply spec/rubocop/cop/style/hash_syntax_spec.rb]: We do indeed. `Layout/SpaceBeforeFirstArg` normally takes care of this. 🙂

**Comment by Drenmi** [comment]
@bbatsov: Rebased.

**Comment by bbatsov** [comment]
👍
