### PR TITLE
[Fix #3300] Do not replace `%q()`s containing escaped non-backslashes

### LINKED ISSUE #3300: Replacement of %q when escape characters are present can break code
The rule that replaces `%q` with a double quote string literal is not correct in the presence of both an escaped backslash and an escaped single quote.

Our real use case was to replace `'hello'` (quotes are part of the string) with `\'hello\'`.

--------

## Expected behavior

No change.

## Actual behavior

```diff
diff --git a/example.rb b/example.rb
index ef2b914..380c92a 100644
--- a/example.rb
+++ b/example.rb
@@ -7,7 +7,7 @@ class TestSample < Test::Unit::TestCase
     target = 'foobar'
     expected = "\\'bar"
     assert do
-      target.gsub('foo', %q(\\\')) == expected
+      target.gsub('foo', "\\\'") == expected
     end
   end
 end
```
## Steps to reproduce the problem

example.rb
```ruby
# frozen_string_literal: true
require 'test/unit'

# comment
class TestSample < Test::Unit::TestCase
  test 'replace' do
    target = 'foobar'
    expected = "\\'bar"
    assert do
      target.gsub('foo', %q(\\\')) == expected
    end
  end
end
```

```
$ ruby example.rb
Loaded suite example
Started
.

Finished in 0.000961 seconds.
---------------------------------------------------------------------------------------------------------
1 tests, 1 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
---------------------------------------------------------------------------------------------------------
```

```
$ rubocop -a example.rb
Inspecting 1 file
C

Offenses:

example.rb:10:26: C: [Corrected] Use %q only for strings that contain both single quotes and double quotes.
      target.gsub('foo', %q(\\\')) == expected
                         ^^^^^^^^

1 file inspected, 1 offense detected, 1 offense corrected
```

```
ruby example.rb
Loaded suite example
Started
F
=========================================================================================================
Failure:
        target.gsub('foo', "\\\'") == expected
        |      |                   |  |
        |      |                   |  "\\'bar"
        |      |                   false
        |      "barbar"
        "foobar"
test: replace(TestSample)
/Users/tony/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/power_assert-0.2.6/lib/power_assert.rb:36:in `start'
example.rb:9:in `block in <class:TestSample>'
      6:   test 'replace' do
      7:     target = 'foobar'
      8:     expected = "\\'bar"
  =>  9:     assert do
     10:       target.gsub('foo', "\\\'") == expected
     11:     end
     12:   end
=========================================================================================================


Finished in 0.005932 seconds.
---------------------------------------------------------------------------------------------------------
1 tests, 1 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
0% passed
---------------------------------------------------------------------------------------------------------
```

## RuboCop version

```
$ rubocop -V
0.41.1 (using Parser 2.3.1.2, running on ruby 2.3.1 x86_64-darwin15)
```

### PR DESCRIPTION
**Pull request by owst**
In `%q(...)` `\\` is the only escape (evaluating to a single `\`), so if a `%q` literal contains escaped characters that are not `\` we should not change to double quotes, since that will change the string:
```
irb(main):001:0> puts %q(\\ \')
\ \'
irb(main):002:0> puts "\\ \'"
\ '
```
Notice how the first prints `\'` but the second just `'`

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Used the same coding conventions as the rest of the project.
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] All tests are passing.
* [x] The new code doesn't generate RuboCop offenses.
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.

[1]: http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html

### CODE REVIEW

File: spec/rubocop/cop/style/unneeded_percent_q_spec.rb [hunk 1]
```diff
@@ -34,24 +34,22 @@
       expect(cop.messages).to be_empty
     end
 
-    it 'registers an offense for a string with single quotes and what appears' \
-       ' to be an escape' do
-      # There is no such thing as escapes in a %q() string
-      # So this can just as well be written with double quotes
-      inspect_source(cop, "%q('hi\\t')")
```
Comment (owst) [inline spec/rubocop/cop/style/unneeded_percent_q_spec.rb]: This test was not correct. The source code string evaluates to `%q('hi\t')`, i.e. there is an escaped `t`. Replacing `%q` here gives a different string:
```
irb(main):001:0> puts "%q('hi\\t')"
%q('hi\t')
=> nil
irb(main):002:0> puts %q('hi\t')
'hi\t'
=> nil
irb(main):003:0> puts "'hi\t'"
'hi     '
```

**Comment by bbatsov** [comment]
This is missing a changelog entry.

**Comment by owst** [comment]
Good spot @bbatsov - fixed!

**Comment by bbatsov** [comment]
👍
