### PR TITLE
[Fix #4517] Add `AllowInHeredoc` option to `TrailingWhitespace` cop.

### LINKED ISSUE #4517: Style/TrailingWhitespace marks offenses when whitespace is in a string
## Expected behavior

Writing a multiline string with trailing whitespace for exact formatting must not cause a `Style/TrailingWhitespace` offense because rubocop cannot know the intended use of a string.

## Actual behavior

Rubocop marks strings with trailing whitespace as a `Style/TrailingWhitespace` offense 

## Steps to reproduce the problem

Write t.rb:

```
STRING = <<-STRING
This line has a trailing space: 

This line has a trailing tab:	

Nothing in this file should cause a Style/TrailingWhitespace offense.
STRING
```

run rubocop:

```
$ rubocop t.rb
Inspecting 1 file
C

Offenses:

t.rb:1:10: C: Freeze mutable objects assigned to constants.
STRING = <<-STRING
         ^^^^^^^^^
t.rb:2:1: C: Use 2 spaces for indentation in a heredoc by using some library(e.g. ActiveSupport's String#strip_heredoc).
This line has a trailing space:  ...
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
t.rb:2:32: C: Trailing whitespace detected.
This line has a trailing space: 
                               ^
t.rb:4:30: C: Trailing whitespace detected.
This line has a trailing tab:	
                             ^

1 file inspected, 4 offenses detected
```

I do not expect the cops on lines 2 or 4 to appear.

## RuboCop version

Include the output of `rubocop -V`. Here's an example:

```
$ rubocop -V
0.49.1 (using Parser 2.4.0.0, running on ruby 2.4.1 x86_64-darwin16)
```

### PR DESCRIPTION
**Pull request by Darhazer**
See #4517 for a discussion on the issue

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `rake default` or `rake parallel`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by bbatsov** [comment]
The implementation looks OK to me, but I'm wonder something - do we ever want to be looking for training whitespace in a heredoc? As it's basically a string I don't think so, but I can also imagine how people can add some whitespace accidentally. Still we should probably not care about this much. 

I think we don't need a config option and this should simply be the default behaviour. Any other opinions?

File: lib/rubocop/cop/layout/trailing_whitespace.rb [hunk 1]
```diff
@@ -34,6 +36,25 @@ def investigate(processed_source)
...
+        end
+
+        def inside_heredoc?(heredoc_lines, index)
+          heredoc_lines.any? { |r| r.include?(index + 1) }
+        end
+
+        def extract_heredoc_lines(ast)
+          return [] unless ast
+          ast.each_node.with_object([]) do |node, heredocs|
+            next unless node.location.is_a?(Parser::Source::Map::Heredoc)
```
Comment (bbatsov) [inline lib/rubocop/cop/layout/trailing_whitespace.rb]: Didn't we also add `node.heredoc?` at some point?

File: lib/rubocop/cop/layout/trailing_whitespace.rb [hunk 2]
```diff
@@ -34,6 +36,25 @@ def investigate(processed_source)
...
           ->(corrector) { corrector.remove(range) }
         end
+
+        private
+
+        def skip_heredoc_lines?
+          cop_config.fetch('AllowInHeredoc', false)
+        end
+
+        def inside_heredoc?(heredoc_lines, index)
```
Comment (bbatsov) [inline lib/rubocop/cop/layout/trailing_whitespace.rb]: I'd name `index` `line_number` (or something like this).

File: lib/rubocop/cop/layout/trailing_whitespace.rb [hunk 3]
```diff
@@ -34,6 +36,25 @@ def investigate(processed_source)
...
+          heredoc_lines.any? { |r| r.include?(index + 1) }
+        end
+
+        def extract_heredoc_lines(ast)
```
Comment (bbatsov) [inline lib/rubocop/cop/layout/trailing_whitespace.rb]: `lines` should be probably be `ranges`, given the context. One would normally expect lines to just be strings.

**Comment by bbatsov** [comment]
Fine by me then - I can live with the config options. :-) Thanks, Max!
