### PR TITLE
[Fix #5221] Switch Layout/SpaceBeforeBlockBraces's empty braces default

### LINKED ISSUE #5221: False positive for `Layout/SpaceBeforeBlockBraces` cop
This report is using RuboCop master (a28c9b2) .
https://github.com/bbatsov/rubocop/commit/a28c9b22f7d59f7b8a47fe71cb83d44c9c527743

I think that it is probably a false positive, but it is confirmed just in case.
AFAIK, it seems to have been changed with the following commit.
https://github.com/bbatsov/rubocop/pull/4926/files#diff-e93280b3b31a6438c533a5f3232340d8

The following is an excerpt of the difference of the config/default.yml file.

```diff
 Layout/SpaceBeforeBlockBraces:
   EnforcedStyle: space
    SupportedStyles:
      - space
      - no_space
 +  EnforcedStyleForEmptyBraces: no_space
    SupportedStylesForEmptyBraces:
      - space
      - no_space
```

## Expected behavior

It is the behavior of RuboCop 0.51.0.

No offenses.

## Actual behavior

It is the behavior of RuboCop 0.60.0? beta (master branch a28c9b2) .

The offense described in the reproduction is detected.

## Steps to reproduce the problem

Put a space between `foo` and `{}`.

```console
% cat /tmp/foo.rb
# frozen_string_literal: true

foo {}
```

Run RuboCop built with master branch (a28c9b2) .

```console
% rubocop /tmp/foo.rb
Inspecting 1 file
C

Offenses:

/tmp/foo.rb:3:4: C: Layout/SpaceBeforeBlockBraces: Space detected to the left of {.
foo {}
   ^

1 file inspected, 1 offense detected
```

This seems not to be the intended behavior for changes that added `EnforcedStyleForEmptyBraces: no_space` to config/default.yml.

## RuboCop version

Include the output of `rubocop -V`. Here's an example:

```
% rubocop -V
0.51.0 (using Parser 2.4.0.2, running on ruby 2.4.2 x86_64-darwin13)
```

__This is not the released RuboCop 0.51.0. It is the master branch (a28c9b2) under development.__

### PR DESCRIPTION
**Pull request by garettarrowood**
As discussed on #5221 , the `EnforcedStyleForEmptyBraces` config for `Layout/SpaceBeforeBlockBraces` should be `space` and not `no_space`. This PR makes that switch.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `rake default` or `rake parallel`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: spec/rubocop/cop/layout/space_before_block_braces_spec.rb [hunk 1]
```diff
@@ -63,11 +63,6 @@
       expect(cop.config_to_allow_offenses).to eq('Enabled' => false)
     end
 
-    it 'auto-corrects unwanted space' do
-      new_source = autocorrect_source('each {}')
-      expect(new_source).to eq('each{}')
-    end
```
Comment (garettarrowood) [inline spec/rubocop/cop/layout/space_before_block_braces_spec.rb]: This test was removed because it was reliant on the default setting. It also was essentially a dup of [this test](https://github.com/bbatsov/rubocop/blob/master/spec/rubocop/cop/layout/space_before_block_braces_spec.rb#L96), where the config is explicitly set.

**Comment by bbatsov** [comment]
That was some epic oversight on my part. Thanks for fixing this!
