### PR TITLE
[Fix #3017][Fix #3056] `Style/StringLiterals` now works with non-ascii strings

### LINKED ISSUE #3017: Style/StringLiterals ignores strings with non-ascii characters
```shell
echo '"Esp"' | rubocop --stdin --only Style/StringLiterals -
```

results in

```
Inspecting 1 file
C

Offenses:

-:1:1: C: Prefer single-quoted strings when you don't need string interpolation or special symbols.
"Esp"
^^^^^

1 file inspected, 1 offense detected
```

whereas

```shell
echo '"España"' | rubocop --stdin --only Style/StringLiterals -
```

results in

```
Inspecting 1 file
.

1 file inspected, no offenses detected
```

```shell
$ rubocop -V
0.39.0 (using Parser 2.3.0.7, running on ruby 2.3.0 x86_64-linux)
```

### LINKED ISSUE #3056: Style/StringLiterals: reports offense on \u0060 and \u0022
## Expected behavior

Not to return error.

## Actual behavior

```ruby
$ rubocop text.rb
Inspecting 1 file
C

Offenses:

text.rb:1:25: C: Prefer single-quoted strings when you don't need string interpolation or special symbols.
OpenStruct.new(content: "\u0060")
                        ^^^^^^^^
text.rb:3:25: C: Prefer single-quoted strings when you don't need string interpolation or special symbols.
OpenStruct.new(content: "\u0022")
                        ^^^^^^^^

1 file inspected, 2 offenses detected
```
## Steps to reproduce the problem
```ruby
$ cat text.rb
OpenStruct.new(content: "\u0060")
OpenStruct.new(content: "\u00b4")
OpenStruct.new(content: "\u0022")
OpenStruct.new(content: "\u201d")
```

## RuboCop version
```
$ rubocop -V
0.39.0 (using Parser 2.3.0.7, running on ruby 2.3.0 x86_64-darwin15)
```

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
Fixes #3017 and #3056.

There were a couple of failing tests which I didn't fix because I don't think the functionality they test makes a lot of sense, but I'm probably missing something.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Used the same coding conventions as the rest of the project.
* [x] Feature branch is up-to-date with `master` (if not - rebase it)
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] All tests are passing.
* [x] The new code doesn't generate RuboCop offenses.
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.

[1]: http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html

### CODE REVIEW

File: lib/rubocop/cop/util.rb [hunk 1]
```diff
@@ -212,32 +212,32 @@ def double_quotes_required?(string)
...
       def double_quotes_acceptable?(string)
         # If a string literal contains hard-to-type characters which would
         # not appear on a "normal" keyboard, then double-quotes are acceptable
-        double_quotes_required?(string) ||
+        needs_escaping?(string) ||
           string.codepoints.any? { |cp| cp < 32 || cp > 126 }
       end
 
+      def needs_escaping?(string)
+        double_quotes_required?(string.inspect)
```
Comment (jonas054) [inline lib/rubocop/cop/util.rb]: A comment here would help me.

**Comment by jonas054** [comment]
The solution looks very elegant, and since the tests pass, I bet it's correct. But I still find it a bit hard to understand. Could you add something at the place I've indicated?

File: lib/rubocop/cop/util.rb (hunk 1 above)
Comment (deivid-rodriguez) [inline lib/rubocop/cop/util.rb]: Hi @jonas054, thanks for reviewing this.

If you see 5b84608c, this is just a refactor to extract the `string.inspect` call to a helper method. Since some usages of `double_quotes_required?` were assigning to an `escape` variable I figured `needs_escaping?` could be a good name for this new auxiliary method.

The reason for this refactor is that in https://github.com/bbatsov/rubocop/pull/3189/commits/e64d0bb99bc77cb049dffe6a4c086e3ceb1c5cf8 I need to call `double_quotes_required?` on something that's already inspected. The reason for that can be seen in this debugging session:

```
deivid@pantani ~/Code/rubocop $ bundle exec rspec spec/rubocop/cop/style/string_literals_spec.rb:102
Run options:
  include {:focus=>true, :locations=>{"./spec/rubocop/cop/style/string_literals_spec.rb"=>[102]}}
  exclude {:broken=>#<Proc:./spec/spec_helper.rb:30>}

Randomized with seed 4386

[7, 16] in /home/deivid/Code/rubocop/lib/rubocop/cop/mixin/string_literals_help.rb
    7:     module StringLiteralsHelp
    8:       include StringHelp
    9: 
   10:       def wrong_quotes?(node)
   11:         require 'byebug'; byebug
=> 12:         src = node.source
   13:         return false if src.start_with?('%', '?')
   14:         if style == :single_quotes
   15:           !double_quotes_required?(src)
   16:         else
(byebug) node.source
"\"Espa\\u00f1a\""
(byebug) node.str_content
"España"
(byebug)
```

`node.source` keeps the unicode control characters as they were originally, so that's what's needed for fixing these unicode issues. But as you can see, that string is already inspected, so I need to perform the regex matching done in `double_quotes_required?` _without_ inspecting the string first. That's why I extracted the `needs_escaping?` method and moved inspecting the string out of `double_quotes_required?`.

I hope this makes sense and helps clarifying! Based on the explanation, what can I do to make the patch clearer? I'm thinking maybe moving `string.inspect` to a `unescape` method could help making the code more self-explanatory?

Comment (jonas054) [inline lib/rubocop/cop/util.rb]: I would call what `inspect` does "escaping" rather than "unescaping". It's putting escape sequences starting with backslash instead of hard-to-print characters. Anyway, this is a really tricky area. It's not like we can make it dead simple with just a little refactoring, and having devoted a few minutes to read the code, I think it makes sense.

Comment (deivid-rodriguez) [inline lib/rubocop/cop/util.rb]: You're right, "escape" makes more sense. Should I extract that method then?

Also, even if the tests pass in both ways, I think `string.inspect[1..-2]` makes more sense than just `string.inspect` since `inspect` adds double quotes around the string that are not relevant for this use case.

Comment (jonas054) [inline lib/rubocop/cop/util.rb]: > You're right, "escape" makes more sense. Should I extract that method then?

I don't think it's necessary.

> Also, even if the tests pass in both ways, I think string.inspect[1..-2] makes more sense than just string.inspect since inspect adds double quotes around the string that are not relevant for this use case.

I agree.

Comment (deivid-rodriguez) [inline lib/rubocop/cop/util.rb]: I ended up using that "escape" method because it was already there: https://github.com/bbatsov/rubocop/pull/3189/commits/44af269942180048355f18900126e5745de2b27f :)

**Comment by jonas054** [comment]
:+1: Looks good!

**Comment by deivid-rodriguez** [comment]
@jonas054 Cool, thanks for reviewing! Rebased on top of latest master.

**Comment by bbatsov** [comment]
The changes look good to me as well, but this will have to be rebased one more time.

File: CHANGELOG.md [hunk 2]
```diff
@@ -40,6 +40,8 @@
 * [#3157](https://github.com/bbatsov/rubocop/issues/3157): Don't let `LineEndConcatenation` and `UnneededInterpolation` make changes to the same string during auto-correct. ([@jonas054][])
 * [#3187](https://github.com/bbatsov/rubocop/issues/3187): Let `Style/BlockDelimiters` ignore blocks in *all* method arguments. ([@jonas054][])
 * Modify `Style/ParallelAssignment` to use implicit begins when parallel assignment uses a `rescue` modifier and is the only thing in the method. ([@rrosenblum][])
+* [#3017](https://github.com/bbatsov/rubocop/issues/3017): Fix `Style/StringLiterals` to register offenses on non-ascii strings. ([@deivid-rodriguez][])
+* [#3056](https://github.com/bbatsov/rubocop/issues/3056): Fix `Style/StringLiterals` to register offenses on non-ascii strings. ([@deivid-rodriguez][])
```
Comment (tejasbubane) [inline CHANGELOG.md]: Although this closes both issues, I think it should be mentioned only once in the changelog with link to either of the two issues.

**Comment by deivid-rodriguez** [comment]
Rebased!

File: CHANGELOG.md (hunk 2 above)
Comment (deivid-rodriguez) [inline CHANGELOG.md]: Not sure, @bbatsov?
