### PR TITLE
[Fix #4001] Fix bug in Metrics/LineLength

### LINKED ISSUE #4001: Lint/UnneededDisable of Metrics/LineLength that isn't unneeded
This line (among many others) is throwing an error for me:

```ruby
  LARGE_DATA_STRING_PATTERN = %r{\A([A-Za-z0-9\+\/#]*\={0,2})#([A-Za-z0-9\+\/#]*\={0,2})#([A-Za-z0-9\+\/#]*\={0,2})\z} # rubocop:disable Metrics/LineLength
```

My full `LineLength` config is as follows:

```yaml
Metrics/LineLength:
  Enabled:                       true
  Max:                           90
  AllowHeredoc:                  true
  AllowURI:                      true
  IgnoreCopDirectives:           true
  URISchemes:
    - 'http'
    - 'https'
```

--------

## Expected behavior

No error for `Lint/UnneededDisable`

## Actual behavior

An error for `Lint/UnneededDisable`

## RuboCop version

```
$ rubocop -V
0.47.1 (using Parser 2.3.3.1, running on ruby 2.4.0 x86_64-darwin16)
```

### PR DESCRIPTION
**Pull request by wkurniawan07**
Metrics/LineLength had a bug when configured with “ignoreCopDirectives” set to true AND checking a line with both directive # and non-directive # present.

For example:
```rb
aaa … aaa # bbb … bbb # rubocop:disable CopName
```
where (aaa … aaa # bbb … bbb) exceeds the specified line length.
The cop would correctly detect it as a violation, but would return the extraneous characters AND the directive in the error message.

```rb
LARGE_DATA_STRING_PATTERN = %r{\A([A-Za-z0-9\+\/#]…)} # rubocop:disable CopName
```
The above line has # as part of regexp and the line is longer than the permissible line length before the directive.
The cop did not detect it as a violation.

**Outline of Solution**

The problem lied in two places, both of which are fixed:
1. Regex for directive comment marked with `\A` assertion. This causes things like `# NOT A DIRECTIVE # rubocop:disable CopName` not to be recognized as a cop directive.
1. When constructing an error message, the line is split by the first # found. This is a clear slip up: the line should be split by the directive comment regexp.

I realize that my solution for (1), which is removing the assertion altogether, might be an overkill and might cause some unintended regressions (the `\A` should be there for a reason, shouldn't it?). I would like to hear from the project team if this is the correct thing to do. If it is not, I will prepare an alternative solution.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Used the same coding conventions as the rest of the project.
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] All tests are passing.
* [x] The new code doesn't generate RuboCop offenses.
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Updated cop documentation with `rake generate_cops_documentation` (required only when you've added a new cop or changed the configuration/documentation of an existing cop).

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by wkurniawan07** [comment]
@bbatsov @mikegee can I request for a review here? :slightly_smiling_face:

File: lib/rubocop/comment_config.rb [hunk 1]
```diff
@@ -11,7 +11,7 @@ class CommentConfig
     COPS_PATTERN = "(all|#{COP_NAMES_PATTERN})".freeze
 
     COMMENT_DIRECTIVE_REGEXP = Regexp.new(
-      ('\A# rubocop : ((?:dis|en)able)\b ' + COPS_PATTERN).gsub(' ', '\s*')
+      ('# rubocop : ((?:dis|en)able)\b ' + COPS_PATTERN).gsub(' ', '\s*')
```
Comment (mikegee) [inline lib/rubocop/comment_config.rb]: Any idea why that `\b` is in there?

Comment (mikegee) [inline lib/rubocop/comment_config.rb]: I just noticed the `gsub` and it makes sense now.

I don't like the `gsub` part. I don't think it contributes to the clarity. Changing that would require changing `COP_NAMES_PATTERN`, so I suppose that's out of scope.

**Comment by bbatsov** [comment]
LGTM

Thanks!
