### PR TITLE
[Fix #5515] Fix Style/EmptyElse autocorrect for nested if and case.

### LINKED ISSUE #5515: Auto correction removes unrelated code block on "Redundant else-clause" error
## Expected behavior

It only removes the redundant else-clause.

## Actual behavior

It removes unrelated code block, resulting in code with syntax error. See below.

## Steps to reproduce the problem

```
$ cat <<EOF > foo.rb
class Foo
  def value
    if @params
      case @params[:x]
      when 'a'
        'b'
      else
        nil
      end
    else
      'c'
    end
  end
end
EOF

$ rubocop foo.rb --auto-correct foo.rb
Inspecting 1 file
E

Offenses:

foo.rb:7:7: C: [Corrected] Style/EmptyElse: Redundant else-clause.
      else
      ^^^^
foo.rb:10:1: E: Lint/Syntax: unexpected token $end
(Using Ruby 2.1 parser; configure using TargetRubyVersion parameter, under AllCops)

1 file inspected, 2 offenses detected, 1 offense corrected

$ cat foo.rb
class Foo
  def value
    if @params
      case @params[:x]
      when 'a'
        'b'
      end
  end
end

$ ruby foo.rb
foo.rb:9: syntax error, unexpected end-of-input, expecting keyword_end
```

## RuboCop version

Include the output of `rubocop -V`. Here's an example:

```
$ rubocop -V
0.52.1 (using Parser 2.4.0.2, running on ruby 2.4.1 i686-linux)
```

### PR DESCRIPTION
**Pull request by asherkach**
In particular, fix the autocorrect to not delete any else statement associated with the outer if statement.

-----------------

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `rake default` or `rake parallel`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by asherkach** [comment]
@bbatsov or @pocke for quick review, after which fix the conflict for thorough review.

File: lib/rubocop/cop/style/empty_else.rb [hunk 1]
```diff
@@ -151,9 +151,12 @@ def else_line_range(loc)
           loc.else.first_line..loc.end.first_line
         end
 
-        def base_if_node(node)
-          return node unless node.case_type? || node.elsif?
-          node.each_ancestor(:if).find { |parent| parent.loc.end } || node
+        def base_node(node)
+          return node if node.case_type?
+          return node unless node.elsif?
+          node.each_ancestor(:if, :case, :when).find do |parent|
```
Comment (rrosenblum) [inline lib/rubocop/cop/style/empty_else.rb]: `find` implements the ability to specify a default value if there are no matches.

```ruby
node.each_ancestor(:if, :case, :when).find(->(node)) do |parent|
  parent.loc.end
end
```

https://ruby-doc.org/core-2.2.3/Enumerable.html#method-i-find

Comment (asherkach) [reply lib/rubocop/cop/style/empty_else.rb]: Done.

**Comment by asherkach** [comment]
No worries. Ready for merge?

**Comment by bbatsov** [comment]
👍
