### PR TITLE
[Fix #1309] Add argument handling to MultilineBlockLayout

### LINKED ISSUE #1309: No offense detected on a block that looks wrong
There should be an offense detected here but there it says "no offenses detected." 

```ruby
    devise_parameter_sanitizer.for(:account_update) do
      |u| u.permit(:username, :email, :password, :password_confirmation, :current_password)
    end
```

### PR DESCRIPTION
**Pull request by lumeet**
The cop now registers an offense for arguments on a wrong line.
Auto-correction is also applied to these expressions.

Fixes #1309.

### CODE REVIEW

File: lib/rubocop/cop/style/multiline_block_layout.rb [hunk 1]
```diff
@@ -38,35 +40,74 @@ def on_block(node)
...
+                         block_body
+                       end
+
+          block_start_col = node.loc.expression.column
+
+          corrector.insert_before(first_node.loc.expression,
+                                  "\n  #{' ' * block_start_col}")
+        end
+
+        def lambda_arg_string(args)
```
Comment (bbatsov) [inline lib/rubocop/cop/style/multiline_block_layout.rb]: lambda -> block

File: lib/rubocop/cop/style/multiline_block_layout.rb [hunk 2]
```diff
@@ -30,6 +30,8 @@ module Style
       #   }
       class MultilineBlockLayout < Cop
         MSG = 'Block body expression is on the same line as the block start.'
+        ARG_MSG = 'Block argument expression is not on the same line as the ' \
```
Comment (bbatsov) [inline lib/rubocop/cop/style/multiline_block_layout.rb]: You should also extend the description comment for the cop.

**Comment by bbatsov** [comment]
Please, mention the fixed issue in the title of the commit - `[Fix ...] ...`.

**Comment by lumeet** [comment]
There we go. By the way, @bbatsov, I forgot to ask if this a new feature, a change or a bug fix? Depending on how you look at it, it can be any of them. So, you decide. :) Currently it's under the Changes heading.

**Comment by bbatsov** [comment]
:+1: Having it listed as a change is fine by me. Thanks!
