### PR TITLE
[Fix #2287] Fix alignment of whitespace lines

### LINKED ISSUE #2287: Parser exception: Parser::Source::Range .. spans more than one line
```
0.34.2 (using Parser 2.2.2.6, running on ruby 2.2.2 x86_64-darwin14)
```

Given the exception, I guess this is ultimately an issue for Parser... but I wouldn't know where to start in isolating it for them.

```
% echo "def x\n\t   y\n \n\trescue\nend\n" > x.rb
% rubocop -a ./x.rb
Inspecting 1 file


0 files inspected, no offenses detected
#<Parser::Source::Range /Users/matthew/x4.rb 12...14> spans more than one line
parser-2.2.2.6/lib/parser/source/range.rb:113:in `column_range'
parser-2.2.2.6/lib/parser/diagnostic.rb:93:in `render'
parser-2.2.2.6/lib/parser/source/rewriter.rb:34:in `block in initialize'
parser-2.2.2.6/lib/parser/diagnostic/engine.rb:67:in `call'
parser-2.2.2.6/lib/parser/diagnostic/engine.rb:67:in `process'
parser-2.2.2.6/lib/parser/source/rewriter.rb:168:in `append'
parser-2.2.2.6/lib/parser/source/rewriter.rb:50:in `remove'
rubocop-0.34.2/lib/rubocop/cop/corrector.rb:56:in `remove'
rubocop-0.34.2/lib/rubocop/cop/mixin/autocorrect_alignment.rb:125:in `remove'
rubocop-0.34.2/lib/rubocop/cop/mixin/autocorrect_alignment.rb:85:in `autocorrect_line'
rubocop-0.34.2/lib/rubocop/cop/mixin/autocorrect_alignment.rb:66:in `block (2 levels) in autocorrect'
rubocop-0.34.2/lib/rubocop/cop/mixin/autocorrect_alignment.rb:139:in `block in each_line'
rubocop-0.34.2/lib/rubocop/cop/mixin/autocorrect_alignment.rb:137:in `each_line'
rubocop-0.34.2/lib/rubocop/cop/mixin/autocorrect_alignment.rb:137:in `each_line'
rubocop-0.34.2/lib/rubocop/cop/mixin/autocorrect_alignment.rb:65:in `block in autocorrect'
[..]
```

### PR DESCRIPTION
**Pull request by lumeet**
The `AutocorrectAlignment` mixin no longer tries to remove whitespace
containing a newline.

### CODE REVIEW

File: lib/rubocop/cop/mixin/autocorrect_alignment.rb [hunk 1]
```diff
@@ -82,7 +82,7 @@ def autocorrect_line(corrector, line_begin_pos, expr, column_delta,
             corrector.insert_before(range, ' ' * column_delta)
           end
         else
-          remove(range, corrector) if range.source =~ /^[ \t]+$/
+          remove(range, corrector) if range.source =~ /\A[ \t]+\z/
```
Comment (bbatsov) [inline lib/rubocop/cop/mixin/autocorrect_alignment.rb]: A rookie mistake on our part. :-)
