### PR TITLE
Fix false positive for Style/TrailingComma cop

### LINKED ISSUE #1955: False positive for Style/TrailingComma cop
In RuboCop version 0.32.0, given the following configuration:

```
Style/TrailingComma:
  EnforcedStyleForMultiline: 'comma'
```

And the following code:

```ruby
Foo.new({})
```

RuboCop generates the following offense:

```
Put a comma after the last parameter of a multiline method call.
Foo.new({})
        ^^
```

With autocorrect enabled, the code is changed to:

```ruby
Foo.new({},)
```

Something is clearly wrong. This was not a problem in earlier versions of RuboCop.

### PR DESCRIPTION
**Pull request by mattjmcnaughton**
Fixes #1955. 

Adds an extra check to the `multiline?` method of the `trailing_comma.rb` method to ensure expressions like `Foo.new({})` are not considered multiline.

### CODE REVIEW

File: lib/rubocop/cop/style/trailing_comma.rb [hunk 1]
```diff
@@ -71,10 +71,14 @@ def check_literal(node, kind)
         # rubocop:disable Metrics/MethodLength
         def check(node, items, kind, begin_pos, end_pos)
           sb = items.first.loc.expression.source_buffer
+
           after_last_item = Parser::Source::Range.new(sb, begin_pos, end_pos)
 
           return if heredoc?(after_last_item.source)
 
+          # Stop Execution if data structure constructed with brackets is empty
+          return if items.first.children.empty?
```
Comment (mattjmcnaughton) [inline lib/rubocop/cop/style/trailing_comma.rb]: My only concern is that, based on this implementation, `Foo.new({}, \n ... 5)` would pass this cop, and perhaps it should not?

**Comment by sferik** [comment]
:+1:

File: lib/rubocop/cop/style/trailing_comma.rb [hunk 2]
```diff
@@ -46,7 +46,6 @@ def on_send(node)
           # It's impossible for a method call without parentheses to have
           # a trailing comma.
           return unless brackets?(node)
-
```
Comment (bbatsov) [inline lib/rubocop/cop/style/trailing_comma.rb]: Why did you remove this blank line?

**Comment by sferik** [comment]
@mattjmcnaughton It looks like this PR has picked up some merge conflicts. Can you please rebase from the `master` branch?

**Comment by bbatsov** [comment]
@mattjmcnaughton Ping

**Comment by mattjmcnaughton** [comment]
@bbatsov @sferik sorry for the delay! i'll have some time tonight and will rebase, add back the needlessly deleted blank line, and also add a test for another error brought up in the issue thread.

**Comment by bbatsov** [comment]
@mattjmcnaughton Looks good. Just remove the `.` from the commit message's title to match our commit message style.

**Comment by mattjmcnaughton** [comment]
Updated :smile:

**Comment by sferik** [comment]
:smile:

**Comment by bbatsov** [comment]
:+1:
