### PR TITLE
[Fix #3629] Add TargetRailsVersion functionality

### LINKED ISSUE #3629: Rails/HttpPositionalArguments points offenses in rails 4.2 apps
It would be great for the new Rails/HttpPositionalArguments to be aware of the rails version it's inspecting to not suggest changes that incompatible with the running version.

---
## Expected behavior

The `get :method, params: { ... }` syntax is only valid in rails 5 and above. However, rubocop points it as an offense to use positional arguments even in rails 4.2 applications. In those, using the `get :method, params: { ... }` syntax breaks tests.
I would expect Rubocop to not point out those as offenses if verifying rails 4.2 (or lower) applications.
## Actual behavior

Rubocop points HttpPositionalArguments arguments but fixing them breaks the tests in Rails 4.2.
## Steps to reproduce the problem
- Create a new rails 4.2 app
- Create a controller spec using `get :show, id: 1`
- Run rubocop
## RuboCop version

```
$ rubocop -V
0.44.1 (using Parser 2.3.1.4, running on ruby 2.3.1 x86_64-darwin15)
```

### PR DESCRIPTION
**Pull request by maxbeizer**
As described in https://github.com/bbatsov/rubocop/issues/3629 , this
adds the option to add a TargetRailsVersion to the rubocop.yml under
AllCops. Thus, Rails-5-specific cops do not have to be manually
disengaged.

The main problem this solves is when adding RuboCop to an older Rails 4
project, running the autocorrect will actually break the specs without
much indication why.

There is a fair bit more duplication (specifically of specs) than I'd
usually like, but I figured it is better to refactor once this PR gets a
+1 from maintainers.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Used the same coding conventions as the rest of the project.
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] All tests are passing.
* [x] The new code doesn't generate RuboCop offenses.
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Updated cop documentation with `rake generate_cops_documentation` (required only when you've added a new cop or changed the configuration/documentation of an existing cop).

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by bbatsov** [comment]
The cop looks good to me. I think some cops are Rails 4 only, so this might also be denoted in them, although probably few people are running Rails 3 in production these days.

File: lib/rubocop/config.rb [hunk 1]
```diff
@@ -18,6 +18,7 @@ class Config
     # 2.1 is the oldest officially supported Ruby version.
     DEFAULT_RUBY_VERSION = 2.1
     KNOWN_RUBIES = [1.9, 2.0, 2.1, 2.2, 2.3, 2.4].freeze
+    DEFAULT_RAILS_MINOR_VERSION = 5.0
```
Comment (Drenmi) [inline lib/rubocop/config.rb]: I think this should be `DEFAULT_RAILS_VERSION`, because to be picky, the minor version here is just `0`. 😉

File: lib/rubocop/config.rb [hunk 2]
```diff
@@ -295,6 +296,15 @@ def target_ruby_version
         end
     end
 
+    def target_rails_version
+      @target_rails_version ||=
+        if for_all_cops['TargetRailsVersion']
```
Comment (Drenmi) [inline lib/rubocop/config.rb]: Could possibly be:

```ruby
for_all_cops['TargetRailsVersion'] || DEFAULT_RAILS_VERSION
```

🙂 

I also thought this would be a `Style/MultilineMemoization` offense ... might be a false negative? 🤔

File: lib/rubocop/config.rb (hunk 1 above)
Comment (maxbeizer) [inline lib/rubocop/config.rb]: I went back and forth a bit on what to name this constant and ultimately decided to overcomplicate 🙁 . I'll update it to `DEFAULT_RAILS_VERSION`

File: lib/rubocop/config.rb (hunk 2 above)
Comment (maxbeizer) [inline lib/rubocop/config.rb]: yeah I, with the intention of following the previously existing style, copied this directly from the `target_ruby_version` right above it. Then I deleted some of the `ruby-version` file checking and this can/should be simplified. I'd probably write it as 

```ruby
for_all_cops.fetch('TargetRailsVersion', DEFAULT_RAILS_VERSION)
```

but I'm happy to use `||` if that is preferred

Comment (Drenmi) [inline lib/rubocop/config.rb]: `#fetch` should be supported by all Rubies we support. I agree with you `#fetch` is nicer. 🙂

**Comment by maxbeizer** [comment]
Requested changes made. I'm happy to squash it all down to one commit when we are all 👍 .

> I think some cops are Rails 4 only, so this might also be denoted in them, although probably few people are running Rails 3 in production these days.

I'm not totally sure which cops this would apply to. The only one I came across what the http verb cop. Are there any others I should look at updating?

**Comment by bbatsov** [comment]
> I'm not totally sure which cops this would apply to. The only one I came across what the http verb cop. Are there any others I should look at updating?

This is certainly Rails 4+ https://rubocop.readthedocs.io/en/latest/cops_rails/#railsactionfilter

Not sure about the rest. Guess someone should consult the Rails 4 changelog as it happened a while ago and I don't remember what else was added then.

**Comment by bbatsov** [comment]
Squash the related commits together and we're good go to.

File: lib/rubocop/cop/rails/action_filter.rb [hunk 3]
```diff
@@ -74,16 +77,22 @@ def message(node)
...
         def good_methods
+          return FILTER_METHODS if filter_only?
           style == :action ? ACTION_METHODS : FILTER_METHODS
         end
 
         def preferred_method(method)
           good_methods[bad_methods.index(method.to_sym)]
         end
+
+        def filter_only?
```
Comment (bbatsov) [inline lib/rubocop/cop/rails/action_filter.rb]: I guess you could have overriden the `style` method or simply disabled the cop on Rails 3 (which was actually my initial idea).

Comment (maxbeizer) [inline lib/rubocop/cop/rails/action_filter.rb]: My thinking was that you'd want to enforce not using `action` methods in Rails < 4.x apps. I see what you're saying about overriding `style` . Happy to change it if you'd like.

Comment (bbatsov) [inline lib/rubocop/cop/rails/action_filter.rb]: Override `style` or disable to cop completely. I'm fine either way.

**Comment by maxbeizer** [comment]
I opted to skip the cop if using Rails < 4.0. All commits fixed up and rebased master

**Comment by bbatsov** [comment]
👍
