### PR TITLE
Shadowed exception

### LINKED ISSUE #3249: Lint/ShadowedException fails for rescue nil
## Test code

```ruby
begin
  # something
rescue nil
end
```
## Actual behavior

`An error occurred while Lint/ShadowedException cop was inspecting /test.rb`

```bash
Scanning /test.rb
An error occurred while Lint/ShadowedException cop was inspecting /vagrant/sellery/app/test.rb.
undefined method `<' for nil:NilClass
/home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rubocop-0.41.1/lib/rubocop/cop/lint/shadowed_exception.rb:63:in `block (2 levels) in contains_multiple_levels_of_exceptions?'
```

## RuboCop version

```
$ rubocop -V
0.41.1 (using Parser 2.3.1.2, running on ruby 2.3.0 x86_64-linux)
```

### PR DESCRIPTION
**Pull request by rrosenblum**
This fixes #3249. I also realized that I had a boolean variable stored as the opposite of its name. 

As mentioned in the issue, it appears that `rescue nil` will effectively disable the `rescue` in Ruby 1.9.3. In versions after 1.9.3, a `TypeError` is thrown when the statement is rescued. There is opportunity for us to add a new Lint cop to recommend against this.

### CODE REVIEW

File: spec/rubocop/cop/lint/shadowed_exception_spec.rb [hunk 1]
```diff
@@ -122,6 +122,37 @@
 
       expect(cop.offenses).to be_empty
     end
+
+    it 'accepts rescueing nil' do
```
Comment (bbatsov) [inline spec/rubocop/cop/lint/shadowed_exception_spec.rb]: Isn't it `rescuing`?

Comment (rrosenblum) [inline spec/rubocop/cop/lint/shadowed_exception_spec.rb]: You are correct. I will fix this.

**Comment by rrosenblum** [comment]
I added an extra commit to improve the highlight area of this cop as well.
