### PR TITLE
[Fix #3439] Properly check left assign from method when a block is used

### LINKED ISSUE #3439: Rails/SaveBang: If you use a do block after a `create`... it won't recognize the `.persisted?` check.
https://github.com/bbatsov/rails-style-guide#save-bang

If you use a do block after a create... it won't recognize the `.persisted?` check.

--------

## Expected behavior
No error

## Actual behavior
Throws: 
> Rails/SaveBang: Use create! instead of create if the return value is not checked.  (https://github.com/bbatsov/rails-style-guide#save-bang)

## Steps to reproduce the problem

Turn on 

```yaml
Rails/SaveBang:
  Enabled: true
```

Then

```ruby
bob = User.create do |user|
  user.name = name
end

if bob.persisted?
  logger.error 'yay'
else
  logger.error 'meow'
end
```

## RuboCop version

Include the output of `rubocop -V`:

```
$ rubocop -V
0.42.0 (using Parser 2.3.1.2, running on ruby 2.1.1 x86_64-darwin16.
```

### PR DESCRIPTION
**Pull request by QuinnHarris**
This addresses https://github.com/bbatsov/rubocop/issues/3439 in a minimal way.
This ensures the ActiveRecord persistence methods are handled the same way if a block is used.
I intend a future PR to improve this cop to look specifically for use of persisted?

### CODE REVIEW

File: lib/rubocop/cop/rails/save_bang.rb [hunk 1]
```diff
@@ -60,6 +60,7 @@ def autocorrect(node)
         def return_value_used?(node)
           return false unless node.parent
           node.parent.lvasgn_type? ||
+            (node.parent.block_type? && node.parent.parent.lvasgn_type?) ||
```
Comment (bbatsov) [inline lib/rubocop/cop/rails/save_bang.rb]: I'm a bit worried that `node.parent.parent` might be nil in some cases.

**Comment by bbatsov** [comment]
👍
