### PR TITLE
[Fix #3578] Fix safe navigation counting in `Metrics/AbcSize`

### LINKED ISSUE #3578: Safe navigator operator (&.) breaks ABC check?
I just noticed that when I added a safe navigator operator (`&.`) `rubocop` stopped reporting a method's ABC size. If anything, there should be even more branches, not less.

I updated to the latest version of rubocop and still see the problem.

Fortunately, I was able to reproduce it with bogus code.

With the safe navigator I have no warning, but without it, I get `C: Assignment Branch Condition size for why? is too high. [15.07/15]`, as expected. Snippets are available on the steps to reproduce section.

--------

## Expected behavior

It should report `C: Assignment Branch Condition size for why? is too high. [15.07/15]`

## Actual behavior

It finds no issues with the method after I introduce a `&.`.

## Steps to reproduce the problem

- 1. Run rubocop on this method:
```ruby
def why?
  @instance1 = other_method
  @instance2 = other_method

  @instance3 = {}

  return if @instance1.blank? || @instance2.blank?

  @instance4 = other_method
  @instance5 = @defined_somewhere_else.method.method

  @instance6 = @instance4.method ? @instance4.other_method : other_method

  @instance7 = @instance6.method { |i| i.method.method }
end
```
- 2. See how it reports `C: Assignment Branch Condition size for why? is too high. [15.07/15]`
- 3. Now add a safe navigator operator on the last line:
```ruby
def why?
  @instance1 = other_method
  @instance2 = other_method

  @instance3 = {}

  return if @instance1.blank? || @instance2.blank?

  @instance4 = other_method
  @instance5 = @defined_somewhere_else.method.method

  @instance6 = @instance4.method ? @instance4.other_method : other_method

  @instance7 = @instance6&.method { |i| i.method.method }
end
```
- 4. See how it no longer reports a problem.

## RuboCop version
```
0.43.0 (using Parser 2.3.1.4, running on ruby 2.3.1 x86_64-darwin15)
```

### PR DESCRIPTION
**Pull request by savef**
This cop wasn't correctly counting method calls that happen with the safe navigation operator (`x&.y`), it has been changed so that they are treated the same as other method calls (like `x.y`).

Adds a test which checks the score of a method with the safe navigation operator. The test would fail without the change in the cop. I'm not sure if it needs a parallel cop with a regular method call scoring the same thing right next to it...

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Used the same coding conventions as the rest of the project.
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] All tests are passing.
* [x] The new code doesn't generate RuboCop offenses.
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.

### CODE REVIEW

File: spec/rubocop/cop/metrics/abc_size_spec.rb [hunk 1]
```diff
@@ -57,7 +57,21 @@
                       'end'])
       expect(cop.messages)
         .to eq(['Assignment Branch Condition size for method_name is too ' \
-                'high. [6.4/0]']) # square root of 1*1 + 5*5 + 2*2 => 6.4
+                'high. [6.4/0]']) # sqrt(1*1 + 5*5 + 2*2) => 6.4
+    end
+
+    context 'target_ruby_version >= 2.3', :ruby23 do
+      # let(:cop_config) { { 'Max' => 0 } }
```
Comment (bbatsov) [inline spec/rubocop/cop/metrics/abc_size_spec.rb]: Why is this commented out line here?

**Comment by bbatsov** [comment]
> I'm not sure if it needs a parallel cop with a regular method call scoring the same thing right next to it...

I don't quite understand what you mean here. Apart from this - the change looks good to me.

**Comment by savef** [comment]
> I don't quite understand what you mean here.

Oops typo. I meant "parallel test". And by that I mean do you also want something like this next to the new test so that we check it counts `x.y` method calls in exactly the same way:
```ruby
      it 'treats regular method calls like safe navigation method calls' do
        inspect_source(cop,
                       ['def method_name',
                        '  object.do_something',
                        'end'])
        expect(cop.messages)
          .to eq(['Assignment Branch Condition size for method_name is too ' \
                  'high. [2/0]']) # sqrt(0 + 2*2 + 0) => 2
      end
```

File: spec/rubocop/cop/metrics/abc_size_spec.rb (hunk 1 above)
Comment (savef) [inline spec/rubocop/cop/metrics/abc_size_spec.rb]: Oops. I'll get rid of it.

**Comment by bbatsov** [comment]
> Oops typo. I meant "parallel test". And by that I mean do you also want something like this next to the new test so that we check it counts x.y method calls in exactly the same way:

Seems redundant to me. The bigger question is whether it's really the best idea to treat safe navigation like regular method calls. Anyways, this will do for now. Just rebase on top of the current `master`.

**Comment by savef** [comment]
> Just rebase on top of the current master.
Done.
