### PR TITLE
[Fix #3271] Fix bad auto-correct for `Style/EachForSimpleLoop` cop

### LINKED ISSUE #3271: 0.41.1: Style/EachForSimpleLoop autocorrection calculates wrong number of repetitions
Style/EachForSimpleLoop autocorrection calculates wrong number of repetitions.

## Test case

    (1..5).each { print '+' } # result: +++++

## Expected behavior

    5.times { print '+' } # result: +++++

## Actual behavior

    4.times { print '+' } # result: ++++

## Steps to reproduce the problem

1. Put test case in a `test.rb` file
2. Run `rubocop -a`

## RuboCop version

    0.41.1 (using Parser 2.3.1.2, running on ruby 2.3.1 x86_64-darwin14)

### PR DESCRIPTION
**Pull request by Drenmi**
There is a bug in `Style/EachForSimpleLoop`, where it auto-corrects with the wrong number of iterations. Consider:

```
(0..10).each { ... }
```

This is an inclusive range of 0 through 10, i.e. 11 iterations. This incorrectly gets auto-corrected to:

```
10.times { ... }
```

It turns out the tests for this auto-correct are incorrect, and missing test cases for the exclusive range cases.

This fix adds test coverage, and makes the auto-correct behave well for inclusive ranges.

### CODE REVIEW

File: lib/rubocop/cop/style/each_for_simple_loop.rb [hunk 1]
```diff
@@ -12,30 +12,44 @@ module Style
...
         end
 
+        private
+
         def autocorrect(node)
           lambda do |corrector|
-            min, max = bad_each_range(node)
+            range_type, min, max = offending_each_range(node)
+
+            max += 1 if range_type == :irange
```
Comment (Drenmi) [inline lib/rubocop/cop/style/each_for_simple_loop.rb]: This is the gist of the bugfix.

**Comment by jonas054** [comment]
:+1: Looks good!

**Comment by bbatsov** [comment]
👍
