### PR TITLE
[Fix #3981] Allow NumericLiterals to be less strict

### LINKED ISSUE #3981: Allow NumericLiterals to be less strict
Recently it appears that `NumericLiterals` was "fixed" such that `12_12_12` now throws an error.  I understand why this was done, however the underscores are used for readability, not simply as "a thousands separator" as [the commit](https://github.com/bbatsov/rubocop/commit/6004788b05ecc0fb59201cb373eff4f517293756#diff-c898d9f92d691f0ca73b37f1993135fe) states.

For example, a good use case of `_` is for currency.  We often have occasion to store money as cents and as such, in tests for example, we might want to list `40000` cents as `400_00` for easier readability.

I'd be willing to PR a change to add a style configuration which will allow this.

I could either do it as an `EnforcedStyle` or as a configuration which would allow users to decide the minimum and maximum number of digits that should be allowed before it's broken up by an underscore.

--------

## Expected behavior

```ruby
  400_00  # Allowed
```

## Actual behavior

```ruby
  40_000
```

## Steps to reproduce the problem

See above.

## RuboCop version

```
$ rubocop -V
0.47.1 (using Parser 2.3.3.1, running on ruby 2.4.0 x86_64-darwin16)
```

### PR DESCRIPTION
**Pull request by iGEL**
This introduces a new configuration option for Style/NumericLiteral called `AllowLessPlacesAtEnd`, which allows numbers which don't have 3 places in the last group separated with underscores. This is useful when specifying monetary values in cents (e.g. $123,456.78 as `Money.new(123_456_78)` instead of `Money.new(12_345_678)`).

I also updated the message to make clearer, that the underscores should be used as a decimal mark.

This was the behavior of RuboCop until the 0.47.0 release, see #3749 for the change and #3981 for the issue discussing that change.

Questions:

* Should it be the default? As it was the behavior until recently, I'd say yes.
* Do I need to update the documentation for the new option and how do I do it? I ran the rake task, but nothing changed.

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Used the same coding conventions as the rest of the project.
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] All tests are passing.
* [x] The new code doesn't generate RuboCop offenses.
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Updated cop documentation with `rake generate_cops_documentation` (required only when you've added a new cop or changed the configuration/documentation of an existing cop).

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/style/numeric_literals.rb [hunk 1]
```diff
@@ -12,8 +12,8 @@ class NumericLiterals < Cop
         include ConfigurableMax
         include IntegerNode
 
-        MSG = 'Separate every 3 digits in the integer portion of a number ' \
-              'with underscores(_).'.freeze
+        MSG = 'Use underscores(_) as decimal mark, separate every 3 digits '\
```
Comment (mikegee) [inline lib/rubocop/cop/style/numeric_literals.rb]: > … as decimal mark, separate …

"… as decimal mark and separate …"

**Comment by bbatsov** [comment]
> Should it be the default? As it was the behavior until recently, I'd say yes.

Probably yes.

> Do I need to update the documentation for the new option and how do I do it? I ran the rake task, but nothing changed.

That's odd - running the rake task is all that needs to be done. Btw, you should also update the cop's class description with examples illustrating the usage of this option.

I don't like the name of this option, as it's a bit confusing IMO. Maybe it should be "AllowMonetaryFormat" or something like this as this is clearly the only usecase that warrants special handling.

**Comment by Drenmi** [comment]
> Maybe it should be "AllowMonetaryFormat" or something like this as this is clearly the only usecase that warrants special handling.

+1 🙂

**Comment by iGEL** [comment]
> Btw, you should also update the cop's class description with examples illustrating the usage of this option.

That's probably what I've missed.

> I don't like the name of this option, as it's a bit confusing IMO. Maybe it should be "AllowMonetaryFormat" or something like this as this is clearly the only usecase that warrants special handling.

Fine with me, but if we make it the default, is should maybe be inversed, for example something like `DisallowMonetaryFormat` or maybe just `Strict`. WDYT?

File: lib/rubocop/cop/style/numeric_literals.rb (hunk 1 above)
Comment (iGEL) [inline lib/rubocop/cop/style/numeric_literals.rb]: Fixed locally, will push it later with the rest. :+1:

**Comment by bbatsov** [comment]
> Fine with me, but if we make it the default, is should maybe be inversed, for example something like DisallowMonetaryFormat or maybe just Strict. WDYT?

I'm fine either way.

**Comment by iGEL** [comment]
@bbatsov Thanks, updated.

**Comment by bbatsov** [comment]
👍
