### PR TITLE
[Fix #4199] Fix incorrect auto correction in `Style/SymbolArray` cop

### LINKED ISSUE #4199: Style/SymbolArray autocorrects without respecting Style/PercentLiteralDelimiters
```yaml
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    "%i": "[]"
```

Will autocorrect `[:foo, :bar]` to `%i(foo bar)`.

### PR DESCRIPTION
**Pull request by pocke**
See #4199

If `PreferredDelimiters` option is specified, `Style/SymbolArray` and `Style/WordArray` cops auto correct to not expected code.
The option is ignored.

For example

```ruby
 # PreferredDelimiters is []

 # Before
 [:a, :b, :c]
 ['a', 'b', 'c']

 # Corrected
 %i(a b c) # Not %i[]
 %w(a b c) # Not %w[]
```

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Used the same coding conventions as the rest of the project.
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] All tests are passing.
* [x] The new code doesn't generate RuboCop offenses.
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Updated cop documentation with `rake generate_cops_documentation` (required only when you've added a new cop or changed the configuration/documentation of an existing cop).

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: spec/rubocop/cop/style/symbol_array_spec.rb [hunk 1]
```diff
@@ -58,6 +69,24 @@
...
+        {
+          'Style/PercentLiteralDelimiters' => {
+            'PreferredDelimiters' => {
+              'default' => '[]'
+            }
+          }
+        }
+      end
+
+      it 'registers an offense with escaping delimiters' do
```
Comment (bbatsov) [inline spec/rubocop/cop/style/symbol_array_spec.rb]: I guess you meant to write something about auto-correct here.

File: spec/rubocop/cop/style/word_array_spec.rb [hunk 2]
```diff
@@ -255,8 +265,25 @@
...
+        {
+          'Style/PercentLiteralDelimiters' => {
+            'PreferredDelimiters' => {
+              'default' => '[]'
+            }
+          }
+        }
+      end
+
+      it 'registers an offense with escaping delimiters' do
```
Comment (bbatsov) [inline spec/rubocop/cop/style/word_array_spec.rb]: Here as well.

**Comment by pocke** [comment]
I fixed the descriptions.

**Comment by Drenmi** [comment]
Awesome patch! <3
