### PR TITLE
[Fix #4886] Fix false offense for Style/CommentedKeyword

### LINKED ISSUE #4886: false offense for Style/CommentedKeyword
## Expected behavior

I expect rubocop to allow literal octothorpes and interpolated strings in method arguments.

## Actual behavior

An offense was generated for an interpolated string in a method argument. The offense claims this is a comment, which triggered a violation of the `Style/CommentedKeyword` cop.

## Steps to reproduce the problem

1. Define a method with an octothorpe in a string as a default method argument.
1. Run `$ rubocop`
1. An offense similar to the screenshot below should get generated.

rubocop v0 51 0 - style commentedkeyword

## RuboCop version

0.51.0

### PR DESCRIPTION
**Pull request by michniewicz**
[Fix #4886] Fix false offense for Style/CommentedKeyword

Fix also contains cop improvements:
Instead of going through each line of the processed_source we can easily take comments only and cop only those lines, where comments are located.
Instead of splitting line with `#` symbol we take column values from `comment.location`.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Used the same coding conventions as the rest of the project.
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] All tests(`rake spec`) are passing.
* [x] The new code doesn't generate RuboCop offenses that are checked by `rake internal_investigation`.
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [ ] Updated cop documentation with `rake generate_cops_documentation` (required only when you've added a new cop or changed the configuration/documentation of an existing cop).

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/style/commented_keyword.rb [hunk 1]
```diff
@@ -57,7 +59,8 @@ def investigate(processed_source)
         ALLOWED_COMMENTS = %w[:nodoc: rubocop:disable].freeze
 
         def offensive?(line)
-          KEYWORDS.any? { |k| line =~ /^\s*#{k}\s+.*#/ } &&
+          line = line.lstrip
+          KEYWORDS.any? { |keyword| line.start_with?(keyword) } &&
```
Comment (pocke) [inline lib/rubocop/cop/style/commented_keyword.rb]: `line.start_with?(*KEYWORDS)`

BTW, we can add a cop for the pattern.

**Comment by bbatsov** [comment]
👍
