### PR TITLE
[Fix #4757] Make Style/TrailingUnderscoreVariable work for nested assignments

### LINKED ISSUE #4757: False positive and bad autocorrect in Style/TrailingUnderscoreVariable
For complex destructuring assignments, Style/TrailingUnderscoreVariable gives false positives and performs the wrong autocorrect.

## Expected behavior

Given the following code:
```ruby
a = [1, 2, [3, 4, 5]]
_, b, (_, c,) = a
_, d, (_, e, _) = a

p a, b, c, d, e
```

I expect RuboCop to:
* report no offense on the second line
* report an offense on the third line, suggesting a change to `_, d, (_, e,) = a`
* autocorrect the third line to  `_, d, (_, e,) = a`

## Actual behavior

RuboCop reports:
```
foo.rb:2:7: C: Do not use trailing _s in parallel assignment. Prefer _, b, = a.
_, b, (_, c,) = a
      ^^^^^^^^
foo.rb:3:7: C: Do not use trailing _s in parallel assignment. Prefer _, d, = a.
_, d, (_, e, _) = a
      ^^^^^^^^^^
```

RuboCop autocorrects the code to:
```ruby
a = [1, 2, [3, 4, 5]]
_, b, = a
_, d, = a

p a, b, c, d, e
```

## Steps to reproduce the problem

Given a file `foo.rb` with:

```ruby
a = [1, 2, [3, 4, 5]]
_, b, (_, c,) = a
_, d, (_, e, _) = a

p a, b, c, d, e
```

* run `rubocop foo.rb` to show the false positive
* run `rubocop -a foo.rb` to show the broken autocorrect

## RuboCop version

Include the output of `rubocop -V`. Here's an example:

```
$ rubocop -V
0.50.0 (using Parser 2.4.0.0, running on ruby 2.4.1 x86_64-linux)
```

### PR DESCRIPTION
**Pull request by donjar**
Fixes #4757.

There's one thing that can be improved, though: for complex assignments with more than one offenses, Rubocop reports more than one offenses on the separate offense. Is it possible to combine them? As shown in the specs:
```
inspect_source('a, (_, (b, _), *_) = foo()')

expect(cop.messages)
  .to eq(['Do not use trailing `_`s in parallel assignment. ' \
          'Prefer `a, (_, (b,), *_) = foo()`.',
          'Do not use trailing `_`s in parallel assignment. ' \
          'Prefer `a, (_, (b, _),) = foo()`.'])
```
It would be nice if it's "Do not use trailing `_`s in parallel assignment. Prefer `a, (_, b,),) = foo()`."

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Used the same coding conventions as the rest of the project.
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] All tests(`rake spec`) are passing.
* [x] The new code doesn't generate RuboCop offenses that are checked by `rake internal_investigation`.
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Updated cop documentation with `rake generate_cops_documentation` (required only when you've added a new cop or changed the configuration/documentation of an existing cop).

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/style/trailing_underscore_variable.rb [hunk 1]
```diff
@@ -89,35 +91,51 @@ def allow_named_underscore_variables
             cop_config['AllowNamedUnderscoreVariables']
         end
 
-        def unneeded_range(node)
-          left, right = *node
-          variables = *left
+        def unneeded_ranges(node)
```
Comment (Drenmi) [inline lib/rubocop/cop/style/trailing_underscore_variable.rb]: Perhaps this method could return a compacted array, so we don't need to do `nil` checks every time the returned array is iterated over?

File: lib/rubocop/cop/style/trailing_underscore_variable.rb [hunk 2]
```diff
@@ -89,35 +91,51 @@ def allow_named_underscore_variables
...
-          range_between(
-            first_offense.source_range.begin_pos,
-            node.loc.operator.begin_pos
-          )
+          range_between(first_offense.source_range.begin_pos,
+                        node.loc.operator.begin_pos)
+        end
+
+        def children_offenses(variables)
+          variables.flat_map { |n| unneeded_ranges(n) if n.mlhs_type? }
```
Comment (Drenmi) [inline lib/rubocop/cop/style/trailing_underscore_variable.rb]: When enumerating over `variables`, `v` seems like a natural identifier for the block. 🙂

File: lib/rubocop/cop/style/trailing_underscore_variable.rb [hunk 3]
```diff
@@ -89,35 +91,51 @@ def allow_named_underscore_variables
...
 
         def unused_variables_only?(offense, variables)
           offense.source_range == variables.first.source_range
         end
 
-        def left_side_range(left, right)
-          range_between(
-            left.source_range.begin_pos, right.source_range.begin_pos
-          )
+        def unused_ranges(node_type, mlhs_node, right)
```
Comment (Drenmi) [inline lib/rubocop/cop/style/trailing_underscore_variable.rb]: This looks like it returns a single range, i.e. `#unused_range`. 🙂

File: lib/rubocop/cop/style/trailing_underscore_variable.rb (hunk 2 above)
Comment (donjar) [reply lib/rubocop/cop/style/trailing_underscore_variable.rb]: I was thinking of `node`. `v` is indeed better!

File: lib/rubocop/cop/style/trailing_underscore_variable.rb (hunk 1 above)
Comment (donjar) [reply lib/rubocop/cop/style/trailing_underscore_variable.rb]: I would prefer it this way, to be honest - I would need to modify both lines 98 and 122 to include the checks. Line 122, in particular, requires me to either use `.compact` or use `inject`; I think it would be easier this way :)

Comment (Drenmi) [reply lib/rubocop/cop/style/trailing_underscore_variable.rb]: It seems that `#children_offenses` is the only source of `nil`s, due to the conditional inside `#flat_map`, but you could also replace this with `#select`:

```ruby
variables.select(&:mlhs_type?).flat_map { |v| unneeded_ranges(v) }
```

Comment (donjar) [reply lib/rubocop/cop/style/trailing_underscore_variable.rb]: Wow, first time hearing that Ruby idiom!

File: lib/rubocop/cop/style/trailing_underscore_variable.rb [hunk 4]
```diff
@@ -89,35 +91,56 @@ def allow_named_underscore_variables
...
         end
 
-        def left_side_range(left, right)
-          range_between(
-            left.source_range.begin_pos, right.source_range.begin_pos
-          )
+        def unused_range(node_type, mlhs_node, right)
+          start_range = mlhs_node.source_range.begin_pos
+
+          end_range = if node_type == :masgn
```
Comment (rrosenblum) [inline lib/rubocop/cop/style/trailing_underscore_variable.rb]: What are your thoughts on using case when here? 

```ruby
end_range = case node_type
            when :masgn
              right.source_range.begin_pos
            when :mlhs
              mlhs_node.source_range.end_pos
            end
```

File: lib/rubocop/cop/style/trailing_underscore_variable.rb [hunk 5]
```diff
@@ -28,22 +28,23 @@ class TrailingUnderscoreVariable < Cop
         UNDERSCORE = '_'.freeze
 
         def on_masgn(node)
-          range = unneeded_range(node)
+          ranges = unneeded_ranges(node)
 
-          return unless range
+          ranges.each do |range|
+            next if range.nil?
```
Comment (rrosenblum) [inline lib/rubocop/cop/style/trailing_underscore_variable.rb]: Is this check still needed now that `unneeded_ranges` has been modified?

**Comment by rrosenblum** [comment]
> There's one thing that can be improved, though: for complex assignments with more than one offenses, Rubocop reports more than one offenses on the separate offense. Is it possible to combine them?

I have run into that same thing on some cops. It would be possible to register a single offense and have the cop handle all fixes at once. However, we tend to try to leave offenses as small as possible and report on things separately. As shown by your example, each offense is independent from the other, and each correction would produce valid Ruby.

File: lib/rubocop/cop/style/trailing_underscore_variable.rb (hunk 4 above)
Comment (Drenmi) [reply lib/rubocop/cop/style/trailing_underscore_variable.rb]: I think most of the existing codebase uses `case`-`when` for node type checks.

File: CHANGELOG.md [hunk 6]
```diff
@@ -10,6 +10,7 @@
 
 ### Bug fixes
 
+## Bug fixes
```
Comment (bbatsov) [inline CHANGELOG.md]: Seems you didn't merge something cleanly.

File: CHANGELOG.md [hunk 7]
```diff
@@ -21,6 +22,8 @@
 * [#4776](https://github.com/bbatsov/rubocop/issues/4776): Non utf-8 magic encoding comments are now respected. ([@deivid-rodriguez][])
 * [#4241](https://github.com/bbatsov/rubocop/issues/4241): Prevent `Rails/Blank` and `Rails/Present` from breaking when there is no explicit receiver. ([@rrosenblum][])
 * [#4814](https://github.com/bbatsov/rubocop/issues/4814): Prevent `Rails/Blank` from breaking on send with an argument. ([@pocke][])
+* [#4757](https://github.com/bbatsov/rubocop/issues/4757): Make Style/TrailingUnderscoreVariable work for nested assignments. ([@donjar][])
```
Comment (bbatsov) [inline CHANGELOG.md]: The name of the cop should be in backticks.

File: CHANGELOG.md [hunk 8]
```diff
@@ -21,6 +22,8 @@
...
+* [#4241](https://github.com/bbatsov/rubocop/issues/4241): Prevent `Rails/Blank` and `Rails/Present` from breaking when there is no explicit receiver. ([@rrosenblum][])
```
Comment (bbatsov) [inline CHANGELOG.md]: Another artefact from a bad merge.

**Comment by bbatsov** [comment]
The PR has some artefacts of a bad merge. It has to be cleaned and properly rebased before it can be merged. I've added a few inline comments.
