### PR TITLE
[Fix #4004] Allow not treating comment lines as gem group separators in `Bundler/OrderedGems` cop

### LINKED ISSUE #4004: Bundler/OrderedGems cop does not catch gems that have a comment between them
When there is a comment between 2 gems in the Gemfile, the OrderedGems cop should still enforce that gems are listed alphabetically.

The docs make it clear that if there's an empty line between them, they don't need to be sorted.  But if a comment is between them, that seems different and I would expect it to sort them.

My reasoning is as followed:

An empty line indicates that they are separate groups of gems.
A comment, on the other hand, does not indicate a separate group--it may indicate that one of the gems within this group requires some explanations.  If you've enabled Style/InlineComment, then you have no other choice but to place the comment on the line above them gem, even if it's in middle of a group.

--------

## Expected behavior

Rubocop should detect 1 offense, just as it does when the comment is not there

## Actual behavior

Rubocop does not detect the offense.

## Steps to reproduce the problem

```
$ cat Gemfile
# frozen_string_literal: true
source 'https://rubygems.org'

gem 'rubocop'
# A comment
gem 'parser'
$ rubocop --only Bundler/OrderedGems
Inspecting 1 file
.

1 file inspected, no offenses detected
```
## RuboCop version

```
$ rubocop -V
0.47.1 (using Parser 2.3.3.1, running on ruby 2.2.2 x86_64-linux)
```

### PR DESCRIPTION
**Pull request by konto-andrzeja**
Fixes [[#4004]](https://github.com/bbatsov/rubocop/issues/4004)

Added `TreatCommentsAsGroupSeparators` option to `Bundler/OrderedGems`.

When it's `false` something like this:
```
# Use sqlite3 as the database for Active Record
gem 'sqlite3'
# Use Puma as the app server
gem 'puma', '~> 3.0'
```
will be autocorrected to this:
```
# Use Puma as the app server
gem 'puma', '~> 3.0'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'
```
When it's `true` no offences will be registered.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Used the same coding conventions as the rest of the project.
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] All tests are passing.
* [x] The new code doesn't generate RuboCop offenses.
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Updated cop documentation with `rake generate_cops_documentation` (required only when you've added a new cop or changed the configuration/documentation of an existing cop).

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: spec/rubocop/cop/bundler/ordered_gems_spec.rb [hunk 1]
```diff
@@ -1,6 +1,8 @@
 # frozen_string_literal: true
 
 describe RuboCop::Cop::Bundler::OrderedGems, :config do
+  let(:cop_config) { { 'EnforcedStyle' => enforced_style, 'Include' => nil } }
```
Comment (pocke) [inline spec/rubocop/cop/bundler/ordered_gems_spec.rb]: I guess `'Include' => nil` is not necessary.

Comment (konto-andrzeja) [inline spec/rubocop/cop/bundler/ordered_gems_spec.rb]: There are lots of fails without it. This solution is used in other specs as well, e.g. [here](https://github.com/bbatsov/rubocop/blob/master/spec/rubocop/cop/rails/not_null_column_spec.rb#L5).

Comment (pocke) [inline spec/rubocop/cop/bundler/ordered_gems_spec.rb]: Sorry, it was my misunderstanding.

File: config/default.yml [hunk 2]
```diff
@@ -1497,3 +1497,9 @@ Rails/SkipsModelValidations:
 Rails/Validation:
   Include:
     - app/models/**/*.rb
+
+Bundler/OrderedGems:
+  EnforcedStyle: no_comment_lines_split
+  SupportedStyles:
+    - no_comment_lines_split
```
Comment (bbatsov) [inline config/default.yml]: I'm not sure this has to be a supported style - probably we really need an option named "TreatCommentsAsGroupSeparators".

File: spec/rubocop/cop/bundler/ordered_gems_spec.rb [hunk 3]
```diff
@@ -131,17 +133,52 @@
...
+    context 'with enforced style set to `no_comment_lines_split`' do
+      it 'registers an offense' do
+        inspect_source(cop, source)
+        expect(cop.offenses.size).to eq(1)
+      end
+
+      it 'has the correct offense message' do
+        inspect_source(cop, source)
+        expect(cop.messages)
+          .to eq(['Gems should be sorted in an alphabetical '\
```
Comment (bbatsov) [inline spec/rubocop/cop/bundler/ordered_gems_spec.rb]: Add space between ' and \. Guess we need some cop for this. :-)

File: spec/rubocop/cop/bundler/ordered_gems_spec.rb [hunk 4]
```diff
@@ -131,17 +133,52 @@
...
+                'order within their section of the Gemfile. '\
```
Comment (bbatsov) [inline spec/rubocop/cop/bundler/ordered_gems_spec.rb]: This should be aligned with the ' on the previous line.

cc @jonas054 - another cop alignment idea :-)

File: spec/rubocop/cop/bundler/ordered_gems_spec.rb (hunk 3 above)
Comment (konto-andrzeja) [inline spec/rubocop/cop/bundler/ordered_gems_spec.rb]: I don't see `'` and `.` next to each other, could you be more specific?

Comment (bbatsov) [inline spec/rubocop/cop/bundler/ordered_gems_spec.rb]: I meant to say `\`.

File: spec/rubocop/cop/bundler/ordered_gems_spec.rb (hunk 4 above)
Comment (konto-andrzeja) [inline spec/rubocop/cop/bundler/ordered_gems_spec.rb]: Fixed [here](https://github.com/bbatsov/rubocop/pull/4139/commits/a934df88f73b4412dcb61f8d70353d1d0c4f36dd).

File: spec/rubocop/cop/bundler/ordered_gems_spec.rb (hunk 3 above)
Comment (konto-andrzeja) [inline spec/rubocop/cop/bundler/ordered_gems_spec.rb]: Fixed [here](https://github.com/bbatsov/rubocop/pull/4139/commits/a934df88f73b4412dcb61f8d70353d1d0c4f36dd).

File: config/default.yml (hunk 2 above)
Comment (konto-andrzeja) [inline config/default.yml]: Fixed [here](https://github.com/bbatsov/rubocop/pull/4139/commits/a934df88f73b4412dcb61f8d70353d1d0c4f36dd).

**Comment by bbatsov** [comment]
The changes look good. Just squash the commits and rebase on top of the current master.

**Comment by jonas054** [comment]
@bbatsov I took the liberty of merging, seeing that a rebase was done.

**Comment by bbatsov** [comment]
@jonas054 You can do this any time. :-)
