### PR TITLE
[Fix #4747] Fix `Rails/HasManyOrHasOneDependent` incorrectly flags `with_options` blocks

### LINKED ISSUE #4747: Rails/HasManyOrHasOneDependent incorrectly flags `with_options` blocks
My code has:

```ruby
class Registrant < ApplicationRecord
  with_options dependent: :destroy do
    has_one :contact_detail, autosave: true, inverse_of: :registrant
    has_one :standard_skill_routine
  end
end
```

And the rubocop HasManyOrHasOneDependent flags it:

```
app/models/registrant.rb:49:5: C: Rails/HasManyOrHasOneDependent: Specify a :dependent option.
    has_one :contact_detail, autosave: true, inverse_of: :registrant
    ^^^^^^^
app/models/registrant.rb:50:5: C: Rails/HasManyOrHasOneDependent: Specify a :dependent option.
    has_one :standard_skill_routine
    ^^^^^^^
```

This is unexpected, since I am specifying a `dependent` option for the has_one...just not directly (which is permitted by rails)

http://api.rubyonrails.org/classes/Object.html#method-i-with_options
--------

## Expected behavior

Not flag my code for having no `dependent:` option.

## Actual behavior

Flags the code as needing a `depndent:` option

## Steps to reproduce the problem

See above code

## RuboCop version

0.50.0

### PR DESCRIPTION
**Pull request by koic**
This PR fixes #4747. `Rails/HasManyOrHasOneDependent` cop will also check `:dependent` option for `with_options` block.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Used the same coding conventions as the rest of the project.
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] All tests(`rake spec`) are passing.
* [x] The new code doesn't generate RuboCop offenses that are checked by `rake internal_investigation`.
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [ ] Updated cop documentation with `rake generate_cops_documentation` (required only when you've added a new cop or changed the configuration/documentation of an existing cop).

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/rails/has_many_or_has_one_dependent.rb [hunk 1]
```diff
@@ -39,17 +39,33 @@ class HasManyOrHasOneDependent < Cop
           (pair (sym :through) !nil)
         PATTERN
 
+        def_node_matcher :with_options_block?, <<-PATTERN
```
Comment (Drenmi) [inline lib/rubocop/cop/rails/has_many_or_has_one_dependent.rb]: I would ✂️ the `?` here, since the matcher captures a node, and doesn't return `true`/`false`. 🙂

File: lib/rubocop/cop/rails/has_many_or_has_one_dependent.rb [hunk 2]
```diff
@@ -39,17 +39,33 @@ class HasManyOrHasOneDependent < Cop
...
+        PATTERN
+
         def on_send(node)
-          unless is_has_many_or_has_one_without_options?(node)
-            pairs = is_has_many_or_has_one_with_options?(node)
-            return unless pairs
-            return if pairs.any? do |pair|
-              has_dependent?(pair) || has_through?(pair)
-            end
+          if !is_has_many_or_has_one_without_options?(node)
```
Comment (Drenmi) [inline lib/rubocop/cop/rails/has_many_or_has_one_dependent.rb]: I would scissor the `is` prefix from the two matchers, since it would be an offense in a regular method definition. (Perhaps we should transpose the method naming cops to an internal investigation cop that checks dynamically generated methods.) 🙂

Comment (koic) [reply lib/rubocop/cop/rails/has_many_or_has_one_dependent.rb]: I fixed them and squashed.

> Perhaps we should transpose the method naming cops to an internal investigation cop that checks dynamically generated methods.

Sure! It is not the scope of this PR, but that is useful if we can catch it with a rule like `Naming/PredicateName` cop :memo:

File: spec/rubocop/cop/rails/has_many_or_has_one_dependent_spec.rb [hunk 3]
```diff
@@ -79,5 +91,28 @@ class Person
         RUBY
       end
     end
+
+    context 'with_options dependent: :destroy' do
```
Comment (bbatsov) [inline spec/rubocop/cop/rails/has_many_or_has_one_dependent_spec.rb]: I think the name of this context is misleading given the example that follows.

File: spec/rubocop/cop/rails/has_many_or_has_one_dependent_spec.rb [hunk 4]
```diff
@@ -79,5 +91,28 @@ class Person
...
+      it 'register an offense for not `with_options dependent: :destroy`' do
```
Comment (bbatsov) [inline spec/rubocop/cop/rails/has_many_or_has_one_dependent_spec.rb]: registers an offense when `dependent: :destroy` is not present (or something like this)

File: spec/rubocop/cop/rails/has_many_or_has_one_dependent_spec.rb [hunk 5]
```diff
@@ -40,6 +40,18 @@ class Person
         RUBY
       end
     end
+
+    context 'with_options dependent: :destroy' do
+      it "doesn't register an offense for `with_options dependent: :destroy`" do
```
Comment (bbatsov) [inline spec/rubocop/cop/rails/has_many_or_has_one_dependent_spec.rb]: You basically repeated the same thing in the context and the example's description.

Comment (koic) [reply spec/rubocop/cop/rails/has_many_or_has_one_dependent_spec.rb]: Thanks for the review. I updated these with the following commit. How about this?
37f7d3c

Comment (bbatsov) [reply spec/rubocop/cop/rails/has_many_or_has_one_dependent_spec.rb]: Yeah, that's much better.

Comment (koic) [reply spec/rubocop/cop/rails/has_many_or_has_one_dependent_spec.rb]: Thanks. I did squash.

**Comment by bbatsov** [comment]
👍

**Comment by yskkin** [comment]
If there are several `has_one`s or `has_many`s in `with_options`, the problem still exists.

`rake spec SPEC="spec/rubocop/cop/rails/has_many_or_has_one_dependent_spec.rb"` fails with following modification.
```
      it "doesn't register an offense for `with_options dependent: :destroy`" do
        expect_no_offenses(<<-RUBY.strip_indent)
          class Person
            with_options dependent: :destroy do
              has_many :foo
              has_many :bar
            end
          end
        RUBY
      end
```

**Comment by koic** [comment]
@yskkin Thanks for the feedback. This PR has been merged and released. Would you please open a issue for new discussion?

**Comment by yskkin** [comment]
Thanks for looking into this. I created #4909.

**Comment by printercu** [comment]
@koic nice fix, it's very helpful! I've found that with this code:

```ruby
  with_options inverse_of: :portfolio, dependent: :destroy do
    has_many :items, class_name: 'PortfolioItem'
    has_many :summaries
  end
```

0.52.0 gives warning only for the first `has_many`, but second is fine:

```
app/models/portfolio.rb:7:5: C: Rails/HasManyOrHasOneDependent: Specify a :dependent option.
    has_many :items, class_name: 'PortfolioItem'
    ^^^^^^^^
```

Is it the same for you?

**Comment by koic** [comment]
@printercu Thanks for feedback. It probably looks like the same issue as #5234.
