### PR TITLE
[Fix #5791] Fix NoMethodError in SafeNavigationConsistency when there is context around the condition

### LINKED ISSUE #5791: Safe Navigation Consistency: undefined method `type' for nil:NilClass
## Expected behavior

The cop should pass

## Actual behavior

```
An error occurred while Lint/SafeNavigationConsistency cop was inspecting <file>
undefined method `type' for nil:NilClass
vendor/bundle/gems/rubocop-0.55.0/lib/rubocop/cop/lint/safe_navigation_consistency.rb:72:in `top_conditional_ancestor'
vendor/bundle/gems/rubocop-0.55.0/lib/rubocop/cop/lint/safe_navigation_consistency.rb:75:in `top_conditional_ancestor'
vendor/bundle/gems/rubocop-0.55.0/lib/rubocop/cop/lint/safe_navigation_consistency.rb:40:in `check'
vendor/bundle/gems/rubocop-0.55.0/lib/rubocop/cop/lint/safe_navigation_consistency.rb:36:in `on_csend'
```

## Steps to reproduce the problem

Failing spec, which is a bit contrived, but illustrates the same failure that I get in my project's code with a more complex line: https://github.com/swrobel/rubocop/commit/12ba988ea1ed047830373d60d63454dd73613644

## RuboCop version

```
$ rubocop -V
0.55.0 (using Parser 2.5.1.0, running on ruby 2.5.1 x86_64-darwin17)
```

cc @rrosenblum

### PR DESCRIPTION
**Pull request by rrosenblum**
This fixes #5791.

### CODE REVIEW

File: spec/rubocop/cop/lint/safe_navigation_consistency_spec.rb [hunk 1]
```diff
@@ -52,6 +52,14 @@
       RUBY
     end
 
+    it 'registers an offense when there is context around the condition' do
```
Comment (bbatsov) [inline spec/rubocop/cop/lint/safe_navigation_consistency_spec.rb]: context in which sense?

Comment (rrosenblum) [reply spec/rubocop/cop/lint/safe_navigation_consistency_spec.rb]: I meant it as supporting code before the conditions. I have updated the PR to provide clearer information.

**Comment by bbatsov** [comment]
One line got too long - that's why the build fails.
