### PR TITLE
[Fix #5429] Detect tabs other than indentation by `Layout/Tab`

### LINKED ISSUE #5429: Layout/Tab ignores tabs that are not indentation
It seems that Layout/Tab will only report on tabs when they are part of a line’s indentation – although [the documentation](http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Layout/Tab) says that “this cop checks for tabs inside the source code.”

# This cop checks for tabs inside the source code.

## Expected behavior

In my test file, there is a tab between `puts` and `42`, which I expect Layout/Tab to detect.

```rb
# frozen_string_literal: true

puts	42
```

## Actual behavior

No offense is reported.

## Steps to reproduce the problem

Run `rubocop` on the file above.

## RuboCop version

Include the output of `rubocop -V`. Here's an example:

```
$ rubocop -V
0.52.1 (using Parser 2.4.0.2, running on ruby 2.4.2 x86_64-darwin15)
```

### PR DESCRIPTION
**Pull request by pocke**
Fix #5429 

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `rake default` or `rake parallel`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/layout/tab.rb [hunk 1]
```diff
@@ -27,17 +27,18 @@ class Tab < Cop
...
+          str_ranges = string_literal_ranges(processed_source.ast)
 
-          processed_source.lines.each_with_index do |line, index|
-            match = line.match(/^( *)[\t ]*\t/)
+          processed_source.lines.each.with_index(1) do |line, lineno|
+            match = line.match(/^([^\t]*)\t+/)
             next unless match
-            next if str_lines.include?(index + 1)
+            prefix = match.captures[0]
+            col = prefix.size
```
Comment (Drenmi) [inline lib/rubocop/cop/layout/tab.rb]: I tend to use `#length` for strings, since it makes sense conceptually. 🙂

File: lib/rubocop/cop/layout/tab.rb [hunk 2]
```diff
@@ -52,21 +53,31 @@ def autocorrect(range)
...
+          ast.each_node(:str, :dstr).each_with_object(Set.new) do |str, ranges|
             loc = str.location
 
-            str_lines = if loc.is_a?(Parser::Source::Map::Heredoc)
-                          body = loc.heredoc_body
-                          (body.first_line)..(body.last_line)
-                        else
-                          (loc.first_line + 1)..(loc.last_line)
-                        end
+            range = if loc.is_a?(Parser::Source::Map::Heredoc)
```
Comment (Drenmi) [inline lib/rubocop/cop/layout/tab.rb]: I think there's a `StrNode#heredoc?` now, but not 100% sure.

Comment (pocke) [reply lib/rubocop/cop/layout/tab.rb]: Definitely. I forgot the helper. Thanks!

**Comment by pocke** [comment]
I rebased and fix broken CI builds.
