### PR TITLE
[Fix #4730] False positive on Lint/InterpolationCheck

### LINKED ISSUE #4730: False positive on Lint/InterpolationCheck
## Expected behavior

Lint/InterpolationCheck should function appropriately for double quoted strings.

## Actual behavior

I'm not entirely sure why it's triggering for this.

## Steps to reproduce the problem

```ruby
variable = 5
"alpha #{variable} beta \#{gamma}\" delta"
```

leads to

```
Inspecting 1 file
W

Offenses:

example.rb:2:19: W: Lint/InterpolationCheck: Interpolation in single quoted string detected. Use double quoted strings if you need interpolation.
"alpha #{variable} beta \#{gamma}\" delta"
                  ^^^^^^^^^^^^^^^^^^^^^^^

1 file inspected, 1 offense detected
```

## RuboCop version

```
$ rubocop -V
0.50.0 (using Parser 2.4.0.0, running on ruby 2.4.1 x86_64-darwin16)
```

### PR DESCRIPTION
**Pull request by koic**
Fixes #4730.

## Summary

It was a problem that `" beta \#{gamma}\" delta"` containing `#{.*}` in the argument of `on_str` method. This PR will not interpolation check if the parent node is dstr.

```console
% cat example.rb
require 'parser/current'

p Parser::CurrentRuby.parse('"alpha #{variable} beta \#{gamma}\" delta"')
% ruby example.rb
warning: parser/current is loading parser/ruby24, which recognizes
warning: 2.4.0-compliant syntax, but you are running 2.4.2.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
s(:dstr,
  s(:str, "alpha "),
  s(:begin,
    s(:send, nil, :variable)),
  s(:str, " beta \#{gamma}\" delta")) # It is judged whether this node's parent is dstr or not.
```

## Other Information

This PR also fixed the following offense caused by this change.

```console
% bundle exec rubocop lib/rubocop/cop/style/variable_interpolation.rb
Inspecting 1 file
W

Offenses:

lib/rubocop/cop/style/variable_interpolation.rb:8:9: W: Unnecessary disabling of Lint/InterpolationCheck.
        # rubocop:disable Lint/InterpolationCheck
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Used the same coding conventions as the rest of the project.
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] All tests(`rake spec`) are passing.
* [x] The new code doesn't generate RuboCop offenses that are checked by `rake internal_investigation`.
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [ ] Updated cop documentation with `rake generate_cops_documentation` (required only when you've added a new cop or changed the configuration/documentation of an existing cop).

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: spec/rubocop/cop/lint/interpolation_check_spec.rb [hunk 1]
```diff
@@ -27,4 +27,10 @@
       foo = "\xff"
     RUBY
   end
+
+  it 'does not register an offense for escapted crab claws in dstr' do
```
Comment (bbatsov) [inline spec/rubocop/cop/lint/interpolation_check_spec.rb]: escaped

Comment (koic) [reply spec/rubocop/cop/lint/interpolation_check_spec.rb]: Oops! I fixed it and rebased. Thanks.

File: lib/rubocop/cop/style/variable_interpolation.rb [hunk 2]
```diff
@@ -5,7 +5,6 @@ module Cop
     module Style
       # This cop checks for variable interpolation (like "#@ivar").
       class VariableInterpolation < Cop
-        # rubocop:disable Lint/InterpolationCheck
```
Comment (Drenmi) [inline lib/rubocop/cop/style/variable_interpolation.rb]: There's a matching `rubocop:enable` directive a few lines down that needs ✂️. 🙂

Comment (koic) [reply lib/rubocop/cop/style/variable_interpolation.rb]: Thanks for the review. I removed a matching `rubocop:enable` and rebased.
