### PR TITLE
[Fix #2173] `Style/AlignParameters` also checks parameters on method defintions

### LINKED ISSUE #2173: No cop checking for indentation of parameters?
Checked on the latest master of RuboCop (0f260a67fd125697b0600f79f4457d5c17df0b70), this file produces no warnings:
```rb
# encoding: utf-8
def x(
    a: 1,
b: 2)
  puts a, b
end

def y(
    a,
b)
  puts a, b
end
```
The indentation is clearly wrong, but what would be the correct indentation?
```rb
def y(
      a,
      b
     )
  puts a, b
end

# or

def y(
  a,
  b
)
  puts a, b
end

# or

def y(a,
      b)
  puts a, b
end
```

### PR DESCRIPTION
**Pull request by alexdowad**
The same 2 styles which AlignParameters already supports are applied in just the same
way to method definitions as to calls.

Fixes #2173.

### CODE REVIEW

File: lib/rubocop/cop/style/align_parameters.rb [hunk 1]
```diff
@@ -20,6 +17,26 @@ def on_send(node)
           check_alignment(args, base_column(node, args))
         end
 
+        def on_def(node)
```
Comment (bbatsov) [inline lib/rubocop/cop/style/align_parameters.rb]: We have a mixin named `OnMethodDef` that you can use to avoid some duplication here for `def` and `defs` nodes.

File: lib/rubocop/cop/style/align_parameters.rb [hunk 2]
```diff
@@ -20,6 +17,26 @@ def on_send(node)
...
+          _method, args = *node
+          args = *args
+          return if args.size <= 1
```
Comment (bbatsov) [inline lib/rubocop/cop/style/align_parameters.rb]: Or just `< 2`. :-) I've always felt that `<=` is not as clear as `<`.

**Comment by alexdowad** [comment]
Updated according to feedback from @bbatsov.

**Comment by bbatsov** [comment]
:+1:
