### PR TITLE
[Fix #5534] remove empty line after `Style/EachWithObject` autocorrect

### LINKED ISSUE #5534: Style/EachWithObject autocorrect should not leave an empty line
Style/EachWithObject autocorrect leaves an empty line which doesn't look good.

--------

## Expected behavior

It should remove empty line.

## Actual behavior

It leaves an empty line.

## Steps to reproduce the problem

```
$ cat test.rb
```

```
[1, 2, 3].inject({}) do |h, i|
  h[i] = i
  h
end
```

```
$ rubocop -a --only Style/EachWithObject ./test.rb
```

```
$ cat test.rb
```

```
[1, 2, 3].each_with_object({}) do |i, h|
  h[i] = i

end
```

But I expect the code to be

```
[1, 2, 3].each_with_object({}) do |i, h|
  h[i] = i
end
```

## RuboCop version

```
$ rubocop -V
0.52.1 (using Parser 2.4.0.2, running on ruby 2.4.3 x86_64-darwin17)
```

### PR DESCRIPTION
**Pull request by flyerhzm**
See #5534 

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `rake default` or `rake parallel`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/style/each_with_object.rb [hunk 1]
```diff
@@ -90,6 +96,14 @@ def first_argument_returned?(args, return_value)
 
           accumulator_var == return_var
         end
+
+        def return_value_occupies_whole_line?(node, return_value)
+          node.body.source.lines.last =~ /\s*#{return_value.source}\s*/
```
Comment (Drenmi) [inline lib/rubocop/cop/style/each_with_object.rb]: Would be nice if this could compare ranges rather than use a regular expression, which can lead to problems with inline comments, etc.

**Comment by flyerhzm** [comment]
@Drenmi updated

**Comment by rrosenblum** [comment]
The change looks good to me. There are some RuboCop failures on the code.

**Comment by flyerhzm** [comment]
@Drenmi @rrosenblum fixed failures

**Comment by flyerhzm** [comment]
@Drenmi @rrosenblum the test failure is caused by rebasing master branch.

**Comment by koic** [comment]
master branch's failure will be resolved by #5575.

**Comment by flyerhzm** [comment]
@Drenmi @rrosenblum @koic test failures are fixed
