### PR TITLE
[Fix #3673] Bug of Style/RedundantSelf

### LINKED ISSUE #3673: RedundantSelf regression
Hi! I've got this code:

``` ruby
  let(:klass) do
    described_class = self.described_class
    Class.new do
      extend described_class
      # ...
    end
  end
```

It's valid in 0.42.0, but 0.43.0 and 0.44.1 give an offence.
## Expected behavior

Rubocop should accept such code.
## Actual behavior

```
spec/rails_stuff/types_tracker_spec.rb:5:23: C: Style/RedundantSelf: Redundant self detected.
    described_class = self.described_class
                      ^^^^^^^^^^^^^^^^^^^^
```
## Steps to reproduce the problem

Copy example into test.rb, run `rubocop test.rb`
## RuboCop version

```
$ rubocop -V
0.44.1 (using Parser 2.3.1.4, running on ruby 2.3.0 x86_64-darwin13)
```

### PR DESCRIPTION
**Pull request by bankair**
Update the Style/RedudantSelf cop to attach assigned variable to the right scope

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Used the same coding conventions as the rest of the project.
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] All tests are passing.
* [x] The new code doesn't generate RuboCop offenses.
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Updated cop documentation with `rake generate_cops_documentation` (required only when you've added a new cop or changed the configuration/documentation of an existing cop).

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: spec/rubocop/cop/style/redundant_self_spec.rb [hunk 1]
```diff
@@ -11,6 +11,12 @@
     expect(cop.offenses.size).to eq(1)
   end
 
+  it 'does not report an offense when receiver and lvalue have the same name' do
+    src = 'a = self.a'
+    inspect_source(cop, src)
+    expect(cop.offenses).to be_empty
+  end
```
Comment (lamont-granquist) [inline spec/rubocop/cop/style/redundant_self_spec.rb]: :+1:

**Comment by printercu** [comment]
@bankair I've an offence with 0.48.1:
```
spec/models/payment_system/form_spec.rb:19:54: C: Redundant self detected.
    amount, currency = payment_system.convert_amount(self.amount)
                                                     ^^^^^^^^^^^
```
Is it going to be fixed later, or it will be left as is?
