### PR TITLE
[FIX #4196] Rails/RelativeDate constant complains on lambda and proc

### LINKED ISSUE #4196: Rails/RelativeDateConstant complains about relative dates in procs
We have some code like
```ruby
CONST = -> { 1.year.ago }

CONST.call
```
By using the lambda we make sure to re-evaluate `1.year.ago`when needed.

## Expected behavior

`Rails/RelativeDateConstant` should not complain about this.

## Actual behavior

```
Offenses:

bug.rb:1:1: C: Rails/RelativeDateConstant: Do not assign ago to constants as it will be evaluated only once.
CONST = -> { 1.year.ago }
^^^^^^^^^^^^^^^^^^^^^^^^^

1 file inspected, 1 offense detected
```

## Steps to reproduce the problem

Above code as `bug.rb`; then `rubocop --rails bug.rb -D`

## RuboCop version

```
$ rubocop -V
0.48.0 (using Parser 2.4.0.0, running on ruby 2.3.1 x86_64-darwin15)
```

### PR DESCRIPTION
**Pull request by smakagon**
Fixes the following case for `Rails/RelativeDate` cop:

`CONST = -> { 1.year.ago }`

Before this fix it would show:

```
bug.rb:1:1: C: Rails/RelativeDateConstant: Do not assign ago to constants as it will be evaluated only once.
CONST = -> { 1.year.ago }
```

As reported [here](https://github.com/bbatsov/rubocop/issues/4196).

### CODE REVIEW

File: lib/rubocop/cop/rails/relative_date_constant.rb [hunk 1]
```diff
@@ -25,6 +25,8 @@ class RelativeDateConstant < Cop
         RELATIVE_DATE_METHODS = %i[ago from_now since until].freeze
 
         def on_casgn(node)
+          return if node.children.last.lambda_or_proc?
```
Comment (bbatsov) [inline lib/rubocop/cop/rails/relative_date_constant.rb]: Please, use node destructuring here (e.g. something like `_scope, const_name, value = *node`) instead of accessing `node.children` directly. I don't like this, because it gives 0 indication what exactly are you checking when you flatten the nodes to an array.

Comment (bbatsov) [inline lib/rubocop/cop/rails/relative_date_constant.rb]: Btw, it seems to me you can return quickly for anything but a `send` node on the right-hand side of the assignment. Obviously - if it's not a `send` it can't be what this cop is checking for. 

Overall this cop is implemented in a rather odd manner and can benefit from using node patterns IMO.

**Comment by bbatsov** [comment]
I'll merge this because I want to cut a release and I'll fix it myself.

**Comment by bbatsov** [comment]
Looking more closely in the code - this part `bad_node = node.descendants.find { |n| bad_method?(n) }` makes no sense to me. We should simply be inspecting whatever's the `rhs` on this assignment. @smakagon I'd appreciate it if you can take a look at improving this code when you have some time.

**Comment by smakagon** [comment]
@bbatsov sure, I'll try to refactor that cop and add more specs.
