### PR TITLE
[Fix #2285] Fix ConfigurableNaming error with singleton methods

### LINKED ISSUE #2285: Style/MethodName error on camel-cased class method
```
0.34.2 (using Parser 2.2.2.6, running on ruby 2.2.2 x86_64-darwin14)
```

Style/MethodName doesn't seem to like:

```ruby
class X
  def self.fooBar
  end
end
```

### PR DESCRIPTION
**Pull request by palkan**
According to [ast format](https://github.com/whitequark/parser/blob/master/doc/AST_FORMAT.md#class) there can be a `nil` among class node children. This hasn't been taken into consideration.

### CODE REVIEW

File: lib/rubocop/cop/mixin/configurable_naming.rb [hunk 1]
```diff
@@ -33,7 +33,7 @@ def class_emitter_method?(node, name)
         return false unless node.defs_type?
         return false unless node.parent
 
-        node.parent.children.any? do |c|
+        node.parent.children.reject(&:nil?).any? do |c|
```
Comment (bbatsov) [inline lib/rubocop/cop/mixin/configurable_naming.rb]: It's better to use `compact` IMO.

Comment (palkan) [inline lib/rubocop/cop/mixin/configurable_naming.rb]: Totally agree.

**Comment by bbatsov** [comment]
Thanks!
