### PR TITLE
[Fix #2696] NestedModifier adds parentheses

### LINKED ISSUE #2696: Auto correction of 'Avoid using nested modifiers' changes logic incorrectly
Hello,

I think I found an issue with the autocorrection for a Rails file.

I applied rubocop autocorrection 
    bundle exec rubocop <file> --rails -a

to a file that contains this line:

     changes.each { |k, v| amended_data[k] = v if !amended_data[k] && k != 'amended_data' } unless changes['report_status'] if self.amended? || self.reported?

And the autocorrection resulted in this line change:

     changes.each { |k, v| amended_data[k] = v if !amended_data[k] && k != 'amended_data' } if self.amended? || self.reported? && !changes['report_status']

However, this changes the logic if compared to the unless/if modifiers used on the original code because of missing parenthesis on the || clause.

The correct code output from the automatic correction should have been:
   
    changes.each { |k, v| amended_data[k] = v if !amended_data[k] && k != 'amended_data' } if (self.amended? || self.reported?) && !changes['report_status']

Thanks!

### PR DESCRIPTION
**Pull request by lumeet**
Auto-correction in `Style/NestedModifier` handles operator precedence
by adding parentheses when needed.

### CODE REVIEW

File: lib/rubocop/cop/style/nested_modifier.rb [hunk 1]
```diff
@@ -83,14 +83,17 @@ def new_expression(outer_node, inner_node)
           outer_keyword = outer_node.loc.keyword.source
           inner_keyword = inner_node.loc.keyword.source
 
-          operator = outer_keyword == 'if' ? '&&' : '||'
+          operator = outer_keyword == 'if' ? '&&'.freeze : '||'.freeze
```
Comment (bbatsov) [inline lib/rubocop/cop/style/nested_modifier.rb]: You can also freeze "if".

**Comment by lumeet** [comment]
Updated and rebased.
