### PR TITLE
[Fix #5640] Only warn about parameter overrides with --debug

### LINKED ISSUE #5640: inherit_mode Documentation Improvements
I'm having some major issues with the new `inherit_mode`.  Specifically around superfluous warning messages being shown that I don't care about and don't know how to get rid of.  The fact that messages are being written to the output which is not consistent with other warning or errors is also breaking build tooling which parse those messages to determine if they're warnings or errors.

What I currently have:

```yaml
# .rubocop.yml

inherit_from:
  - '.rubocop_core.yml'

Lint/HandleExceptions:
  Enabled: false
```

```yaml
# .rubocop_core.yml

Lint/HandleExceptions:
  Enabled: true
```

What I see in my output:

```
.rubocop.yml: Lint/HandleExceptions:Enabled overrides the same parameter in .rubocop_core.yml
```

I've tried changing `.rubocop.yml` to add:

```yaml
inherit_from:
  - '.rubocop_core.yml'

inherit_mode:
  override:
    - 'Enabled'

Lint/HandleExceptions:
  Enabled: false
```

I've tried both `override` and `merge` and neither of them fix the issue.

## RuboCop version

```
$ rubocop -V
0.53.0 (using Parser 2.5.0.2, running on ruby 2.4.3 x86_64-darwin16)
```

/cc @leklund

### PR DESCRIPTION
**Pull request by jonas054**
Overriding a parameter within user configuration with another setting -- also in user configuration -- may be a legitimate use case. So we only print the message about overriding if the `--debug` option is given. The message will be on stdout now like the other debug messages.

### CODE REVIEW

File: lib/rubocop/config_loader.rb [hunk 1]
```diff
@@ -35,7 +35,6 @@ def clear_options
       end
 
       def load_file(file)
-        return if file.nil?
```
Comment (jonas054) [inline lib/rubocop/config_loader.rb]: I removed this line to squeeze under the `Metrics/AbcSize` limit. All tests still pass. I figure this an old special case that's not relevant anymore.
